### ISSUE TITLE
?phetioDebug won't run in Studio

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#100]
For https://github.com/phetsims/qa/issues/789. Seen on Win 11 Chrome.
When trying to run studio with the `?phetioDebug` parameter, I got the below error and studio would not load.
<img width="960" alt="debugpopup" src="https://user-images.githubusercontent.com/41024075/159568740-08d7331c-f0a9-430f-986c-f696ff155462.png">

**Comment by KatieWoe** [comment]
The same seems to happen in the state wrapper:
<img width="960" alt="similarstate" src="https://user-images.githubusercontent.com/41024075/159569732-29c76be1-4025-4d32-929e-a226318e2278.png">

**Comment by chrisklus** [comment]
@samreid and I identified two steps for this issue:

1. Related to https://github.com/phetsims/center-and-variability/issues/99 - marking SoccerPlayers as `phetioDynamicElement: true`. And other possible errors from phet-io debug, like missing required tandems.
2. Making a phet-io issue to investigate why some modes of running the sim (`phetioDebug`) identify these errors, and others do not.

**Comment by samreid** [comment]
This seems fixed after the commits.  @KatieWoe can you please verify on phettest?  If all is well, please relabel as "ready for cherry pick".

**Comment by KatieWoe** [comment]
`?phetioDebug` seems to be included automatically in master, and both studio and state loaded fine.

**Comment by samreid** [comment]
@chrisklus and I confirmed this is fixed in in https://github.com/phetsims/center-and-variability/issues/122, closing.
