### ISSUE TITLE
First kicks of sim on Firefox flash

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#101]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/789. 
When you first enter the sim and kick the soccer balls, the kickers flash as they kick. After the first round this flash no longer happens, even if you reset all or refresh the page. As such, this is best reproduced in incognito mode.
**Steps to reproduce**
1. Open the sim in incognito mode
2. Go to the first screen
3. Press Kick 5 and observe flashes
4. After round stops, press kick 1 and observe steady images

**Visuals**
![firstkicksflash](https://user-images.githubusercontent.com/41024075/159581152-f4b6dd6a-09eb-485a-9954-55a191a3301f.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Variability‬
URL: https://phet-dev.colorado.edu/html/center-and-variability/1.0.0-rc.1/phet/center-and-variability_all_phet.html
Version: 1.0.0-rc.1 2022-03-21 16:46:53 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0
Language: en-US
Window: 1280x667
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
It also seems to occur again if the page is left for some time and then returned to. After creating this issue in a different browser I saw this bug again when I returned to the sim.

**Comment by Nancy-Salpepi** [comment]
@KatieWoe I think this is the same issue as https://github.com/phetsims/center-and-variability/issues/91

**Comment by KatieWoe** [comment]
Looks like, sorry about that.
