### ISSUE TITLE
Sorting Arrow hint doesn't always appear in State wrapper

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#103]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/789
After moving cards in the downstream sim, pressing "set state now" will not make the blue sorting arrow hint reappear. It will reappear after pressing the 'Reset All' button in the downstream sim.  

* The sorting arrow doesn't disappear in the downstream sim, when sorting in the upstream sim (only sorting in the downstream sim causes the arrow to disappear)
* In Studio, the sim always launches with the sorting arrow hint (even if not present in studio prior to launching). 

**Steps to reproduce**
1. Select the Median screen
2. Set State Rate = 0
3. In the upstream sim, kick a couple of balls so that the blue sorting arrow appears
4. Press 'Set State Now'
5. In the downstream sim, move cards to make the arrow disappear
6. Press 'Set State Now'

**Visuals**

https://user-images.githubusercontent.com/87318828/159722259-367d2fa3-9c1d-42ab-8157-6a7718b08600.mp4

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi! @samreid and I agree the drag indicator should be stateful. If the client wants to re-show it after they set up the cards in a certain state, then they can make it visible again.

**Comment by samreid** [comment]
Fixed in the commit.  Can @marlitas or @matthew-blackman please review? You can test the old behavior by commenting out the phet-io metadata, then using the state wrapper. Feel free to test/review asynchronously or wait for a zoom call.

**Comment by samreid** [comment]
We will continue in https://github.com/phetsims/center-and-variability/issues/129, closing.
