### ISSUE TITLE
Should pressing the eraser button reset the sorting arrow hint?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#108]
**Test device**
iMac 

**Operating System**
10.5.7

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/789, I was wondering if the eraser button should reset the sorting arrow hint? Currently, the hint will only reappear after "reset all" is pressed. 

**Steps to reproduce**
1. On the median screen, kick a couple of balls
2. Move a card so that the sorting hint disappears
3. Press the eraser button
4. Kick a couple of balls --no hint appears.

**Visuals**

https://user-images.githubusercontent.com/87318828/159972987-1b9b83d0-ff2f-47dd-a893-234abab99f82.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Variability‬
URL: https://phet-dev.colorado.edu/html/center-and-variability/1.0.0-rc.1/phet/center-and-variability_all_phet.html
Version: 1.0.0-rc.1 2022-03-21 16:46:53 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36
Language: en-US
Window: 1242x739
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by amanda-phet** [comment]
We thought the sorting hint didn't need to be reset in this case because they already learned how it works, and the erase button just erases the data and doesn't reset anything else about the sim. 

I'll close this since it was an intentional decision, but added it to my list of things to look for in interviews.
