### ISSUE TITLE
Distribution Property Possibly Wrong in Studio

### ISSUE THREAD

**Issue by DevonQui** [phetsims/center-and-variability#112]
**Test device**
MacBook Pro M1

**Operating System**
12.2.1

**Browser**
Safari 15.3

**Problem description**
This is for https://github.com/phetsims/qa/issues/789

I noticed that the left and right skew distributions are possibly switched in Studio. When I was testing left skew, it only produced a left-skewed distribution 9% of the time, the other 91% were right-skewed distributions. This was similar to testing right-skew which mostly produced left-skew distributions when all 15 balls were released.

If you need a refresher on the left and right skews, the mean is to the left of the median for left-skew and the mean is to the right of the mean for right-skew. I'll include a picture in the issue.

**Steps to reproduce**
1. Open sim in Studio
2. find "meanAndMedianScreen" in studio tree and expand its "model" subtree
3. set the "distributionProperty" to either left or right skew and do 10 tests recording how many of the resulting distributions are right-skewed and how many are left-skewed with the distribution property set to either left or right skewed for those 10 tests. You should notice that when the distributionProperty is set to left-skewed it will mostly produce right-skewed distributions and vice-versa.
**Visuals**
![left-right-skews](https://user-images.githubusercontent.com/72042459/160471007-8e0ddf1f-870e-44d6-8d1e-e890a1c751a9.jpeg)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Variability‬
URL: https://phet-dev.colorado.edu/html/center-and-variability/1.0.0-rc.1/phet/center-and-variability_all_phet.html
Version: 1.0.0-rc.1 2022-03-21 16:46:53 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15
Language: en-US
Window: 1512x865
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment]
Great catch, thanks!  @chrisklus and I were surprised to read this google search that said:

> In statistics, a negatively skewed (also known as left-skewed) distribution is a type of distribution in which more values are concentrated on the right side (tail)

We previously had that backwards and will correct it.  Tagging @amanda-phet so she is aware.

**Comment by amanda-phet** [comment]
I've checked both screens and kicked 15 balls a number of times and this doesn't seem fixed. I am on phettest incognito, so there shouldn't be a caching issue, but I often have issues with not seeing the latest version. 

![image](https://user-images.githubusercontent.com/7852916/160708429-b24f4ac7-5212-48a5-96d5-2a2c4d0c998f.png)

**Comment by kathy-phet** [comment]
I am also seeing the same thing as Amanda. It doesn't appear fixed.

**Comment by DevonQui** [comment]
I second this. For both screens, the left-skew and right-skew are still switched. I switched browsers and opened up a second window to address any caching issues but the problem still persisted.

**Comment by samreid** [comment]
Thanks for checking, there was indeed one more place where the values were incorrectly mapped.  I pushed a fix for that.  Ready for re-review at your convenience.

**Comment by samreid** [comment]
Also a note we may change this PhET-iO API as we add support for arbitrary distributions.

**Comment by samreid** [comment]
Based on remarks from @kathy-phet and discussion with @chrisklus, we would like to proceed with the proposal in https://github.com/phetsims/center-and-variability/issues/116.  On hold until there is progress in that issue.

**Comment by samreid** [comment]
We decided #116 is good for this milestone, so this is ready for cherry-picking in the milestone.

**Comment by chrisklus** [comment]
@samreid and I spot-checked this for https://github.com/phetsims/center-and-variability/issues/122, closing.
