### ISSUE TITLE
Name change to 'Kick 5' button not maintained in launched sim

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#114]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3 

**Browser**
chrome

**Problem description**
For https://github.com/phetsims/qa/issues/789

The launched sim doesn't show any changes to the name of the 'Kick 5' button. This happens on both screens. 
This issue isn't seen with the 'Kick 1' button. 

**Steps to reproduce**
1. In studio, go to `view.kickButtonGroup.kickFiveButton.labelNode.textProperty` on either screen
2. Change the name of the button 
3. Launch sim

**Visuals**
<img width="800" alt="Screen Shot 2022-03-29 at 10 52 18 AM" src="https://user-images.githubusercontent.com/87318828/160640207-aad85842-7aef-428b-bc4c-43f6e6935f62.png">

**Comment by samreid** [comment]
Good discovery, thanks!  The button label for the Kick 5 is dynamically computed based on the number of remaining balls, so it can sometimes say "Kick 4" etc.  Therefore @chrisklus and I recommend making the labels on the button non-customizable by removing their instrumentation.

**Comment by samreid** [comment]
Fixed as described above.  @Nancy-Salpepi can you please review on phettest?  Please mark for cherry-picking if all is well.

**Comment by Nancy-Salpepi** [comment]
That makes total sense! 
I no longer see the labelNode in the tree for either button on both screens.

**Comment by samreid** [comment]
@chrisklus and I confirmed this is fixed in in https://github.com/phetsims/center-and-variability/issues/122, closing.
