### ISSUE TITLE
Add PhET-iO support for arbitrary distributions

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#116]
From https://github.com/phetsims/center-and-variability/issues/112 and slack:

@kathy-phet said:

> One of the iO requests (not for this version) was to be able to set the distribution. Do you envision adding a CUSTOM to the distribution choices, and then having something the client can "Set" for that distribution? I think it would be good for the client to have access to the actual fixed distributions as well. The "ideal" or "population" being selected from. These are all requests for later, I just wanted make sure they were on the radar.

I replied:
> I was picturing something like:

```ts
phetioClient.invoke( 'centerAndVariability.medianScreen.model.distributionProperty', 'setValue', [ [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15] ] );
```

> Would it be OK if we change distribution from enumeration to array to support this?

**Comment by samreid** [comment]
This patch supports arbitrary distributions, but un-names the left and right skewed distributions, is that OK?

<details>

```diff

Index: js/common/model/SoccerModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/SoccerModel.ts b/js/common/model/SoccerModel.ts
--- a/js/common/model/SoccerModel.ts	(revision aad789bd0a493d5cf0272f4b06fda020d047a5a7)
+++ b/js/common/model/SoccerModel.ts	(date 1648592854955)
@@ -29,7 +29,8 @@
 import NullableIO from '../../../../tandem/js/types/NullableIO.js';
 import ReferenceIO from '../../../../tandem/js/types/ReferenceIO.js';
 import { DistributionType } from './DistributionType.js';
-import EnumerationProperty from '../../../../axon/js/EnumerationProperty.js';
+import ArrayIO from '../../../../tandem/js/types/ArrayIO.js';
+import NumberIO from '../../../../tandem/js/types/NumberIO.js';
 
 type SelfOptions = {};
 type SoccerModelOptions = SelfOptions & CAVModelOptions;
@@ -46,7 +47,7 @@
 
   private readonly timeWhenLastBallWasKickedProperty: NumberProperty;
   private readonly ballPlayerMap: Map<CAVObject, SoccerPlayer>; // TODO: Add to PhET-iO State
-  distributionProperty: EnumerationProperty<DistributionType>;
+  distributionProperty: Property<ReadonlyArray<number>>;
 
   constructor( maxNumberOfBalls: number, options: SoccerModelOptions ) {
 
@@ -96,8 +97,9 @@
     this.hasKickableSoccerBallsProperty = new DerivedProperty( [ this.numberOfRemainingKickableSoccerBallsProperty ],
       numberOfRemainingKickableObjects => numberOfRemainingKickableObjects > 0 );
 
-    this.distributionProperty = new EnumerationProperty( SoccerModel.chooseDistribution(), {
-      tandem: options.tandem.createTandem( 'distributionProperty' )
+    this.distributionProperty = new Property<ReadonlyArray<number>>( SoccerModel.chooseDistribution(), {
+      tandem: options.tandem.createTandem( 'distributionProperty' ),
+      phetioType: Property.PropertyIO( ArrayIO( NumberIO ) )
     } );
 
     this.objectValueBecameNonNullEmitter.addListener( casObject => {
@@ -123,8 +125,8 @@
     } );
   }
 
-  static chooseDistribution(): DistributionType {
-    return dotRandom.nextBoolean() ? DistributionType.LEFT_SKEWED : DistributionType.RIGHT_SKEWED;
+  static chooseDistribution(): ReadonlyArray<number> {
+    return dotRandom.nextBoolean() ? DistributionType.LEFT_SKEWED.data : DistributionType.RIGHT_SKEWED.data;
   }
 
   /**
@@ -209,7 +211,7 @@
     // console.log( inputNormalized );
     // console.log( resultNormalized );
 
-    const weights = this.distributionProperty.value.data;
+    const weights = this.distributionProperty.value;
 
     assert && assert( weights.length === this.physicalRange.getLength() + 1, 'weight array should match the model range' );
     const x1 = dotRandom.sampleProbabilities( weights ) + 1;

```

</details>

<img width="635" alt="image" src="https://user-images.githubusercontent.com/679486/160717489-dd912bdd-04c6-49c4-bebc-54b9c136d4b3.png">

**Comment by kathy-phet** [comment]
This works for me. @amanda-phet - Are you OK with this?

**Comment by kathy-phet** [comment]
@samreid -  Can you add some documentation on what this is? And its requirements? does it require integers? Describe that it is normalized to 1 to determine the probabilities or something.

**Comment by kathy-phet** [comment]
I like that you see the distribution. Then we don't have to deal with that crazy definition of left and right skewed which frankly I also didn't know. It seems backwards to me and could create confusion if an instructional designer doesn't know what is going on.

**Comment by samreid** [comment]
Based on remarks from @kathy-phet and discussion with @chrisklus, we would like to proceed with the proposal in this issue.  We committed above and it's ready for review.  @amanda-phet can you please take a look?  Please mark for cherry picking if it seems alright.

**Comment by samreid** [comment]
@chrisklus has some documentation changes in his working copy.  Also we need to guard that values are non-negative.

**Comment by chrisklus** [comment]
>@chrisklus has some documentation changes in his working copy.  Also we need to guard that values are non-negative.  Once that is complete @amanda-phet and I agreed this issue is ready for cherry-picking.

These changes are complete and tested in Studio. Marking for cherry-picking.

**Comment by chrisklus** [comment]
@samreid and I spot-checked this for https://github.com/phetsims/center-and-variability/issues/122, closing.

**Comment by KatieWoe** [comment]
I noticed this isn't a Featured Element in https://github.com/phetsims/qa/issues/795. Should this be revisited?

**Comment by samreid** [comment]
Please see https://github.com/phetsims/center-and-variability/issues/119#issuecomment-1093417931

**Comment by amanda-phet** [comment]
We haven't done any featuring yet in studio, so I'd like to close this.
