### ISSUE TITLE
PhET-iO design of distribution 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/center-and-variability#117]
From reviewing #116 and #112 , I wanted to move further PhET-iO design discussions to another issue. 

1. Math educators know what skewed left and right are, so I am not concerned about that terminology. 
2. Having the choice to select between skewed-right and skewed-left seems advantageous to me, since those are important concepts in this sim, and are learning goals for lessons designed around this sim. Being able to choose left vs. right is very simple, compared to noticing the values are skewed and knowing to flip them if you want to skew the other direction. 
3. In a later screen (Spread), the players will have 4 distinct underlying distributions, and so whether it's in the code or the documentation, we will need to name distributions 

I would like to discuss the option of having three radio buttons for #116 that are skewed left, skewed right, and custom. I would also like to discuss how we want to handle this on the Spread screen so we can be consistent.

**Comment by samreid** [comment]
Also, a note in the code says:

>     // TODO: PhET-iO wants to be able to set these values. Maybe in the preferences, we would also add a "custom"
    //       option that would allow the user to specify the distribution parameters. Or for PhET-iO, and query parameters

**Comment by samreid** [comment]
Today we agreed the devs have enough to go on for an initial draft, and we can reach out for feedback as necessary.

**Comment by samreid** [comment]
Maybe each scene should have an enumeration for distribution type:

1. random skewed
2. specified distribution
3. exact sequence

That last part has a note in the phet-io document:

> Explore for an hour - AFTER all is well on everything else

But if we have to abstract for (1)-(2) anyways we should accommodate (3) while we are there.

We would also have more flexibility to design the studio controls if we implemented https://github.com/phetsims/studio/issues/292

**Comment by samreid** [comment]
I committed an initial draft. Next steps:

* Review existing implementation with other devs
* Address TODOs
* Review with phet-io design team

**Comment by samreid** [comment]
After today's meeting, I'm feeling this should move into a child of the sceneModel, to make it more discoverable.

**Comment by samreid** [comment]
OK I refactored the code to move KickDistanceStrategy to a separate class. It is working well and customizable in studio.  The tandems are like: `centerAndVariability.medianScreen.model.sceneModel.kickDistanceStrategy` and the studio documentation looks like this:

![image](https://github.com/phetsims/center-and-variability/assets/679486/ecccbb8e-eddb-4b8a-a72f-7f5b9b79a418)

I would like help on the next steps:
1. Addressing TODOs in the code
2. Should `kickDistanceStrategyFromStateObject` be passed in?  Or can it get baked into KickDistanceStrategy?
3. Should TKickDistanceStrategy be renamed?
4. Should TKickDistanceStrategy (after possibly renaming) move into KickDistanceStrategy.ts?
5. I think we should change the object outputs from `{ "distributionType": "probabilityDistributionByDistance[0,0,1,3,5,7,3,3,1,1,0,0,0,0,1]" }` to `{ "distributionType": "probabilityDistributionByDistance", "values: [0,0,1,3,5,7,3,3,1,1,0,0,0,0,1] }` but want to make sure that won't confuse designers.  That change will make the state input/output simpler as well as improving the state schema and potential future migration.

**Comment by catherinecarter** [comment]
Let's update the Probability distribution by distance documentation could be more clear. Currently, the documentation is: 

![Image](https://github.com/phetsims/center-and-variability/assets/109630002/b609e52e-815f-48f5-9c90-33b3763301be)


Let's update to say, "The distribution of frequencies or probabilities per location on the number line. This is a non-normalized array of non-negative floating point numbers where each number in the array represents the relative likelihood that a ball will land in each position from 1 to 15, in order."

**Comment by catherinecarter** [comment]
For `exact distance distribution`, current language says, "Exact Location each ball will land (in order). Indicates the exact distance each ball will be kicked in order. Keep in mind the maximum number of kicks may be as high as 30, depending on the selection in the preferences dialog. e.g.,..."

Let's add, "for future kicks" and also add that whatever kick number is next will be pulled from the array in that position. In other words, if three balls have been kicked, and the user sets the exact location array, the fourth ball will land at the number that's in the fourth position in the array.

**Comment by samreid** [comment]
OK I updated the documentation as recommended in the 2 preceding comments.  @catherinecarter can you please review the wording?

Anything else for this issue other than code review with @marlitas and/or @matthew-blackman?

**Comment by catherinecarter** [comment]
Looks great, thanks!

**Comment by samreid** [comment]
Also, some recommendations in https://github.com/phetsims/center-and-variability/issues/117#issuecomment-1604327684 that are not complete. Changing the data structure type.

**Comment by marlitas** [comment]
@samreid if you have a chance to answer before your vacation...

> I think we should change the object outputs from { "distributionType": "probabilityDistributionByDistance[0,0,1,3,5,7,3,3,1,1,0,0,0,0,1]" } to { "distributionType": "probabilityDistributionByDistance", "values: [0,0,1,3,5,7,3,3,1,1,0,0,0,0,1] } but want to make sure that won't confuse designers. That change will make the state input/output simpler as well as improving the state schema and potential future migration.

I remember talking about this, but I don't remember what we landed on for the exact structure of the data. Is there documentation for that? I believe we were thinking about a different key name than `distributionType?`

**Comment by samreid** [comment]
I think the key name `distributionType` sounds good.

**Comment by matthew-blackman** [comment]
Patch from pairing work:

<details>

```diff

Subject: [PATCH] Kick distance strategy patch
---
Index: js/model/TKickDistanceStrategy.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/model/TKickDistanceStrategy.ts b/js/model/TKickDistanceStrategy.ts
--- a/js/model/TKickDistanceStrategy.ts	(revision a81b79b9b8b63206739311c4ec1a48bcc3c44d4f)
+++ b/js/model/TKickDistanceStrategy.ts	(date 1691606884266)
@@ -12,13 +12,17 @@
 export type TKickDistanceStrategy = {
   reset(): void;
   getNextKickDistance( kickNumber: number ): number;
-  toStateObject(): string;
+  toStateObject(): any;
 };
 
 // These values are used in the state object, should be changed with caution, because changes to the state API
 // would require migration rules.
 const PROBABILITY_DISTRIBUTION_KEY = 'probabilityDistributionByDistance';
 const EXACT_DISTANCE_KEY = 'exactDistanceByIndex';
+const RANDOM_SKEW_KEY = 'randomSkew';
+
+const KICK_DISTANCE_STRATEGY_KEYS = [ PROBABILITY_DISTRIBUTION_KEY, EXACT_DISTANCE_KEY, RANDOM_SKEW_KEY ] as const;
+type kickDistanceStrategyKey = typeof KICK_DISTANCE_STRATEGY_KEYS[number];
 
 export class DistributionStrategy implements TKickDistanceStrategy {
 
@@ -35,8 +39,11 @@
     // Nothing to do
   }
 
-  public toStateObject(): string {
-    return `${PROBABILITY_DISTRIBUTION_KEY}[${this.distribution.join( ', ' )}]`;
+  public toStateObject(): any {
+    return {
+      type: PROBABILITY_DISTRIBUTION_KEY,
+      values: this.distribution.join( ', ' )
+    };
   }
 
   public static fromStateObject( stateObject: string ): DistributionStrategy {

**Comment by samreid** [comment]
@marlitas and @matthew-blackman and I made a lot of good progress on this today. The foundational data structures are good, and studio/states/get/set all seem to be working and matching the schema and API we want. There are some TODOs in the code to update other parts. @matthew-blackman volunteered to update the documentation in KickDistanceStrategy, and I'm happy to work on the other parts.

**Comment by samreid** [comment]
OK I fixed everything except the documentation (there is a TODO for it). @matthew-blackman volunteered to work on that part, so I'll leave it assigned to him. But let's also review these changes with @catherinecarter soon (whether or not the documentation is complete).

**Comment by catherinecarter** [comment]
The documentation looks very clean and easier to read than prior. Nice! For the distanceByIndex, I'd like to tweak the documentation slightly. 

Current documentation: 
>Distance By Index: Defines the location that each ball will land in the order it is kicked. e.g. If three balls have been kicked, the next ball will land at the value in fourth position in the "values" array. Values should be positive integers from 1 to 15, and have a length equal to the maximum number of kicks for the scene. (Note: The maximum number of kicks may be as high as 30, depending on the selection in the preferences dialog)

New documentation: 

Distance By Index: Defines the location on the number line each ball will land in the order it is kicked. Values should be positive integers from 1 to 15. The length of the "values" array should equal the maximum number of kicks for the scene (defined in preferences). Note: This works whether any balls have been kicked or not. For example, if zero balls have been kicked prior to the set value command, the first ball will land at the value in the first position of the "values" array. If three balls have been kicked prior to the command, the next ball will land at the value in the fourth position in the "values" array.

**Comment by samreid** [comment]
I updated the documentation as prescribed above. In today's meeting about https://github.com/phetsims/center-and-variability/issues/444 we observed that the soccer player 3 and 4 distributions were incorrectly randomSkew (and hence changed on reset). So we resolved that in a commit. @catherinecarter @matthew-blackman @marlitas reviewed the behavior in studio and the documentation and I think this issue is at a good point to close. Anyone feel free to reopen or create new issues for any reason.
