### ISSUE TITLE
Further refinements to kicker artwork 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/center-and-variability#118]
Based on #12, there are a few things that @chrisklus still wants to change about the artwork. I would like to discuss modifying the artwork to address these concerns: 
 
- if we can make standing foot flat on the grass instead of dipping below the horizon or having a dramatic heel above the horizon
- if we can adjust some of the kicking feet to not dip below the horizon line
- if we can fine-tune the pivot from standing to PoisedToKick to look the most natural

**Comment by catherinecarter** [comment]
Here are some screenshots of no gradient versus a slight gradient: 
Original (no gradent): 
![image](https://user-images.githubusercontent.com/109630002/235741426-08086729-d3e8-4660-b353-49f4928abfa9.png)

New (with gradient):
![image](https://user-images.githubusercontent.com/109630002/235741612-dc37fde5-fe3c-40c9-ac55-ba5335b9fca0.png)

**Comment by samreid** [comment]
From today's design meeting, we are not concerned about the kicker's foot dropping below y=0. We feel the gradient is unnecessary.  We prefer the solid green.  Closing as wontfix.
