### ISSUE TITLE
New PhET-iO client requests

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/center-and-variability#119]
In a discussion with instructional designer partners, the following requests came out of the meeting: 

~(1) Can we limit the kicker to be just one person (so, just the artwork for player01 for all 15 kicks)~
- [x] (2) Can we make x balls not movable, and y balls movable (e.g. 14 frozen, 1 that can move)
- [x] (3) Can we change the appearance of balls that are movable and balls that are not (this is a big design question I’ve had)
- [x] (4) Instrument the banner question at the top of the sim so that we can hide both the colored banner and the text question.

For (1), I think this is straightforward. We just want to use the same artwork for each kick. If we can provide a list of all 15 players and the client selects the one they want, I think that would be nice. But if it's not possible, we can just use player01 as the single player. 

(2) This design doesn't seem possible without (3). But as far as the implementation goes, I am thinking that in the tree, each `soccerBallNode_x` would have its own `inputEnabledProperty`, rather than the group having that property. When that is checked, we need to change the appearance as well (or provide a way to adjust the opacity?). 

(3) I added this because I am concerned about making some balls movable and others not movable without changing their appearance. I think we need a design discussion about this. If we make them semi-transparent, they may look like they "are not part of the data set" since that's what we're doing for the ball about to be kicked. However, this seems like a straightforward approach. Another idea is to use a different png file for any "frozen" balls, such as a soccer ball that has inverted colors, or looks more flat (doesn't have shading), or some other visual difference that doesn't use reduced opacity.

**Comment by amanda-phet** [comment]
@chrisklus and I discussed these and (2) and (3) are doable, and we decided to have the soccer ball change appearance when `inputEnabledProperty` is false. He is also going to instrument the bar at the top to address (4). 

(1) The prompt we wanted to write for this can be achieved with the sim as it is, and the Spread screen will fully address the questions we had in mind, so I've decided to scrap this from the list. 

Here is a mockup of (3): 

![image](https://user-images.githubusercontent.com/7852916/161174630-fc593196-319c-4314-8765-8c8edec6c08c.png)

**Comment by amanda-phet** [comment]
Here is the asset: 

![soccerball_not pickable](https://user-images.githubusercontent.com/7852916/161174733-80b13661-95bf-4999-9384-48a6837c0207.png)

**Comment by amanda-phet** [comment]
Here is a slightly lighter ball
![soccerball_not pickable](https://user-images.githubusercontent.com/7852916/161325188-b988b007-a72b-43c3-afa7-ee4f214cefd1.png)

**Comment by chrisklus** [comment]
This issue is complete, ready for review by @amanda-phet and @samreid

**Comment by amanda-phet** [comment]
Looks great! Thanks for making this possible. These changes are going to make the wrappers even better.

**Comment by samreid** [comment]
Would this simplify the boolean logic a bit?  I haven't tested it:

```ts
          // if input is disabled and the ball is in the play area, show the darker version
          if ( options.objectViewType === CAVObjectType.SOCCER_BALL && value !== null ) {
            soccerBallDarkNode.visible = !inputEnabled;
            soccerBallNode.visible = inputEnabled;
          }
```

Other than that, the code review looks good.

**Comment by chrisklus** [comment]
Thanks @samreid - the else was needed for when switching from input disabled -> enabled, but i used your idea to improve what was there like this:

```js
if ( options.objectViewType === CAVObjectType.SOCCER_BALL ) {

  // if input is disabled and the ball is in the play area, show the darker version
  const showDisabledSoccerBall = !inputEnabled && value !== null;
  soccerBallDarkNode.visible = showDisabledSoccerBall;
  soccerBallNode.visible = !showDisabledSoccerBall;
}
```

Thanks all for reviewing, closing.

**Comment by chrisklus** [comment]
Oops, did not mean to close. Reopening for cherry picking.

**Comment by amanda-phet** [comment]
This all looks good to me!

**Comment by chrisklus** [comment]
@samreid and I spot-checked this for https://github.com/phetsims/center-and-variability/issues/122, closing.

**Comment by KatieWoe** [comment]
Reopening for https://github.com/phetsims/qa/issues/795. I found it odd that this was not a Featured Element. Should this be revisited?

**Comment by samreid** [comment]
As far as I know, nothing is intended to be featured for this milestone, and featured elements will be designed by @amanda-phet for 1.1.

**Comment by amanda-phet** [comment]
Correct, we haven't done any featuring yet in studio. Re-closing.
