### ISSUE TITLE
Add cueing arrow to 15th ball

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/center-and-variability#120]
After the user kicks 15 balls, this cueing arrow will appear above the final ball. Once a ball has been dragged (either before or after the arrow appears), the arrow won't reappear unless the sim is reset (identical behavior to the cueing arrow above the number cards on the Median screen). 

We also need to make sure that if a PhET-iO client disables any/all of the balls on the field, the cueing arrow does not appear above balls that are not movable. 

![image](https://user-images.githubusercontent.com/7852916/161323573-9067a6de-ae66-4665-9ef7-b4452956fb89.png)

**Comment by chrisklus** [comment]
@samreid and I completed this in the above commit, @amanda-phet can you please review?

**Comment by amanda-phet** [comment]
This is working great for the PhET version. 

PhET-iO issue: When I make the group not movable, the arrow still shows up
![image](https://user-images.githubusercontent.com/7852916/161633791-042cdf43-1766-4132-a73f-e8cf4acf9ade.png)

**Comment by chrisklus** [comment]
>PhET-iO issue: When I make the group not movable, the arrow still shows up.

This was fixed in the above commit. Marking ready for cherry picking

**Comment by chrisklus** [comment]
@samreid and I spot-checked this for https://github.com/phetsims/center-and-variability/issues/122, closing.
