### ISSUE TITLE
Create rc.2

### ISSUE THREAD

**Issue by chrisklus** [phetsims/center-and-variability#122]
@samreid and I decided to do this by merging master into 1.0, since we did not find any breaking changes related to dependencies for the sim.

We also need to cherry-pick one commit from Studio, https://github.com/phetsims/studio/commit/9af65d0bde5cbce63446e207ec164577adb48b79

**Comment by samreid** [comment]
@chrisklus and I created RC.2 by merging master into 1.0.  

https://phet-dev.colorado.edu/html/center-and-variability/1.0.0-rc.2/phet-io/?phetioDebug&phetioElementsDisplay=all
https://phet-dev.colorado.edu/html/center-and-variability/1.0.0-rc.2/phet/center-and-variability_en_phet.html

We checked all of the cherry-pick issues and didn't see any problems.  This was delivered to @amanda-phet and the next step is to create a QA issue.  Closing.
