### ISSUE TITLE
DragIndicatorNodes do not autoselect in Studio

### ISSUE THREAD

**Issue by chrisklus** [phetsims/center-and-variability#123]
When verifying https://github.com/phetsims/center-and-variability/issues/120 for https://github.com/phetsims/center-and-variability/issues/122, we noticed that both DragIndicatorNodes do not autoselect in Studio.

**Comment by samreid** [comment]
Perhaps only interactive things autoselect in studio?

**Comment by samreid** [comment]
Fixed by removing `pickable: false`, and it's working well in studio. Closing.
