### ISSUE TITLE
Median arrow appears in the question bar on startup

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#127]
- The arrow appears at wider aspect ratios in question. Remains on left edge of screen further down.
![Screen Shot 2022-04-08 at 12 27 35 PM](https://user-images.githubusercontent.com/42476338/162500259-1459a7b5-c0de-4913-b53c-648be113a350.png)
.

**Comment by marlitas** [comment]
![Screen Shot 2022-04-08 at 12 30 28 PM](https://user-images.githubusercontent.com/42476338/162500657-612ddb5e-c7c2-4118-a1a6-0399bfacd8f5.png)

**Comment by samreid** [comment]
I accidentally broke this in https://github.com/phetsims/center-and-variability/issues/76, fixed, closing.
