### ISSUE TITLE
DragIndicatorNode sometimes above 14th ball in State wrapper

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#130]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.31.1

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/795 in the State Wrapper:
Sometimes the dragIndicatorNode appears above the 14th ball instead of the 15th in the downstream sim. 

**Steps to reproduce**
1. In the state wrapper, press the `Kick 5` button 3 times
2. Press Reset All and repeat step 1 (you may need to do this several times)

I have also seen this when setting the state with set state rate = 0.

**Visuals**

https://user-images.githubusercontent.com/87318828/162582200-f3ee1680-49e2-4253-86bb-76ff3df1e3ce.mp4

**Comment by Nancy-Salpepi** [comment]
I was also able to reproduce this in the Studio wrapper on both screens and in the PhET brand sim. It seems to occur when the 14th ball lands after the 15th ball.

**Comment by samreid** [comment]
@chrisklus and I think this would be appropriate for discussion for 1.1.

**Comment by samreid** [comment]
I was able to reproduce this problem.

**Comment by samreid** [comment]
I was going to ask if we really like using PhetioGroup in this sim, or if we want to abandon it and eagerly create all objects, and use the `isActiveProperty` like we used in Mean: Share and Balance. That would likely solve this problem (though it is not the only way to solve it).

**Comment by samreid** [comment]
Today we discussed that we should probably move toward static elements and `isActiveProperty`. We agreed it will be ok in studio to see all 15 things even though they aren't active. I proposed visual UI that grays out inactive items in the tree, but we were told that is not needed.

**Comment by samreid** [comment]
This looks fixed after https://github.com/phetsims/center-and-variability/issues/160, closing.
