### ISSUE TITLE
Consider redesigning arrow location

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#131]
Seen while testing https://github.com/phetsims/qa/issues/795:

With the median checkbox in the play area checked, sometimes the dragIndicatorNode and the Median arrow overlap:
<img width="269" alt="Screen Shot 2022-04-11 at 4 33 14 PM" src="https://user-images.githubusercontent.com/87318828/162827572-31baa58b-8692-47fb-95cf-d8aeb23a38ea.png">

**Comment by samreid** [comment]
This seems reasonable to address in 1.1.

**Comment by samreid** [comment]
From today's design meeting, since the blue arrow only appears when all soccer balls are kicked and is transient. So we aren't too worried.  

We would like to move the blue arrow to a stack that doesn't have the median location.

**Comment by samreid** [comment]
@marlitas addressed most of this problem in https://github.com/phetsims/center-and-variability/issues/189.  We still need to have it not go behind the accordion box.  I'll open a new issue for that.
