### ISSUE TITLE
Soccer balls tend towards higher numbers

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#132]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/795.
When kicking balls in the sim, they seem to tend towards higher numbers (8-15) rather than smaller numbers (1-7). According to @chrisklus this should be 50/50, but it definitely seemed to tend towards higher numbers from what I saw.

**Steps to reproduce**
1. Kick all balls and observe where they land
2. Repeat several times

Troubleshooting information:
<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Variability‬
URL: https://phet-dev.colorado.edu/html/center-and-variability/1.0.0-rc.2/phet/center-and-variability_all_phet.html
Version: 1.0.0-rc.2 2022-04-06 18:08:39 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by amanda-phet** [comment]
This is how the sim is designed to behave.  

What should be 50/50 (over a large enough sample) is if the balls skew right vs. skew left, since the distribution is randomly chosen between those two.

**Comment by amanda-phet** [comment]
So, I'm not sure if this is actually a bug. If you run the sim many times, say 20-30 times, you should see the balls skew left roughly half the time, but it's like flipping a coin, and won't necessarily happen exactly 50% of the time.

**Comment by chrisklus** [comment]
@amanda-phet can this be closed?

**Comment by amanda-phet** [comment]
As long as there isn't a bug, then yes I think this can be closed.
