### ISSUE TITLE
Add screenshots

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#134]
@chrisklus and I were asked to publish 1.0 today, but we do not have a screenshot.  We will take a screenshot so we can proceed, but @amanda-phet should design one for the long term.

**Comment by samreid** [comment]
@chrisklus and I created a screenshot, but ideally we would prefer one that shows the soccer player kicking, and has a ball flying through the air.

**Comment by chrisklus** [comment]
@samreid improved the screenshot to have the player kicking, with the soccer ball in the air. Here's what was published:

![center-and-variability-screenshot](https://user-images.githubusercontent.com/5618316/163074209-17f46daf-8cba-48d0-82dd-539e26119544.png)

Leaving assigned to @amanda-phet to make the final screenshots to maintenance release with.

**Comment by chrisklus** [comment]
@samreid and i addressed all of the other issues for maintenance releasing 1.0, so will proceed with the maintenance release once we hear from @amanda-phet that this issue is ready to go.

**Comment by chrisklus** [comment]
@samreid and I deployed these changes for version 1.0.1, closing.
