### ISSUE TITLE
TypeScript review of a few files

### ISSUE THREAD

**Issue by chrisklus** [phetsims/center-and-variability#135]
Hey @jessegreenberg - could you please have a look at CAVModel.ts, SoccerModel.ts, CAVObject.ts, and CAVObjectNode.ts for general TypeScript review? Thanks!

**Comment by jessegreenberg** [comment]
These files look really nice! My comments are mostly very minor recommendations or questions for myself:

### CAVModel.ts
- [ ] For `CAVModelOptions` haven't seen the combination with an empty type before, is this necessary?
- [ ] The `merge` call is putting an entry on the `providedOptions` that is not allowed for in `SelfOptions`. I am not familiar with PhetioGroup, but is it OK to modify the `providedOptions` like this? If so, should this use `optionize`?
- [ ] Can `updateMeanAndMeadian` and `updateAnimation` be `private`, and should `step` be protected?
- [ ] `providedOptions` is not an optional argument currently, is that correct?
- [ ] Options `includeCards` and `instrumentMeanPredictionProperty` do not have defaults and are not optional, is that OK?

### SoccerModel.ts
- [ ] The `options` arg should be `providedOptions`. Also, should it be optional?
- [ ] Should `chooseDistribution` be private?
- [ ] There are a few missing return types for methods.
- [ ] I am unsure here, does the return type for `chooseDistribution` need to match the return type of the constants it returns? `CAVConstants.LEFT_SKEWED_DATA` is not a `ReadonlyArray` so I am surprised TypeScript is OK with this.
- [ ] Can `soccerBallLandedListener` be private?

### CAVObject.ts
- [ ] Should the options be optional or are they acting more like a config?
- [ ] Do we need the `any` in `CAVObjectIO.stateToArgsForConstructor`?

### CAVObjectNode.ts
- Looks really great, no comments!

Back to @chrisklus.

**Comment by samreid** [comment]
> and should step be protected?

I believe all 3 step must be public.
