### ISSUE TITLE
Add a keyboard help dialog

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#139]
Similar to https://github.com/phetsims/mean-share-and-balance/issues/32, it seems this sim should have a keyboard help dialog.

**Comment by marlitas** [comment]
Added keyboard help dialog, but in testing noticed that the PredictionNode is not instrumented for alternative input, and is a drag listener instead of what I assumed was a slider. Creating a new issue to address that.

**Comment by marlitas** [comment]
This issue is ready for review. @samreid or @matthew-blackman, take a look?

**Comment by samreid** [comment]
Looks really great, I tested the keyboard help dialog, and I tested moving the prediction orbs like sliders (including holding down shift.) Nice work, closing.
