### ISSUE TITLE
Design questions about dragging data points to the bucket in the lab screen.

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#14]
In the lab screen, when dragging a data point to the bucket, does it "detach" from the data set?  Does it start dragging continuously?

**Comment by samreid** [comment]
Like number line integers, as soon as it gets far enough away, it will detach.

**Comment by chrisklus** [comment]
@samreid can this issue be closed?

**Comment by samreid** [comment]
Perhaps leave it open and unassigned as a marker for when we get to that screen?

**Comment by samreid** [comment]
According to #1 there will no longer be a lab screen, closing.
