### ISSUE TITLE
Use string literal union enumerations instead of EnumerationValue

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#141]
From https://github.com/phetsims/axon/issues/373

**Comment by samreid** [comment]
In a recent discussion with @jessegreenberg, it seems like `EnumerationValue` has advantages over string literal union for searchability or refactoring.  So I'm inclined to leave this as it is for now.  @marlitas or @matthew-blackman sound OK?

**Comment by samreid** [comment]
Please note there are some TODO referencing this issue, which can be removed if we decide to close with wontfix.

**Comment by marlitas** [comment]
That makes sense to me. I'm good with closing.
