### ISSUE TITLE
support ?shuffleListeners

### ISSUE THREAD

**Issue by zepumph** [phetsims/center-and-variability#143]
From https://github.com/phetsims/axon/issues/215

**Comment by zepumph** [comment]
I'll see if we have more CT problems from here.

**Comment by zepumph** [comment]
Looking clear on CT this morning.

**Comment by samreid** [comment]
`listenerOrder=random(123)&fuzz` looks great in local testing, closing.

**Comment by samreid** [comment]
Oops, there is a daunting `hasListenerOrderDependencies` in the code.

**Comment by samreid** [comment]
This seems fixed now.  Closing.
