### ISSUE TITLE
Median soccer ball circled is incorrect

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#144]
The soccer ball(s) showing the median is circling the incorrect ball(s). The top graph (line plot or dot plot) is correct. See screenshot below. 
![Screenshot 2023-04-20 at 3 22 16 PM](https://user-images.githubusercontent.com/109630002/233491155-71285a76-81c8-45cc-ae86-c5021fa1840a.png)

Assigned @samreid, @marlitas, and @matthew-blackman, feel free to unassign if not involved.

**Comment by samreid** [comment]
@matthew-blackman said he will take a look, so I'll self-unassign for now.

**Comment by catherinecarter** [comment]
Looks great. Thank you! Closing.

**Comment by matthew-blackman** [comment]
Reopening for a code review @samreid or @marlitas

**Comment by samreid** [comment]
@matthew-blackman and I made further improvements, @matthew-blackman will double check on his side. Thanks!

**Comment by matthew-blackman** [comment]
Double-checked and behavior looks good, code looks good, closing!
