### ISSUE TITLE
PredictionNode should be instrumented for AlternativeInput

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#145]
In https://github.com/phetsims/center-and-variability/issues/139 I discovered the PredictionNode is not keyboard accessible. I was also surprised to discover it is not a slider. I think having this extend from a slider will help with alternative input functionality, and be more robust in general.

**Comment by marlitas** [comment]
PredictionNode now extends AccessibleSlider, and functionality seems to be working the same as before. However, when using keyboard input the slider does not stick the the 0.5 `roundToInterval` option, so there is still work to be done there.

**Comment by samreid** [comment]
I added options that seem to keep it in a good interval, @marlitas can you please review and test?

**Comment by marlitas** [comment]
Looks good! I was just curious about why we have to shift the keyboardStep by 0.1? That seems a bit magi numbery to me, but maybe that's typical for alt input?

**Comment by samreid** [comment]
If you hold down the shift modifier key, it makes it more "fine grained".

**Comment by marlitas** [comment]
Sounds good. I'm going to close this as completed then.
