### ISSUE TITLE
Keep play area arrow from overlapping the accordion box

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#146]
From https://github.com/phetsims/center-and-variability/issues/58

>  For the arrow pointing to the balls, it would have a max height that is just below the accordion box (so this is variable depending on whether the accordion box is expanded or collapsed).

Here is a horrible experimental/investigative patch to keep the play area arrow under the accordion box:

<details>

```diff

Subject: [PATCH] Prevent the median bar node from going off the top of the accordion box, https://github.com/phetsims/center-and-variability/issues/58
---
Index: js/common/view/MeanOrMedianScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/MeanOrMedianScreenView.ts b/js/common/view/MeanOrMedianScreenView.ts
--- a/js/common/view/MeanOrMedianScreenView.ts	(revision 20cfc6d90a6cba637dbb402439710d3f8f07f453)
+++ b/js/common/view/MeanOrMedianScreenView.ts	(date 1682081604195)
@@ -29,7 +29,7 @@
 export type MeanOrMedianScreenViewOptions = SelfOptions & SoccerScreenViewOptions;
 
 class MeanOrMedianScreenView extends SoccerScreenView {
-  private readonly accordionBox: CAVAccordionBox;
+  protected readonly accordionBox: CAVAccordionBox;
   protected readonly accordionBoxContents: Node;
 
   public constructor( model: SoccerModel, providedOptions: MeanOrMedianScreenViewOptions ) {
Index: js/common/view/CAVScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/CAVScreenView.ts b/js/common/view/CAVScreenView.ts
--- a/js/common/view/CAVScreenView.ts	(revision 20cfc6d90a6cba637dbb402439710d3f8f07f453)
+++ b/js/common/view/CAVScreenView.ts	(date 1682081731707)
@@ -189,12 +189,22 @@
 
         this.playAreaMedianIndicatorNode.centerX = this.modelViewTransform.modelToViewX( medianValue );
         this.playAreaMedianIndicatorNode.bottom = this.modelViewTransform.modelToViewY( 0 ) + viewHeight;
+
+        if ( this.accordionBox ) {
+          this.playAreaMedianIndicatorNode.top = this.accordionBox.bottom + 10;
+        }
       }
       this.playAreaMedianIndicatorNode.visible = visible;
     };
     model.medianValueProperty.link( updateMedianNode );
     model.objectChangedEmitter.addListener( updateMedianNode );
     model.isShowingPlayAreaMedianProperty.link( updateMedianNode );
+    this.visibleBoundsProperty.link( updateMedianNode );
+    setTimeout( () => {
+      if ( this.accordionBox ) {
+        this.accordionBox.expandedProperty.link( updateMedianNode );
+      }
+    }, 100 );
 
     this.medianPredictionNode = new PredictionNode( model.medianPredictionProperty, this.modelViewTransform, model.physicalRange, {
       center: this.layoutBounds.center,

```

</details>

**Comment by samreid** [comment]
This patch is much better, but it still doesn't work because the accordion box bounds don't change when it expands and collapses. I could use help here.

<details>

```diff

Subject: [PATCH] Update documentation, see https://github.com/phetsims/center-and-variability/issues/128
---
Index: js/common/view/MeanOrMedianScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/MeanOrMedianScreenView.ts b/js/common/view/MeanOrMedianScreenView.ts
--- a/js/common/view/MeanOrMedianScreenView.ts	(revision 84778c9c89f4c53854174dd4871e95d5fd5b7548)
+++ b/js/common/view/MeanOrMedianScreenView.ts	(date 1682174753263)
@@ -79,6 +79,14 @@
         valueReadoutsNode: options.isMedianScreen ? null : new ValueReadoutsNode( model )
       } );
     this.contentLayer.addChild( this.accordionBox );
+    this.accordionBox.boundsProperty.link( () => {
+      this.topOfUsablePlayAreaProperty.value = this.accordionBox.bottom + 5;
+      console.log( this.accordionBox.bottom );
+    } );
+    this.accordionBox.expandedProperty.link( () => {
+      this.topOfUsablePlayAreaProperty.value = this.accordionBox.bottom + 5;
+      console.log( this.accordionBox.bottom );
+    } );
 
     const BOTTOM_CHECKBOX_PANEL_MARGIN = 12.5;
 
Index: js/common/view/CAVScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/CAVScreenView.ts b/js/common/view/CAVScreenView.ts
--- a/js/common/view/CAVScreenView.ts	(revision 84778c9c89f4c53854174dd4871e95d5fd5b7548)
+++ b/js/common/view/CAVScreenView.ts	(date 1682174286936)
@@ -30,6 +30,7 @@
 import StrictOmit from '../../../../phet-core/js/types/StrictOmit.js';
 import Property from '../../../../axon/js/Property.js';
 import Range from '../../../../dot/js/Range.js';
+import NumberProperty from '../../../../axon/js/NumberProperty.js';
 
 type SelfOptions = {
 
@@ -64,6 +65,8 @@
   protected readonly medianPredictionNode: PredictionSlider;
   protected readonly meanPredictionNode: PredictionSlider;
 
+  protected readonly topOfUsablePlayAreaProperty = new NumberProperty( 0 );
+
   public constructor( model: CAVModel, modelViewTransform: ModelViewTransform2, providedOptions: CAVScreenViewOptions ) {
     const options = optionize<CAVScreenViewOptions,
       StrictOmit<SelfOptions, 'topCheckboxGroupOptions' | 'bottomCheckboxGroupOptions'>, ScreenViewOptions>()( {}, providedOptions );
@@ -186,12 +189,16 @@
 
         this.playAreaMedianIndicatorNode.centerX = this.modelViewTransform.modelToViewX( medianValue );
         this.playAreaMedianIndicatorNode.bottom = this.modelViewTransform.modelToViewY( 0 ) + viewHeight;
+        if ( this.playAreaMedianIndicatorNode.top < this.topOfUsablePlayAreaProperty.value ) {
+          this.playAreaMedianIndicatorNode.top = this.topOfUsablePlayAreaProperty.value;
+        }
       }
       this.playAreaMedianIndicatorNode.visible = visible;
     };
     model.medianValueProperty.link( updateMedianNode );
     model.objectChangedEmitter.addListener( updateMedianNode );
     model.isShowingPlayAreaMedianProperty.link( updateMedianNode );
+    this.topOfUsablePlayAreaProperty.link( updateMedianNode );
 
     this.medianPredictionNode = new PredictionSlider( model.medianPredictionProperty, this.modelViewTransform, model.physicalRange, {
       predictionThumbNodeOptions: {
Index: js/common/model/SoccerModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/SoccerModel.ts b/js/common/model/SoccerModel.ts
--- a/js/common/model/SoccerModel.ts	(revision 84778c9c89f4c53854174dd4871e95d5fd5b7548)
+++ b/js/common/model/SoccerModel.ts	(date 1682174541840)
@@ -212,7 +212,7 @@
     const weights = this.distributionProperty.value;
 
     assert && assert( weights.length === this.physicalRange.getLength() + 1, 'weight array should match the model range' );
-    const x1 = dotRandom.sampleProbabilities( weights ) + 1;
+    const x1 = 5;//dotRandom.sampleProbabilities( weights ) + 1;
 
     // Range equation is R=v0^2 sin(2 theta0) / g, see https://openstax.org/books/university-physics-volume-1/pages/4-3-projectile-motion
     // Equation 4.26

```

</details>

**Comment by samreid** [comment]
We implement this for the play area median arrow, @amanda-phet and/or @catherinecarter can you please test/review?  Please close if all is well.

**Comment by catherinecarter** [comment]
Looks great, thanks!

**Comment by samreid** [comment]
There is a problem that the arrow doesn't readjust if the screen size changes or the accordion box collapses/expands.

**Comment by samreid** [comment]
Fixed in the commit.  @marlitas and/or @matthew-blackman can you please review before we re-verify with @amanda-phet or @catherinecarter?

**Comment by marlitas** [comment]
I reviewed this as part of https://github.com/phetsims/center-and-variability/issues/197. 

In that issue I commented the following:

> The positioning gap no longer exists, but it does seem like it's too close now?

![image](https://github.com/phetsims/center-and-variability/assets/42476338/0c402784-fdbd-470e-9564-b65ac700d01d)

Feels like that comment is better suited in this issue for review by @catherinecarter and @amanda-phet

**Comment by catherinecarter** [comment]
I think the red highlight got thicker. Here's a shot of what's in the published prototype: 
![image](https://github.com/phetsims/center-and-variability/assets/109630002/f0a9bd00-1f2f-4d44-8c66-ba0074beb06e)

And here's what's in development:
![image](https://github.com/phetsims/center-and-variability/assets/109630002/4a485057-a15b-46fb-b6ae-102f31e4fc37)

So I notice three things:
1. The width of the outline is thicker, and 
2. The overlap has changed. The bottom ball's outline layered on top, and the upper ball's outline layered behind at the bottom but on top at the top. 
3. The outline in the top image layers in front of the number line tick mark while the image on the bottom has the tick mark layered in front of the outline.

The behavior and layering in the published sim seems to be nice. The arrow pointing into the red outline is not an issue for me, especially if we reduce the thickness of that stroke.

**Comment by samreid** [comment]
Based on the comments above, it seems the recommendations are: 

- [ ] Reduce the stroke width to what it used to be.  In slack @marlitas said:  I did a very small commit relating to the outline width that I’ll point to 146,
- [ ] The z-order of the circles should be changed so that the lower balls highlight circles are in front. This will be difficult since we adjusted the z-ordering of the soccer balls in https://github.com/phetsims/center-and-variability/issues/175 so that higher soccer balls are in front.  Currently the highlight region is in the same layer as the soccer ball, so the z-orders are tied together.  How important is it to decouple these? If it's important, should we move the red highlights to a completely separate layer so its z-order can be controlled independently?
- [ ] Move the tick mark in front of the red outline.

**Comment by marlitas** [comment]
> Reduce the stroke width to what it used to be. In slack @marlitas said: I did a very small commit relating to the outline width that I’ll point to 146,

I forgot to push the commit for that... pushed above.

**Comment by marlitas** [comment]
> The z-order of the circles should be changed so that the lower balls highlight circles are in front. This will be difficult since we adjusted the z-ordering of the soccer balls in https://github.com/phetsims/center-and-variability/issues/175 so that higher soccer balls are in front. Currently the highlight region is in the same layer as the soccer ball, so the z-orders are tied together. How important is it to decouple these? If it's important, should we move the red highlights to a completely separate layer so its z-order can be controlled independently?

I was also concerned about this and I think it would be useful to chat with design team about this directly. Marking for design: meeting.

**Comment by catherinecarter** [comment]
I am wondering if making the distance between soccer balls 0.00 rather than 0.04 would solve the issue. Is this a quick fix, or should I mock up some options as mentioned this morning?

**Comment by marlitas** [comment]
This is with 0.00 soccer ball overlap.

Here are three different situations showing that behavior.
<img width="386" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/d9dad9f8-efb9-4a8f-a62d-f60eee72f88a">

<img width="232" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/7fbcb06a-ccc1-41d4-96bc-74f61c517125">

<img width="283" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/ebea2a74-9f47-405d-82d4-4204f6391274">

**Comment by matthew-blackman** [comment]
The arrow no longer overlaps with the accordion box, closing this issue to continue further z-index and ball-overlap work in https://github.com/phetsims/center-and-variability/issues/200
