### ISSUE TITLE
Allow up to 30 data points screens 2-3

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#148]
I uncommented the VariabilityScreen and saw an error. Apparently it was trying to load 20 characters and we only have 15.  So for now, I copy/pasted the last character 5x more times.

In slack, I said:

> A note in the code says we were going to have 20 soccer balls on screen 3. Is that still correct?

@kathy-phet replied:

> Yes - I recall that was the plan.
> To really get a sense of a distribution and a skewed distribution.

Assigning to @catherinecarter and @amanda-phet to confirm, and to plan the artwork.

**Comment by samreid** [comment]
@amanda-phet said:

> thought we decided on 15 all around? @catherinecarter and I have talked about this a lot and 20 would be great but I thought they wouldn't fit anymore.

**Comment by samreid** [comment]
Fixed, closing.

**Comment by samreid** [comment]
@amanda-phet said:

> Well 20 would be great! It would mean that we can get in a situation where it's not possible to see all 20 (right now 15 fit in a stack). But if the team is ok with that then I know CC will be very happy to have 20.

Reopening. Let's discuss or confirm this soon.

**Comment by samreid** [comment]
@kathy-phet said:

> Let’s see if we can find a solution for 20, but we can start with 15 and get the base functionality in.

**Comment by samreid** [comment]
Thanks, I opened https://github.com/phetsims/center-and-variability/issues/154 about the 4 kickers and artwork.

**Comment by samreid** [comment]
@kathy-phet said:

> Braindump on an idea - building off of the ideas from yesterday re PhET-iO set up and other goals:
Have a max number of static number of "balls"/"data points" possible (say 20 or 30). In preferences menu (and a query parameter), be able to choose the "Max number of kicks" (as spinner with default being 15 - current). This max kicks will effectively limit the number of balls (if kicking), but doesn't change the size of the PhET-iO array that is max number of balls.

**Comment by catherinecarter** [comment]
I asked Marilyn and Kelly, both of whom were on the original pedagogy team, about the number of kicks possible. 

My email:
> Considering the benefits of exploring both an even and odd number of kicks, we're curious about your thoughts regarding the default number of kicks. 
> Options for Median&Mean and Variability screens: 
> 1. Default = 15 kicks with options to change to 20, 25, 30 (four total choices)
> 2. Default = 20 kicks with options to change to 15, 25, 30 (four total choicees)
> 3. Default = 20 kicks with options to change to 25, 30 (three total choices)

Marilyn's reply: 
> I think I value option #1 the most. Starting with 15 kicks means students will see a median that is concrete right away and while it may not have the variability we seek to illustrate initially, it will be easy to see once students add more kicks. I also think having four total options where two data sets have an even number of data points and two sets with an odd number of data points is ideal. 

Kelly's reply (I mentioned what David Webb said, that many teachers wished there were more kicks available): 
> I also think 15 feels slightly limiting. I remember having a conversation about that and worrying about having too high a stack potentially if we go higher than 15. I don't know how much of a problem that is, but it would be nice if >15 was an option.
> I don't know if I have much opinion of those options. My gut says the default should start at 15 since that's what they saw on the previous page, and then have the option to increase. But I'm not sure if there are arguments for starting at 20. So weight that opinion rather low, and the other options also seem very reasonable.

**Comment by samreid** [comment]
With more data points, we may need to revisit when/how the blue "drag" arrow indicator is shown.

**Comment by samreid** [comment]
From today's design meeting:

We would like to try the idea:

> Default = 15 kicks with options to change to 20, 25, 30 (four total choices)

And this would be changed in preferences.  If you change this value, it would only change the max number on screens 2-3 (not on median screen because of the card limit, and it's not necessary there for the learning goals).  Do we need a message "some may go offscreen"?  Probably not, because the user is the one responsible for creating such a large stack.

**Comment by samreid** [comment]
@catherinecarter said:

> I was looking at my notes and remembered in the last design meeting, I was going to see what it might look like to have a pull-down menu with options for max number of kicks. Here’s one idea with increments of 5 max. Initial thoughts?

<img width="899" alt="image" src="https://user-images.githubusercontent.com/679486/236700708-3e9be90d-914a-4723-ae30-429757ed5dc0.png">

<img width="897" alt="image" src="https://user-images.githubusercontent.com/679486/236700716-8bdb07c9-d7e9-4578-bae4-2c286eaa7048.png">

I replied:

> Maybe a “max kicks” label outside the box, then the combo box can show its selected number?

And @kathy-phet and @amanda-phet reacted with ➕ 

@catherinecarter said:

<img width="890" alt="image" src="https://user-images.githubusercontent.com/679486/236700746-00a89a00-d9c6-4620-ae4e-3abc760fe9ed.png">

<img width="891" alt="image" src="https://user-images.githubusercontent.com/679486/236700758-3d5ef410-898a-4732-8622-c007cc576a10.png">

> or something like this:

<img width="225" alt="image" src="https://user-images.githubusercontent.com/679486/236700765-f3dda364-2ea3-4799-8d25-f4b60fbf6004.png">

I wrote:

> The combo box with outside label looks clearer and more usable to me

@catherinecarter said:

> Here’s what it would look like with the new artwork (I have the number slider in there in this shot since I didn’t include the entire picture):

<img width="905" alt="image" src="https://user-images.githubusercontent.com/679486/236700783-84ce1312-4acc-44b4-9338-2419a8aa77f2.png">

@kathy-phet replied:

> I like the combo box better too. Very clear, and we have a better choice as to what to do when they select a new value. We can either
> * Clear all the balls (e.g. they start over)
> * Remove the last "n" balls, if Max>current number of balls
> The slider it is more confusing. And sliders are good when there is an immediate response ... which isn't the case here ... there is not immediate dynamic feedback/relationship you are trying to build here.

**Comment by amanda-phet** [comment]
I think this brings up an important question about the model. Is each individual ball's distance calculated with each kick? Or are all 15 calculated at the same time? I thought I remembered hearing that all 15 distances are calculated before the 15 kicks occur. If that's the case, I would think switching between different maximums could lead to some weirdness if we don't reset the kicks each time that value is changed. But I will admit, when I played with the sim and changed the values, I was bummed that I lost my data and had to kick the balls again. 

Another question that I'm thinking about is how often someone will want to change this value. Is it useful to change it often? Or do we think users will want to set it and forget it? Every time you reset the sim, that value will reset. However if it lives in preferences, it won't be reset.

**Comment by samreid** [comment]
OK I moved to the preferences dialog, and it always clears data on change. @amanda-phet and @catherinecarter can you please review/test and let us know what recommendations you have?

**Comment by catherinecarter** [comment]
Looks really great to me! The checkboxes remain in their current state, the number of kicks increases for both the 2nd and 3rd screen, and the query parameter is really nice. I tried to say ?maxKicks=22, and I got a nice error dialog box letting me know 22 was not an allowable number of max kicks. My only recommendation is to have the error dialog say how many kicks the default is (currently it tells me default values will be used, but doesn't tell me how many this is, or what values are allowed). 

Is there value in also saying, "You can change the max number of kicks in the preferences menu." Or something like that to point users to where they can change this and see possible values that are valid?

**Comment by samreid** [comment]
Thanks, I opened a Joist issue about the dialog recommendations.  @catherinecarter do you feel that is critical for this release, or ok to publish without it?  If it is critical for this release, let's open an CAV issue to track the joist one.  If not, let's close this issue and https://github.com/phetsims/joist/issues/923 can be worked on independently (if at all).

**Comment by catherinecarter** [comment]
I don't think the error dialog should block publication. Thanks for opening it and considering it as an option!

**Comment by samreid** [comment]
Thanks, closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
