### ISSUE TITLE
Evaluate "centralized code with options" vs "extendable base classes" for this sim

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#153]
While implementing https://github.com/phetsims/center-and-variability/issues/149, it seems the sim is more based on options and having parent types implement things (like the accordion box), but this is making it difficult to adjust and customize for the Variability screen. For instance, we need to add different checkboxes, an info button and move the left edge to the right.  Should all of this be through options, or should the VariabilityScreenView create its own CAVAccordionBox that it customized appropriately?  I want to discuss this with @marlitas and/or @matthew-blackman before working on it, because there are tradeoffs either way and it would be good to discuss before spending a lot of time on it.

**Comment by samreid** [comment]
This issue has some overlap with https://github.com/phetsims/center-and-variability/issues/152

**Comment by marlitas** [comment]
Completed the readouts in accordion boxes. Over to @samreid for review, and perhaps closing this off together.

**Comment by samreid** [comment]
Commits above look good. The proposed changes in #170 also match this pattern. I feel this issue can be closed.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by samreid** [comment]
All TODOs addressed. Ready for review.  In my opinion, I feel there are still some places that could use refactoring like this, but we can address them if/when discovered. @marlitas can you please review recent commits and close if all is ok?

**Comment by marlitas** [comment]
Reviewed with @samreid. Any other work regarding this topic will be done on an as-needed basis. We are ready to close.
