### ISSUE TITLE
Add artwork for the 4 different kickers on the Variability screen

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#154]
Somewhat related to https://github.com/phetsims/center-and-variability/issues/148, the design doc shows a character with a number jersey for the Variability screen.

**Comment by amanda-phet** [comment]
@catherinecarter and I exported and named the files for the kickers for this screen. We think they are ready to go! @catherinecarter also updated the ai asset. 

[variability kickers.zip](https://github.com/phetsims/center-and-variability/files/11408380/variability.kickers.zip)

Next steps: @catherinecarter is refining how the scene selection buttons should look and will open an issue for that once those are ready.

**Comment by catherinecarter** [comment]
Mariah made the colors with the numbers different than the mockups. 
![image](https://user-images.githubusercontent.com/109630002/236544072-70d66721-e87f-4df3-9fe4-b9239dedcea0.png)

The scene selection buttons will need to match the color of the new characters, and the number on the shirts will need to match the kickers (which with a black border). Something like this: 
![image](https://user-images.githubusercontent.com/109630002/236544306-f57b5e71-1a6c-470a-8f3e-e73275fae198.png)

Let me know if a .png is needed, or if these can be done in code.

**Comment by samreid** [comment]
I'll work on this

**Comment by samreid** [comment]
I implemented this, and committed it, but the push keeps timing out.

```
~/apache-document-root/main/center-and-variability$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
~/apache-document-root/main/center-and-variability$ git pull
Already up to date.
~/apache-document-root/main/center-and-variability$ git push
Enumerating objects: 47, done.
Counting objects: 100% (47/47), done.
Delta compression using up to 8 threads
Compressing objects: 100% (36/36), done.
Writing objects: 100% (36/36), 1.43 MiB | 443.00 KiB/s, done.
Total 36 (delta 11), reused 0 (delta 0), pack-reused 0

[[process hangs]]
```

**Comment by samreid** [comment]
OK I pushed an initial draft. I'd like to discuss with @marlitas and @matthew-blackman whether we should:

* Reimplement the model so that in the variability screen has 1 SoccerPlayer model that kicks over and over

or

* Use the same strategy as screens 1-2 where there is a line of kickers. In this case, the kickers are clones of each other (currently implemented)

**Comment by marlitas** [comment]
hmmm... as weird as the second strategy seems... I kind of like it, and it's not affecting UX at all. Changing the model to work with only one soccer player in the third screen seems unnecessarily annoying...

**Comment by samreid** [comment]
Sounds good, and I agree. I also created `getSoccerPlayerImageSet` to make it easier for each screen to depict the soccer players.  Closing.
