### ISSUE TITLE
Variability Screen icon

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#155]
We need an icon for the variability screen. How should it look? Want to draw it in the code or with an image file?

**Comment by catherinecarter** [comment]
I think this is the one we're going with: 
![image](https://user-images.githubusercontent.com/109630002/236055535-d9c929f0-e51c-42c1-801f-d3833689f4e6.png)

If it's easier to do in code, yes, please do that. The median arrow should match the one on the M&M screen icon.

**Comment by catherinecarter** [comment]
Looks great! Thanks! 

Close if all is well on your side.

**Comment by samreid** [comment]
Double checking if we prefer this in code or PNG-- @marlitas and @matthew-blackman what do you recommend and why?

**Comment by matthew-blackman** [comment]
I went with PNG for two reasons:

1. The other screen icons are done this way, and the 'Mean and Median' screen looks like it could have been done via code.
2. It is much faster to implement design changes if the designers can make an updated png file.

Thoughts @samreid ?

**Comment by matthew-blackman** [comment]
3. The image is 4 KB, which seems small enough that any load time benefits of drawing via code would be negligible.

**Comment by marlitas** [comment]
I think code provides more flexibility for changes in the future, but png is consistent with the other icons... It would be a little odd to me if they are implemented differently...

**Comment by samreid** [comment]
At some point, will we decide to make adjustments, like making these arrows look consistent in the icons?  If so, we may want to put all the icons in code.  If not, then PNGs are probably ok.  Or we could make things look consistent in the PNGs. 

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/679486/236286686-5dea6262-2837-4c77-aad6-1e9361cf3bed.png">

I don't think it would be too difficult to do all icons in code. But not sure it is worth that time.  I'm ok to close if you are.

**Comment by amanda-phet** [comment]
It's not unusual for screen icons to be PNGs, and I don't see a good reason for these to be in code.

**Comment by samreid** [comment]
Reopening to see if it it auto-adds to the project board.
