### ISSUE TITLE
What is the minimum number of data points to show the IQR and its computation?

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#157]
We require at least 1 data point to show the range.  The design doc says you need at least 5 points. But you can compute IQR with a single data point.  Can you show a box plot with 4 data points?

**Comment by catherinecarter** [comment]
The minimum number is 5. The box plot is created using the "5-number summary," which is the: min, Q1, median, Q3, and max. They're all quartiles, with the min being quartile 0, quartile 1 is the end of the first 25% of the data, median is quartile 2 (end of the first 50%), quartile 3 is the end of the first 75% of the data, and the max is the end of 100% of your data. 

So to answer your question, you do need 5 data points (minimum) to plot a box plot.

**Comment by samreid** [comment]
Assigning to @matthew-blackman since he volunteered for #158

**Comment by samreid** [comment]
That's great, thanks!  Closing.
