### ISSUE TITLE
Ball positionProperty and valueProperty are not tied together ( PhET-iO )

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#159]
During a CaV PhET-iO meeting we noticed that you can set the value of the ball's position in studio, but that does not update the ball's value.

**Comment by samreid** [comment]
Today we saw that changing `valueProperty` had the correct behavior. Let's just mark `positionProperty` as readonly.

**Comment by samreid** [comment]
OK I made soccerBall.positionProperty read-only and confirmed in studio. I also tested that changing `soccerBall.valueProperty` correctly moves the soccer ball.  @marlitas can this issue be closed?

**Comment by marlitas** [comment]
Yup! That looks good. Closing.
