### ISSUE TITLE
Adjust colors if necessary

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#161]
I added grayDataPointFill to the color wrapper. There was a note:

```
// TODO-design: This is the color from the design doc, but perhaps #777777 or darker would be better? Let's discuss once the IQR lines are drawn
```

Anyways, this issue is about finalizing this color and making adjustments to other colors.  No need to wait until the sim is fully ready, let's do our best now and we can always update it later on.

**Comment by catherinecarter** [comment]
Once we decide on the order of all the layers (number line, dots, yellow spread tool, calculated spread colors, boxplot, etc., we can decide on the color of the dots to make sure they're viewable but not impeding the important conceptual tools on each radio button scene.

**Comment by catherinecarter** [comment]
In order from back to front (within the accordion box): 
1. Interval Tool
2. Dots/x's 
3. Measure of Spread rectangles
4. Plot (boxplot, MAD horizontal bars)

I'm curious how this looks (with the dots behind the spread rectangle indicator. If it looks weird, we may want to switch the order of 2 and 3 above. Thanks!
