### ISSUE TITLE
Wording for the MAD description

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#163]
I said:

> We discussed phrasing it as “MAD is the average distance between each point and the mean.” however, that seems too easy for someone to misread and think it is about distance between points. So should I leave it as “MAD is the average distance from each point to the mean.“?

@catherinecarter said:

> I like putting the mean as the starting point, let’s switch the order: “MAD is the average distance from the mean to each point.”
I’ll email Marilyn to confirm.
> I confirmed with Marilyn, the design doc wording is the way to go. “MAD is the average distance each data point is from the mean.”
> She said this is how it should be worded, and then teachers can unpack what it means using more informal language. The informal language varies from teacher to teachers, so this more formal language is the grounding definition.

I replied:

Thanks, I updated it in this commit. https://github.com/phetsims/center-and-variability/commit/33b2eb0618046788176b74e20ca697c2ee5a91f9. I’m still trying to identify why it bothered me in the first place.  I guess for me it’s like the difference between these 2 sentences:
* 5 meters is the distance the car is from the house
* 5 meters is the distance from the car to the house

To me, the latter is much easier to parse, understand and convey, even for middle schoolers. I don’t see the advantage at all of the top sentence.  But I’ve committed it and if I’m the only one that feels this way, we should move on.

**Comment by catherinecarter** [comment]
We can definitely discuss this with others at the design meeting. For context, here is an email exchange between me and Marilyn Hartzell, who was a part of the original pedagogy team. 

My email: 
> On the MAD screen, students can press an "Info" button to see how the MAD is calculated. I'm curious about how you would word the definition of the MAD. In my high school experience, we word it like this, "MAD is the average distance each data point is from the mean." My definition may be confusing for 6th graders. Can you help me word the MAD definition? 

Her reply: 
> For the wording I would use the same that you described as my initial definition. Then I would break it down into less formal language. Something along the lines of, “basically the MAD let’s us know how far away the data is from the mean, it helps us to know if the data is bunched/close together when the MAD is small or when the data is spread out when the MAD is a larger number”. The exact wording can be adjusting but I definitely talk about distance using less formal language and refer to the average as the mean. Standardized testing always asks about the mean and the not the average in the middle grades, so they are more familiar with “mean” than “average”.

**Comment by amanda-phet** [comment]
Removing the meeting label, since this has already had enough time and careful consideration, with people weighing in. I agree with @catherinecarter 's final definition.

**Comment by samreid** [comment]
Updated, closing.
