### ISSUE TITLE
On the variability screen, each player sets a different "scene" and remembers its data

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#164]
From today's design meeting: On the variability screen, each player sets a different "scene" and remembers its data

**Comment by samreid** [comment]
We will likely rename CAVModel => CAVSceneModel and pull out appropriate parts to a new CAVModel, which has 1+ CAVSceneModels.

**Comment by samreid** [comment]
Clarifying some behavior before we get too far on this:

* Are the checkbox selections Variability/Median/Mean/Range shared across scenes?
* Is the accordion box expand/collapse state shared across scenes?
* Is the measure radio button Range/IQR/MAD shared across scenes?

The only mention I saw in the design doc regarding different scenes for the different t-shirts said this, so it would be good to clarify:

> If the user switches to a different player, they will encounter the same flow again

Next question: if the user kicks soccer ball "A" in t-shirt-1, then switches to t-shirt-2, then switches back to t-shirt-1, will the soccer ball "A" still be flying through the air? (It would be paused when on another scene)?

Does the clear button clear all the scenes or just the selected scene?

**Comment by samreid** [comment]
From today's design meeting:

* This should only change the data.  Other settings and accordion box state, etc should remain as they were. This will help someone compare a measure across the different players.
* When you switch away from a player, the non-selected players pause.  (If this leads to difficulty/complexity, we can reconsider).
* The clear button just clears the selected player

**Comment by samreid** [comment]
The main work for this issue is complete. But let's review and also check @kathy-phet comments in https://github.com/phetsims/center-and-variability/issues/164#issuecomment-1531735225 to see if there is more to do.

**Comment by samreid** [comment]
I opened an issue specifically for the PhET-iO design for scenes and @kathy-phet's comment above. https://github.com/phetsims/center-and-variability/issues/193

Let's complete this issue with a code review.

**Comment by marlitas** [comment]
- [ ] Left some TODO's mentioning this issue (mostly regarding file documentation). 

- [ ] This code seems messy to me:

```js
 // TODO: See https://github.com/phetsims/center-and-variability/issues/153
    const varModel = model as VariabilityModel;
    const varSceneModel = sceneModel as VariabilitySceneModel;

    // TODO: Do we want this information in the model? Do we want one player that re-kicks, or a list of clones? https://github.com/phetsims/center-and-variability/issues/154
    const isVariabilityModel = !!varModel.isInfoShowingProperty;
    let sceneIndex = 0;
    if ( isVariabilityModel ) {
      sceneIndex = varModel.variabilitySceneModels.indexOf( varSceneModel );
    }
...
if ( varModel && varModel.isInfoShowingProperty && varModel.selectedSceneModelProperty && varSceneModel ) {
      const infoDialog = new InfoDialog( varModel, varSceneModel, {
        tandem: options.tandem.createTandem( 'infoDialog' )
      } );

      Multilink.multilink( [ varModel.isInfoShowingProperty, varSceneModel.isVisibleProperty ],
        ( isInfoShowing, isVisible ) => {
          if ( isInfoShowing && isVisible ) {
            infoDialog.show();
          }
          else {
            infoDialog.hide();
          }
        } );
    }
```

and I agree with the TODO, that a lot of that info should be in the model. Type casting the model, as well as checking the type of the model seems brittle to me, and very tricky. Perhaps this work can be moved out to https://github.com/phetsims/center-and-variability/issues/153, but it does feel related to the scene separation that was happening in this issue, and worth mentioning.

Otherwise the scenes seem to be working properly overall, and nothing else stood out as problematic or concerning in the changes. 

Back to @samreid.

**Comment by marlitas** [comment]
Just pushed the TODOs up. Sorry for that delay.

**Comment by samreid** [comment]
Thanks, I added some documentation, and addressed the variabilityModel problems in https://github.com/phetsims/center-and-variability/issues/153.  I added a new TODO that I could use help with.  Back to @marlitas for re-review and discussion.

**Comment by marlitas** [comment]
Addressed TODO. Closing as completed.
