### ISSUE TITLE
The newly landed ball should animate to the top of the stack

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#165]
From discussion in https://github.com/phetsims/center-and-variability/issues/125, after changes in that issue, we will need to make the recently-landed ball animate to the top of the stack.  That's so that when you drag anywhere in the stack, (thus making the topmost ball move), it corresponds to the rightmost card.  Likewise, the 2nd from the top ball would correspond to the 2nd from the right card.

**Comment by samreid** [comment]
Mostly fixed, but I left one TODO for a part I don't understand and need help with.

**Comment by samreid** [comment]
Also, when landing, the balls sort of "click" into place awkwardly.

**Comment by marlitas** [comment]
> Also, when landing, the balls sort of "click" into place awkwardly.
I am not seeing the "clicking" into place behavior.

**Comment by samreid** [comment]
Thanks! I resolved that part by adding a listener to occur after the soccer ball landed in https://github.com/phetsims/center-and-variability/commit/4ca92aa8020b7ed801dd42a222f5e3b050cbebe6

**Comment by matthew-blackman** [comment]
I'm not seeing the "clicking" behavior on my end either, so that look resolved. Nice job!

I noticed that the stacking movement speed of the balls looks awkward because the animation time is fixed, independently of the distance that the balls animate. I tried out the following change in the animateSoccerBallStack function in CAVSceneModel, and it looks like an improvement to the overall animation look and feel. Thoughts @samreid @marlitas?

```
const animationTime = 0.06 * this.getStackAtLocation( value ).length;

    if ( soccerBall.animation ) {
      soccerBall.animation.stop();
    }
    soccerBall.animation = new Animation( {
      duration: animationTime,
      targets: [ {
        property: soccerBall.positionProperty,

        // TODO: Without rounding, the soccer ball stacks are lopsided. Why? See https://github.com/phetsims/center-and-variability/issues/165
        to: new Vector2( Utils.roundSymmetric( soccerBall.positionProperty.value.x ), targetPositionY ),
        easing: Easing.QUADRATIC_IN_OUT
      } ]
    } );
```

**Comment by matthew-blackman** [comment]
@samreid @marlitas and I reviewed the latest commits and believe this issue is complete from a dev perspective.

Assigning to the design team for testing and a review of the ball animation speed.

**Comment by catherinecarter** [comment]
Looks good to me, I don't see any obvious bugs. The speed looks good, and the cards on the Median screen seem to follow the ball on the top of the stack.

**Comment by samreid** [comment]
@matthew-blackman and I worked on this some more, and this led us to an improvement for https://github.com/phetsims/center-and-variability/issues/186, which is working much better now.  The main behavior here is working as prescribed and @matthew-blackman will open a side issue about testing corner cases.
