### ISSUE TITLE
AccordionBox layout (info button and dot plot)

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#166]
We created https://github.com/phetsims/sun/issues/843 in sun, because we would like to remove this line of hacky code in `CAVAccordionBox`:

```js
    backgroundNode.localBounds = backgroundNode.localBounds.copy();
```
This code currently provides a workaround that allows us to render the info button and dot plot points on top of the `titleNode` in `AccordionBox`

**Comment by samreid** [comment]
Closing as duplicate of https://github.com/phetsims/center-and-variability/issues/170

**Comment by samreid** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by samreid** [comment]
Closing, we will work on this in #170
