### ISSUE TITLE
Rounding numbers for the MAD calculation

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#169]
The design doc says:

> Case for MAD calculation
1.01 + 1.01 + 1.01 + 1.01 + 1.01 + 1.01 + 1.01 = 7.07
1.0 + 1.0 + 1.0 + 1.0 + 1.0 + 1.0 + 1.0 = 7.1
> 
> Example of ball positions for MAD 
(1 + 1 + 1 + 1 + 1 + 1+ 1)/7 = 7/7 = 1
> 
> Do 6th graders know the approximate symbol? ()

The written consensus says:

> Adjust one of the values’ number of decimal places.
> Test this situation and see how it goes.

**Comment by samreid** [comment]
@catherinecarter can you please clarify the consensus for this?

**Comment by catherinecarter** [comment]
I believe from the design meeting that people were ok with adjusting a value if the sum didn't match the rounded addends (that's what I meant by 'consensus'). Additional options to consider:

1. For 12 values or fewer (this number is somewhat arbitrary), display 2 decimal places to alleviate the rounding issue. Then, for 13 values or higher, show one decimal place and adjust if needed.
2. Show tenths only for all values, and have an asterisk indicating values might not match due to rounding error
3. Detect when the sums don't match, and adjust an addend if needed

@amanda-phet and I agree that the values shown on the horizontal distances need to match the addends shown. Adjusting an addend without adjusting a distance might be confusing for students. And having a stack of balls with different distances shown might also be confusing. 

Can we create some of these situations intentionally to see what the code might do to adjust the rounding error creating a rounded sum different than the rounded addends?

**Comment by samreid** [comment]
From today's meeting, we would like to try option (2) from above. Values in the sum will match the horizontal distances exactly, but a note that the sum (left hand side) may not equal the total (right hand side).  Even better, only show the asterisk if it doesn't add up (asterisk by the total, footnote below).

**Comment by samreid** [comment]
Progress on the "dynamic footnote" idea.  Still needs the footnote at the bottom to be shown/hidden dynamically.  But I'm surprised this is happening very frequently (almost every single run).  Due to the frequency, I'm wondering if we should explore other solutions, perhaps see how frequent it is with 2 decimal places?  Anyways, here's the patch so far:

<details>

```diff

Subject: [PATCH] Show tenths for MAD, see https://github.com/phetsims/center-and-variability/issues/169
---
Index: js/variability/view/MADInfoNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/variability/view/MADInfoNode.ts b/js/variability/view/MADInfoNode.ts
--- a/js/variability/view/MADInfoNode.ts	(revision fc4522e6013826c64fe15cd45c79c145524ab36d)
+++ b/js/variability/view/MADInfoNode.ts	(date 1683943821047)
@@ -26,6 +26,8 @@
     const resultNumeratorText = new Text( '', { fontSize: 16 } );
     const resultDenominatorText = new Text( '', { fontSize: 16 } );
 
+    const footnoteAsterisk = new Text( '*', { fontSize: 16 } );
+
     sceneModel.objectChangedEmitter.addListener( () => {
       const values = sceneModel.getSortedLandedObjects().map( landedObject => landedObject.valueProperty.value! );
       const mads = values.map( value => Math.abs( value - sceneModel.meanValueProperty.value! ) );
@@ -37,6 +39,17 @@
       const sum = _.reduce( mads, ( sum, mad ) => sum + mad, 0 );
       resultNumeratorText.string = Utils.toFixed( sum, 1 );
       resultDenominatorText.string = values.length.toString();
+
+      const leftHandTerms = madStrings.map( Number.parseFloat );
+
+      const leftHandSum = _.reduce( leftHandTerms, ( sum, term ) => sum + term, 0 );
+      const rightHandSum = Number.parseFloat( resultNumeratorText.string );
+
+      const footnoteVisible = Math.abs( leftHandSum - rightHandSum ) > 1E-6;
+      if ( footnoteVisible ) {
+        console.log( 'values do not match: LHS = ' + numeratorText.string + ' = ' + leftHandSum + ', but RHS = ' + rightHandSum + ' = ' + resultNumeratorText.string );
+      }
+      footnoteAsterisk.visible = footnoteVisible;
     } );
 
     const calculationFraction = new VBox( {
@@ -63,21 +76,35 @@
           maxWidth: CAVConstants.INFO_DIALOG_MAX_TEXT_WIDTH,
           layoutOptions: { bottomMargin: 10 }
         } ),
+
+        // Show the footnote to the top right of the errant equation, if they don't match. I tried a ManualConstraint
+        // for this, but it went into an infinite loop.
         new HBox( {
-          spacing: 10,
-          children: [
-            new Text( CenterAndVariabilityStrings.madEqualsStringProperty, { fontSize: 18 } ),
-            calculationFraction,
-            new Text( MathSymbols.EQUAL_TO, { fontSize: 18 } ),
-            resultFraction
-          ],
-          visibleProperty: hasEnoughDataProperty
+          spacing: 6,
+          align: 'top',
+          children: [
+            new HBox( {
+              spacing: 10,
+              children: [
+                new Text( CenterAndVariabilityStrings.madEqualsStringProperty, { fontSize: 18 } ),
+                calculationFraction,
+                new Text( MathSymbols.EQUAL_TO, { fontSize: 18 } ),
+                resultFraction
+              ],
+              visibleProperty: hasEnoughDataProperty
+            } ),
+            footnoteAsterisk
+          ]
         } ),
 
         new Text( new PatternStringProperty( CenterAndVariabilityStrings.madCalculationResultPatternStringProperty, {
           mad: new DerivedProperty( [ sceneModel.madValueProperty ], madValue => madValue === null ? null : Utils.toFixed( madValue, 1 ) )
         } ), { fontSize: 18, visibleProperty: hasEnoughDataProperty, maxWidth: CAVConstants.INFO_DIALOG_MAX_TEXT_WIDTH, layoutOptions: { bottomMargin: 10 } } ),
 
+        new Text( 'Values may not match due to rounding errors.', {
+          fontSize: 12
+        } ),
+
         new MADNode( model, sceneModel, {
           parentContext: 'info',
           tandem: options.tandem.createTandem( 'madNode' )

```

</details>

**Comment by samreid** [comment]
I implemented the dynamic footnote, and it console.logs when it occurs when using ?dev.  Ready for dev review, then we can bring it back to the design team.

**Comment by samreid** [comment]
From today's meeting, we would like to try it with 2 decimal places.  But the main consideration is when you have 30 data points, that will be a lot of horizontal space.

**Comment by matthew-blackman** [comment]
Reviewing this with @samreid and @marlitas, we were unsure if there was a final decision here. @catherinecarter do you mind clarifying the desired behavior of the numbers in the MAD calculation?

**Comment by samreid** [comment]
In discussion with @catherinecarter, we affirmed that the consensus decision is at the end of this comment: https://github.com/phetsims/center-and-variability/issues/169#issuecomment-1549934918 and we feel we cannot have more than 1 decimal point because it is too long for 30 data points.

@catherinecarter surmises that when a student calculates the MAD, they may round "as they go" anyways, and hence their computation would match what is happening in the simulation. However, @matthew-blackman and I are concerned that calculating it that way is still incorrect.  For instance, the true MAD could be 2.4 but the sim shows 2.3. @catherinecarter said it could bother certain teachers, but it doesn't bother her as much, because it is easy to explain. But she recommends waiting until we get complaints on phethelp.

But we used this opportunity to re-discuss the idea of "use one decimal place for all terms, and if it is consistent and correct, use it.  If not correct, add another decimal place" etc. But we don't know how many decimal places may be eventually needed, and showing more than one decimal place for the 30 data points doesn't sound good.

But it's a 6th grade sim, and we would like to keep it simple (round as you go) for this case.  But we can reopen if we get reports from teachers etc.

@matthew-blackman points out this problem is subject to appear in any quantitative sim that shows a calculation like this. We may need a more general discussion about how we handle this generally.  @catherinecarter points out that consideration of the grade level and target audience may impact how we handle each situation (may be different for elementary school vs college students).  Sometimes showing the logic + steps of how the calculation is done is more important than getting the final correct answer at the right precision.  Perhaps as we develop more math sims this will become more important.

So now that we clarified the design, this issue is ready for @matthew-blackman and @marlitas to code review. Happy to review synchronously, and that may be most efficient. Would be good to get this issue closed out.

**Comment by samreid** [comment]
Keep in mind there is a separate issue for the implementation detail #370

**Comment by samreid** [comment]
Please see also related comment https://github.com/phetsims/center-and-variability/issues/346#issuecomment-1644676705

**Comment by matthew-blackman** [comment]
The MAD calculation now has single-decimal precision in all deviations and the sum of the deviations, making then consistent with the precision of the result. Would be good to review @marlitas and design review @catherinecarter.

**Comment by matthew-blackman** [comment]
Reviewed this with @marlitas and it's ready for a design review @catherinecarter. Note that the MAD calculation now shows 1 decimal point for all deviations in the numerator, as well as for the sum of the deviatiors.
