### ISSUE TITLE
Problems on Reset

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#172]
Sim can get frozen.

card arrow can show over nothingness

<img width="235" alt="image" src="https://user-images.githubusercontent.com/679486/236331129-75e851cb-24ea-4367-8231-66125cc8e2c3.png">

**Comment by samreid** [comment]
One time after resetting there was a leftover card in the card panel

<img width="791" alt="image" src="https://user-images.githubusercontent.com/679486/236629458-2704f23e-ec94-4fe7-a965-c1571f1bca34.png">

**Comment by samreid** [comment]
Something like this may help with that unresetted card:

<details>

```diff

Subject: [PATCH] Clear card cells on inactive, see https://github.com/phetsims/center-and-variability/issues/172
---
Index: js/median/view/CardNodeContainer.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/median/view/CardNodeContainer.ts b/js/median/view/CardNodeContainer.ts
--- a/js/median/view/CardNodeContainer.ts	(revision 6e8d554607922202e5631e08fba478dc76a69a6b)
+++ b/js/median/view/CardNodeContainer.ts	(date 1683383199141)
@@ -207,8 +207,22 @@
         }
         else if ( !isActive ) {
           const index = this.cardNodeCells.indexOf( cardNode );
-          this.cardNodeCells.splice( index, 1 );
-          this.cardNodeCellsChangedEmitter.emit();
+
+          if ( index >= 0 ) {
+            this.cardNodeCells.splice( index, 1 );
+            this.cardNodeCellsChangedEmitter.emit();
+          }
+        }
+      } );
+
+      cardModel.soccerBall.valueProperty.link( value => {
+        if ( value === null ) {
+          const index = this.cardNodeCells.indexOf( cardNode );
+
+          if ( index >= 0 ) {
+            this.cardNodeCells.splice( index, 1 );
+            this.cardNodeCellsChangedEmitter.emit();
+          }
         }
       } );
 

```

</details>

**Comment by samreid** [comment]
Fixed in the commit, with one TODO for discussion.

**Comment by samreid** [comment]
Can't test this until https://github.com/phetsims/center-and-variability/issues/189 is fixed. So perhaps I'll increase its priority.

**Comment by samreid** [comment]
Reset seems pretty nice in my testing.  @marlitas or @matthew-blackman want to review/test?

**Comment by marlitas** [comment]
Played around with some different scenarios and I am not seeing any remaining issues related to reset functionality. Commits are small, and seem appropriate. No concerns here. Ready to close if @samreid is.

**Comment by samreid** [comment]
Thanks! Closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by matthew-blackman** [comment]
@samreid and I tested the behavior without the dragPositionProperty being reset, and found no issues. The valueProperty of the soccerBall is now being reset correctly. We feel that this issue can be closed.
