### ISSUE TITLE
Range info box

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#174]
Opening so we have an issue for each info box separately. This one is for the range. Here's an image of the range info box. 

Things to notice:
- [x] The distance between the last Range calculation and the number line is smaller to reduce whitespace
- [x] The height of the green rectangle is slightly above the highest data point
- [x] The definition of the range is simpler.

![image](https://user-images.githubusercontent.com/109630002/236335147-1ea28d52-65c6-48d2-8a52-ad394da27d4e.png)

**Comment by samreid** [comment]
> The distance between the last Range calculation and the number line is smaller to reduce whitespace

This is caused by the Rectangle in CAVPlotNode: 

```ts
const backgroundNode = new Rectangle( 0, 0, CAVConstants.CHART_VIEW_WIDTH, 180 );
    this.addChild( backgroundNode );
```

But changing the height doesn't fix it, since it leaves a floating rectangle in the air.

**Comment by samreid** [comment]
I tried to address the previous comment in https://github.com/phetsims/center-and-variability/commit/94bdd7b3a74ded2a74757a848278b745e88a9016, but it could use a careful review. @marlitas can you please help?

**Comment by samreid** [comment]
After the commits, it looks like this:

![image](https://github.com/phetsims/center-and-variability/assets/679486/94be2403-c4b0-4e9f-bc39-d216d7d4ece6)

Let's continue in review.

**Comment by catherinecarter** [comment]
The spacing between the range number above the rectangle looks good. Wondering if we can add a buffer between the top-most data point and the top of the rectangle, maybe 2 or 3 pixels?

Also, the minus sign is short. Is there a longer character, like the one on the keyboard (Mac) when you press option and the dash key simultaneously? Here's what they look like side by side (option plus dash versus dash alone):
– vs
-

Last, can the number line be centered in the info box?

**Comment by marlitas** [comment]
@catherinecarter, those changes have been applied. Can you review on your end and close if all looks well?

**Comment by marlitas** [comment]
I'm a little confused... I see a light gray stroke on both the MAD rectangles and the Range rectangles. And I also see that this is consistent between the accordionBox and the infoDialog. Are you wanting to take the stroke off of all the rectangles, or is there a different rectangle I'm not seeing?

<img width="251" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/0e257d7d-76e9-4ca0-838a-99d46435cb12">
<img width="345" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/8cf29b78-8dba-413b-9691-17df71337777">

**Comment by catherinecarter** [comment]
Let's take the stroke off all of the rectangles, both in the accordion box and in the info box. I don't think they're needed. Thanks.

**Comment by marlitas** [comment]
Done! If all is well go ahead an close :-)

<img width="205" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/3877e37b-b33a-4e69-a027-88894c584c66">
<img width="207" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/45941b8d-5f49-4a35-9e38-9c01ce21e5b6">

**Comment by catherinecarter** [comment]
Looks great. Thanks @marlitas :)
