### ISSUE TITLE
Enforce "half a data point or soccer ball is occluded" design

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#175]
The design called for half of a data point (or soccer ball?) to be occluded/clipped when going out of bounds, so it is clear there is more. We haven't enforced this programmatically. Should we enforce this somehow, or just manually adjust it? Is this still an important aspect of the design?

**Comment by matthew-blackman** [comment]
5/8 design check-in with @catherinecarter:

@catherinecarter agrees that being able to see a partial ball is important, but not essential to make sure that it is exactly half. The sim should require that a minimum amount of any occluded ball is shown.

Note: In the chart we may autoscale the size of the data points to accomodate this.

**Comment by samreid** [comment]
From today's design meeting:

* In the worst case scenario (window is short and wide), we would like to see at least part of a soccer ball cut off by the collapsed accordion box.  When the accordion box is expanded, it would be nice to see a fractional ball.  But the user put those soccer balls there on purpose, so they will know they are there. And they can collapse the accordion box to see more.

** The main thing is on screen 1 where there is a max of 15 balls that the entire stack should be under collapsed accordion box.** 

We will start with that bolded part, and re-evaluate if we determine students are being confused by occluded/clipped soccer balls.

**Comment by samreid** [comment]
After recent adjustments, the stack looks like this in screen 1 with the collapsed accordion box:

<img width="1190" alt="image" src="https://github.com/phetsims/center-and-variability/assets/679486/720e33a3-1790-40c2-8416-be5561effd09">

I'm not really sure what this comment is about, but let's work on that in a separate issue:

> We also like the soccer balls somewhat overlapping, but will need to fix the z-ordering in reorganize stack.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
