### ISSUE TITLE
MADNode should depict the mean location

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#180]
From a TODO:

> TODO: The design calls for a depiction of the mean location.  This is not yet implemented.

**Comment by samreid** [comment]
I used the same depiction as in the 2nd screen (since it was the minimum amount of effort, and is consistent with previously designed efforts). @catherinecarter is it important to be a different representation in the MAD scene?

**Comment by catherinecarter** [comment]
@samreid, by "different," do you mean with no horizontal line on the x-axis? I see there's a horizontal line on the 2nd screen that's the same color as the mean to represent a "scale-like" feeling where the mean is the balancing point. On the 3rd screen, there's so much going on, I don't think it's critical to mimic the 2nd screen look for the mean. Having just the arrow feels appropriate and a little less cluttered. Is this what you meant by your question? Let me know if not.

**Comment by samreid** [comment]
The 3rd screen also shows the purple vertical line: 

<img width="462" alt="image" src="https://github.com/phetsims/center-and-variability/assets/679486/a7cb5336-99c1-4808-ab67-b7447f3b0685">

Generally, it helps to keep the sim simpler, easer to test, easier to maintain, and more self-consistent (from a UX standpoint) to use the same representations throughout.  I also agree with your point that the MAD has a lot going on, so we can add an option to hide the "horizontal scale like" part (please confirm that part). Also, do you want to add the vertical purple line from the design doc? I'm not sure it's necessary since the purple triangle is already very clear, and you can already see an "edge" where the horizontal lines line up in the middle.

**Comment by catherinecarter** [comment]
I think the default should be to not show the horizontal scale, but the option to show it seems nice. Maybe put it preferences? 

For the vertical line above the mean, yes, I'd like to see that. It doesn't have to be as thick as the horizontal purple scale line. And I agree the horizontal lines create a nice vertical-line-ish space, it's confusing when there are only a few points. Here's with 2, and it's not clear the points are the distance from an imaginary vertical line. 

<img width="194" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/7d3f3f59-e263-4247-b8e4-732fdeddf6e6">

**Comment by catherinecarter** [comment]
I noticed there's no marker to indicate the distance from the mean to a point on the mean is zero. Can we add a dot to indicate the distance is zero? 
![image](https://github.com/phetsims/center-and-variability/assets/109630002/d31fbc87-34fc-4eb1-9050-573c0af5d6ab)

Notice, too, how the distances are so close together here, it looks like 0.40.4. Not sure how to handle that one. Maybe make the distances a minimum distance apart, even if it means they aren't centered?

**Comment by samreid** [comment]
> I think the default should be to not show the horizontal scale, but the option to show it seems nice. Maybe put it preferences?

In the commit I removed the range display from the x-axis in MAD display in the variability screen. To me, it seems too much of a minor detail (and something that doesn't pertain to the MAD) to put in the preferences.

**Comment by samreid** [comment]
> I noticed there's no marker to indicate the distance from the mean to a point on the mean is zero. Can we add a dot to indicate the distance is zero?

I added the dot when the line is too short, it currently looks like this. Please let me know if you want any changes to that look:

<img width="504" alt="image" src="https://github.com/phetsims/center-and-variability/assets/679486/fd4fdb4b-1934-41aa-9a44-151b0bddb351">

**Comment by samreid** [comment]
Also I added a commit so if the readouts overlap, they are moved apart, it looks like this:

<img width="137" alt="image" src="https://github.com/phetsims/center-and-variability/assets/679486/f8c0c0ba-026d-4a4a-8e6f-4970244e8803">

**Comment by samreid** [comment]
Next I added the mean line. It looks like this:

<img width="416" alt="image" src="https://github.com/phetsims/center-and-variability/assets/679486/cbd609a6-131d-44be-aa93-fbbe44a73b69">

and when it overlaps the "0" dots, it looks like this:

<img width="511" alt="image" src="https://github.com/phetsims/center-and-variability/assets/679486/71915129-5bcf-4450-bd6c-211378be2890">

Let me know if you want to adjust the line width or dot sizes.

**Comment by catherinecarter** [comment]
Yes, let's make the dots a little bigger. We could try small rectangles if the dots are too hard to see even when made a bit bigger. Let's also bring the first horizontal line down so there's a bit more of the mean line showing above the first horizontal line.

**Comment by samreid** [comment]
I increased the dot radii by 50% and moved the first horizontal line down a bit, now it looks like this:

![image](https://github.com/phetsims/center-and-variability/assets/679486/4fecf219-ec8a-4892-8d13-f1185436eed3)

![image](https://github.com/phetsims/center-and-variability/assets/679486/bceaf624-07e4-4a3f-820e-c9c2eafcefa1)

**Comment by catherinecarter** [comment]
I think it looks great! Thanks, @samreid. Feel free to close when ready.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
