### ISSUE TITLE
Interval Tool icon

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#182]
The interval tool icon will look like the other spread icons (rectangle with arrow spanning width), but will be smaller to accommodate the handles below. The handles should have the same gradient as the Predict Mean and Predict Median handles, but will have the color base be #fff8a0.

Here's a png for guidance on how to create this in code: 
![intervalToolIcon](https://user-images.githubusercontent.com/109630002/236542049-39da44b5-4814-457c-a7a5-53276693ffb8.png)

**Comment by samreid** [comment]
I'll work on this.

**Comment by samreid** [comment]
I added a first draft, it's looking like this at the moment:

<img width="609" alt="image" src="https://user-images.githubusercontent.com/679486/236684282-7ea56cca-99a8-44a0-98cc-28df89ea7bfb.png">

I could use help fine-tuning the dimensions and gradients, and it's ready for code review.  @marlitas or @matthew-blackman can you please take a look?

**Comment by marlitas** [comment]
Besides some small pixel polishes you mentioned looks good. Using the word "beam" for the two vertical rectangles on each side was confusing for me. I usually associate beam either with a beam of light, or a beam in construction to support a floor or ceiling... which is horizontal. Both definitions didn't connect with the vertical rectangle here. Perhaps "handle"? Or if you were going the construction context route, "column"?

**Comment by matthew-blackman** [comment]
Looks good over here as well. I'd propose calling the vertical rectangles 'posts' since they looks like sign posts to me.

**Comment by catherinecarter** [comment]
I feel like the gradient ball handles are a little dingy (I was having trouble making them feel brighter in my mockups). Can we make them a little brighter?

**Comment by samreid** [comment]
In the commit, I added the colors to the color profile.  @catherinecarter can you please use that to specify the colors?

**Comment by catherinecarter** [comment]
From issue [#194](https://github.com/phetsims/center-and-variability/issues/194), let's try this: 
centerAndVariability.intervalToolIconShadedSphereMainColor #FDF581
centerAndVariability.intervalToolIconShadedSphereHighlightColor #FDFDF2

**Comment by samreid** [comment]
I committed the colors from above, and now it looks like this:

<img width="142" alt="image" src="https://github.com/phetsims/center-and-variability/assets/679486/dd0f6d58-3b9f-4993-a167-9798cc296f5c">

Can this issue be closed?  If we make more decisions about how the handles look in #194, we can adjust the icon there.

**Comment by catherinecarter** [comment]
I think the icon looks great! Not dingy, and the color seems to match with the rectangle. Thanks. Ok with me to close.
