### ISSUE TITLE
When dragging a ball quickly, sometimes it doesn't show at the top of each stack

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#186]
Discovered in https://github.com/phetsims/center-and-variability/issues/82, When dragging a ball quickly, sometimes it doesn't show at the top of each stack

**Comment by samreid** [comment]
I can no longer reproduce this error in local testing, @marlitas or @matthew-blackman can you please verify?

**Comment by marlitas** [comment]
I can reproduce on my local machine.

**Comment by matthew-blackman** [comment]
I am also able to reproduce this, but I'm not sure if it's just a timestep resolution issue. When I drag a soccer ball at a slow or medium speed, the behavior of the stacks looks correct. When I drag a ball quickly, it only appears to skip a stack if the cursor moved at a fast enough rate. Couldn't the browser just detect the position of the cursor to have skipped a stack in a single time step? If this is the case I'm not sure this is an issue that can be fixed.

**Comment by samreid** [comment]
@matthew-blackman and I addressed performance problems and this seems much better.  Maybe fixing performance is still the way to make further improvements, if desired.

**Comment by samreid** [comment]
This feels fixed to me, it is still possible to skip a stack if you. drag the mouse quickly, but that is to be expected.  I recommend closing this issue. @matthew-blackman and @marlitas sound OK?

**Comment by matthew-blackman** [comment]
I agree with your comment above @samreid. Closing this issue, can reopen if this reappears.
