### ISSUE TITLE
Testing corner cases with ball animation and input events

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/center-and-variability#188]
Since the sim uses animation on objects that have input enabled, we feel that it will be helpful to test out the following to confirm the desired behavior:

- [x] More than one ball lands in the same stack in rapid succession
- [x] While one or more balls are animating to the top of a stack, the user clicks on that stack
- [x] While one or more balls are animating to the top of a stack, another ball is dragged onto that stack
- [x] While one or more balls are animating to the top of a stack, another ball is dragged past that stack
- [x] The user hits 'clear data' or 'reset all' while a ball is animating

This is a continuation of the work done in https://github.com/phetsims/center-and-variability/issues/165

**Comment by matthew-blackman** [comment]
There is some buggy behavior here. Testing with the query params 'slowAnimation' and 'sameSpot' to make it easier to see animation and input issues. Since the code is starting to get complicated with listeners and callbacks, I think we should lay out the desired behavior before discussing a solution @samreid @marlitas.

Here are some of the scenarios we will need to account for, to confirm UX:

- While a ball lands on a stack that already has other balls, its z-index should immediately be moved to the front.
- If a ball lands on a stack that has other balls animating, all animations continue and the balls animate to their correct positions on the stack
- Any click event on a stack should cancel all animations and immediately rearrange the balls in the stack to their final positions
- Dragging a ball onto or over another stack should also cancel all animations and immediately rearrange the balls in the stack to their final positions
- If a ball lands on a stack that is currently being dragged, what should we do?

We may want to set aside some design time to discuss the UX here. Thoughts?

**Comment by marlitas** [comment]
Here's a patch that has an interesting floating ball bug.

<details>

```diff
Subject: [PATCH] clearAnimation
---
Index: js/common/model/SoccerBall.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/SoccerBall.ts b/js/common/model/SoccerBall.ts
--- a/js/common/model/SoccerBall.ts	(revision f14888a75f80e32c7ea6cce2980eca109f03ad81)
+++ b/js/common/model/SoccerBall.ts	(date 1684255978237)
@@ -109,6 +109,12 @@
     } );
   }
 
+  public clearAnimation(): void {
+    if ( this.animation ) {
+      this.animation.stop();
+      this.animation = null;
+    }
+  }
   public step( dt: number ): void {
     if ( this.animationModeProperty.value === AnimationMode.FLYING ) {
 
Index: js/common/model/CAVSceneModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/CAVSceneModel.ts b/js/common/model/CAVSceneModel.ts
--- a/js/common/model/CAVSceneModel.ts	(revision f14888a75f80e32c7ea6cce2980eca109f03ad81)
+++ b/js/common/model/CAVSceneModel.ts	(date 1684256111146)
@@ -158,6 +158,7 @@
           const oldStack = this.getStackAtLocation( oldValue );
           if ( oldStack.length > 0 ) {
             this.reorganizeStack( oldStack );
+            this.clearAnimationsInStack( oldStack );
           }
 
           const objectsAtTarget = this.soccerBalls.filter( otherSoccerBall => {
@@ -166,7 +167,9 @@
 
           // Sort from bottom to top, so they can be re-stacked. The specified object will appear at the top.
           const sortedOthers = _.sortBy( objectsAtTarget, object => object.positionProperty.value.y );
-          this.reorganizeStack( [ ...sortedOthers, soccerBall ] );
+          const newStack = [ ...sortedOthers, soccerBall ];
+          this.reorganizeStack( newStack );
+          this.clearAnimationsInStack( newStack );
         }
       } );
 
@@ -298,6 +301,11 @@
     } );
   }
 
+  // Cancel out all animations in the soccer ball stack.
+  private clearAnimationsInStack( stack: SoccerBall[] ): void {
+    stack.forEach( soccerBall => soccerBall.clearAnimation() );
+  }
+
   protected updateDataMeasures(): void {
     const sortedObjects = this.getSortedLandedObjects();
     const medianObjects = CAVSceneModel.getMedianObjectsFromSortedArray( sortedObjects );
@@ -345,13 +353,6 @@
     // collapse the rest of the stack. NOTE: This assumes the radii are the same.
     let position = CAVObjectType.SOCCER_BALL.radius;
     soccerBallStack.forEach( soccerBall => {
-
-      // If a ball was animating to the top of the stack, stop it. This prevents a floating ball if a lower ball
-      // is moved out from underneath
-      if ( soccerBall.animation ) {
-        soccerBall.animation.stop();
-        soccerBall.animation = null;
-      }
       soccerBall.positionProperty.value = new Vector2( soccerBall.valueProperty.value!, position );
       position += CAVObjectType.SOCCER_BALL.radius * 2 * ( 1 - CAVConstants.SOCCER_BALL_OVERLAP );
     } );
@@ -492,7 +493,7 @@
   }
 
   /**
-   * When a ball lands on the ground, animate all other balls that were at this location above the landed ball.
+   * When a ball lands on the ground, animate the ball to the top of the stack.
    */
   private animateSoccerBallStack( soccerBall: SoccerBall, value: number ): void {
     const otherObjectsInStack = this.getActiveSoccerBalls().filter( x => x.valueProperty.value === value && x !== soccerBall );
@@ -505,9 +506,7 @@
     const animationSlowdownFactor = CAVQueryParameters.slowAnimation ? 10 : 1;
     const animationTime = animationSlowdownFactor * 0.06 * this.getStackAtLocation( value ).length;
 
-    if ( soccerBall.animation ) {
-      soccerBall.animation.stop();
-    }
+    soccerBall.clearAnimation();
     soccerBall.animation = new Animation( {
       duration: animationTime,
       targets: [ {
```
</details>

**Comment by matthew-blackman** [comment]
Improvements to soccerBall animationModeProperty from above commit:

- Renamed ‘animationModeProperty’ to ‘soccerBallPhaseProperty’
- Add enumeration values for INACTIVE, READY and STACKED
- Set soccerBall.isActiveProperty to a DerivedProperty based on whether soccerBallPhaseProperty is anything other than INACTIVE

@samreid  and I discussed a plan to centralize the soccer ball “state” into the soccerBallPhaseProperty, to make it more maintainable to find out which part of the motion each soccer ball is currently in.

There are still z-ordering issues to resolve, but this is looking much better!

**Comment by matthew-blackman** [comment]
Pushed commit to wrong issue:
[https://github.com/phetsims/center-and-variability/commit/1cb985b56901376376bb439fc7030f1b247a977d](url)

**Comment by matthew-blackman** [comment]
Improvements to soccerBall animationModeProperty from above commit:

Renamed ‘animationModeProperty’ to ‘soccerBallPhaseProperty’
Add enumeration values for INACTIVE, READY and STACKED
Set soccerBall.isActiveProperty to a DerivedProperty based on whether soccerBallPhaseProperty is anything other than INACTIVE
@samreid and I discussed a plan to centralize the soccer ball “state” into the soccerBallPhaseProperty, to make it more maintainable to find out which part of the motion each soccer ball is currently in.

There are still z-ordering issues to resolve, but this is looking much better!

**Comment by matthew-blackman** [comment]
Bug report:
Hitting reset while soccer balls are animating can lead to scenarios like this:
![Screen Shot 2023-05-16 at 6 09 16 PM](https://github.com/phetsims/center-and-variability/assets/108756567/64fd8216-03d1-4d86-bd19-19037e37329d)

**Comment by matthew-blackman** [comment]
Screen recording showing z-index issues with balls landing out-of-order:
https://github.com/phetsims/center-and-variability/assets/108756567/672324e8-d0fd-4276-b4c7-979911ebf3da

**Comment by matthew-blackman** [comment]
The above commits address the scenario of while one or more balls are animating to the top of a stack, the user clicks on that stack.

**Comment by matthew-blackman** [comment]
Screen recording: hitting 'reset all' while a ball is animating

https://github.com/phetsims/center-and-variability/assets/108756567/d7c2c4e8-d11d-4456-a90a-b686da19d83c

**Comment by matthew-blackman** [comment]
Commit [c8b518d](https://github.com/phetsims/center-and-variability/commit/c8b518da717305e724a53c706ecb383918b4d3fe) resolves the 'reset' and 'clear' issue in the screen recording above.

**Comment by marlitas** [comment]
Is this a design question? From the comment above it seems like it might be, so marking it as such.

**Comment by samreid** [comment]
Today in design meeting, we reviewed the behavior where dragging a ball across an animating stack, and the animations jump to their destinations, and we agreed it seems OK.  Nice work everyone, closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by matthew-blackman** [comment]
I addressed the two remaining TODOs in this issue. The median highlight and all arrows appear to be working nicely. Labeling as ready-for-review.

**Comment by samreid** [comment]
@matthew-blackman and I reviewed the latter commits and also made another improvement by removing SoccerBall.isActiveProperty.  Closing.
