### ISSUE TITLE
drag indicator node not showing

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#189]
While working on https://github.com/phetsims/center-and-variability/issues/172 and related to https://github.com/phetsims/center-and-variability/issues/129, the drag indicator node is not showing even after kicking all soccer balls.

**Comment by samreid** [comment]
Fixed, closing.

**Comment by samreid** [comment]
On second thought, maybe this should be code reviewed. @matthew-blackman or @marlitas can you please review?

**Comment by samreid** [comment]
@marlitas said she is working on this, self-unassigning.

**Comment by marlitas** [comment]
I moved it over, and I think it's better than being in the view, but I'm not sure I'm convinced by my implementation... I started with using DerivedProperties for both the dragIndicatorVisibleProperty and the dragIndicatorValueProperty, but that felt like it was getting expensive when the DerivedProperty had to listen to every soccer ball's valueProperty... I'm not sure this is any better though. 

As I was testing this I was noticing that reset was taking longer than expected. Not sure if this is related to my changes or something else, but either way I'm worried about performance.

Would like to review with @samreid or @matthew-blackman.

**Comment by samreid** [comment]
I skimmed through the commit and feel it is the right direction. Reset already took a long time before these changes, and will probably need optimization. This issue seems a good one to review synchronously.  I'll mark as help-wanted, and self-unassign for now.

**Comment by marlitas** [comment]
@samreid would like to review this asynchronously.

**Comment by samreid** [comment]
Code review and sim behavior seem good, nice work! Closing.
