### ISSUE TITLE
SceneView and visibility problems

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#192]
From https://github.com/phetsims/center-and-variability/issues/172, the drag indicator arrow node was showing for the incorrect scene. That case was fixed, but maybe the same problem could happen for other objects? Please see frontObjectLayer and backObjectLayer usages.

**Comment by samreid** [comment]
OK I think there is a better way--we can have SceneView return a frontNode and backNode that the container adds and manages.

**Comment by samreid** [comment]
The commit seems much better, @marlitas can you please review?

**Comment by marlitas** [comment]
I like this. We're no longer relying on a scene visibility property, rather we're using Toggle Nodes. This seems more consistent with the rest of the architecture in the sim now, and flows more smoothly. 

No comments or recommendations from my end. It was good to see that change.

Back to you @samreid, is this ready to close?

**Comment by samreid** [comment]
Thanks, closing.
