### ISSUE TITLE
PhET-iO design for scenes

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#193]
From https://github.com/phetsims/center-and-variability/issues/164, we split up the model into scenes.  @kathy-phet said:

Hey Sam, Cathy, 
Agree with the above in terms of the what changes when you select a different player (just the data). Everything else stays the same - so you can easily compare data sets. 

In thinking about PhET-iO of this aspect, I was thinking that each player should have the following data available under it: 
- Array of data points 
- Probability distribution that drives the data for this person 
- Mean
- Median 
- IQR
- MAD
- Range
- maybe an isActive read-only flag
So that with the PhET-iO interface you can always access the data for each player, even if they are not the one that is visible. 

Then there could be the a data structure in PhET-iO that is the "currently displayed values" that is read only. So that if you built a "save data" function to pull values into your system, you always get the visible data using the same static PhET-iO Element ID. 
- Active Player (who is visible) 
- Probability Distribution 
- Data array Values 
- Mean 
- Median 
- IQR
- MAD
- Range

**Comment by matthew-blackman** [comment]
@samreid @marlitas and I discussed this and would like to move ahead with the following: In CAVModel, create a new IO type CAVModelIO, which would have a new method called getCurrentSceneData.

**Comment by samreid** [comment]
I'll work on this.

**Comment by samreid** [comment]
I implemented this and it can be called like:

```ts
await phetioClient.invokeAsync('centerAndVariability.medianScreen.model','getCurrentSceneData');
```

or 

```ts
await phetioClient.invokeAsync('centerAndVariability.variabilityScreen.model','getCurrentSceneData');
```

It contains the state data for everything pertinent to that scene.  For instance, the variability screen shows MAD values but the median screen does not.

Let's review this in an upcoming phet-io check-in.

**Comment by samreid** [comment]
We reviewed this with @catherinecarter and @matthew-blackman and it seems like it is ready to close.  But we want to share it with @kathy-phet at an upcoming team meeting so she is aware, and to get any other feedback.

**Comment by catherinecarter** [comment]
If my memory serves me well, I believe we ran this by @kathy-phet, but I'm not 100% sure. I'll run it by her before saying yes here.

**Comment by catherinecarter** [comment]
@kathy-phet is hoping to have another look at the second part of the comment from the top of this issue.

Simplified data structure to give the main pedagogical things for the data that's currently be displayed so no one needs to do back-processing to know what scene you're on. One array data structure to capture what's currently on the screen.

- Always want to access the data for the current screen (only visible data)
   - this is already ready with the command above, but explore minimizing the prefix 
   - pair down what data is being given
- Also want to get the data for the scenes not visible (all data whether visible or not)

Requesting a meeting with MS, MB, KP, SR to discuss.

**Comment by samreid** [comment]
In the conversation above, we also noted that `getCurrentSceneData` requires the user to invoke it on the appropriate screen (i.e. it doesn't solve the problem of knowing which screen the user is on.)

Jotting down a note that may inform us when we meet with @matthew-blackman.  Here is the code a client could use to get the current screen, current scene, and mean value on that scene.  It uses one phet-io API call and processes the state. I'm not saying this is obvious or easy, but it is something we could document in the examples.md document:

```ts

// Get the entire state from the sim
const state = await phetioClient.invokeAsync('phetioEngine','getState');

// Identify which screen is currently selected
const screen = state['centerAndVariability.homeScreen.model.selectedScreenProperty'].value.phetioID;

// Identify which scene within that screen is currently selected
const scene = state[screen+'.model.selectedSceneModelProperty'].value.phetioID

// Access whatever data measures are of interest
const mean = state[scene+'.meanValueProperty'].value
```

**Comment by samreid** [comment]
I elaborated on the code above to use a better model property for the selected screen, and also a better way of getting the scene for screen 1-2.  

```ts
// Get the entire state from the sim
const state = await phetioClient.invokeAsync( 'phetioEngine', 'getState' );

// Identify which screen is currently selected
const screen = state[ 'centerAndVariability.general.model.screens.selectedScreenProperty' ].value.phetioID;

// Identify which scene within that screen is currently selected
const scene = screen === 'centerAndVariability.meanAndMedianScreen' ? 'centerAndVariability.meanAndMedianScreen.model.sceneModel' :
              screen === 'centerAndVariability.medianScreen' ? 'centerAndVariability.medianScreen.model.sceneModel' :

                // Variability screen has different scenes
              state[ screen + '.model.selectedSceneModelProperty' ].value.phetioID

// Access whatever data measures are of interest
const mean = state[ scene + '.meanValueProperty' ].value
const median = state[ scene + '.medianValueProperty' ].value

console.log( 'mean=' + mean );
console.log( 'median=' + median );
```

**Comment by samreid** [comment]
Tagging for #136

**Comment by samreid** [comment]
Closing since the remaining work will be done in #136

**Comment by samreid** [comment]
Reopened for discussion today

**Comment by samreid** [comment]
We discussed this may be a more appropriate level for examples.md, in order to find what scene is selected, and to get some data for the selected scene:

```ts
const scene = (await phetioClient.invokeAsync('centerAndVariability.variabilityScreen.model.selectedSceneModelProperty','getValue')).phetioID;
await phetioClient.invokeAsync(scene + '.meanValueProperty', 'getValue');
```

**Comment by samreid** [comment]
Here's a cleaner version:

```ts

const sceneElement = await phetioClient.invokeAsync('centerAndVariability.variabilityScreen.model.selectedSceneModelProperty','getValue');
await phetioClient.invokeAsync(sceneElement.phetioID + '.meanValueProperty', 'getValue');
```

**Comment by samreid** [comment]
Leaving @catherinecarter assigned to make sure this is documented in the examples.

**Comment by catherinecarter** [comment]
Thanks. I've copied your code from above and have it recorded in examples. Closing.
