### ISSUE TITLE
Drag indicator arrow should not go behind the accordion box

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#198]
Use the same logic we used for preventing the median arrow node from going behind the accordion box.  From https://github.com/phetsims/center-and-variability/issues/131.

**Comment by samreid** [comment]
This is implemented and working correctly, but I was unable to use accordionbox.boundsProperty and accordionbox.bottom because the bounds wasn't triggering an update.  @marlitas can you help with this part?  Synchronously or asynchronously is great.

**Comment by samreid** [comment]
Specifically, with this patch:

<details>

```diff

Subject: [PATCH] Keep the drag indicator underneath the accordion box, see https://github.com/phetsims/center-and-variability/issues/198
---
Index: js/common/view/CAVScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/CAVScreenView.ts b/js/common/view/CAVScreenView.ts
--- a/js/common/view/CAVScreenView.ts	(revision 5069f3cd2f84b10228fc2569e4cf45f2f9b9a51e)
+++ b/js/common/view/CAVScreenView.ts	(date 1684588716862)
@@ -201,9 +201,8 @@
         // The arrow shouldn't overlap the accordion box
         // TODO: https://github.com/phetsims/center-and-variability/issues/198 why can't we use accordionbox.bottom?
         if ( this.accordionBox ) {
-          const accordionBoxHeight = this.accordionBox.expandedProperty.value ? this.accordionBox.getExpandedBoxHeight() : this.accordionBox.getCollapsedBoxHeight();
-          if ( dragIndicatorArrowNode.top < this.accordionBox.top + accordionBoxHeight ) {
-            dragIndicatorArrowNode.top = this.accordionBox.top + accordionBoxHeight + 4;
+          if ( dragIndicatorArrowNode.top < this.accordionBox.bottom + 4 ) {
+            dragIndicatorArrowNode.top = this.accordionBox.bottom + 4;
           }
         }
       }
@@ -235,9 +234,8 @@
         // The arrow shouldn't overlap the accordion box
         // TODO: https://github.com/phetsims/center-and-variability/issues/198 why can't we use accordionbox.bottom?
         if ( this.accordionBox ) {
-          const accordionBoxHeight = this.accordionBox.expandedProperty.value ? this.accordionBox.getExpandedBoxHeight() : this.accordionBox.getCollapsedBoxHeight();
-          if ( playAreaMedianIndicatorNode.top < this.accordionBox.top + accordionBoxHeight ) {
-            playAreaMedianIndicatorNode.top = this.accordionBox.top + accordionBoxHeight + 4;
+          if ( playAreaMedianIndicatorNode.top < this.accordionBox.bottom + 4 ) {
+            playAreaMedianIndicatorNode.top = this.accordionBox.bottom + 4;
           }
         }
       }
@@ -286,8 +284,8 @@
     this.sceneViews.forEach( sceneView => sceneView.setAccordionBox( accordionBox ) );
 
     // TODO: Why doesn't accordionBox.bounds work? https://github.com/phetsims/center-and-variability/issues/198
-    this.accordionBox.expandedProperty.link( this.updateMedianNode );
-    this.accordionBox.expandedProperty.link( this.updateDragIndicatorNode );
+    this.accordionBox.boundsProperty.link( this.updateMedianNode );
+    this.accordionBox.boundsProperty.link( this.updateDragIndicatorNode );
   }
 
   protected setBottomControls( controlNode: Node ): void {

```

</details>

When the accordion box collapses, it does not move the arrow up:

<img width="1069" alt="image" src="https://github.com/phetsims/center-and-variability/assets/679486/2a1bef02-29a9-4307-af65-a765086d9e64">

**Comment by marlitas** [comment]
> // TODO: Why doesn't accordionBox.bounds work? https://github.com/phetsims/center-and-variability/issues/198

Because the bounds of the accordionBox aren't changing. The expanding/collapsing does not adjust the accordion box bounds, it just changes what is visible in the accordionBox. There is an option to change this: `useExpandedBoundsWhenCollapsed`, which currently defaults to true. If we pass in `useExpandedBoundsWhenCollapsed: false` through CAVAccordionBox options then the boundsProperty will change when the accordionBox is collapsed and the link will trigger.

> // TODO: https://github.com/phetsims/center-and-variability/issues/198 why can't we use accordionbox.bottom?

I don't understand... Perhaps this is because the bounds weren't changing. When I pass through `useExpandedBoundsWhenCollapsed: false`  It's working as expected on my end.

I applied changes in the above commit to resolve those TODO's.

**Comment by samreid** [comment]
Excellent, thanks! I did not know about `useExpandedBoundsWhenCollapsed` but it makes sense and also explains `accordionBox.bottom`.  I feel this issue can be closed.
