### ISSUE TITLE
Use 1-based indexing for counting suffixes in tandem names

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#203]
I saw that some things used 1-based indexing (scene1,2,3,4) and others used 0-based indexing (sceneView0,1,2,3). Most importantly, we should be consistent. In the past, I have advocated for 0-based indexing, but perhaps 1-based indexing would be most appropriate for this context.

**Comment by samreid** [comment]
Fixed and would be good to spot check review.

**Comment by samreid** [comment]
If there is just one scene/sceneModel/etc, let's drop the suffix.

**Comment by zepumph** [comment]
I like that PhetioGroup starts at 0, as does many other indices and naming on the project. Let's not change that unless there is a good reason to, or a client asks for it.

**Comment by pixelzoom** [comment]
We have discussed this previously.  When the indexing is relevant to the UI, or talking about the UI in a classroom setting, we use 1-based index.  Otherwise it's up to developer discretion -- I think; I'm a little fuzzy about that part of the previous discussion.

**Comment by zepumph** [comment]
Discussed at PhET-iO meeting today, and updated the doc accordingly. Since the scene UI shows the count, then they should be 1,2,3,4.

**Comment by matthew-blackman** [comment]
@marlitas @samreid and I were discussing the consistecy of indexing across the sim, and we agree that if 1-based indexing is used for tandem names, the same pattern should be used across the sim. We would like @zepumph to weigh in here on whether the pattern used in PhetioGroup should take precendence, or if this sim can use 1-based indexing since it doesn't use PhetioGroup.

**Comment by pixelzoom** [comment]
Perhaps PhetioGroup should have an option to set the starting index, something like `groupElementStartIndex: 0`.  It's currently hard-coded to zero in 2 places:

```ts
    // (only for PhetioGroupIO) - for generating indices from a pool
    this.groupElementIndex = 0;
...
    if ( options.resetIndex ) {
      this.groupElementIndex = 0;
    }
```

**Comment by zepumph** [comment]
That sounds totally fine with me. Should we default it to 1?

**Comment by pixelzoom** [comment]
> That sounds totally fine with me. Should we default it to 1?
>
> OR should we just not have an option and change the start index to 1?

Would either of those changes require a migration rule?

**Comment by samreid** [comment]
Using this patch, I saw there was still a tandem starting at 0, so I corrected it in the preceding commit.

<details>

```diff

Subject: [PATCH] Convert tandem to lowercase, see https://github.com/phetsims/center-and-variability/issues/222
---
Index: js/phetioEngine.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/phetioEngine.ts b/js/phetioEngine.ts
--- a/js/phetioEngine.ts	(revision 56ef3a77af53b797a5032addbf5c6cfa3a1893df)
+++ b/js/phetioEngine.ts	(date 1686659222217)
@@ -661,11 +661,19 @@
    * Only to be used in this file!
    */
   public phetioObjectAdded( phetioObject: PhetioObject ): void {
+
     assert && assert( arguments.length === 1, 'Called with incorrect signature' );
     assert && assert( phetioObject instanceof phet.tandem.PhetioObject, 'must be PhetioObject' ); // eslint-disable-line no-simple-type-checking-assertions
     assert && assert( phetioObject, 'Only non-falsy components should be registered' );
     const phetioID = phetioObject.tandem.phetioID;
 
+    if ( /[a-zA-Z]0/.test( phetioID ) ) {
+      console.log( 'The string contains the number 0 preceded by a word character or a period.' + phetioID );
+    }
+    else {
+      // console.log( 'The string does not contain the number 0 in these positions.' );
+    }
+
     assert && Tandem.VALIDATION && assert( !this.phetioObjectMap.hasOwnProperty( phetioID ),
       `phetioID already registered: ${phetioID}` );
 

```

</details>

I feel recent questions about PhetioGroup and migration rules do not pertain to Center and Variability since it has no PhetioGroups and no migration rules, so I'll move that discussion to a tandem-centric issue.

Searching for `createTandem.*\+` I see that this sim has 9 occurrences of indexing in tandems.  I considered whether we may want a function in tandem like `createTandemIndexedStartingAt1('myTandem',index)` or `createTandemIndex1('myTandem',index)` but would that make the code less searchable? It's nice that `createTandem` is ubiquitous. Perhaps we should try it and see how it feels.

**Comment by samreid** [comment]
OK I created and used `Tandem.createTandemIndex1` and it seems to help for Center and Variability.

**Comment by zepumph** [comment]
Can we rename `createTandemIndex1` to `createTandem1Indexed`? It sounds a bit like `1` means that it is the first implementation of a `createTandemIndex` implementation, it also sounds like it creates an index, not a `Tandem`.

**Comment by samreid** [comment]
OK I renamed it in the commits. Anything else for this issue?

**Comment by samreid** [comment]
Thanks, I feel this issue can be closed.
