### ISSUE TITLE
Address PhET-iO Design

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#204]

**Comment by matthew-blackman** [comment]
@samreid @marlitas and I would like to split this up into individual design issues, but for now we will use this issue to track all remaining work that needs to be done with implementing the PhET-io design.

**Comment by matthew-blackman** [comment]
Up next, @samreid @marlitas and I will go through the design doc and create issues for each design implementation.

**Comment by marlitas** [comment]
For iteration K we are going to parse this doc (https://docs.google.com/document/d/1Z73-qNEMDVXinHsGYtruuaRKu8gO4EkH_6bD1Uf-ZAc/edit) into github issues if needed, or quickly address if the effort is low and can be covered by this issue.
