### ISSUE TITLE
Move the red highlight in front of the tick mark

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#208]
From a request in https://github.com/phetsims/center-and-variability/issues/146#issuecomment-1548783735

@catherinecarter showed this is the published prototype:

<img width="249" alt="image" src="https://github.com/phetsims/center-and-variability/assets/679486/2a40247a-12d2-43ed-9f08-cb58de9e3a09">

And this is in development:

<img width="232" alt="image" src="https://github.com/phetsims/center-and-variability/assets/679486/ff869f84-9be8-48eb-adbc-299999fa4b33">

@catherinecarter said:

> The outline in the top image layers in front of the number line tick mark while the image on the bottom has the tick mark layered in front of the outline.
> 
> The behavior and layering in the published sim seems to be nice

**Comment by samreid** [comment]
I guess the main question for this issue and https://github.com/phetsims/center-and-variability/issues/146#issuecomment-1548783735 is whether it is worth it to decouple the highlight regions from SoccerBallNode and create an independent layer for that.

**Comment by samreid** [comment]
Today we agreed it is preferable to have the highlight and soccer ball both in front of the tick mark.  We will not need to create a separate highlight layer.

**Comment by matthew-blackman** [comment]
We created MedianHighlightLayer as part of https://github.com/phetsims/center-and-variability/issues/232, so this was pretty straghtforward. Reordering the adding of nodes in CAVScreenView appears to solve this nicely.

**Comment by samreid** [comment]
The refactoring looks correct, and it looks like this at runtime:

![image](https://github.com/phetsims/center-and-variability/assets/679486/2076e5c6-024a-4852-b29f-c7a35e2f6167)

Closing.
