### ISSUE TITLE
Added boxplot feature showing outliers or not

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#209]
Curious how much time/effort it would cost to add a preference where the user could choose to see a "modified" box plot that would show outliers or not (default would not). The preference would ask users whether they want to see outliers with a "Show outliers" checkbox or something like that. 

Default (as is):
![image](https://github.com/phetsims/center-and-variability/assets/109630002/20399c75-bdf3-49fa-a48c-eddb9badd45f)

"Show outliers" checked:
![image](https://github.com/phetsims/center-and-variability/assets/109630002/17a75ff3-775d-4422-8cc9-04eb34089e99)

The rule to calculate mathematical outliers is to take 1.5 IQR's from the edges of the box, and anything outside of that is considered a mathematical outlier. So anything outside of:
   Q1 - 1.5(IQR) and/or Q3 + 1.5(IQR)
is an outlier.

The whisker goes all the way to the last data point within the limits of the outlier, and then there are asterisks, or dots, or something to show where the outliers are. 

Wondering if it's worth the time/effort to add this feature? The modification to the boxplot would appear in both the accordion box and the info box.

**Comment by matthew-blackman** [comment]
@catherinecarter the devs discussed this and would like to move forward with implementation. We have one question about the UI - should this be a single checkbox for "Show outliers" in the preferences menu, or should the preferences menu checkbox cause another checkbox to be created in the play area?

**Comment by catherinecarter** [comment]
First, YAY! Second, the checkbox in the preferences will be sufficient. There’s no need for another checkbox in the play area. Thanks!

**Comment by catherinecarter** [comment]
I should be more clear about the text for the preference. When I wrote the above, my head was in the space of the boxplot, but when a user is in the preferences, it may be unclear where the outliers would be shown. The checkbox text should say, "Show outliers (boxplot only)" to be consistent with the "Max kicks (for screens with plots)" format. If someone suggests to change the language of one of these, we should change the other.

**Comment by matthew-blackman** [comment]
The preferences checkbox is working and ready for your review @catherinecarter! It's a lot of fun :)

**Comment by matthew-blackman** [comment]
Good catch! Should be fixed now, please confirm.
