### ISSUE TITLE
Variability specific model values should be moved from CAVSceneModel to VariabilityModel

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#211]
While working on https://github.com/phetsims/center-and-variability/issues/169, I saw that Variability-specific properties were moved to CAVSceneModel in https://github.com/phetsims/center-and-variability/commit/2d1e0e5da12d0f06525f0e4e72c29e270eb9d260 but I feel these should move back to VariabilitySceneModel.

That change is part of a patch I was working on for https://github.com/phetsims/center-and-variability/issues/169 but I thought it deserved a separate issue for visibility and discussion.

@marlitas sound OK?

**Comment by matthew-blackman** [comment]
@samreid @marlitas and I discussed that this is no longer a problem, and @samreid will address if needed in working on https://github.com/phetsims/center-and-variability/issues/169

**Comment by samreid** [comment]
Fixed, closing.
