### ISSUE TITLE
Align checkboxes in accordion box and play area?

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/center-and-variability#212]
@samreid and I were working on the accordion box for the variability screen, and came across the following TODO in the code: "Align the checkboxes in the accordion box with the checkboxes in the play area.

We were looking at the variability screen and were wondering if this is still a design priority. The screenshot below shows the current checkbox layout, which @samreid and I thought looked good. @catherinecarter can you confirm whether we should work on aligning the checkboxes?

![Screen Shot 2023-05-17 at 3 33 26 PM](https://github.com/phetsims/center-and-variability/assets/108756567/cec1e158-02cb-4622-ad2d-7a8217d6f081)

**Comment by catherinecarter** [comment]
No, I think the checkbox in the accordion box is fine not being aligned with the checkboxes in the play area. Thanks for checking.

**Comment by matthew-blackman** [comment]
Sounds good! Closing.
