### ISSUE TITLE
Number lines in the info dialogs are not centered

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#215]
From https://github.com/phetsims/center-and-variability/issues/207, we found that the info dialog number lines are not aligned with the play area number line, see:

![image](https://github.com/phetsims/center-and-variability/assets/679486/7189d9f3-2e04-4b1e-82ee-b7f2520fa252)

Same for range and mad.  We will need code that aligns them.  Maybe use the same strategy as in the accordion box.

**Comment by marlitas** [comment]
We checked on this today and infoDialog numberLine is still not aligned, and it gets extra wonky when using dynamic strings.

<img width="941" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/d6b052ee-2eee-44b2-b8a0-49498355af5e">

**Comment by matthew-blackman** [comment]
This has been fixed by the updates to https://github.com/phetsims/center-and-variability/issues/223. Closing!
