### ISSUE TITLE
Add basic kick sound and field number tone

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/center-and-variability#217]
[Here is a basic kick sound to add in quickly.](https://drive.google.com/file/d/1GAXkYWJH69ZeeJ04GR5zP8vXb97b6gHV/view?usp=share_link)

Also the sound you want to call for the field number tone is brightMarimba.mp3. Its in the folder tambo/sounds/brightMarimba.mp3

**Comment by Ashton-Morris** [comment]
@samreid I have added these variations[ to this folder.](https://drive.google.com/drive/folders/1bs8Zqy7rwAI9A9a7mkYm3eV_UdZgIcAj?usp=share_link)

- cernter-and-variability-kick-v1.mp3
- cernter-and-variability-kick-v2.mp3
- cernter-and-variability-kick-v3.mp3
- cernter-and-variability-kick-v4.mp3
- cernter-and-variability-kick-v5.mp3
- cv-field-number-tone-v1.mp3
- cv-field-number-tone-v2.mp3
- cv-field-number-tone-v3.mp3
- cv-field-number-tone-v4.mp3
- cv-field-number-tone-v5.mp3

I forgot to mention that for the **cv-field-number-tone** sounds the sfx is at the lowest pitch and after it should be mapped from 0 to +14 semitones with +14 being the highest possible pitch.  Ex. a kick of 4 is at +3 semitones and a kick of 1 is at +0 semitones. 

If you have any questions I'll be available early tomorrow.

**Comment by samreid** [comment]
I added the sounds listed above.  If you open the dev tools, it shows how to enter code to change the sounds while the sim is running.

**Comment by samreid** [comment]
Here are my notes from the prior design meeting: 

> Go with number tone 2 and kick 1.

**Comment by samreid** [comment]
OK I updated the number tone to index 2.  The kick 0 and kick 1 are the same, but kick 0 had whitespace trimmed out of the beginning so there wouldn't be too much delay, so I'll leave it at 0.

**Comment by samreid** [comment]
In the commit, I also removed 57 lines of code that were harnesses for loading different sounds and choosing between them.

**Comment by emily-phet** [comment]
hey Sam - is the current default number line sound in Center and Variability the marimba? There was a wood instrument that I think was originally preferred. Can you please have that be the default?

**Comment by samreid** [comment]
At the previous meeting, we agreed the number tone is the correct one.  I also removed the unused mp3s.  Closing.

**Comment by samreid** [comment]
I addressed one TODO.  The remaining ones are:

* // TODO: There is a one animation frame (about 16 ms) delay for this sound to play
* // TODO: Create one per ball? One per location? Or multiple?

In my opinion, it has been working well.  The kick delay doesn't seem bothersome or easy to change (unless we play it when the soccer player is in `POISED_TO_KICK`), and it seems to work ok to just have one soundClip for all the number tones (but I haven't tested this with multitouch).  Let's discuss.

**Comment by matthew-blackman** [comment]
@samreid @marlitas and I discussed this and agree that the delay doesn't seem like a problem and did not come up in interviews. We feel that it's not an issue unless designers have an issue with it. 

@samreid also tested multitouch and found that the sound files play as expected when multiple balls are being dragged at the same time.

For MB to review closely: NumberTone.ts and the call sites.

**Comment by samreid** [comment]
I have some changes coming in to support https://github.com/phetsims/center-and-variability/issues/252

**Comment by samreid** [comment]
I also added some documentation in the commit above.

**Comment by matthew-blackman** [comment]
Reviewed with @samreid and @marlitas and we added a few final improvements in the above commit. This is looking and sounding great, closing.
