### ISSUE TITLE
Making soccer balls look tangent to each other

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#219]
We noticed a bit ago that the space between the balls made it look like they were floating on top of each other. So we changed the spacing to 0.04, which was nice, but it created a new problem (see #200 ), so we changed to to 0.0 thinking it would create a nice 'stacked' look while offering room for the median highlight. 

What we didn't anticipate was that setting the space between the stacked soccer balls to be 0.0 made them look floating again:
![image](https://github.com/phetsims/center-and-variability/assets/109630002/83f77d2b-b509-4fa3-8c09-626c72db32dd)

@samreid suggested in slack:
> we should probably leave a nonzero tuning parameter for overlap.

The goal is to have the stacks look like a dotplot where the balls are tangent, or maybe overlapping juuust enough where it doesn't look like the balls are flat or squishing into each other, and simultaneously offering a nice look to the median highlight. This is especially important when there are an even number of balls in the play area so the median is split between two balls.

**Comment by marlitas** [comment]
Okay I set the overlap to 0.01 and it looks like this:

<img width="648" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/4b5036fa-f7cc-45a6-b02f-7adeba5c9306">


Over to @catherinecarter

**Comment by marlitas** [comment]
Also important to note is how it looks with the median highlight:

<img width="403" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/8caf516a-3119-44a7-9287-2d66ecce152f">

**Comment by samreid** [comment]
@catherinecarter said this looks great, and this issue can be closed.
