### ISSUE TITLE
Reset sometimes shows pointer area on unkicked ball

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/center-and-variability#221]
To reproduce:

- Run sim with showPointerAreas
- Kick 1 or more balls
- Reset all
- Observe pointer area on unkicked ball

![Screen Shot 2023-05-25 at 10 18 14 AM](https://github.com/phetsims/center-and-variability/assets/108756567/6e0cbb69-6663-4ddb-9118-2c009533f925)

**Comment by matthew-blackman** [comment]
Reset issues and multiple soccer ball rendering issue look to be resolved. The above commits appear to clean things up nicely, and there are no known remaining input or reset issues. Marking as ready-for-review.

**Comment by samreid** [comment]
After 5-10 tries, using kick 5 and the clear button, I once again saw this bug appear:

<img width="1046" alt="image" src="https://github.com/phetsims/center-and-variability/assets/679486/edea51a5-1707-47c5-919e-8922ed3b77d9">

**Comment by samreid** [comment]
https://github.com/phetsims/center-and-variability/commit/8553adaca3ac39d4a317b646610f80906f18af8a looks suspicious.  Why shouldn't the 1st ball be active on startup?

https://github.com/phetsims/center-and-variability/commit/1aed8c27c8139ebc7e83a7475f8666f971787120 looks suspicious.  Why would we notify listeners that reset is complete before we have cleared the data?

**Comment by marlitas** [comment]
I was able to reproduce an unkicked ball having a pointer area on all screens using the following steps:

1. Kick 1 ball
2. Press the clear button

I also was able to reproduce @samreid's buggy screenshot above, but was not able to find an easily reproducible method to get there.

The commits @samreid pointed out look suspicious to me as well.

**Comment by matthew-blackman** [comment]
I reverted the suspicious commits and cleaned up some unneeded calls of getNextBallFromPool. The soccer ball phase reset is handling all of the behavior that getNextBallFromPool was doing, so I don't think we need it. Still looking into the pointer area bug, but the duplicated soccer balls should be fixed by the most recent commits.

**Comment by marlitas** [comment]
The commits and behavior look good to me. I think this is ready to close on my end. Back to @matthew-blackman in case there's any follow up work before close.
