### ISSUE TITLE
Info dialogs need to have better maxWidth for text

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#224]
From https://github.com/phetsims/center-and-variability/issues/170, note that the number lines don't line up either.

![image](https://github.com/phetsims/center-and-variability/assets/679486/bda81859-de6c-45f1-ab59-708669431c98)

**Comment by samreid** [comment]
It looks like this now. 

![Image](https://github.com/phetsims/center-and-variability/assets/679486/86cfcb99-b6df-4de2-8002-ea99b0c9dc60)


I'm not sure what the problem is with max width on the text.  @matthew-blackman or @marlitas do you recall? If not, this issue can be closed.

**Comment by matthew-blackman** [comment]
Text and layout on all info dialogs looks good with dynamic string length. There are remaining issues with specific components like https://github.com/phetsims/center-and-variability/issues/349, but we can continue that work in the related issues. Closing.
