### ISSUE TITLE
Review Success Sounds before Tuesday sound design meeting

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/center-and-variability#226]
I have created a video showing 7 SFX examples for possible success sounds. [You can watch it here.](https://drive.google.com/file/d/1B36TmK_pIX-Ma0WOTFQjBozXcFuSsEA3/view?usp=share_link)

If there is a preferred one, I can create a few variations matching the animations with the instrumentation of the preferred SFX. Alternatively we can just use the same one for every success notification if we like it enough.

**Comment by samreid** [comment]
Here are some quick reactions from my review:

1 = too tinny
2 = pretty great, top pick
3 = ok, second place
4 = too clanky
5 = could be ok if we tone it down/shorten it slightly?
6 = sounds too much like something is broken
7 = ok, maybe tied for 2nd place

@Ashton-Morris what is your recommendation? Want me to add one into the sim?

**Comment by emily-phet** [comment]
Ahhh, it got migrated! I found it in Sharepoint. 
I think the sound needs to be 1) feel short - could have long decay to match duration of animation, and 2) very clearly "success"
1- too long - a shorter version may work
2 - very abrupt,
3 - very abrupt
4 - unclear it's "success" 
5 - don't love the "choir" association, but I like that it's not too abrupt, clearly success, and not "too playful" (ha! had it to get in somewhere ashton. :))
6 - unclear it's "success"
7 - I like this one, feels like success, not too abrupt, not overly playful

**Comment by marlitas** [comment]
1. I like this one if the end bit is cut off. The first part of it is really fun though.
2. This one is nice, It's also my top pick.
3. Reminds me of cowbells, not necessarily "success"
4. Don't love this... The choir association is a bit too much
5. A little too "dingly". Does sound a bit like something is broken.
6. Reminds me of the "magic" sounds in 90's movies. I don't mind it.
7. This one sounds a bit like a phone is ringing. This is probably second or third place for me.

My order of favorites:
- Number 2
- Number 1 ( if the end were cut off)
- Number 7

**Comment by Ashton-Morris** [comment]
@samreid I have added a shorter version of success sound 7 (chimes) in case the original is too long sounding when implemented. 

[I have added it to the new sharepoint but this is my first time using it so please let me know if there are any issues.](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/PhET%20Files/Forms/AllItems.aspx?id=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Sim%20Design%2FMeet%20in%20the%20Middle%20HTML5%20%28Suite%29%2FCenter%20and%20Variability%20HTML5%2FSounds&viewid=3aa550f4%2Df9ef%2D4871%2Dbcb3%2Da192486a9aaa)

- cv-success-options-007-shorter.mp3

**Comment by samreid** [comment]
Thanks! I'll incorporate it.  For future sounds, can you please use camelcase naming to streamline how we integrate them into the sims?  Like cvSuccessOptions007Shorter.  For instance, see the filenames listed in https://github.com/phetsims/greenhouse-effect/tree/d92db2bc155ed0427d8cbd53e6eebc67a52a544f/sounds.  Thanks again!

**Comment by Ashton-Morris** [comment]
Ok, will do!

**Comment by samreid** [comment]
OK I added the success sound 007-shorter and "rough-draft" adjusted the volume.

**Comment by samreid** [comment]
OK we incorporated the requested success sound, the other trial sounds have been removed.  Closing.
