### ISSUE TITLE
Implement sounds for moving or arranging cards.

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/center-and-variability#227]
[I have seven sounds for us to put into the sim for the card arranging.](https://drive.google.com/drive/folders/1bs8Zqy7rwAI9A9a7mkYm3eV_UdZgIcAj?usp=share_link)

- cv-card-movement-sounds-001.mp3
- cv-card-movement-sounds-002.mp3
- cv-card-movement-sounds-003.mp3
- cv-card-movement-sounds-004.mp3
- cv-card-movement-sounds-005.mp3
- cv-card-movement-sounds-006.mp3
- cv-card-movement-sounds-007.mp3

**This is how I think the sound should be implemented: For moving a card to the left** 

- Play a random sound from the above sound files every time a card is played to the left, excluding from the random selection the last sound file played (so there is no repetitiveness). 

- For the sounds moving to the right, implement the audio the same as above but play all of those audio files +4 semitones higher (at a faster playback rate). 

I think with the difference in semitones from right to left it might stand out which direction you are moving the cards, and therefore sound natural while doing so.

Also, @samreid feel free to lower the volume a little at your own descretion as these are designed to be more in the background.

**Comment by samreid** [comment]
I added the card movement sounds as described above.

**Comment by samreid** [comment]
On slack @emily-phet said:

> These sounds are not what we’re looking for, as currently implemented. Not sure what the root of the issue is, but they don’t sound like what Ashton demoed. Sometimes that happens because of an implementation problem, sometimes other reasons. So if you listen and don’t like them, that’s ok. They’re definitely not “it”! We can talk through with Ashton / Sam tomorrow and get to the root of the issue.

I used the sounds specified above, and the randomness specified above.  It looks like my commit accidentally used 3 semitones instead of 4, so I'll commit that fix momentarily.  I also didn't implement the "excluding from the random selection the last sound file played (so there is no repetitiveness)." part yet.  Not sure how it differs from today's demo or how it is supposed to sound different.

**Comment by emily-phet** [comment]
Thanks @samreid!
As implemented, the sound is too sharp and heavy. The light paper flutter feel isn't coming across. I just wanted to give folks a heads up, so no one spends more time than it merits thinking deeply about how it sounds aesthetically before we meet. As is, it's not what I was asking for at all, so we can sort out what's up tomorrow.

**Comment by Ashton-Morris** [comment]
@samreid Can you lower the volume for the cards by 50% and try a low pass filter on them as well?

**Comment by samreid** [comment]
From slack:

Sam Reid

> I put the volume to 50% and it still sounds way too loud.  I put it to 10% and it sounds much better.  Can I use that or do we need a query parameter to tune it?

Ashton Morris

> I think you can use it, it was supposed to be put in pretty quietly so I am sure it is better

Sam Reid

> OK I committed the 0.1, I’m looking into filtering next

Ashton Morris

> 👍

**Comment by emily-phet** [comment]
I think this is a reasonable sound, but not what I had in mind. This sounds like a sound in a game. I was aiming for something slightly more physical, like a paper flutter sound.

**Comment by samreid** [comment]
My sharepoint link no longer works as it did before.  Can you share the link to those files?

**Comment by samreid** [comment]
I added the card sounds as specified.  But there were requests for new card sounds, and also we are doing a lot of the card work in https://github.com/phetsims/center-and-variability/issues/245, so let's close this one and continue over there.
