### ISSUE TITLE
Mean Indicator is buggy

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#229]
During CAV Sound Design we noticed that the mean indicator in the play area was incorrect.

**Comment by marlitas** [comment]
After doing a lot of numberLine work I hypothesized that it was off by the margin amount the NumberLine is given. It indeed was fixed with the following code:

```js
meanIndicatorNode.centerTop = new Vector2( modelViewTransform.modelToViewX( meanValue ), 0 ).plusXY( -CAVConstants.NUMBER_LINE_MARGIN_X, 0 );
```

But I'm still a bit confused as to why and how that margin seemed to be doubly applied... Perhaps because the margin is applied to the NumberLineNode, and the mean indicator is a child of that NumberLineNode and was spacing inside a local coordinate frame? However I tried converting the Vector from localToParent and localToGlobal, and that did not work either...

**Comment by catherinecarter** [comment]
I also noticed that the mean indicator seems to be in the correct place on the lower number line, but the mean indicator in the accordion box is now off. Strangely, the amount the indicators are away from each other seem to be the same as they were prior to the lower mean indicator being fixed, but in the opposite direction.

**Comment by marlitas** [comment]
Bummer. I thought I checked that. I think this issue is now dependent on https://github.com/phetsims/center-and-variability/issues/223 since this is an MVT mismatch problem.

**Comment by samreid** [comment]
@matthew-blackman @marlitas and I corrected it in the commit, closing.
