### ISSUE TITLE
MAD info box polishes

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#231]
I noticed in the MAD info box there are a few things.
<img width="881" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/1dbdf5a9-dd4e-451f-9782-12e9af551a56">

- [x] When the data points are close to the mean, the distance values overlap (and sometimes straddle) the mean line. Let's make a minimum distance from the mean in the direction (left/right) the data points are so there's no overlap. And then once the distance the data point is from the mean line reaches and exceeds the minimum, then the distance centers. Maybe 3-5 pixels from the mean line? When the distance = 0.0, let's put the distance of 0.0 on the right side of the mean.
- [ ] The box seems to be too tall when there are 25-30 data points
- [x] The size of the word, "Distance (meters)" is small. Let's increase the font size (I don't know what it is currently so I don't have a good recommendation). Actually, this will need to happen on the main screens (all 3) and all the info boxes.

**Comment by catherinecarter** [comment]
The info dialog box looks fine smaller, but it does make the other font sizes look exaggeratedly big. Not sure what font size the definition of the MAD is (and subsequent calculations), but we could decrease the font of all of those so the disparity isn't so large. This would include the numbers below the number line. 

We could decrease the font size of the other info box definitions/calculations to match. Is this what you meant by "other labels?"

**Comment by samreid** [comment]
After the commit, texts are nudged to the side like this.  ![image](https://github.com/phetsims/center-and-variability/assets/679486/620f3449-81de-4133-b6ba-472681cd883d)

Also, I bump 0.0 to the right:

![image](https://github.com/phetsims/center-and-variability/assets/679486/180b30f4-ccf8-4302-bd1f-54b9d376d967)

**Comment by samreid** [comment]
> Let's increase the font size (I don't know what it is currently so I don't have a good recommendation). 

You can usually say something like "increase it by 20%" or some relative proportion.

**Comment by samreid** [comment]
> The box seems to be too tall when there are 25-30 data points

It is now this size:

![image](https://github.com/phetsims/center-and-variability/assets/679486/34a3b998-60e8-4268-a24a-e3f6bd0c050e)

Is that ok? I think this issue is ready for design review.

**Comment by samreid** [comment]
I slacked @jessegreenberg to ask for assistance.

**Comment by marlitas** [comment]
Un-assigning myself since it seems what is left here is design review. If notes come back feel free to assign me again.

**Comment by catherinecarter** [comment]
The font sizes and the placement of the distances look great. There is overlap at the top of the labels with the notches on the MAD marker.


![Image](https://github.com/phetsims/center-and-variability/assets/109630002/50bd988e-9ce3-4e28-aeaf-fce2bf57ec89)


Let's move the notches up so the distance measurement at the top doesn't overlap with the MAD marker. Looking really good!

**Comment by samreid** [comment]
Excellent, thanks.  To keep this issue clearer, I'll move that last request to a dedicated issue, and close this one.
