### ISSUE TITLE
All PatternStringProperties should be instrumented

### ISSUE THREAD

**Issue by zepumph** [phetsims/center-and-variability#238]
From https://github.com/phetsims/phet-io/issues/1942, I passed some tandems through but mostly `Tandem.OPT_OUT`s, please review this sim's instrumentation of PatternStringProperties in correlation to this sims' phet-io priorities.  In general all PatternStringProperties should be instrumented unless they are just symbols or patterns that aren't for i18n purposes. 

UPDATE: This is in line with our agreement that all translatable on-screen text should be studio autoselectable.

**Comment by samreid** [comment]
In reviewing this issue, I saw there is only one remaining OPT_OUT and it is unrelated to PatternStringProperty.  I saw that all 14 PatternStringProperty occurrences have tandems, and I also recall we discussed with @pixelzoom @arouinfar and @zepumph that we no longer have the constraint that every text on the screen must be autoselectable.  I also tested in studio and saw that the text I tested did have autoselect. Closing.
