### ISSUE TITLE
Duplicated code for sorting soccer balls

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#242]
Duplicated in 3 places, in 3 files:

```ts
      const sortedDots = _.sortBy( sceneModel.getActiveSoccerBalls().filter( soccerBall => soccerBall.valueProperty.value !== null ),
        object => object.valueProperty.value );
```

Suggested that you move this into something like `sceneModel.getActiveSoccerBallsSorted`.

**Comment by matthew-blackman** [comment]
I will take a look at this and try to refactor the code to use a public method in SceneModel.

**Comment by matthew-blackman** [comment]
This is ready for your review @marlitas. It does seem like the sorting in CAVSceneModel could be further optimized, but when I tried to use getSortedLandedObjects as a part of getSortedStackedObjects, I ran into some issues with the IQRNode not updating correctly.

**Comment by marlitas** [comment]
I think this refactor is great and cleaned up that duplication. I don't think further optimization is necessary. I checked for duplication of `this.getActiveSoccerBalls().filter( soccerBall => soccerBall.valueProperty.value !== null )` and didn't find anything. I'm ready to close!
