### ISSUE TITLE
Factor out duplicate expression

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#243]
In MADNode.ts https://github.com/phetsims/center-and-variability/commit/a24b49ffc61e11eb4b84b7dd43d6a40380c13c6a ...

`( options.parentContext === 'info' || model.isMADVisibleProperty.value ) && mad !== null && sortedDots.length > 1` is duplicated 4 times on the righthand side of each of these assignments:

```ts
      leftBar.visible = ( options.parentContext === 'info' || model.isMADVisibleProperty.value ) && mad !== null && sortedDots.length > 1;
      rightBar.visible = ( options.parentContext === 'info' || model.isMADVisibleProperty.value ) && mad !== null && sortedDots.length > 1;
      leftReadout.visible = ( options.parentContext === 'info' || model.isMADVisibleProperty.value ) && mad !== null && sortedDots.length > 1;
      rightReadout.visible = ( options.parentContext === 'info' || model.isMADVisibleProperty.value ) && mad !== null && sortedDots.length > 1;
```

**Comment by pixelzoom** [comment]
Or if the visibility of all all 4 Nodes (`leftBar`,...) is intended to be the same, then add them to a parent Node, and control the parent's visibility.

**Comment by matthew-blackman** [comment]
@samreid @marlitas and I agree that this can be refactored by nesting the child components in a single node, so their visibility can be controlled together.

**Comment by matthew-blackman** [comment]
The above agreed-upon changes have been implemented and are very straightforward. Closing.
