### ISSUE TITLE
Card Sounds

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#245]
While going through https://github.com/phetsims/center-and-variability/issues/235, I was surprised to find that the card shuffling sound does not play when a user checks `Sort Data`. It seemed odd to me that we would hear the shuffling sound in one context, but not the other. My recommendation would be to add it so that the shuffling sound plays both when a user shuffles the cards themselves, or when the `Sort Data` checkbox shuffles the cards for the user.

Sending over to designers to confirm wether or not this would be desired.

**Comment by emily-phet** [comment]
Agreed - We were trying to hear the sound in the context, this wasn't the complete design implemented.

**Comment by marlitas** [comment]
That is enough of a go-ahead for me. Assigning back to @samreid and I, for whoever can tackle first.

**Comment by matthew-blackman** [comment]
One additional note here: When the checkbox is clicked, we will play the default checkbox sound. Additionally, if this causes the cards to sort we also want to play the card shuffling sound.

**Comment by emily-phet** [comment]
I think the default checkbox sound should be removed. Unless you tried it and feel strongly otherwise, my guess is the default checkbox sound will be unnecessary since you'll hear a paper shuffling sound (as the papers are sorted), or a paper confirmation sound (if the papers are already sorted). 
The default checkbox sound could be played if the checkbox is available when there are no cards to sort.

**Comment by catherinecarter** [comment]
I think we'll want to hear a small sound to indicate the cards have been sorted rather than the default checkbox sound. Maybe the default when the user unchecks the box, but when the user chooses to sort the cards by using the checkbox, there should probably be a confirmation sound that the cards have been sorted (different sound than the celebration from manually sorting).

**Comment by catherinecarter** [comment]
I guess Emily and I were thinking the same thing at the same time :)

**Comment by matthew-blackman** [comment]
Thanks for clarifying @emily-phet and @catherinecarter! To confirm the design, we will have multiple sound effects to account for here:

1) A paper shuffling sound
2) A paper confirmation sound (different than the celebration sound?)
3) A celebration sound
4) The default checkbox sound

The devs would like some additional clarity on when these sounds should be played, and whether there should be cases in which multiple sounds are played.

We also discussed the case in which a new ball lands when 'Sort Data' is checked, which causes existing cards to shift position. In this case, we feel that it wouldn't make sense to play the card shuffle sound, but we want to confirm with the designers.

**Comment by emily-phet** [comment]
My thoughts:

There is also a paper pick up sound played when a paper is picked up, and a drop sound when the paper is released.

1. The paper shuffling sound should play whenever a card moves position. This sound becomes associated with the movement of the card (not appearance, just movement), so any card movement should have an associated shuffle sound, regardless of whether or not the card is moving because of a user action or because of a sim setting.
2. Not sure what you refer to here - I think using the language in the sound design doc will be helpful in keeping things straight. I think you might mean - confirmation sound heard when "sort data" is checked AND the cards are already sorted. This would play only in this specific scenario. No default checkbox sound would be heard in this situation. 
3. The celebration sound plays only when the celebration animations are occurring. 
4. The default checkbox sound only plays when the sort data checkbox is selected and there are no cards to sort.

We have updated the sound design doc to start with 3 tables, one for each screen, that lists the individual sounds, has a place for the sound mapping and a description of the aesthetics of the sound, and the current status. That would probably be helpful to review and use those sound names for reference.

**Comment by samreid** [comment]
> regardless of whether or not the card is moving because of a user action or because of a sim setting.

Thanks, I wanted to ask about this.  I recalled a design consideration that sounds are generally associated with user input, like in the input listeners) rather than driven by the model. I thought this was due to exceptions like "we don't want the sound during reset all, or when phet-io sets the state, or when phet-io makes an API call" So this would be good to clarify. I feel the implementation may be simplest and most robust if we can implement it in the model, and add exceptions as necessary.

**Comment by samreid** [comment]
Another patch with ideas about playing sounds based on card movement:

<details>

```diff

Subject: [PATCH] Another
---
Index: js/median/view/CardNodeContainer.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/median/view/CardNodeContainer.ts b/js/median/view/CardNodeContainer.ts
--- a/js/median/view/CardNodeContainer.ts	(revision cbde23dba23017449b9d9d07df1eccbed0d31a64)
+++ b/js/median/view/CardNodeContainer.ts	(date 1686107771268)
@@ -67,11 +67,15 @@
   cvCardMovementSound7_mp3
 ];
 
-const cardMovementSoundClips = cardMovementSounds.map( sound => new SoundClip( sound, {
-  initialOutputLevel: 0.4,
+export const cardMovementSoundClips = cardMovementSounds.map( sound => new SoundClip( sound, {
+  initialOutputLevel: 1,
   additionalAudioNodes: [ new BiquadFilterNode( phetAudioContext, {
-    frequency: 750,
-    Q: 0.5,
+    frequency: 800,
+    Q: 10,
+    type: 'highpass'
+  } ), new BiquadFilterNode( phetAudioContext, {
+    frequency: 1400,
+    Q: 10,
     type: 'lowpass'
   } ) ]
 } ) );
@@ -146,7 +150,7 @@
         if ( !isPressed && !isSettingPhetioStateProperty.value ) {
 
           // Animate the dropped card home
-          this.animateToHomeCell( cardNode, 0.2 );
+          this.animateToHomeCell( cardNode, 0.2, true );
 
           if ( this.isReadyForCelebration ) {
             const inProgressAnimations = this.cardNodeCells.filter( cardNode => cardNode.animation )
@@ -248,7 +252,7 @@
 
           // Animate all displaced cards
           for ( let i = targetIndex; i < this.cardNodeCells.length; i++ ) {
-            this.animateToHomeCell( this.cardNodeCells[ i ] );
+            this.animateToHomeCell( this.cardNodeCells[ i ], 0.3, true );
           }
 
           this.cardNodeCellsChangedEmitter.emit();
@@ -432,7 +436,7 @@
           this.cardNodeCells[ originalCell ] = currentOccupant;
 
           // Just animated the displaced occupant
-          this.animateToHomeCell( currentOccupant );
+          this.animateToHomeCell( currentOccupant, 0.3, false );
           CAVQueryParameters.cardTones && NumberTone.play( currentOccupant.soccerBall.valueProperty.value! );
 
           // See if the user unsorted the data.  If so, uncheck the "Sort Data" checkbox
@@ -448,7 +452,7 @@
           const randomSound = cardMovementSoundClips[ dotRandom.nextInt( cardMovementSoundClips.length ) ];
 
           // Moving to the right, go up in pitch by 4 semitones
-          randomSound.setPlaybackRate( dragCell < originalCell ? 1 : Math.pow( 2, 4 / 12 ) );
+          randomSound.setPlaybackRate( ( dragCell < originalCell ? 1 : Math.pow( 2, 4 / 12 ) ) /2 );
           randomSound.play();
         }
       }
@@ -609,8 +613,8 @@
     return new Vector2( getCardPositionX( homeIndex ), 0 );
   }
 
-  public animateToHomeCell( cardNode: CardNode, duration = 0.3 ): void {
-    cardNode.animateTo( this.getHomePosition( cardNode ), duration );
+  public animateToHomeCell( cardNode: CardNode, duration: number, audio: boolean ): void {
+    cardNode.animateTo( this.getHomePosition( cardNode ), duration, true );
   }
 
   public setAtHomeCell( cardNode: CardNode ): void {
@@ -640,7 +644,7 @@
     const sorted = _.sortBy( this.cardNodeCells, cardNode => cardNode.soccerBall.valueProperty.value );
     this.cardNodeCells.length = 0;
     this.cardNodeCells.push( ...sorted );
-    this.cardNodeCells.forEach( cardNode => this.animateToHomeCell( cardNode, 0.5 ) );
+    this.cardNodeCells.forEach( cardNode => this.animateToHomeCell( cardNode, 0.5, true ) );
     this.cardNodeCellsChangedEmitter.emit();
   }
 
Index: js/median/view/CardNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/median/view/CardNode.ts b/js/median/view/CardNode.ts
--- a/js/median/view/CardNode.ts	(revision cbde23dba23017449b9d9d07df1eccbed0d31a64)
+++ b/js/median/view/CardNode.ts	(date 1686107123131)
@@ -23,6 +23,8 @@
 import TEmitter from '../../../../axon/js/TEmitter.js';
 import NumberTone from '../../common/model/NumberTone.js';
 import CAVQueryParameters from '../../common/CAVQueryParameters.js';
+import dotRandom from '../../../../dot/js/dotRandom.js';
+import { cardMovementSoundClips } from './CardNodeContainer.js';
 
 type SelfOptions = EmptySelfOptions;
 export type CardNodeOptions = SelfOptions & NodeOptions & PickRequired<NodeOptions, 'tandem'>;
@@ -108,7 +110,7 @@
     this.soccerBall.dragStartedEmitter.addListener( () => this.moveToFront() );
   }
 
-  public animateTo( destination: Vector2, duration: number ): void {
+  public animateTo( destination: Vector2, duration: number, audio: boolean ): void {
 
     if ( this.animation ) {
 
@@ -146,6 +148,12 @@
       this.animationTo = null;
     } );
 
+    const randomSound = cardMovementSoundClips[ dotRandom.nextInt( cardMovementSoundClips.length ) ];
+
+    // Moving to the right, go up in pitch by 4 semitones
+    randomSound.setPlaybackRate( destination.x < this.positionProperty.value.x ? 1 : Math.pow( 2, 4 / 12 ) );
+    randomSound.play();
+
     this.animation.start();
   }
 }

```

</details>

I feel it would be better to work on this with improved sounds.  I was unable to get the sound effect we discussed via filters.

**Comment by emily-phet** [comment]
Note - I don't think we've said this explicitly, but we'll also want to hear card "sliding" sound when new cards are added and the "Sort Data" checkbox is selected and cards are animated as sliding to fit into their correct location.

**Comment by marlitas** [comment]
> The card "whoosh/paper flutter" sound is the sound of cards sliding along the "surface" of the accordion box (like sliding along a table top). Cards animated in front of other cards are moving as if they had been picked up, and do not make the whoosh/paper flutter sound.

I looked through the code to see if I could start with some implementation that works along this logic... These are the things I noticed that could be blockers, but @samreid may have a clearer idea since he has worked in this part of the code more:

1. We are not currently tracking the z-order of cards... and I would not recommend that we do track the z-order. Anytime I've had to do that it's been a nuisance... We have plenty of soccerBall z-order issues in this repo we can refer to as an example of that.
2. Without tracking the z-order I do not know how to determine which cards are sliding in front, and which are sliding behind... Which means that I don't know which cards to turn sound on for with the suggested implementation.
3. Currently the cards are being sorted in a very simple and straightforward way. We essentially just reassign the cardNodeCells to the cards sorted by their value... this also means that we are not tracking how they used to be sorted, where they came from, or how many of them moved. 

Overall I would recommend not overhauling the way we sort cards. It's very straightforward with almost no complexity. I would hope that we can find a sound design that works with this current implementation.

**Comment by samreid** [comment]
Summarizing recommendations from above:

### When the checkbox is checked
- [ ] If the cards move, play the card movement sounds.
- [ ] If there are no cards, play the default sound.
- [ ] If the cards are already sorted, play a sort confirmation sound.
- [ ] There is also a paper pick up sound played when a paper is picked up, and a drop sound when the paper is released.
- [ ] The paper shuffling sound should play whenever a card moves position. Even if other sounds are playing at the same time. Even when a ball lands and "sort" is checked.
- [ ] When multiple cards move at once, we only need to play one sound per direction.

> Cards animated in front of other cards are moving as if they had been picked up, and do not make the whoosh/paper flutter sound.

That seems inconsistent with the prior decision that dragging a picked up card and translating it does play a sound of that card (and not of the other cards that move out of the way).

Also, I observed that some people refer to them as paper, and some refer to them as cards. So I recommend we defer to the terminology established in the design doc which is a "value card", "number card" or simply "card".

**Comment by samreid** [comment]
I implemented a first draft of all the checkboxes above, each with placeholder audio sounds that can be easily replaced when we have the desired mp3s.

**Comment by Ashton-Morris** [comment]
Emily and I talked about the card sounds today. We both agreed that upon reflection that they sound good as is.

But I am curious @samreid if you could create a version where the playback rate of the cards is sped up 10%-15% (your discretion) if it would sound more like cards and less like large paper? **Could you create a build I could hear that on?**

Also PhET has sims have a default IR Reverb on the sounds and I was wondering if its possible to disable the IR just for the card sounds? I think it might sound more natural without it.

**Comment by Ashton-Morris** [comment]
I have added these sounds to our [CV Sounds folder ](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/PhET%20Files/Forms/AllItems.aspx?id=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Sim%20Design%2FMeet%20in%20the%20Middle%20HTML5%20%28Suite%29%2FCenter%20and%20Variability%20HTML5%2FSounds&viewid=3aa550f4%2Df9ef%2D4871%2Dbcb3%2Da192486a9aaa)to be tested out for picking up and dropping cards. Hopefully they are short enough. 

- cvCardDropSound.mp3
- cvCardPickupSound.mp3

**Comment by samreid** [comment]
Here is a "before" URL with the sounds as they are now, before making the changes requested in the preceding 2 comments: https://phet-dev.colorado.edu/html/center-and-variability/1.1.0-dev.7/phet/center-and-variability_all_phet.html

**Comment by samreid** [comment]
I added a query parameter `cardMovementSoundPlaybackRate` defaulting to 1.1,  But it sounds like 1.5 is ok too.  You should also experiment with extremes like 2 or 10.  Here's a link for the 1.5, for example: https://bayes.colorado.edu/dev/phettest/center-and-variability/center-and-variability_en.html?ea&brand=phet&cardMovementSoundPlaybackRate=1.5

I didn't change the card drop and pick up sounds yet.

**Comment by samreid** [comment]
I implemented the new card pick up and drop sounds.  They do not change the playback rate. Ready for testing on the link above.  Also, I have noticed in several audio files there is a long, quite lead in before the sound starts:

![image](https://github.com/phetsims/center-and-variability/assets/679486/61b68670-3ceb-41ff-bae0-32353e89ebd5)

This can lead to a perceived delay in the responsiveness of the audio.  Should we trim some of the audio clips?

**Comment by Ashton-Morris** [comment]
I think 1.5 sounds great. I also played with different rates which do sound good, so I am curious to hear what the team things at 1.5.

As for shortening them, I don't think we need to adjust them. I know that visually we can see the gap but realistically each playback is a fraction of a second (and less if its at 1.5.) I don't think people can pick up on those microsecond differences.

**Comment by Ashton-Morris** [comment]
> I added a query parameter `cardMovementSoundPlaybackRate` defaulting to 1.1, But it sounds like 1.5 is ok too. You should also experiment with extremes like 2 or 10. Here's a link for the 1.5, for example: https://bayes.colorado.edu/dev/phettest/center-and-variability/center-and-variability_en.html?ea&brand=phet&cardMovementSoundPlaybackRate=1.5
> 
> I didn't change the card drop and pick up sounds yet.

@emily-phet take a listen to this link when you get a chance.

**Comment by catherinecarter** [comment]
I also really like the 1.5 playback speed. I think it sounds really great.

I look forward to hearing what the pick up/drop sounds like when coupled with the 1.5 right/left speed. It's distracting to me right now when I pick up, but especially when I drop a card.

**Comment by samreid** [comment]
Thanks, I set the default cardMovementSoundPlaybackRate to 1.5.  Based on @catherinecarter's remark above, it sounds like she wants to try speeding up the pick up/drop sounds accordingly.

**Comment by samreid** [comment]
In the next commit, I also apply the cardMovementPlaybackRate to the card pick up/drop sounds.  I don't know if that's what @Ashton-Morris originally intended, and I also don't know if it sounds better. But it is easy to adjust. Let me know what speed we want for those sounds.

**Comment by Ashton-Morris** [comment]
@samreid Unless it sounds out of place. I think the pick up and drop should be at the same playback rate as whatever we choose for the rest of the cards.

**Comment by samreid** [comment]
OK I implemented that, thanks. You can hear it on https://bayes.colorado.edu/dev/phettest/center-and-variability/center-and-variability_en.html?ea&brand=phet

**Comment by emily-phet** [comment]
I listened to the sim in the link from the [previous comment](https://github.com/phetsims/center-and-variability/issues/245#issuecomment-1603383594).

I think that the sounds for the cards are fine; this just seems to be one of those tricky sounds. There is some clunkiness in how they are experienced currently. 

- There is not a consistent association of the "pick up" sound with the visual experience of "picking up" the cards. You hear the sound whether or not the card has changed position, which does not feel good to me. For example, you can click on a card repeatedly and hear the pick up and drop sounds without the carding appearing to have moved at all. More ideal is if the card appears to be slightly raised in the z-plane once it is picked up. Then repeated clicking would raise and lower the card, the sound would feel consistent with that and you're providing visual feedback to the learner that they have actually done something to affect the card. 

- The pickup and drop sounds feel very loud and emphatic. Not sure if decrease in gain is the solution, or a filter, but they feel too emphatic to me. 

- It doesn't seem like the card sorting logic is in place. I do think that the card drop sound is a good one for the case when "sort data" is checked but the cards are already sorted. Even better would be to animate them all to slightly raise and lower, then there would be consistency across the visual and auditory space, and learners would get a cue that the act they requested in checking the box actually happened (just no cards needed to be moved). 

- it seems like the cards are not implemented with alternative input access, for example, I couldn't tab to them. Let me know if that is the case and if that is intentional. I would suggest they be implemented for alternative input access. Perhaps there is an issue with a design pattern for sorting?

**Comment by samreid** [comment]
Patch from today's mockup, playing when cards animate past each other:

<details>

```diff

Subject: [PATCH] Change success sound, see https://github.com/phetsims/center-and-variability/issues/226
---
Index: main/center-and-variability/js/median/view/CardNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/center-and-variability/js/median/view/CardNode.ts b/main/center-and-variability/js/median/view/CardNode.ts
--- a/main/center-and-variability/js/median/view/CardNode.ts	(revision 58139a4f40340bc720f2d42a92e4fd560872c8ac)
+++ b/main/center-and-variability/js/median/view/CardNode.ts	(date 1687549724388)
@@ -22,7 +22,7 @@
 import PickRequired from '../../../../phet-core/js/types/PickRequired.js';
 import TEmitter from '../../../../axon/js/TEmitter.js';
 import dotRandom from '../../../../dot/js/dotRandom.js';
-import { cardMovementSoundClips } from './CardNodeContainer.js';
+import CardNodeContainer, { cardMovementSoundClips } from './CardNodeContainer.js';
 import SoundClip from '../../../../tambo/js/sound-generators/SoundClip.js';
 import soundManager from '../../../../tambo/js/soundManager.js';
 import cvCardPickupSound_mp3 from '../../../sounds/cvCardPickupSound_mp3.js';
@@ -60,7 +60,7 @@
 
   public static readonly CARD_DIMENSION = 43;
 
-  public constructor( cardModel: CardModel, position: Vector2, getDragRange: () => Range, providedOptions: CardNodeOptions ) {
+  public constructor( public readonly cardNodeContainer: CardNodeContainer, cardModel: CardModel, position: Vector2, getDragRange: () => Range, providedOptions: CardNodeOptions ) {
 
     const cornerRadius = 10;
     const rectangle = new Rectangle( 0, 0, CardNode.CARD_DIMENSION, CardNode.CARD_DIMENSION, cornerRadius, cornerRadius, {
@@ -160,6 +160,22 @@
     } );
     this.animationTo = destination;
 
+    let numberCardsOnTheLeft = this.cardNodeContainer.countCardsToTheLeft( this );
+    this.animation.beforeStepEmitter.addListener( () => {
+      numberCardsOnTheLeft = this.cardNodeContainer.countCardsToTheLeft( this );
+    } );
+    this.animation.updateEmitter.addListener( () => {
+      const newNumberOfCardsToTheLeft = this.cardNodeContainer.countCardsToTheLeft( this );
+
+      if ( newNumberOfCardsToTheLeft !== numberCardsOnTheLeft ) {
+        const randomSound = cardMovementSoundClips[ dotRandom.nextInt( cardMovementSoundClips.length ) ];
+
+        // Moving to the right, go up in pitch by 4 semitones
+        randomSound.setPlaybackRate( CAVQueryParameters.cardMovementSoundPlaybackRate * ( destination.x < this.positionProperty.value.x ? 1 : Math.pow( 2, 4 / 12 ) ) );
+        randomSound.play();
+      }
+    } );
+
     this.animation.endedEmitter.addListener( () => {
       this.animation = null;
       this.animationTo = null;
Index: main/twixt/js/Animation.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/twixt/js/Animation.ts b/main/twixt/js/Animation.ts
--- a/main/twixt/js/Animation.ts	(revision bd5e8059472d35d6e320cb0b433b75f6287b3e4b)
+++ b/main/twixt/js/Animation.ts	(date 1687549641425)
@@ -111,6 +111,7 @@
 
   // Fired when (just after) the animation has changed animated values/targets.
   public readonly updateEmitter = new Emitter();
+  public readonly beforeStepEmitter = new Emitter();
 
   /**
    * The constructor config will define one or more animation "targets" (specific values to be animated). The config
@@ -265,6 +266,8 @@
    */
   public step( dt: number ): this {
 
+    this.beforeStepEmitter.emit();
+
     // Ignore the step if our animation is not running
     if ( !this.runningProperty.value ) {
       return this;
Index: main/center-and-variability/js/median/view/CardNodeContainer.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/center-and-variability/js/median/view/CardNodeContainer.ts b/main/center-and-variability/js/median/view/CardNodeContainer.ts
--- a/main/center-and-variability/js/median/view/CardNodeContainer.ts	(revision 58139a4f40340bc720f2d42a92e4fd560872c8ac)
+++ b/main/center-and-variability/js/median/view/CardNodeContainer.ts	(date 1687549828688)
@@ -138,7 +138,7 @@
     } );
 
     this.cardNodes = model.cards.map( ( cardModel, index ) => {
-      const cardNode = new CardNode( cardModel, new Vector2( 0, 0 ), () => this.getDragRange(), {
+      const cardNode = new CardNode( this, cardModel, new Vector2( 0, 0 ), () => this.getDragRange(), {
         tandem: options.tandem.createTandem( 'cardNodes' ).createTandem1Indexed( 'cardNode', index )
       } );
 
@@ -694,6 +694,10 @@
     this.cardNodeCellsChangedEmitter.emit();
   }
 
+  public countCardsToTheLeft( cardNode: CardNode ): number {
+    return this.cardNodes.filter( otherCardNode => otherCardNode.positionProperty.value.x < cardNode.positionProperty.value.x ).length;
+  }
+
   private getDragRange(): Range {
     const maxX = this.cardNodeCells.length > 0 ? getCardPositionX( this.cardNodeCells.length - 1 ) : 0;
     return new Range( 0, maxX );

**Comment by samreid** [comment]
> There is not a consistent association of the "pick up" sound with the visual experience of "picking up" the cards.

Should we try a drop shadow + offset when grabbing a card?

> The pickup and drop sounds feel very loud and emphatic. Not sure if decrease in gain is the solution, or a filter, but they feel too emphatic to me.

We softened it and increased the pitch during the meeting, and all agreed it sounded better.  @catherinecarter was interested in testing without a drop sound, but if we add a drop shadow when dragging it may be clearer when something is picked up/dropped and the sound may be more sensible.

> It doesn't seem like the card sorting logic is in place.

It sounds like the recommendation is to add an animation for when the data is already sorted, like the cards are all "picked up" but don't need to go anywhere, so they are dropped in place.  Should we try something like that?

> it seems like the cards are not implemented with alternative input access, for example, I couldn't tab to them.

We intend to implement that feature in https://github.com/phetsims/center-and-variability/issues/256

Lots of other comments from today's meeting including a mock-up of cards playing sounds when they animate past one another in https://github.com/phetsims/center-and-variability/issues/245#issuecomment-1604854799.  I feel today's meeting had good discussion and brainstorming, but next steps/decisions are somewhat unclear.

**Comment by samreid** [comment]
One implementation idea that may simplify "animate past each other" patch in https://github.com/phetsims/center-and-variability/issues/245#issuecomment-1604854799. In order to satisfy the "if the user is dragging a card to the right, play an increased pitch sound", we could change the patch to say: if the animated card moved past a card that has `isDragging===true`, play the opposite pitch.  And we would remove the "user dragging the card" sounds. Since a card animates out of the way when the user drags a card, the effect would be that if the user is dragging a card, you still get the pitch you want, but you don't get double sounds, and the implementation is simpler since it is all based on the animation step.

**Comment by catherinecarter** [comment]
Summarizing for the meeting, we will discuss the following sounds related to the cards:

- [ ] Animation for pick up/drop card
- [ ] For consistency, will leave pick up/drop sound in
- [ ] Shuffling of cards upon auto-sort
- [ ] Single sound for when cards are already sorted, perhaps a slight animation

**Comment by samreid** [comment]
I'll move the remaining requests to side issues, and close this one.

**Comment by samreid** [comment]
All side issues noted above, closing.
