### ISSUE TITLE
MAD plot updating twice per ball

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/center-and-variability#249]
The MAD plot is updating once when a ball lands and again when the ball reaches the top of the stack (see video below). We want to update this behavior to be consistent with https://github.com/phetsims/center-and-variability/issues/228 and update everything when the ball reaches the top of the stack.

https://github.com/phetsims/center-and-variability/assets/108756567/22f2b262-f688-4176-a140-46ece29a7718

**Comment by matthew-blackman** [comment]
This is ready for review. I set the variability plot nodes to update with variabilityDataMeasuresUpdatedEmitter, and limited updateDataMeasures to only be called in a ball finished stacking or is dragged to a new position.

**Comment by samreid** [comment]
Looks great to me, nice work.  Closing.
