### ISSUE TITLE
Accordion Box Median "Red Dot" Animation Sounds

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/center-and-variability#253]
Here is a video of how it sounds on my system.

[cvMedianComboBoxReadoutMockup.mov](https://o365coloradoedu.sharepoint.com/:v:/r/sites/PHYS-phet-pilot/PhET%20Files/PhET%20Files/PhET%20Sim%20Design/Meet%20in%20the%20Middle%20HTML5%20(Suite)/Center%20and%20Variability%20HTML5/Videos/[cvMedianComboBoxReadoutMockup.mov](https://o365coloradoedu.sharepoint.com/:v:/r/sites/PHYS-phet-pilot/PhET%20Files/PhET%20Files/PhET%20Sim%20Design/Meet%20in%20the%20Middle%20HTML5%20(Suite)/Center%20and%20Variability%20HTML5/Videos/cvMedianComboBoxReadoutMockup.mov?csf=1&web=1&e=99aNTG)?csf=1&web=1&e=99aNTG)

And here is a screenshot of my note mapping 
![Screenshot 2023-06-08 at 1 38 18 PM](https://github.com/phetsims/center-and-variability/assets/34492870/ed65ae24-b15a-4fe4-92d0-d6d75d7c22da)

I do feel like its a bit confusing to explain but here is how I am thinking you could implement it.

1. Start withe the Marimba sound for the counting down animation and use the Woodblock for the final number readout of the median.
2. Use a pentatonic scale like we discussed
3. The with of the pentatonic scale that plays before the median note rings out would be determined by the number of kicks. (I think) So 10 kicks would be 5 pairs of notes descending and ascending toward the final median note, and 30 kicks would be 15 pairs of notes.  
5. The notes in the pentatonic scale get successively higher and lower for each pair of kicks.
6. Move the entire sequence up or down depending on what number the median ends up being. 

So 4 kicks would look like this: 
![Screenshot 2023-06-08 at 1 56 54 PM](https://github.com/phetsims/center-and-variability/assets/34492870/34869e52-5084-4773-9f88-2115f4d88b20)
And 8 kicks would look like this:
![Screenshot 2023-06-08 at 1 57 06 PM](https://github.com/phetsims/center-and-variability/assets/34492870/2ccb4a87-94e2-4818-a59f-3f7230d5644b)

**Comment by samreid** [comment]
That *.mov link did not work for me, can it be checked?

**Comment by Ashton-Morris** [comment]
I had the same issue? [Ok check this one.](https://o365coloradoedu.sharepoint.com/:v:/s/PHYS-phet-pilot/ETWhZgjvq5NNt3b3JL4-1KEB6aEkz3U1fcXN_H_Y1JCl-A?e=01Ieu4)

**Comment by marlitas** [comment]
The CT error `Uncaught Error: Assertion failed: value null is out of range` popped up because of https://github.com/phetsims/center-and-variability/commit/b6bf23ac9d37e8d89fff05d62538d18e2a017f86. I was able to fix by first checking that medianValueProperty was not null before triggering the animation. Seems to be working as expected now, but would be good for @samreid to double check.

**Comment by samreid** [comment]
Thanks @marlitas. I feel this issue is ready for design feedback.  @Ashton-Morris can you please test it on phettest and let us know how it sounds?

**Comment by Ashton-Morris** [comment]
@samreid This sounds perfect! Spot on to what I had imagined.

**Comment by samreid** [comment]
Excellent, thanks! I'll reassign to @marlitas and @matthew-blackman for a code review.  After that, the issue can be closed.

**Comment by marlitas** [comment]
The commits here look good @samreid, but I did have a question come up about the variables: `upperSoundClip` and `lowerSoundClip`. I couldn't tell if these were named that way because one is played in the "upper" accordion box area, and the other is played in the "lower" play area, or if it was in reference to their actual pitch... 
 
Either way I think they need a bit more documentation.

**Comment by samreid** [comment]
The design team agreed the sound is good. Just wrapping up code review here.

**Comment by samreid** [comment]
I updated the documentation and inlined some variables.  @marlitas can you please re-review?

**Comment by samreid** [comment]
And sneaked in one more commit.

**Comment by marlitas** [comment]
Looks good! Closing.
