### ISSUE TITLE
Be able to load a new set of data mid-sim run

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/center-and-variability#258]
- Set an new set data during the sim run (set Value for the the array of balls - their position rather than a frequency distribution) - Perhaps this would be done the same way as we did it in  CCK Circuits
- Add iO type per screen+scene
- API call on that iO type that says “set data points” 
- If the user sets 7 points, for example, only 7 balls would be in the play area (no more are kickable after this method is called)
- Clear
- What if the max is set to 15 but a user sets data for 16?
  - Truncate to 15 but put a message that 15 have been exceeded to console
  - Validate values to be within 1-15, inclusive, could validate to the number of max kicks
  - Use standard validation stage to say the array is ‘out of bounds’
- phetioClient.invoke(‘centerAndVariability.variabilityScreen.model.scene1Model’,’setDataPoints’,([1,1,3,2,7,7,3])
- VS 
- centerAndVariability.variabilityScreen.model.scene1Model.dataValues
  - setValue
  - getValue

**Comment by samreid** [comment]
This may overlap with the ability to set the value of individual soccer balls as described in https://github.com/phetsims/center-and-variability/issues/262

**Comment by samreid** [comment]
Implemented above and tested with these API calls:

```ts
phetioClient.invoke('centerAndVariability.medianScreen.model.sceneModel','setDataPoints',[[1,2,3,4,4,4,4]]);

phetioClient.invoke('centerAndVariability.variabilityScreen.model.sceneModel1','setDataPoints',[[1,2,3,4,4,4,4,9,9,9,10,10]]);
```
You can paste those commands into the console while running studio.
Everything seems to work well, the only problem I'm aware of is that a sound effect plays when the cards are created.

Also, I still need to guard against if this value exceeds `maxKicks`.

**Comment by samreid** [comment]
I was going to commit this patch to gracefully ignore data points beyond the max:

<details>

```diff

Subject: [PATCH] Add a PhET-iO API call to set data points, see https://github.com/phetsims/center-and-variability/issues/258
---
Index: js/soccer-common/model/SoccerSceneModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/soccer-common/model/SoccerSceneModel.ts b/js/soccer-common/model/SoccerSceneModel.ts
--- a/js/soccer-common/model/SoccerSceneModel.ts	(revision d5c0d3cdfcb34fea9b78bf0f4d675d55fdb3b8d7)
+++ b/js/soccer-common/model/SoccerSceneModel.ts	(date 1687313237287)
@@ -47,6 +47,7 @@
 import SoccerCommonQueryParameters from '../SoccerCommonQueryParameters.js';
 import Tandem from '../../../../tandem/js/Tandem.js';
 import ArrayIO from '../../../../tandem/js/types/ArrayIO.js';
+import CAVConstants, { MAX_KICKS_PROPERTY } from '../../common/CAVConstants.js';
 
 const kickSound = new SoundClip( basicKick_mp3, { initialOutputLevel: 0.2 } );
 soundManager.addSoundGenerator( kickSound );
@@ -618,6 +619,12 @@
    */
   public setDataPoints( dataPoints: number[] ): void {
 
+    // Ignore any data points beyond the max supported by MAX_KICKS_PROPERTY. Note this means a PhET-iO client needs
+    // to specify the MAX_KICKS_PROPERTY value before calling this method.
+    if ( dataPoints.length > MAX_KICKS_PROPERTY.value ) {
+      dataPoints.length = MAX_KICKS_PROPERTY.value;
+    }
+
     // Clear pre-existing data
     this.clearData();
 

```

</details>

However, it is does not correctly distinguish between the different max values between screen 1 (always limited to 15) and 2/3.  Also, there is another phet-io issue where the phet-io design team requested to be able to set the max kicks per scene, so we should figure that out before completing this issue.  Going on hold.

**Comment by marlitas** [comment]
We added this documentation to clarify the behavior of the function since it will ignore values in arrays if the array is too long.

> 'Sets the data points for the scene model. Array lengths that exceed maxKicks will ignore excess values.'

We may want to add to this in the future.

**Comment by marlitas** [comment]
I'm unclear what the status of this issue is... Is it now just waiting for review or can we close? Marking as help-wanted to discuss.

**Comment by matthew-blackman** [comment]
Everything looks good here, I think we just wanted to make a note that will need to be documented in examples.md. Closing this issue, feel free to reopen if anything else needs to be done.
