### ISSUE TITLE
Need an easy way to get the array of all current ball position values for what’s visible in the scene

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/center-and-variability#259]
Summary: This should be a method in the scene like in CCK.

**Comment by samreid** [comment]
```ts
await phetioClient.invokeAsync('centerAndVariability.medianScreen.model.sceneModel','getDataPoints',[]);
```

**Comment by samreid** [comment]
I also added an adapter that you can get/set the data for the currently selected scene in a model.  Tested via `await phetioClient.invokeAsync('centerAndVariability.variabilityScreen.model','getDataPoints',[]);` in the variability screen.

**Comment by samreid** [comment]
This should be documented in the examples guide.  Let's review it with the design team at an upcoming post-standup.

**Comment by catherinecarter** [comment]
Closing, will reference when the examples.md document gets created. Will copy the code above and explain how to get/set an array of ball locations.
