### ISSUE TITLE
If you click in the splash screen, a sound plays on startup

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#261]
If you click in the splash screen, a sound plays on startup. Discovered in https://github.com/phetsims/center-and-variability/issues/252

**Comment by samreid** [comment]
I ran 12 tests to check this, and I heard a half cut-off card whoosh sound once.  Very difficult to reproduce the problem.  @marlitas or @matthew-blackman does this occur more frequently on your platforms?

**Comment by marlitas** [comment]
@samreid I tried this about 10 times and didn't hear anything... This might be a "Let's see if it crops up in QA" bug... if it's that rare might not be worth investigation.

**Comment by matthew-blackman** [comment]
I think I can reproduce this pretty regularly, but only when dev tools are not open in Chrome. Super weird. Is it the faint "thud" sound that sometimes plays when clicking on the loading screen with the PhET logo?

Did some logging on startup and found that the following are logged on launch, but there are no changes to the logs when the errant sound is produced.
```
NumberTone.ts:139 medianSoundClip.play()
CardNode.ts:173 randomSound.play() - logged 15 times
CardNode.ts:173 randomSound.play() - logged 15 times
NumberTone.ts:139 medianSoundClip.play()
NumberTone.ts:139 medianSoundClip.play()
```

Could this be something happening as sounds are being loaded/buffered?

**Comment by samreid** [comment]
Thanks, with the chrome dev tools closed, I was able to hear a sound in 2/6 tries. It sounds like the card sound to me.

**Comment by samreid** [comment]
@matthew-blackman and I tracked down the sounds with SoundClip.play debugger, and found that several sounds were triggered during construction.  We changed the links to lazyLink, and it seemed to work well.  We will open a tambo issue to discuss with @jbphet whether tambo should gracefully ignore sounds before the sim starts, or throw an assertion.  Closing.
