### ISSUE TITLE
Changing the value of a soccer ball in studio is buggy

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#262]
Setting an unkicked ball from null to a number creates a card, but does not move the ball.

Changing the value from a number to null deletes a card but does not do anything to the soccer ball.

We aren't sure whether to implement this with guards or to try to handle it properly.  This overlaps with https://github.com/phetsims/center-and-variability/issues/258 somewhat.

**Comment by matthew-blackman** [comment]
@samreid @marlitas discussed this, and feel that this should be an implementation detail for https://github.com/phetsims/center-and-variability/issues/258. A designer should not be able to set the value of individual soccer balls that have not yet been kicked, but should not be able to set the value of a soccer ball from null to non-null. We also need to check the state wrapper to make sure that the state wrapper can differentiate between the readonly or non-readonly state of the soccer ball value property if it is updated.

We still have a lot of questions around the design of this, and would like to discuss it further to develop a plan.

**Comment by matthew-blackman** [comment]
The devs discussed this with @catherinecarter and @brent-phet, and the following considerations were brought up:

- A designer can already set a distribution of soccer balls to appear on load by using the following API:
   - phetioClient.invoke('centerAndVariability.medianScreen.model.sceneModel','setDataPoints',[[1,2,3,4,4,4,4]]);
- A designer should be able to change the value of a soccer ball once it is already on the field and has a non-null value.
- We do not need to support designers setting the value of a soccer ball from null to non-null via studio, as this would create significant complexity and brittleness in the code. If a designer wants to place an unkicked ball on the field, they can use the setDataPoints API.
- The devs will discuss what should happen if a designer tries to set the value of an unkicked soccer ball to non-null:
  - Option 1: Throw an error if the designer tries to do this
  - Option 2: Add an assertion that catches when a designer tries to do this
  - Option 3: Fail silently when a designer tries to do this
  - Option 4: Gracefully ignore when a designer tries to do this

**Comment by matthew-blackman** [comment]
The devs agreed to try Option 2 above, so that clients can catch any errors during testing with assertions turned on.

**Comment by samreid** [comment]
Implemented via collaboration with @marlitas and @matthew-blackman.  We would like a quick spot check review from @zepumph regarding the strategy and that it is an assertion instead of an error.  And we would like to check in at today's phet-io meeting with @kathy-phet @catherinecarter.

**Comment by marlitas** [comment]
We got a live visit from @zepumph and we will be ready to close if the spot check goes well.

**Comment by zepumph** [comment]
What do you think about making  class called `SoccerBallValueProperty`? This may keep the organization a bit better. Then you could override getValidationError on the actual class instead of just hacking it into the IOType. 

I'm also wondering if this could be solved with isValidValue if we outfitted that function to hold an optional previousValue argument, like `link` has. Probably not worth the effort. Oh, also we only want this behavior in the PropertyIO type, not the underling model setting.

**Comment by catherinecarter** [comment]
@kathy-phet is ok with this solution, is reminding us the documentation needs to be up to date and clear. For example, in `centerAndVariability.medianScreen.model.sceneModel.soccerBalls.soccerBall9.valueProperty`, the documentation could be, "In the case of a null value (meaning the ball has not been kicked yet), value cannot be set by user." Or something along those lines.

**Comment by marlitas** [comment]
@zepumph, @matthew-blackman and I talked through the refactor you suggested in  https://github.com/phetsims/center-and-variability/issues/262#issuecomment-1612062062. We have a lot of questions, and didn't feel comfortable moving forward with an implementation before clearing some things up. Would be great to connect synchronously with you on this.

**Comment by zepumph** [comment]
@matthew-blackman @marlitas and I did the refactor into SoccerBallValueProperty and things are looking very good! 

I was curious if we could move this to the isValidValue function instead of clogging up the IOType with the complexity, and it looks like we can't, since we don't know if the model (ok) is setting from null to non-null, or if a PhET-iO client (not ok) is. Here is a patch that we should never apply ever.


<details>

```diff
Subject: [PATCH] remove one ts-expect-error
---
Index: js/soccer-common/model/SoccerBallValueProperty.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/soccer-common/model/SoccerBallValueProperty.ts b/js/soccer-common/model/SoccerBallValueProperty.ts
--- a/js/soccer-common/model/SoccerBallValueProperty.ts	(revision 130ee98b1eef4991ce3486fa1ec550cdb95ee002)
+++ b/js/soccer-common/model/SoccerBallValueProperty.ts	(date 1688761027484)
@@ -10,14 +10,11 @@
  */
 
 import StrictOmit from '../../../../phet-core/js/types/StrictOmit.js';
-import ReadOnlyProperty, { PropertyOptions, ReadOnlyPropertyState } from '../../../../axon/js/ReadOnlyProperty.js';
+import { PropertyOptions } from '../../../../axon/js/ReadOnlyProperty.js';
 import optionize, { EmptySelfOptions } from '../../../../phet-core/js/optionize.js';
 import Property from '../../../../axon/js/Property.js';
 import soccerCommon from '../soccerCommon.js';
-import IOType from '../../../../tandem/js/types/IOType.js';
 import NullableIO from '../../../../tandem/js/types/NullableIO.js';
-import StringIO from '../../../../tandem/js/types/StringIO.js';
-import VoidIO from '../../../../tandem/js/types/VoidIO.js';
 import NumberIO from '../../../../tandem/js/types/NumberIO.js';
 
 type SelfOptions = EmptySelfOptions;
@@ -26,68 +23,42 @@
 export type SoccerBallValuePropertyOptions = SelfOptions & StrictOmit<PropertyOptions<number | null>, 'isValidValue' | 'valueType' | 'phetioValueType'>;
 
 export default class SoccerBallValueProperty extends Property<number | null> {
+  private allowNull = true;
 
-  public constructor( value: number | null, providedOptions?: SoccerBallValuePropertyOptions ) {
+  public constructor( value: null, providedOptions?: SoccerBallValuePropertyOptions ) {
+
+    let calledSuper = false;
 
     // Fill in superclass options that are controlled by BooleanProperty.
     const options = optionize<SoccerBallValuePropertyOptions, SelfOptions, PropertyOptions<number | null>>()( {
       phetioValueType: NullableIO( NumberIO ),
-      phetioOuterType: () => SoccerBallValueProperty.SoccerBallValuePropertyIO
+      validators: [ {
+        isValidValue: v => {
+          if ( calledSuper ) {
+            if ( !this.allowNull && v === null ) {
+              return false;
+            }
+            if ( this.value === null && v !== null ) { // This will never be useful since we don't know if it is from the model or PhET-iO
+              return false;
+            }
+          }
+          return true;
+        },
+        validationMessage: 'Cannot set to null after construction'
+
+      } ]
     }, providedOptions );
 
     super( value, options );
+    calledSuper = true;
+    this.allowNull = false;
   }
-
-  // See SoccerBallValuePropertyIO.documentation
-  private static validateSoccerBallValue( oldValue: number | null, newValue: number | null ): string | null {
-    if ( oldValue === null && newValue !== null ) {
-      return 'Cannot change a null value to a non-null value.';
-    }
-    else if ( oldValue !== null && newValue === null ) {
-      return 'Cannot change a non-null value to a null value.';
-    }
-    else {
-      return null;
-    }
-  }
-
-  public static SoccerBallValuePropertyIO = new IOType<ReadOnlyProperty<number | null>, ReadOnlyPropertyState<number | null>>( 'SoccerBallValuePropertyIO', {
-    documentation: 'Soccer ball values cannot be changed from null to non-null or vice versa by PhET-iO clients. This ' +
-                   'IOType adds validation and assertions for those cases.',
-    supertype: ReadOnlyProperty.PropertyIO( NullableIO( NumberIO ) ),
-    parameterTypes: [ NullableIO( NumberIO ) ],
-    methods: {
-      getValidationError: {
-        returnType: NullableIO( StringIO ),
-        parameterTypes: [ NullableIO( NumberIO ) ],
-        implementation: function( this: ReadOnlyProperty<number | null>, value: number | null ) {
-
-          return SoccerBallValueProperty.validateSoccerBallValue( this.value, value ) ||
-
-                 // Check with the supertype to see if it is valid, this will check if it is range, etc.
-                 ReadOnlyProperty.PropertyIO( NullableIO( NumberIO ) ).methods!.getValidationError.implementation.call( this, value );
-        },
-        documentation: 'Checks to see if a proposed value is valid. Returns the first validation error, or null if the value is valid.'
-      },
-
-      setValue: {
-        returnType: VoidIO,
-        parameterTypes: [ NullableIO( NumberIO ) ],
-        implementation: function( this: SoccerBallValueProperty, value: number | null ) {
-
-          const validationError = SoccerBallValueProperty.validateSoccerBallValue( this.value, value );
-          if ( validationError ) {
-            throw new Error( validationError );
-          }
 
-          this.set( value );
-        },
-        documentation: 'Sets the value of the Property. If the value differs from the previous value, listeners are ' +
-                       'notified with the new value.',
-        invocableForReadOnlyElements: false
-      }
-    }
-  } );
+  public override reset(): void {
+    this.allowNull = true;
+    super.reset();
+    this.allowNull = false;
+  }
 }
 
 soccerCommon.register( 'SoccerBallValueProperty', SoccerBallValueProperty );
\ No newline at end of file

**Comment by marlitas** [comment]
After the collaboration with @matthew-blackman and @zepumph I think this issue is ready to close. Thanks everyone!
