### ISSUE TITLE
soccerBallNodeGroup should not be nested under dragIndicator Model

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#264]
There's some trickiness here... we would like to discuss.

**Comment by samreid** [comment]
I'll take a look.  Self assigning.

**Comment by samreid** [comment]
In the commit, I moved it out to the model:

> Move soccerBallNodeGroup.inputEnabledProperty to model.soccerBallsInputEnabledProperty

Ready for review.
