### ISSUE TITLE
SoccerBall.isQ1Object should not exist in screens 1-2

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#265]
From https://github.com/phetsims/center-and-variability/issues/204, SoccerBall.isQ1Object should not exist in screens 1-2 (if it's not too difficult).

![image](https://github.com/phetsims/center-and-variability/assets/679486/caac4652-9aa3-47a9-aefa-840447c2fb9f)

**Comment by samreid** [comment]
Fixed and would be good to review.

**Comment by matthew-blackman** [comment]
@marlitas and I reviewed this and the commits above look really good. Closing this issue.
