### ISSUE TITLE
On the variability screen, The dots need to be a little darker.

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#268]
From https://github.com/phetsims/center-and-variability/issues/161#issuecomment-1589644682

> On the variability screen, The dots need to be a little darker.

Do this after #267

**Comment by samreid** [comment]
Now that the accordion box background has been made white in #267, @catherinecarter can you please use the color editor to specify a color for `centerAndVariability.grayDataPointFill`?

**Comment by samreid** [comment]
Also, I renamed it to `variabilityDataPointFill`

**Comment by catherinecarter** [comment]
#949494 passes contrast tests, so let's use that.

**Comment by samreid** [comment]
Fixed. I presume @catherinecarter has already tested that color in the sim, so I feel this can be closed.
