### ISSUE TITLE
Change outlier marker for better visibility

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#271]
After seeing the outliers appear in #209, the marker was difficult to distinguish from the x's in the line plot. After design meeting 06.15.23, we decide to change the marker to an open diamond with a thick border:

![image](https://github.com/phetsims/center-and-variability/assets/109630002/f1925b1c-31fc-49f7-ba5e-02a90b2e4c88)

**Comment by samreid** [comment]
@matthew-blackman want to take the lead on this one?

**Comment by catherinecarter** [comment]
This looks great. The marker is much easier to see when on the line plot option. Ready to close when you are.
