### ISSUE TITLE
Update draggable cues on cards (Median screen)

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#273]
After interviews, the blue cueing arrows weren't clear as to what their purpose was. This was true both on the cards on the median screen and the balls in the play area (after the last kick appeared).

Let's change the cueing indicator to be a hand overlapping the card (for the median screen), and move the blue cueing arrows to surround a ball in the play area. For the median screen, this also inspired a change in where the median is shown when the checkbox is activated (which also alleviates touch occlusion with the user's hand):

![image](https://github.com/phetsims/center-and-variability/assets/109630002/01e317f4-86e6-47ee-a0f6-6d682fae5222)

Summarizing:
- [ ] Change blue cueing arrow to hand partially covering the card from the bottom
~- [ ] Move the median measurement and red lines that cut the data in 1/2 to the top~ moved to https://github.com/phetsims/center-and-variability/issues/296

**Comment by samreid** [comment]
I'd like to work on this one. Do we have a font awesome 5 hand shape that we use, or other artwork that should be used for that? Also, what if the user tries to drag the hand? From a development perspective, it would be easiest to make it non-pickable (transferring handling to the card and making the hand disappear when you drag it may be odd).

**Comment by catherinecarter** [comment]
Will this work? I can put it in the asset folder if it's better? I took the hand from the Common .ai components file and added the arrow (dashed):

![Asset 8](https://github.com/phetsims/center-and-variability/assets/109630002/b6a73602-ea07-4fbe-b91e-dd7755482469)

**Comment by samreid** [comment]
> I took the hand from the Common .ai components file

What is the licensing information for that hand? Who is the author?  Should we use the built in font awesome 5 one, which looks kind of like this?

![image](https://github.com/phetsims/center-and-variability/assets/679486/260459aa-9455-4e0c-8f0d-5866cc67dcda)

**Comment by samreid** [comment]
Here's a patch that uses the font awesome hand pictured above. I'll hold off work until hearing back about which artwork to use.  Adding the dashed arrow in code would be very easy.

<details>

```diff

Subject: [PATCH] Add a darker color for variabilityDataPointFill, see https://github.com/phetsims/center-and-variability/issues/268
---
Index: js/median/view/CardNodeContainer.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/median/view/CardNodeContainer.ts b/js/median/view/CardNodeContainer.ts
--- a/js/median/view/CardNodeContainer.ts	(revision 5bd64ed15edd0600ef6b2b07ce5810b19b98b36c)
+++ b/js/median/view/CardNodeContainer.ts	(date 1687026057764)
@@ -8,10 +8,9 @@
  */
 
 import centerAndVariability from '../../centerAndVariability.js';
-import { LinearGradient, Node, NodeOptions, Text } from '../../../../scenery/js/imports.js';
+import { LinearGradient, Node, NodeOptions, Path, Text } from '../../../../scenery/js/imports.js';
 import { EmptySelfOptions } from '../../../../phet-core/js/optionize.js';
 import SoccerBall from '../../soccer-common/model/SoccerBall.js';
-import ArrowNode from '../../../../scenery-phet/js/ArrowNode.js';
 import CardNode from './CardNode.js';
 import Vector2 from '../../../../dot/js/Vector2.js';
 import Range from '../../../../dot/js/Range.js';
@@ -32,7 +31,6 @@
 import PhetFont from '../../../../scenery-phet/js/PhetFont.js';
 import PickRequired from '../../../../phet-core/js/types/PickRequired.js';
 import Matrix3 from '../../../../dot/js/Matrix3.js';
-import DragIndicatorArrowNode from '../../soccer-common/view/DragIndicatorArrowNode.js';
 import TEmitter from '../../../../axon/js/TEmitter.js';
 import MedianModel from '../../median/model/MedianModel.js';
 import PatternStringProperty from '../../../../axon/js/PatternStringProperty.js';
@@ -55,6 +53,7 @@
 
 import cvSuccessOptions007Shorter_mp3 from '../../../sounds/cv-success-options-007-shorter_mp3.js'; // eslint-disable-line default-import-match-filename
 import isSettingPhetioStateProperty from '../../../../tandem/js/isSettingPhetioStateProperty.js';
+import handPointerSolidShape from '../../../../sherpa/js/fontawesome-5/handPointerSolidShape.js';
 
 const cvSuccessOptions007ShorterSoundClip = new SoundClip( cvSuccessOptions007Shorter_mp3, {
   initialOutputLevel: 0.2
@@ -98,7 +97,7 @@
     notchDirection: 'up',
     barStyle: 'split'
   } );
-  private readonly dragIndicatorArrowNode: ArrowNode;
+  private readonly handNode: Path;
 
   // Indicates whether the user has ever dragged a card. It's used to hide the drag indicator arrow after
   // the user dragged a card
@@ -314,10 +313,16 @@
 
     this.addChild( this.cardLayer );
 
-    this.dragIndicatorArrowNode = new DragIndicatorArrowNode( {
+    this.handNode = new Path( handPointerSolidShape, {
+      fill: 'white',
+      stroke: 'black',
+      lineWidth: 15,
+      maxWidth: 30,
       tandem: options.tandem.createTandem( 'dragIndicatorArrowNode' )
     } );
 
+
+
     // Add or remove the arrow node child
     const dragIndicatorContainer = new Node();
     this.addChild( dragIndicatorContainer );
@@ -329,13 +334,13 @@
 
       const hasPressedCard = this.hasDraggedCardProperty.value;
 
-      const newChildren = leftCard && rightCard && !hasPressedCard ? [ this.dragIndicatorArrowNode ] : [];
+      const newChildren = leftCard && rightCard && !hasPressedCard ? [ this.handNode ] : [];
 
       if ( newChildren.length !== dragIndicatorContainer.children.length ) {
         dragIndicatorContainer.children = newChildren;
 
         if ( leftCard && rightCard ) {
-          this.dragIndicatorArrowNode.centerBottom = leftCard.bounds.centerTop.plusXY( 0, -8 );
+          this.handNode.centerTop = leftCard.bounds.centerBottom.plusXY( 20, -8 );
         }
       }
     };

**Comment by catherinecarter** [comment]
@amanda-phet said in Slack: 
This is for anyone to use and add to! Many components are common code, so there is a corresponding node or something in code. In some cases you wouldn't want to modify it, since things like buttons and check boxes are standard.

I'd like to use the hand with the arrow from above, it's softer. The font awesome hand looks harsh - maybe it's the lines on the back of the hand?

**Comment by samreid** [comment]
I implemented it with the given artwork, it looks like this:

![image](https://github.com/phetsims/center-and-variability/assets/679486/95bb5c94-b171-4b54-9d7c-fe331d6aed42)

@catherinecarter can you please review? And check in an *.ai file in the assets folder in case we need to modify it?

**Comment by catherinecarter** [comment]
The artwork looks great, and I uploaded an .ai file into the assets folder. 

I'm wondering if we can make the hand fade in? It looks pretty abrupt when it appears on the 2nd kick. Also, if I grab the hand itself, the card doesn't move. Can we increase the touch area to include the hand and the card?

**Comment by samreid** [comment]
In the 2 commits above, I added a fade and expand the mouse/touch area to include the hand. I first tried DragListener.createForwardingListener but it became very complicated and it seems adjusting the pointer areas is a better solution.  @catherinecarter can you please review/test? If there are adjustments or problems, please reassign to me. If it's all good, please reassign to @marlitas and @matthew-blackman for code review.

**Comment by catherinecarter** [comment]
Looks really good. The fade is much less abrupt, and the increased pointer area is very clear, easy to pick up the card. Thanks @samreid. Assigning to @marlitas and @matthew-blackman.

**Comment by matthew-blackman** [comment]
Fade out is implemented and design reviewed by @catherinecarter. Also did some refactoring. Over to you for code review @samreid.

**Comment by samreid** [comment]
See also related issue #329 and https://github.com/phetsims/center-and-variability/issues/330

**Comment by samreid** [comment]
I opened a side issue for a phet-io aspect.  This issue together with #329 and #330 are ready for review.  @matthew-blackman can you please take a look?

**Comment by matthew-blackman** [comment]
Code review looks good and the refactor in https://github.com/phetsims/center-and-variability/commit/2205daa2da9bcf45c4fa97c547ab146b1cd4b645 cleans things up nicely. The updated property/method names make sense. Did some testing with card and reset/erase interactions and everything is behaving well. Closing.
