### ISSUE TITLE
Add Info dialog on the Median screen

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#277]
Add an info dialog on the Median screen. Match what's in the accordion box in the info screen, but the cards will always be sorted in the info box, regardless if the user has sorted the data in the accordion box or not. Pressing the info button will not auto-sort the cards in the accordion box (in other words, when a user presses the info box button, they will see a sorted list of their cards, and when they exit the info box, whatever state their cards were in prior to pressing the info button will remain as is.

![image](https://github.com/phetsims/center-and-variability/assets/109630002/9fb17480-150f-4068-adee-209ab6a0e069)

**Comment by amanda-phet** [comment]
Minor request: instead of "Values = " could it be "Values: " ? It's not
really something that could be equal to something, we are just listing
numbers.

**Comment by samreid** [comment]
I'll work on this one

**Comment by samreid** [comment]
I observed there was a similar display in the IQR node, and so I factored it out.  Note it used to read "Data Values:" in the IQR node, so I simplified it to "Values:".  Would be good for @matthew-blackman to review the 2x preceding commits.  And this issue still needs the card display.

**Comment by samreid** [comment]
We should add a "need at least one kick" message.

**Comment by samreid** [comment]
I feel this issue is ready for design review. It looks like this now:

![image](https://github.com/phetsims/center-and-variability/assets/679486/669659c3-3281-4df4-89df-783469823ebd)

I believe there is another issue to move the median bars above.  @catherinecarter can you please review? If all is well, please reassign to @marlitas for code review.

**Comment by catherinecarter** [comment]
I think there needs to be a little more padding between the list of data values and the cards. When the median is shown from the top, I'll revisit since it will look different visually. 

I'd also like to see the font size of the definition increase a bit to differentiate between the definition and the example below the definition. Just from looking at it, it looks like the top line font size is 18 and the example below is 16 pt (it's a guess, maybe 16 and 14?). If the size is 18, let's make the first line 20pt.

**Comment by catherinecarter** [comment]
Looking great.

**Comment by marlitas** [comment]
We did some pixel polishes together after standup and now ready to close!
