### ISSUE TITLE
Add info box on Mean & Median screen

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#278]
After interviews, it was clear an info box needed to be added to all screens. 

For the M&M screen, both the median and mean will be defined with their calculations shown so the user can more easily compare the mean and median for the same set of data.

![image](https://github.com/phetsims/center-and-variability/assets/109630002/31460a93-af07-49c8-b4bc-6f6e68fc854b)

**Comment by marlitas** [comment]
I'll handle this since I'm already in the area.

**Comment by marlitas** [comment]
I think we're going to want to discuss contrast here with @catherinecarter... marking for design.

**Comment by marlitas** [comment]
<img width="238" alt="Screenshot 2023-06-26 at 1 20 05 PM" src="https://github.com/phetsims/center-and-variability/assets/42476338/c7e829e1-a95f-4d8d-abfb-b6a1587b5710">

**Comment by catherinecarter** [comment]
Looks much better with black data points. I'm excited all the info boxes match exactly what's in each corresponding accordion box.

**Comment by marlitas** [comment]
Okay this is ready for design review! Sending over to @catherinecarter. If all is good, please assign by so I can get code review going.

**Comment by samreid** [comment]
I noticed there is an except in PhET-iO brand:

```
assert.js:28 Uncaught Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (assert.js:28:13)
    at Emitter.initializePhetioObject (PhetioObject.ts:204:7)
    at new PhetioObject (PhetioObject.ts:184:12)
    at new PhetioDataHandler (PhetioDataHandler.ts:102:5)
    at new Emitter (Emitter.ts:44:5)
    at new PushButtonModel (PushButtonModel.ts:75:25)
    at new RectangularPushButton (RectangularPushButton.ts:51:29)
    at new CloseButton (CloseButton.ts:61:5)
    at new Dialog (Dialog.ts:241:25)
    at new MedianInfoDialog (MedianInfoDialog.ts:17:5)
```

Perhaps we need to pass a tandem to the dialog.

**Comment by marlitas** [comment]
> Perhaps we need to pass a tandem to the dialog.

Fixed in the above commit.

**Comment by catherinecarter** [comment]
Info boxes look great in terms of matching the accordion box. For the M&M screen, let's add "meters" as a label for the median and mean values. 


![Image](https://github.com/phetsims/center-and-variability/assets/109630002/76d5f484-9306-4f11-8eaa-a0399d740182)

**Comment by marlitas** [comment]
Adding unit of measurement expanded to another issue, so marking this as ready for code review.
