### ISSUE TITLE
Decrease size of title bar and grass, increase size of accordion box

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#279]
The 'meat' of the statistical content is in the accordion box, so in brainstorming ways to increase the size of the accordion box, the sizes of the grass and question bar are decreased.
![image](https://github.com/phetsims/center-and-variability/assets/109630002/47b16adb-4000-4d6f-8efe-eb4110474104)

This will impact the size of the predict mean/median markers on the first two screens, and possibly the size of the interval tool handles on the Variability screen. Let me know what you need from me to help answer questions :)

**Comment by samreid** [comment]
I'll take a look

**Comment by samreid** [comment]
Want to keep the median accordion box its same size?  It just has cards so doesn't need a lot more vertical space.

**Comment by samreid** [comment]
I made adjustments to the question bar size, accordion box top margin, grass height and accordion box size in screens 2-3.  We will likely want to fine tune these values, then adjust the size of objects in the accordion boxes accordingly.  I feel this is at a good point for synchronous check-in and tuning with @catherinecarter, hopefully on Monday.

**Comment by matthew-blackman** [comment]
Reminder that we want to revisit https://github.com/phetsims/center-and-variability/issues/280 to finalize the highlight rectangle size after this issue has been closed.

**Comment by catherinecarter** [comment]
Thanks, Matt, for the reminder. Yes, we will need to revisit the rectangle heights (as well as the notched length indicator) now that the accordion box size is increased. 

The height of the accordion box looks great. Prior to changing its size, there was a lot of intentionality of making sure there was a partial ball under the accordion box or data point inside the accordion box. With the change, this property is no longer true. Not sure what a good solution is; moving the accordion box down a few pixels? Would love to discuss.

**Comment by catherinecarter** [comment]
Closing this issue as @samreid pushed a change to change the height of the accordion box to be slightly smaller so there's a partial ball showing. Closing.
