### ISSUE TITLE
What is the spatial value range on the Spread screen?

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#28]
What is the spatial value range on every screen?  I recalled that the spread screen would have a wider range and the camera would be zoomed out.  The Feb 1 meeting notes say:

> Spread screen has issue with larger ball size- can make that screen different, or make them all smaller? 
Just spread screen uses smaller ball
Also shrink kicker
Increase range, too

But Screenshots for the Spread screen updated after that show a range 1-16, so I'm not sure what we decided.  @amanda-phet can you please advise?

**Comment by samreid** [comment]
In slack, @amanda-phet replied:

> I'm not positive about the range changing. 16 seems reasonable still, and I don't want to change it just because the person and ball need to shrink. Let's revisit when we are looking at artwork.
>
> It would be great to code things flexibly so I can change the range later, but the width of the "field" can remain the same.

**Comment by samreid** [comment]
If we decide to zoom out the camera on some screens, we will likely want to change the touch area as described in this TODO:

```ts
    // expand the horizontal touch areas but don't overlap with the neighboring columns.
    // TODO: do we want to expand the vertical touch areas for the top and bottom ball in a stack?  It may depend on
    // whether the Spread screen reduces the size of the balls, see https://github.com/phetsims/center-and-spread/issues/28
    this.touchArea = this.localBounds.dilatedX( 10 );
```

**Comment by samreid** [comment]
@amanda-phet what is necessary for this issue for this week's sprint?

**Comment by amanda-phet** [comment]
I'm actually not sure why this was added to the prototype milestone. Since this is about the Spread screen, I think we can get to this after the sprint.

**Comment by samreid** [comment]
I believe today @catherinecarter may have said the range will be 1-15. @catherinecarter is that correct?

**Comment by amanda-phet** [comment]
It should be 1-15 to match the previous screens.

**Comment by catherinecarter** [comment]
Yes, the range being 1-15 is correct. Ok to close this?

**Comment by samreid** [comment]
Yes, screen 1-2 are already 1-15 and we will keep that for screen 3, closing.
