### ISSUE TITLE
Preferences are resetting with reset all

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#282]
I noticed when I pressed 'reset all,' the preferences set by the user reset as well. 

In Calculus Grapher, the preferences set by the user remained in their chosen state when the reset all button was pressed, which I believe is the desired behavior.

This will need to be updated to save the state of the user-chosen preferences, even upon reset all.

**Comment by marlitas** [comment]
This looks like it was just vestigial from when `maxKicks` was not in preferences. I removed the `maxKicksProperty.reset()` call. Is now working as expected. Closing.
