### ISSUE TITLE
Add a phet-io API call to get the order of the cards in the median screen

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#283]
From https://github.com/phetsims/center-and-variability/issues/204

On the median screen:

> Get card values in the order they appear (i.e. kick order) as an array

* client could get the order of the cards (which is in the order the balls were kicked rather than ordered on the number line)
* We will add an API call that the user can query on-demand.

**Comment by samreid** [comment]
@marlitas and I wondered if there should be a card container model.  If we implement/refactor that, it would impact this issue.

**Comment by samreid** [comment]
After the commit, you can get the values of the cards like so: `await phetioClient.invokeAsync('centerAndVariability.medianScreen.view.accordionBox.cardNodeContainer','getData',[]);`. We will have to decide whether we want to move this to the model. And also tagging for #136

**Comment by marlitas** [comment]
@matthew-blackman and I reviewed the changes. We just made some small documentation adjustments, everything else looks good. Tested in studio!

**Comment by catherinecarter** [comment]
Updating the command to: 
`await phetioClient.invokeAsync('centerAndVariability.medianScreen.model.cardContainerModel','getData',[]);`

**Comment by samreid** [comment]
New command: `await phetioClient.invokeAsync('centerAndVariability.medianScreen.model.distanceAccordionBox.cardContainerModel','getData')`
