### ISSUE TITLE
Have a flag for cards sorted vs not sorted that could be “listened” to

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#284]
From https://github.com/phetsims/center-and-variability/issues/204, 

> Have a flag for cards sorted vs not sorted that could be “listened” to

While investigating this, @marlitas and I observed that there is no model for the order of the cards--it is all handled in the CardContainerNode.  So we should investigate better model/view separation for that.

Ideally we would have an `areCardsSortedProperty` boolean Property in MedianModel or perhaps a new thing called MedianModel.cardContainerModel.areCardsSortedProperty.

**Comment by samreid** [comment]
Implemented and would be good to review/test/discuss.

**Comment by marlitas** [comment]
We may want to move the `this.areCardsSortedProperty` into the CardNodeContainerModel once that is ready. https://github.com/phetsims/center-and-variability/issues/314

We reviewed the commit synchronously, and the implementation looks good. We want to double check that `this.cardNodeCellsChangedEmitter` is being called appropriately and will confirm that after the https://github.com/phetsims/center-and-variability/issues/314 refactor. 

This is ready to close.

**Comment by marlitas** [comment]
We found a bug while testing. The `this.cardNodeCellsChangedEmitter` is not being called when you drag a soccer ball in the play area. This allows `this.areCardsSortedProperty` to read as true when the cards are in fact not sorted. 

<img width="357" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/1602f741-65ac-4d9a-98ef-c038cb4fef08">

We think this fix may be as easy as adding a listener to each soccer ball's valueProperty. We can do this by hooking through the cardModel to the soccerBall model.

**Comment by marlitas** [comment]
@matthew-blackman and I committed the above fix. We tested in studio in a variety of scenarios and areCardsSortedProperty is working well! Closing.
