### ISSUE TITLE
Hide points on plot Node

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#288]
Form the CaV PhET-iO Design Doc:

> Hide the points on the dotplot to show only the graph (whatever graph is up) to declutter the screen (Variability Screen only)

We would like to instrument the visibility of all the points in the dot plot as a single entity.

**Comment by samreid** [comment]
Adding this in the mean and median screen was easy, however the variability screen was missing an important tandemName which cut 1500 instrumented instances out of the studio tree.  When I restored the tandemName, it takes about 19 seconds longer to start studio: 

![Image](https://github.com/phetsims/center-and-variability/assets/679486/bfb98d5a-fa4f-4e22-aea9-b5631bee99a4)

**Comment by samreid** [comment]
Studio now initializes with `'featured'` which causes a lot of time in filtering the tree.  Even when you have ?phetioElementsDisplay=all.  Heads up to @zepumph

**Comment by samreid** [comment]
I added the basic instrumentation, but I left one line commented out, because with the studio problem as it is, it triggers the sim to take around 18-19 more seconds to launch.  Will need help.

**Comment by marlitas** [comment]
This looks to be working and we no longer have the studio loading issue... however navigating to these data point layers in the tree is a mess... opening up a separate issue for that.
https://github.com/phetsims/center-and-variability/issues/353

Closing this issue as completed! Thanks all!
