### ISSUE TITLE
Provide distribution options for clients to set

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#290]
From the CaV PhET-iO Design Doc:

> Change the size of the variability for the distribution

> PhET-brand sim
Kicker 1: small spread, unimodal and symmetric
Kicker 2: larger spread, unimodal and symmetric
Kicker 3: skewed left
Kicker 4: skewed right
Possible other options: bimodal, uniform, ‘top hat’
KP: options for distribution= skewed right, skewed left, etc.? 

First step here seems to be identifying the options we want to provide a client. So far the options seems to be:
- unimodal
- bimodal
- uniform
- skewed right
- skewed left
- top hat

**Comment by catherinecarter** [comment]
I have a probability distribution in the [google spreadsheet](https://docs.google.com/spreadsheets/d/1GM8a0JVuV46Mm_ieF8jUKhatj2qU9nIegG9t_LE8ZyY/edit#gid=1733061379) for the Uniform, Bimodal, and Top Hat distributions if we want to give this a start. 

I don't think any other distributions would be included here. These are the main distributions, even through high school. The only other two I can think of would be to stack all the balls in one-three spots. Not sure that would be useful.

**Comment by samreid** [comment]
We agreed instead of developing code to provide nicknames for each distribution type, we would like to list them in the examples guide in a way that clients can copy/paste or adjust the different types.  Tagging for #136
