### ISSUE TITLE
Consistent Icon Sizes

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#292]
From https://github.com/phetsims/center-and-variability/issues/272. When I removed the handles of the Interval Tool icon and had it match the size of the Range, IQR, and MAD checkbox icons it looked significantly bigger than the median icon and the mean icon. 
<img width="247" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/4e4a05f4-aa06-4111-9b8b-1e2d564c11ac">

I then made the sizing consistent across all checkbox icons, and the mean icon seems too big now. I think there's a middle ground and this issue will track that back and forth.

<img width="253" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/08b62255-501b-443f-b1d1-97b31cb15492">

**Comment by catherinecarter** [comment]
Changed the size of the interval tool icon so the other icons could be slightly increased in size without feeling overly huge. The icons for the predict mean/median will need to be adjusted for two reasons:
1. they need to increased slightly to match the change in size of the icons
2. the actual predict mean/median arrows in the green area need to be shorter now that we've decreased the size of the grass, and the icons will be updated to match the change (slightly)

**Comment by catherinecarter** [comment]
@marlitas, the icons look large in the current test version. Did you apply the patch so we can take a look?

**Comment by marlitas** [comment]
The patch was applied as well as some other minor adjustments. @catherinecarter can you take a look at the icons on all screens on your end? Feel free to close if all looks well!

**Comment by catherinecarter** [comment]
The icons for the mean/median still look unusually large while the predict mean/median icons look very small. Let's discuss in standup.

**Comment by marlitas** [comment]
@catherinecarter checked in real time, and all is looking good. Closing!
