### ISSUE TITLE
Checkbox icons can go out of bounds when text changes

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#293]
![image](https://github.com/phetsims/center-and-variability/assets/679486/95d2874a-0a1c-40f8-a74d-8008a99d8433)

Checkbox icons can go out of bounds when text changes, see in the accordion box. This test was generated in studio.

**Comment by samreid** [comment]
@marlitas can you please help investigate this?

**Comment by marlitas** [comment]
Fixed. Is a rather straightforward usage of AlignBox, so I don't think a review is necessary, but please re-open if you feel otherwise.

**Comment by marlitas** [comment]
JK, was definitely look at the wrong screen when I fixed this. Checking Mean and Median now.

**Comment by marlitas** [comment]
Same fix for Mean and Median, and is working well on the variability screen. closing.
