### ISSUE TITLE
MedianBarNode is being misused

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#295]
Discovered in https://github.com/phetsims/center-and-variability/issues/244, MedianBarNode was incorrectly used when I developed the RangeNode to show the value over the top of the range. That kind of usage has proliferated. Instead, we should factor out a new type for rendering the "top half" of a rectangle that indicates a range.  Like this but without the arrow:

![image](https://github.com/phetsims/center-and-variability/assets/679486/08b96077-ef39-4915-9816-2105b72483df)

Then MedianBarNode can use it, and IQRNode/RangeNode can use it too.

**Comment by samreid** [comment]
This seems like an important refactor, but somewhat risky because there are many usage sites that could be disrupted.

**Comment by samreid** [comment]
I think this is fixed in the commits.  I created IntervalBarNode and use it in range, mad and IQR. I tested in the accordion box and info dialogs and it seems OK but I'm not sure of all the corner cases.  @matthew-blackman can you please help test/review?

**Comment by matthew-blackman** [comment]
I noticed that the range label was a little bit further from the bar node than the IQR and MAD labels. The above commit uses the same method to position the range bar label as the other two. Everything else looks great here - nice work @samreid! Closing.
