### ISSUE TITLE
Decrease size of predict mean/median sliders in grass

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#297]
The predict mean/median sliders need to be decreased in length now that the height of the grass has been decreased.

Currently in dev:

<img width="221" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/60064af4-8000-4e73-a9ed-37e2a2173faf">

Mock up with smaller slider:

![image](https://github.com/phetsims/center-and-variability/assets/109630002/f636a5e6-11a4-43ed-8a5f-a766af410737)

The distance between the arrow and the number should match the distance between the drag handle and the bottom of the grass.

**Comment by samreid** [comment]
After the changes:

![image](https://github.com/phetsims/center-and-variability/assets/679486/30e8dec9-c4cc-43d2-96a3-d28f90017c4b)

Note that the icons in the checkboxes were also adjusted, but to me and @matthew-blackman that also looks better.

**Comment by samreid** [comment]
@catherinecarter does that look good to you?  If so, please close.

**Comment by catherinecarter** [comment]
Looks great.
