### ISSUE TITLE
Card sounds should not play when soccer balls land.

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#298]
From https://github.com/phetsims/center-and-variability/issues/245 we agreed that card sounds should not play when soccer balls land.  But if the user drags a card or clicks sort data while a ball happens to land, that can still have a sound.

**Comment by samreid** [comment]
Fixed.  @marlitas or @matthew-blackman can you please review?

**Comment by marlitas** [comment]
Straightforward. Looks good! Closing.
