### ISSUE TITLE
Mean prediction should play a sound each time it moves on a keypress with the shift modifier

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#302]
Mean prediction should play a sound each time it moves on a keypress with the shift modifier.  Currently it only plays when passing a half integer.

**Comment by samreid** [comment]
To implement this, it seems we need to tap into AccessibleSlider.startDrag/endDrag like we did in SoccelBallNode.  However, it is getting complicated because there is already another `isBeingDragged` property that just refers to the mouse.  So I'm not sure at all of the right way to do this.  That being said, I committed a working version that is kind of messy.  Could use assistance and collaboration.

**Comment by marlitas** [comment]
@samreid and I reviewed together. This issue can now be closed.
