### ISSUE TITLE
Interval tool width indicator sound

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#310]
This is a child of #236 to hone in on the sound the interval will make when one of the handles is dragged. 

There are two options: 
- A continuous sound as the tool's width is changed (one of the handles is dragged), with the width sound changing (higher for smaller interval and lower for wider intervals) continuously
   - example: https://bayes.colorado.edu/dev/phettest/center-and-variability/center-and-variability_en.html?ea&brand=phet
   
- A continuous sound when the width changes, but with a pulse to indicate the handle is passing a width marker
  - example: https://bayes.colorado.edu/dev/phettest/center-and-variability/center-and-variability_en.html?ea&brand=phet&intervalToolSoundInterval=0.05  

A note: I listened to both options and prefer the pulse as it more nicely makes the connection between the sound and the change in width. @marlitas, @samreid, and @matthew-blackman also listened to both options as well. They all also liked the 2nd option better.

**Comment by samreid** [comment]
In response to:

> To test the thresholded approach, please launch with ?intervalToolSoundInterval=0.05 and keep in mind it only applies when the width changes. I'm not sure if we will like it or not (or even if I like it or not). @catherinecarter and @emily-phet and @Ashton-Morris can you please test? If we like it, we could apply a similar "pulsing" approach to when translating the interval tool. Here's a link for testing: https://bayes.colorado.edu/dev/phettest/center-and-variability/center-and-variability_en.html?ea&brand=phet&intervalToolSoundInterval=0.05

@Ashton-Morris said:

> I think this sounds good.

**Comment by samreid** [comment]
In discussion, @marlitas @catherinecarter @matthew-blackman and I agreed the interval tool should have a fundamentally different sound strategy than the mean prediction tool (even though both are continuous), because the interval tool portrays a width rather than a position on the number line.  We also agreed the new sounds from @Ashton-Morris are much better, so I committed our 2 favorite sounds, and switched to the fully-continuous implementation (non pulsing).

**Comment by samreid** [comment]
We listened to the sound in today's sound design meeting. @Ashton-Morris indicated that on some speakers the lower frequencies may be a bit quieter. We could check in with @jbphet about this later on. But @Ashton-Morris thinks it sounds good and we are in a good range.  As a team, we prefer cvIntervalToolLoopSoundV1_wav slightly over cvWaveMeterSawTone_mp3 (the latter sounds too electronic and like an organ).

**Comment by samreid** [comment]
At today's sound meeting, we agreed this sounds good, and can be closed.
