### ISSUE TITLE
MAD info box: widen equation width

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#311]
In reviewing #266, I noticed the equation seems to be squished when it appears there's room to the right.

<img width="1000" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/0cce0364-f5bf-4fc1-9e19-63e264c3e6d0">

Can we increase the width of the equation so the numerator doesn't feel squished too soon?

**Comment by samreid** [comment]
Good idea, after the commit it looks like this:

![image](https://github.com/phetsims/center-and-variability/assets/679486/a1afb895-c229-4e27-8ad3-1af53164ac91)

@catherinecarter please review and close if all is well.

**Comment by samreid** [comment]
On second thought, it looks like lots of things are still getting compressed.  Let me try a few different values for that maxWidth.

**Comment by samreid** [comment]
OK here's with maxWidth:700, and looks much better:

![image](https://github.com/phetsims/center-and-variability/assets/679486/41c3fa06-8084-4e98-acf1-543a25750861)

**Comment by samreid** [comment]
@catherinecarter reviewed this and agreed it is good to close.
