### ISSUE TITLE
MAD Info box: data points are occluding the length marker

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#312]
In reviewing #266, I noticed the lengths above the horizontal lines are behind the data points. 

<img width="215" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/954afba2-4f57-47ce-921e-84bb6314aea4">

The lengths should be in front for easier reading.

**Comment by matthew-blackman** [comment]
@catherinecarter it looks like the text is rendering in front of the data points (screenshot below), but it is definitely hard to read because there is so much going on behind it.

<img width="98" alt="Screen Shot 2023-06-22 at 2 53 11 PM" src="https://github.com/phetsims/center-and-variability/assets/108756567/6714d6fa-10aa-48c9-a38a-e0f7be3fe2a3">

Could this be solved by putting a background on the text with some transparency?

**Comment by catherinecarter** [comment]
Hm, I guess you're right. Not sure how to fix it.

**Comment by matthew-blackman** [comment]
One option would be to "snap" the text labels to the nearest half-integer value in the x-direction, so that they always appear between the data points. Not sure how this would look in edge cases, but it would solve the issue of text label readability. Thoughts?

**Comment by catherinecarter** [comment]
Sounds like a reasonable option, but I'd have to see it to know whether or not the non-centered distance would look strange. Would another option be to bold the text? That might look strange, too. Not sure.

**Comment by matthew-blackman** [comment]
Here is a screenshot with bold text. Looks like an improvement but might still be hard to read.
<img width="844" alt="Screen Shot 2023-06-22 at 3 27 22 PM" src="https://github.com/phetsims/center-and-variability/assets/108756567/f2a9b301-d0fc-435c-921d-650fe30e636b">

**Comment by catherinecarter** [comment]
Yeah, I don't love it. It's still difficult to read. Let's try shifting the length away from the on-tick-mark when the data point will overlap. I don't think we need to do this for all the distances. The ones on the left, for example (the 2.1 distance at the top) would be occluded by the 7, but they aren't because they're so high. Is there a way to detect occlusion?

For the 0.1 lengths, the bottom three are hard to read, but we wouldn't want to shift them any farther to the left. The only time this is going to happen is when the right-hand data points occlude closer to the axis. Like in this example: 
<img width="414" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/c8d7262d-9cd1-47b8-b893-4f3ee10b5918">

The lengths on the right that are 2.1 would be in trouble, but they aren't. The only one that's a challenge to read is the 4.1. How do you recommend this is handled?

**Comment by matthew-blackman** [comment]
The devs discussed this with @catherinecarter and we agree that we want to maintain the location of the labels, since they show the progression of the values visually. We tried setting the text labels to bold, and found that they are more readable. We also noted that these values are also listed in the equation at the top of the info display. Over to you for design review @catherinecarter - feel free to close if all looks good.

**Comment by catherinecarter** [comment]
Looks good, closing.

**Comment by catherinecarter** [comment]
Reopening due to a new idea. The bold is a nice addition, but it's still bothering me that the numbers and the ball marker are occluding each other. What if we try this: put the distance all the way to the far end of the horizontal marker, minus 0.5. So the visual cue that the distances are increasing is still there (meaning the distances aren't all stacked in the same location even when their values are different), the distance is closer to the data point its referencing, and the length won't sit on an integer. Here's a mockup: 


![Image](https://github.com/phetsims/center-and-variability/assets/109630002/c4968881-e14f-4c77-b46b-e155bab8ef5d)

**Comment by marlitas** [comment]
Sounds like a great solution. I think @matthew-blackman has been working mostly in this area so assigning to him. Feel free to reach out if you need help or feedback!

**Comment by samreid** [comment]
Today we realized that sometimes 0.0 can appear left of the axis and sometimes to the right.  We would like to stringify/parse the numbers before deciding how to position it.  Here is a pic of all to the right:

![image](https://github.com/phetsims/center-and-variability/assets/679486/cea1fc2d-7da5-41c4-8124-633d8ea5e4af)

Everything else is great, nice work @matthew-blackman

**Comment by matthew-blackman** [comment]
@catherinecarter I have tested this and it looks like the labels of zero will always appear to the right side of the mean line. Can you double check and close this issue if all looks good?

**Comment by catherinecarter** [comment]
Looks great!
