### ISSUE TITLE
MAD info box: Add mean label in info box

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#313]
Every time I press the info button, I look for the actual value of the mean. While there's a marker on the number line to indicate location, I think the actual value would enhance the usability and understandability of the MAD in the info box. 

I'm on the fence of where to put it
- above the rectangle
- between the title and MAD calculation

Would love feedback on which is easier to notice and use. Thanks!

Images of options:
![image](https://github.com/phetsims/center-and-variability/assets/109630002/8527cc21-d65e-49ce-99eb-cd820d89598d)
![image](https://github.com/phetsims/center-and-variability/assets/109630002/00aa6aea-ec67-401b-a63f-ccaee69f6b2e)

**Comment by samreid** [comment]
I would like to vote for the latter option. Having that readout left aligned with the other equations seems most discoverable/readable to me.

**Comment by catherinecarter** [comment]
In design meeting, @matthew-blackman, @marlitas, @samreid, and I decided to try the mean above the label marker centered on the mean line (first option above).

<img width="519" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/0c0109c9-a6ac-4a68-b303-2083cd7e2bce">

There should be a little padding between the MAD label and the mean label to avoid cluttering the space.

**Comment by catherinecarter** [comment]
Looks great. The distance from the top of the numerical MAD value to the mean location looks good, as does the distance from the mean to the left text. The location is nice compared to the vertical mean line, and the value was correct for all the times I checked it. Nice @matthew-blackman.

**Comment by matthew-blackman** [comment]
@samreid this is ready for a code review. If you can take a look at how we implemented rounding and pattern string for the mean value here, I think those are the main areas for review.

**Comment by catherinecarter** [comment]
Before y'all code review, I just had a meeting with AP, and he suggested a better connection to the mean value and the mean position. Something like this: 
![image](https://github.com/phetsims/center-and-variability/assets/109630002/8d7b2222-4220-4bea-a4b0-9ff4a4ffa395)

The idea is to not have the purple line extend all the way to the mean value; I mocked this up and it made it very challenging to tell that the two 1.8 values were broken into two pieces. Instead, have the center tick mark be purple, like the mean, and extend closer to the mean value. Let's try it.

**Comment by matthew-blackman** [comment]
All set and ready for review @catherinecarter :)

**Comment by catherinecarter** [comment]
Looks good. @matthew-blackman and I discussed the special case when there is only one data point. In this case, the line will connect so the Mean line is continuous rather than broken as in all other cases. So in this situation (in image below), the mean line would be a single vertical line, but even when two balls are stacked, the line will be broken because there's a MAD value of zero to show on either side of the line (left image will have a single vertical line, right image will remain as is: 
<img width="136" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/c6eee4b2-738e-43e1-a08b-1e7482bd6aa4">  <img width="141" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/b3c4f770-2d12-40b6-b479-e3c7ce59d6cf">

**Comment by catherinecarter** [comment]
Looks great! Ready on my end for closing.
