### ISSUE TITLE
Manual card sort celebration occludes Median

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#317]
When the median checkbox is active on the Median screen and a user manually sorts the data, the celebration banner, "You sorted the data!" occludes the median. One solution could be to move the celebration below the cards. Here's a video:

https://github.com/phetsims/center-and-variability/assets/109630002/6ae2a83d-5e98-4d6f-9d88-5002b5006ebe

**Comment by marlitas** [comment]
I moved the celebration to the bottom. 

<img width="245" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/1b849c95-d26f-476a-a85d-7d7575eaf796">

@catherinecarter if that change looks good go ahead and un-assign yourself!


I also added a TODO... @samreid or @matthew-blackman do you have ideas on how to address?

```js
else {
                dataSortedNode.centerX = getCardPositionX( ( this.cardNodeCells.length - 1 ) / 2 );

                // TODO: I have no clue how to test this scenario to see where this actually ends up, https://github.com/phetsims/center-and-variability/issues/317
                dataSortedNode.top = 14;
              }
```

**Comment by samreid** [comment]
@catherinecarter reviewed it and confirmed the design is good, nice work!

**Comment by samreid** [comment]
I used this patch to see the location of the data sorted node:

<details>

```diff

Subject: [PATCH] When checking the "sort data" checkbox and the data is already sorted, play a card sound effect and animate the cards, see https://github.com/phetsims/center-and-variability/issues/333
---
Index: js/median/view/CardNodeContainer.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/median/view/CardNodeContainer.ts b/js/median/view/CardNodeContainer.ts
--- a/js/median/view/CardNodeContainer.ts	(revision b77a475e3614f4c31ac13aaa143470ee6b5eb3bd)
+++ b/js/median/view/CardNodeContainer.ts	(date 1687912619963)
@@ -181,6 +181,7 @@
 
                 // TODO: I have no clue how to test this scenario to see where this actually ends up, https://github.com/phetsims/center-and-variability/issues/317
                 dataSortedNode.top = 14;
+                console.log( 'hello' );
               }
 
               if ( dataSortedNode.left < 0 ) {
@@ -200,12 +201,12 @@
                 delay: 2,
                 targets: [ {
                   property: dataSortedNode.opacityProperty,
-                  to: 0,
+                  to: 0.5,
                   easing: Easing.QUADRATIC_IN_OUT
                 } ]
               } );
               this.dataSortedNodeAnimation.finishEmitter.addListener( () => {
-                dataSortedNode.visible = false;
+                // dataSortedNode.visible = false;
                 this.dataSortedNodeAnimation = null;
               } );
               this.dataSortedNodeAnimation.start();
@@ -468,7 +469,7 @@
 
     model.selectedSceneModelProperty.value.resetEmitter.addListener( () => {
       totalDragDistanceProperty.reset();
-      dataSortedNode.visible = false;
+      // dataSortedNode.visible = false;
       if ( this.dataSortedNodeAnimation ) {
         this.dataSortedNodeAnimation.stop();
         this.dataSortedNodeAnimation = null;
@@ -561,6 +562,7 @@
         }
       } );
 
+
       const scaleUpAnimation = new Animation( {
         duration: adjustCentering ? 0.2 : 0.15,
         targets: [ {

```

</details>

And I saw that it never got to the that code.  And the message remained in its usual place:  
![image](https://github.com/phetsims/center-and-variability/assets/679486/15e1071c-78c2-41af-bc1c-52fa525369fe)

So I think we should turn it into an assertion.  I'll commit that shortly.

**Comment by samreid** [comment]
I added the assertion, and tested and fuzzed and didn't see any problems.  @marlitas what do you think?

**Comment by marlitas** [comment]
I hit the assertion in a fuzz... I don't feel confident about it. I don't know how to reproduce locally, but fuzz will definitely hit the scenario. 

<img width="440" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/e6c68429-bfa3-4528-9f38-7b6dc43331fa">

**Comment by marlitas** [comment]
This is no longer occluding the median, so closing this issue. The remaining CT error work coming from the commits in this issue is now being tracked here: https://github.com/phetsims/center-and-variability/issues/358
