### ISSUE TITLE
Add animation to card pick up/drop

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#320]
On the Median screen, add a small drop shadow to make the card look like it's coming towards you when picked up. 

If the card is moved up and to the left, the shadow appears at the bottom and right. This will require a slight adjustment to the red median lines as they will need to be moved up to not interfere with the card animation.

<img width="336" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/9bf40c2d-602f-445f-b355-9efb93af8460">

**Comment by samreid** [comment]
In testing, it seemed popping the card forward was a better user experience, and it makes sense to play the card pick up and drop sounds.

Like this:

<details>

```diff

Subject: [PATCH] Fix alignment of readouts in the variability accordion box
---
Index: js/median/view/CardNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/median/view/CardNode.ts b/js/median/view/CardNode.ts
--- a/js/median/view/CardNode.ts	(revision 9022f039d5acc94a288b0c9a493276ee13c2e5c4)
+++ b/js/median/view/CardNode.ts	(date 1687812450172)
@@ -104,6 +104,7 @@
       const delta = this.translation.minus( before );
       if ( dragging ) {
         this.dragDistanceEmitter.emit( Math.abs( delta.x ) );
+        this.translate( -4, -4 );
       }
     } );
 
@@ -113,11 +114,13 @@
       start: () => {
         dragging = true;
         this.moveToFront();
-        cardPickUpSoundClip.play();
+        this.translate( -4, -4 );
+          cardPickUpSoundClip.play();
       },
       end: () => {
         dragging = false;
-        cardDropSoundClip.play();
+        this.translate( 4, 4 );
+        // cardDropSoundClip.play();
       }
     } );
     this.addInputListener( this.dragListener );

```

</details>

**Comment by samreid** [comment]
In review today, we agreed we like the card popping up to the left, but we do not want a drop shadow.

**Comment by samreid** [comment]
This does not play a sound, but ties in with the card pick up/drop feature, so I labeled it for sonification.

**Comment by samreid** [comment]
Implemented and I adjusted the median bar up slightly so there is a clear separate between it and the dragged card.  @catherinecarter can you please review for functionality and behavior?  Please reassign to me if there are recommendations for improvement, or if you notice bugs.  Please reassign to @marlitas and @matthew-blackman for code review if everything seems OK.

**Comment by catherinecarter** [comment]
I couldn't find anything weird or buggy with the cards being picked up and dragged places. I moved them quickly and slowly, and all seemed well. It looks so natural, I can't remember what it was like without it.

**Comment by matthew-blackman** [comment]
The code and behavior look really good here. I updated a line of documentation and refactored a constant to simplify the y-margin logic. Nice work @samreid! Closing.
