### ISSUE TITLE
Median readout bumps up and down if you move a card all the way to the left

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#321]
![image](https://github.com/phetsims/center-and-variability/assets/679486/22435f37-08b9-439b-802e-ebb7242a4692)

**Comment by matthew-blackman** [comment]
I was not able to reproduce this in my working copy, and @samreid confirmed that the described behavior only appears when [this patch](https://github.com/phetsims/center-and-variability/issues/320#issuecomment-1608233239) is applied from https://github.com/phetsims/center-and-variability/issues/320. We should wait until #320 is closed before checking for this behavior.
