### ISSUE TITLE
Median arrow appears in info display when there are zero kicks

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#323]
On the Mean & Median screen, when there are zero kicks, the median arrow appears.

<img width="815" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/dbf85d4e-a4dc-47eb-9c85-d7d1bc7e3b8c">

**Comment by marlitas** [comment]
This is fixed from commits in: https://github.com/phetsims/center-and-variability/issues/278
