### ISSUE TITLE
Median arrow in info dialog off true median

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#324]
When I kicked two balls, the median in the info box was correct. Then I moved one or both of the balls in the play area and returned to the info dialog box. At this point, the median was off by 1/2. After kicking another ball and going to the info dialog, the median was correct. Moved one or more balls, and the median arrow was off by 1. 

After moving one of two balls: 
<img width="817" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/aae01dcb-3008-4f58-ad26-c71db232ba00">

After moving one of the three balls:
<img width="819" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/0f28df53-0443-4a23-8d1b-7cbee68cc6c4">

**Comment by marlitas** [comment]
This was a rather straightforward fix. I was only listening to the objectChangedEmitter, and not the medianValueProperty as well. This was causing some listener order inaccuracies. 

Fixed and closing.
