### ISSUE TITLE
In info box, when the value is 1, make the label singular (Range, IQR scene only)

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#325]
In the info dialog box for the range and the IQR, when the value of these measures of spread are 1, the "meters" label should be singular. For the MAD info box, 1.0 should stay plural.

<img width="255" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/9e6fbc70-5405-4047-a0a7-30d5fecbd7b3">

**Comment by samreid** [comment]
@matthew-blackman volunteered to investigate this, thanks!

**Comment by samreid** [comment]
@matthew-blackman recommended a better way, and it seems to be working well. He will apply that solution in a few other places as well. Consider whether something could be factored out?

**Comment by matthew-blackman** [comment]
Singular and plural tenses for the units have been implemented on the IQR and Range info panels, as well as the median readout in the MeanAndMedian info panel. Feel free to close if all looks good @catherinecarter.

**Comment by catherinecarter** [comment]
I looked at the Mean&Median screen info dialog, and the Median looks good but the Mean says, "1 meters." 
<img width="254" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/d27debeb-b8ba-47e4-90ce-52ecef370d8d">

The rest of the screens and info boxes look great!

**Comment by catherinecarter** [comment]
In Slack, @matthew-blackman wrote:

> I have a quick question about https://github.com/phetsims/center-and-variability/issues/325. In the other places in the sim where the mean is shown, it is always with one decimal point (even if an integer). Double-checking whether the mean readout in the Mean & Median info box should be different than the others and not show a decimal point if the mean is an integer.

I think for consistency, and to reinforce the idea that the mean is, in this case, a real number, the mean should be consistent and have a tenth decimal place consistently. So the above image where the mean still says, "1 meters" would be taken care of with "1.0 meters," which is consistent across the sim.

**Comment by matthew-blackman** [comment]
From Slack:
> Matthew Blackman
From your reply it sounds like we can close this issue with the 'meter'/'meters' and I can open a new one about the mean decimal point. What do you think? 

> Catherine Carter
I think so. I checked all the median instances of 1, and they all looked good. With the mean being 1.0, the plural makes sense, and then no special logic needs to be implemented.

Closing
