### ISSUE TITLE
On the variability screen, show the player after all kicks have been kicked

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#328]
Like this

![image](https://github.com/phetsims/center-and-variability/assets/679486/a78db729-2a27-4614-8385-2e218b94c348)

No soccer ball and no buttons though.  Great idea @matthew-blackman

**Comment by matthew-blackman** [comment]
This is ready for design review @catherinecarter 😃

Can you double check the following?
- All screens show the correct players for all values of maxKicks
- All screens show the correct behavior when players are done kicking

**Comment by catherinecarter** [comment]
Checked all screens and all Max Kicks. Looks good!

**Comment by matthew-blackman** [comment]
Implemented and documented. Closing.
