### ISSUE TITLE
Hide the hand when its card disappears

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#329]
![image](https://github.com/phetsims/center-and-variability/assets/679486/6a67ad70-ad3a-4b33-bce1-347e3db01c13)

**Comment by samreid** [comment]
@matthew-blackman can you please take a look?

**Comment by matthew-blackman** [comment]
@samreid is this behavior produced when setting the visible property of the leftmost card to false via PhET-iO?

**Comment by samreid** [comment]
I'll work on this as part of https://github.com/phetsims/center-and-variability/issues/273

**Comment by samreid** [comment]
Fixed and should be reviewed with #273 and #330, @matthew-blackman can you please take a look and test?

**Comment by matthew-blackman** [comment]
Code review completed as part of https://github.com/phetsims/center-and-variability/issues/273. Commit https://github.com/phetsims/center-and-variability/commit/01c96452aed021af0447d6adf6c769cbff92fdae looks good and straightforward. Closing.
