### ISSUE TITLE
Should the hand move when the cards are sorted?

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#330]
![image](https://github.com/phetsims/center-and-variability/assets/679486/9a002586-50c6-4765-9177-9bce3a256421)

**Comment by catherinecarter** [comment]
I don't think the hand should move with the original first card when the sort button is pressed prior to one of the cards being moved. The card the hand is pointing to is arbitrary, in terms of the numerical value of the card. If the hand moved with the card, this may give a false impression that this single card is more important than another card. 

I noticed, however, that with the hand pinned on the left coupled with the fade out of the hand, it's strange that the hand fades out when the card is moved. Here's a video (about the 6-7 second mark is where it looks strange): 

https://github.com/phetsims/center-and-variability/assets/109630002/5ff91f4f-4f48-4532-a849-6b3231bf93a1

Some solution ideas: 
* Move the hand along with the card, but only if the first card moved is the far left one
* Remove the fade out

I don't know what either would look like, and I'd also love some more ideas.

**Comment by matthew-blackman** [comment]
Ready for a design review @catherinecarter

**Comment by catherinecarter** [comment]
I think the hand fading without moving with the card is fine. The hand is buggy, though (see images). Not sure exactly when the hand acts unexpectedly, but it happens mostly when the sort data checkbox has been checked but sometimes it happens at random times. Here are some screenshots:

<img width="298" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/1bd94113-6205-425c-a591-76e77e4ea6cd">
<img width="397" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/a0fbc44a-a223-40b7-8d4a-43ad3bc487b4">

**Comment by samreid** [comment]
Fixed, @matthew-blackman can you please review this with #273 and #329? @catherinecarter can you please test the behavior?

**Comment by matthew-blackman** [comment]
Code review completed in https://github.com/phetsims/center-and-variability/issues/273. Closing.
