### ISSUE TITLE
Should say: "Need at least one Kick" whenever a "?" appears

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#331]
In the accordionBox we should see the string "Need at least one kick", if the value of a calculation is "?".

<img width="1399" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/6b6d7e4a-2e45-4419-b622-4cbb44ebb435">

**Comment by matthew-blackman** [comment]
Very straightforward fix, tested and all looks good. Closing.
