### ISSUE TITLE
Median bars on Median screen in accordion box are misaligned

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#338]
@matthew-blackman noticed the median bars in the accordion box are misaligned. Looks like they're shifted to the right a bit too far, as indicated by the spacing from the leftmost notch to the leftmost card being smaller than the spacing between the rightmost card and the rightmost notch.

<img width="1478" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/d0d24e54-aa38-44f2-a39d-2268c3fd9a99">

**Comment by samreid** [comment]
I added a drag container area for the pick-up effect, I wonder if it disrupted this at all?  But I would have expected that to disrupt it in the opposite direction.

**Comment by matthew-blackman** [comment]
Ready for design review @catherinecarter

**Comment by catherinecarter** [comment]
Reviewed. Kicked one ball at a time with the Sort checkbox checked and the Median checkbox checked. For all kicks in succession, the median bars were aligned to center and equally spaced around the end cards. Nice!

**Comment by matthew-blackman** [comment]
The fix in commit [Center median label for cards - see](https://github.com/phetsims/center-and-variability/commit/4f3c5b44e56655b27e5fd0501af8765aea4be98f) is straightforward and all looks good here. Closing.
