### ISSUE TITLE
Cueing hand on cards and eraser buttons are making the hand buggy

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#339]
I noticed when the cueing hand appears on a card, and user doesn't move any of the cards, but instead presses the eraser button, the hand is buggy. Here a short video of where the hand ends up. The video starts after kicking 10 balls and the I pressed the eraser button.

https://github.com/phetsims/center-and-variability/assets/109630002/80597b27-a902-4875-9e0b-5fee7b569235

**Comment by marlitas** [comment]
This might have gotten addressed in another issue because I cannot recreate it now. Feel free to re-open if it emerges again.
