### ISSUE TITLE
Info box has cursor that looks pickable

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#343]
In the info dialog box on the Mean & Median screen and the Variability screen, the cursor changes as if indicating the plot markers (x's or dots) are movable. I couldn't get my screen capture to include the cursor, so here's a short screen recording to show the cursor changing from non pickable to pickable.

https://github.com/phetsims/center-and-variability/assets/109630002/800456f0-1db6-400f-ac53-8e378cbe61eb

**Comment by samreid** [comment]
I committed a proposed fix.  @catherinecarter can you please test?  If all is well, please close.

**Comment by catherinecarter** [comment]
Looks great. Thanks, @samreid.
