### ISSUE TITLE
Change visual order of min/quartile1 or Q3/max are overlapping in info box

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#344]
On the variability screen for the Boxplot info dialog, AP pointed out that the order of the labels is visually challenging when Q1 and Q3 aren't on the same horizontal line. Here's are two examples: 

<img width="231" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/8b2a3f8e-b7dd-4edf-bb93-041b5a6479c3"> <img width="162" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/1dfa5f7d-8922-4787-8ad0-cb7824a04b9f">

Let's change the order so the Q1 and Q3 are on the same horizontal line, right above the arrow in the cases when the min/Q1 are at the same location, and when Q3/max are at the same location as shown above (so in the image above, the Q1 and Min would change places, nothing else would change.

The order of the labels as shown in the images below will remain as they are (when Q1 and Q3 are stacked):
<img width="164" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/0958a5ae-a13a-4059-a18f-5866d8896c38"> 
<img width="207" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/5252a71e-e6b7-4634-9e3d-7c9bb57b2a2c">

**Comment by matthew-blackman** [comment]
Updated and looking really great! Ready for you review @catherinecarter. Code changes were very straightforward, feel free to close if all looks good.

**Comment by matthew-blackman** [comment]
Reviewed with @catherinecarter and all looks good! Closing.
