### ISSUE TITLE
Rounding the mean in info box on Mean & Median screen

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#346]
I noticed that the mean has many digits after the decimal point in the info box on the M&M screen. Let's round to two decimal points in the info box, and leave it to rounding to one decimal point in the accordion box. 

<img width="817" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/722afa2b-26b9-4549-af7a-7eb0013c26ee">

**Comment by matthew-blackman** [comment]
When working on https://github.com/phetsims/center-and-variability/issues/325, we discussed with @catherinecarter that the mean value should always be rounded to one decimal point, even if it is an integer.

**Comment by samreid** [comment]
The top comment also says "Let's round to two decimal points in the info box" but the next comment says "the mean value should always be rounded to one decimal point, even if it is an integer."  The commit above has it always at one decimal point.  @catherinecarter or @matthew-blackman can this issue be closed?

**Comment by catherinecarter** [comment]
I emailed Kelly F. to see if he recalled any specific conversations surrounding the rounding during the pedagogy meeting phase, and here is his reply: 
>I don't recall a discussion about rounding—maybe there was, but it wasn't particularly salient!
>While 2 decimal places is more precise than 1, I actually like just keeping it at 1 decimal place. 1 decimal feels precise enough to see how MAD or mean change as a soccer ball moves or gets added to the sample. It's not like I have to move a ball 6 units to see a change. The MAD and mean change with almost every movement, even at 1 decimal place of precision.
I think the 1 decimal components leading to a 2 decimal answer feels confusing with the formula. My concern is that that could become a distraction if noticed.

With the discussion yesterday and Kelly's input, I'm comfortable closing this with the decision to keep the rounding to the tenths place for the mean and MAD throughout the sim. Thanks!

**Comment by matthew-blackman** [comment]
The related issue with the MAD node is linked above and this issue can be closed.
