### ISSUE TITLE
dragIndicationCardProperty will need to be PhET-iO instrumented if we want it to persist in the state

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#347]
From https://github.com/phetsims/center-and-variability/issues/273, dragIndicationCardProperty will need to be PhET-iO instrumented if we want it to persist in the state.  Probably.  Maybe use IOType like NullableIO(ReferenceIO)?

**Comment by marlitas** [comment]
I tried to do this and I couldn't figure out the ReferenceIO thing... I tried creating a CardModelIO to pass through to the NullableIO but that didn't work either... will need help here.

**Comment by zepumph** [comment]
@marlitas @matthew-blackman and I worked out this and it seemed to be going alright. Unfortunately there were enough other issues with CardContainerModel state that I don't want to commit this just yet. Good luck and let me know if you need more help.


```

    this.dragIndicationCardProperty = new Property<CardModel | null>( null, {
      phetioValueType: NullableIO( ReferenceIO( IOType.ObjectIO ) ),
      tandem: options.tandem.createTandem( 'dragIndicationCardProperty' )
    } );
```

**Comment by marlitas** [comment]
I addressed state for both the cell order of the cards and the dragIndicationCardProperty above. Tested in the state wrapper and all looks good.

Would be good to get a review from @matthew-blackman.

**Comment by marlitas** [comment]
While doing a memory test we hit an assertion created by https://github.com/phetsims/center-and-variability/commit/d12e7f181d4952c31753c56aec5f077efb49471f. That should now be addressed with the above commit. Over to @matthew-blackman to test on his side and review.

**Comment by marlitas** [comment]
@matthew-blackman if all looks good here, can you confirm that https://github.com/phetsims/center-and-variability/issues/336 is good to go as well?

**Comment by marlitas** [comment]
@matthew-blackman This issue also seems interconnected. I tested on state wrapper and am no longer getting the error, but would be good for you to confirm on your end as part of this review. https://github.com/phetsims/center-and-variability/issues/337

**Comment by matthew-blackman** [comment]
Reviewed this as part of #314 and the visibility appears to be updating correctly via state wrapper. I noted the following:

> In studio, dragIndicationCardProperty behaves in a way I didn't expect. If I click 'Get Value', its phet-io ID is "centerAndVariability.medianScreen.model.cardContainerModel.cards.card1". But if I try to change the last part to "card3" and click 'Set Value', nothing happens. I also tried pasting the 'Get Command' code in the console and nothing happened. But I'm wondering, does this need to be instrumented at all? Having the drag indicator over the leftmost card seems to make sense to me, and I think its visibility would be enough to instrument via PhET-iO.

Despite these tandems appearing in studio, the current level of customizability is what I would expect - being able to turn the drag indicator on or off in the initial sim state. Customization beyond that might be too much in my opinion. Could simplify this with a dragIndicatorVisibleProperty? Thoughts @marlitas?

**Comment by marlitas** [comment]
I think this is ready to close based on commits to address review comments in #314
