### ISSUE TITLE
Median Arrow does not update with dynamic strings

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#349]
While working on https://github.com/phetsims/center-and-variability/issues/147 I noticed:
<img width="1135" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/f71d3dec-0595-40e8-887d-02370234b4bf">

It seems this just requires another listener for when the bounds change. ManualConstraint might work here.

**Comment by marlitas** [comment]
We addressed this with ManualConstraint and it's working really well, however we didn't feel great about creating a class property for medianValueNodes. Would like for @samreid to review.

**Comment by samreid** [comment]
@matthew-blackman and I reviewed this, and it is really great. @matthew-blackman will apply the same strategy in another spot in another issue.

**Comment by matthew-blackman** [comment]
Closing and continuing data values work in https://github.com/phetsims/center-and-variability/issues/363
