### ISSUE TITLE
Dynamic String Pixel Polish

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#350]
From https://github.com/phetsims/center-and-variability/issues/147,

The sim could probably use a once over by @catherinecarter to make sure maxWidths are looking okay in the sim. 

Use the query parameter `stringTest=dynamic` and the arrow keys to see how the sim will update and what the different string lengths will look like.

**Comment by catherinecarter** [comment]
All long strings look like they're behaving as they're supposed to. All text stays within the confines of their corresponding buttons or accordion boxes, and shrinks when too long to fit in the designed text constraints.

**Comment by marlitas** [comment]
With @catherinecarter's feedback this is ready to close.
