### ISSUE TITLE
Checkboxes alignment across screens (in play area)

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#352]
Currently, the checkbox group in the lower right in the play area are in different locations. They are different distances from the end of the number line (all the screen shots are from the same position in the sim, so the left edge is a good reference point). It looks like they are right-aligned with the reset-all button. 

Is it possible to make all of the checkboxes themselves be in the same position in the sim (sky)? 

<img width="235" alt="Screenshot 2023-07-07 at 8 39 53 AM" src="https://github.com/phetsims/center-and-variability/assets/109630002/b532c411-26fc-41be-b181-6d4aac951940">
<img width="235" alt="Screenshot 2023-07-07 at 8 39 57 AM" src="https://github.com/phetsims/center-and-variability/assets/109630002/984c60bf-64e2-4257-b8a1-9adb0ea9ca82">
<img width="235" alt="Screenshot 2023-07-07 at 8 40 00 AM" src="https://github.com/phetsims/center-and-variability/assets/109630002/e0810c00-baf6-49f9-9ff0-291b20a573cd">

**Comment by marlitas** [comment]
> Is it possible to make all of the checkboxes themselves be in the same position in the sim (sky)?

I'm a little confused at the request. Would you rather they be left aligned with the numberLine rather than right aligned with the ResetAll button?

**Comment by catherinecarter** [comment]
Thanks for asking, @marlitas :) I mean for the checkboxes to left aligned with each other (the checkbox itself) on each screen, not with the number line. In the current prototyped sim, moving from one screen to another doesn't have the checkbox group bounce to a new location: 
<img width="251" alt="Screenshot 2023-07-17 at 3 55 04 PM" src="https://github.com/phetsims/center-and-variability/assets/109630002/593ea25d-96c5-4d95-a2a7-abf24d26ade4"> <img width="251" alt="Screenshot 2023-07-17 at 3 55 08 PM" src="https://github.com/phetsims/center-and-variability/assets/109630002/29f2145a-dd20-410b-b409-d2978def0f17">

The checkboxes are the same distance from the end of the number line, and the bottom checkboxes are the same height from the grass. The goal is to not have the checkbox group bounce to different locations when changing screens. Does that help add clarity?

**Comment by marlitas** [comment]
So the reason they are lined up in the prototype is because they have the same width. Technically they are both still right aligned with the resetAll button. I'll switch it so it is left aligned with the number line with a padding or margin between.

**Comment by marlitas** [comment]
This has been addressed in the above commit. @catherinecarter over to you for review.

**Comment by catherinecarter** [comment]
The left alignment looks great. Wondering if we can make the icons line up as well? They will be further from the end of their description, but I think that will be ok (as shown by the Median on the first two screens). Currently screens 1 and 2 line up (probably naturally as the descriptions are the same length as each other), but the Variability screen has the icons lining up closer to their description: 

<img width="251" alt="Screenshot 2023-07-19 at 9 03 01 AM" src="https://github.com/phetsims/center-and-variability/assets/109630002/719d3eb1-7631-4db7-9838-08c76709fb73"> <img width="251" alt="Screenshot 2023-07-19 at 9 02 58 AM" src="https://github.com/phetsims/center-and-variability/assets/109630002/a13afb2a-effe-4392-a0ee-c7661c7e549d"> <img width="251" alt="Screenshot 2023-07-19 at 9 03 04 AM" src="https://github.com/phetsims/center-and-variability/assets/109630002/91137d07-8887-4a6b-8cb2-323458a14722">

**Comment by marlitas** [comment]
@catherinecarter Just to confirm. You want to widths to be the same across all screens, or just the padding between the icon and the text to be the same?

**Comment by catherinecarter** [comment]
Let's go with the width so left to right distance from the left edge of the checkbox to the right edge of the icon is the same for all screens.

**Comment by marlitas** [comment]
This has been addressed! Over to you for review @catherinecarter

**Comment by marlitas** [comment]
Great. This is ready to close.
