### ISSUE TITLE
Navigating to DataPointLayer in VariabilityScreen is messy

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#353]
The tree looks like this to get there:
<img width="407" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/d746a39e-3683-4f13-b002-3ec69ae6b249">

That seems unnecessarily complex and nested. This is a PhET-iO polish, so not a high priority, but putting on @catherinecarter's radar.

**Comment by catherinecarter** [comment]
There's a possible reorganization in https://github.com/phetsims/center-and-variability/issues/418 that will likely address this. Feel free to close this issue as it will most likely be addressed in the other issue, as well as https://github.com/phetsims/center-and-variability/issues/394, and https://github.com/phetsims/center-and-variability/issues/395, as well as #388.

**Comment by samreid** [comment]
We purposefully uninstrumented that parent toggle node in https://github.com/phetsims/center-and-variability/commit/d363704aea0760a410086feb6e5131bbb0c1c3f9, so this no longer appears in the tree. I feel we should close this issue and continue in https://github.com/phetsims/center-and-variability/issues/418
