### ISSUE TITLE
Add documentation to the maxKicks Median screen dependency

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#355]
In the PhET-iO studio tree, the maxKicks is indicated to have valid values of 5, 10, and 15. The tree dependency points to the preferences choice and includes 20, 25, and 30. 

Current indication: `centerAndVariability.medianScreen.model.maxKicksProperty`
Dependency immediately below: `centerAndVariability.medianScreen.model.maxKicksProperty.dependencies.centerAndVariability-global-model-preferences-maxKicksProperty`

Let's add documentation on the Median screen model to indicate that while the maxKicks can be set to higher than 15, the Median screen is restricted to maxKicks = 15.

**Comment by matthew-blackman** [comment]
Added documentation to the Median screen maxKicks property. Ready for review @catherinecarter

**Comment by matthew-blackman** [comment]
Reviewed with @catherinecarter and also added the line of documentation to centerAndVariability.global.model.preferences.maxKicksProperty in addition to centerAndVariability.medianScreen.model.maxKicksProperty. We'd like to discuss how this appears in studio with @arouinfar before closing.

**Comment by marlitas** [comment]
We met and decided on documentation to add to the global property. Commit incoming.

**Comment by samreid** [comment]
@catherinecarter anything else for this issue?
