### ISSUE TITLE
Setting activeKickerIndexProperty does not cycle through to complete maxKicks

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#357]
In testing the studio tree, I set the `activeKickerIndexProperty` to a number higher than zero. When I kicked as many balls as I could until the Kick 1/5 buttons disappeared, the maximum number of kicks had not been kicked yet. When I pressed, Set Value again, a kicker appeared and I was able to complete the maximum number of kicks.

`centerAndVariability.meanAndMedianScreen.model.sceneModel.activeKickerIndexProperty`

Perhaps there are a couple solutions:
- have the `activeKickerIndexProperty` set the first kicker, and then when kicker number 15 is reached, if the `maxKicks` hasn't been reached, start the count back to 0 for the kicker index until `maxKicks` has been reached
- only cycle through the kickers from the `activeKickerIndexProperty` to 15, then back to `activeKickerIndexProperty`
- something else?

**Comment by catherinecarter** [comment]
@marlitas, @zepumph, and I discussed and decided to make this a phet-io readOnly: true option to minimize the coding effort to change the behavior of the preset array of kickers, which is based on the maxKicks value.

**Comment by matthew-blackman** [comment]
Implemented, tested and very straightforward. Closing.
