### ISSUE TITLE
Add Pointer to Variability Screen

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#359]
@kathy-phet suggested adding the opportunity to have a pointer, similar to the Predict Mean/Median tools on Screens 1 and 2, where the user can predict freely a location on the number line.

Based on a short design meeting with @marlitas, @matthew-blackman, @kathy-phet, @ariel-phet, and I, we decided to implement the tool. Important decisions for this implementation are: 

1. **Name**: Pointer
2. **Behavior**: Will mimic the Predict Mean tool from the Mean & Median screen in the following ways:
   - Continuous movement along the number line
   - Shape (but different color)
   - Sound  
3. **z-order**: Will be 'always in front' of the interval tool handles
4. **Color**: will match the Interval tool handles, but be slightly deeper or more pronounced (color to be decided once all colors are locked in)
5. **Checkbox**: The order within the checkbox group will be third, with an icon matching it in the same way as the Predict Median/Mean pointers are on the M&M screen. 
   <img width="162" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/62f13015-f12d-452e-b540-eba0ed74c20b">

**Comment by marlitas** [comment]
The new pointer enhancement is added in. I'm assuming we'll want to adjust colors since the color matching the IntervalTool fill looks slightly off. @catherinecarter this is ready for you to review. 

@matthew-blackman this is also ready for code review. Thanks!

**Comment by matthew-blackman** [comment]
Code review complete and looking great! I fixed a small typo and noticed a change in the z-ordering behavior of the interval tool handles. The previous behavior was that grabbing a handle causes it to move in front of the other handle. From yesterday's design discussion it looks like the pointer tool should always be in front, but the interval tool handles can swap z-order when selected. I will give this a go, should be straightforward. Nice work @marlitas!

**Comment by matthew-blackman** [comment]
Z-ordering for interval tool handles is fixed and ready for design review. @catherinecarter please confirm that the z-ordering is correct for the interval tool handles and pointer.

The above commit was very straightforward so we can consider the code review wrapped up. Feel free to close if all looks good @catherinecarter 😊

**Comment by catherinecarter** [comment]
I played with the pointer and the interval tool for a while, and after moving the interval tool handle direction over the top of the pointer, then wanting to move the thing I'd just dropped again (interval tool handle) but something else moved (the pointer), it was an unexpected and minorly annoying interaction. 

I propose to have whatever was most recently dropped to be the z-ordered 'in front' object. An idea for when the pointer would be hidden behind the interval tool handle would be to make a slight transparency in the interval tool handles, maybe 0.75. Here's what it might look like: 
<img width="318" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/89a54477-734f-4033-951b-d37d3d216106">

That way, the most recently touched thing would be the thing you can immediately grab again, but the pointer could always be seen. Thoughts?

**Comment by matthew-blackman** [comment]
It seems like this warrants some design discussion before moving ahead with development. Labeling for design.

**Comment by catherinecarter** [comment]
I'm actually going to make the call to do it. I don't think we need a design meeting for it.

**Comment by matthew-blackman** [comment]
Sounds good @catherinecarter. I have a few questions about the design before proceeding. The transparency idea will introduce some complexity into the code since it is behavior-dependent, so I think it would be worth discussing before we invest a good chunk of work into development.

1. If the interval tool handle is transparent, how will the user know if it is in front of or behind the pointer? In your screenshots it looks like the thin black border around the circle is the only way for the user to see which one is in front.
2. What if all three of the handles are overlapping?

If we move ahead with this it will be a fair amount of development work, so just want to double-check that we are 100% confident about the design and all corner cases before implementing.

**Comment by catherinecarter** [comment]
Let's discuss next week when @marlitas returns. Great questions and worth a discussion for sure.

**Comment by catherinecarter** [comment]
@matthew-blackman and I discussed 07.14 and decided to change the z-order to have the most recently touched item active be in front. Then, with 75% opacity, there is a faint outline of the pointer tool's arrow behind the interval tool handle, which is nice.
<img width="297" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/70873890-5308-4d12-ba7d-39e4a0b974bc">

One thing to still do: make the 'sticks' above the handles stretch only to the top of the handle knob so they don't show behind the knob. 

One thing to note in interviews: is it confusing to see a 75% opacity which might imply disabled?

**Comment by matthew-blackman** [comment]
Ready for review @catherinecarter :D

**Comment by catherinecarter** [comment]
The z-ordering looks great. I don't see any opacity to the knobs on the interval tool. Did you implement? I looked in an incognito window in case my browser was caching, but the knobs looked to be at 100% opacity. Can you check the opacity?

**Comment by matthew-blackman** [comment]
Updated opacity to 0.7 - let me know how you like it @catherinecarter or feel free to close if all looks good.

**Comment by catherinecarter** [comment]
I think it's a little too transparent. They look inactive. Let's try 0.75 and see how that looks.

**Comment by catherinecarter** [comment]
After discussing with @arouinfar and @ariel-phet, I've come to a place of comfort. Here's what we'll do: 
- move the opacity of the handles back up to 100%
- move all the pointers up closer to the numbers themselves so the pointer is under the number with a few pixels of padding between the bottom of the number line number and the top of the arrow. We can do this for all the screens.
- move the handles of the interval tool down, so the 'stick' is extended to below the bottom of the arrow head so there's a little of the arrow handle showing between the bottom of the arrow and the top of the interval tool handle knob. See below.
- the z-order will remain as-is, with the last object dropped is the active object

<img width="343" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/37a355a1-9dde-48dc-b3df-ccd60ed342ad"> <img width="346" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/2146e0ef-8491-46d9-8671-54f31bc2f61b">


<img width="210" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/dda393d7-3dbd-4a52-ace0-6bed31dc2215">


I'll play with the colors so you can tell the difference between the interval tool handle and the pointer when all colors are decided upon.

**Comment by matthew-blackman** [comment]
Updated and ready for design review @catherinecarter 😎

**Comment by catherinecarter** [comment]
Looks great!

**Comment by marlitas** [comment]
Thanks for the initial code review @matthew-blackman. Looked over the smaller recent changes and all looks good. Closing!
