### ISSUE TITLE
Revisit scaling of x's/dots for maxKicks = 20, 25, 30 now that accordion box is taller

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#360]
@matthew-blackman and I were reviewing the height of the range rectangle in the info box (#345), we remembered the markers in the accordion box were scaled to accommodate more of them when maxKicks was set to a number higher than 15. Now that the accordion box is much bigger, we'd like to revisit whether the scaling is needed anymore.

The important thing would be to ensure a partial marker would be at the top of the accordion box, indicating there are more markers in the stack, and if a user wants to see them all, they can go to the info box.

**Comment by marlitas** [comment]
We met and decided we want to keep scaling, but ensure that rectangle padding in the infoDialog is taking the scaling into account. That will be addressed in https://github.com/phetsims/center-and-variability/issues/345
