### ISSUE TITLE
Pointer checkbox doesn't reset

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#361]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
Seen on master on 7/13/23
The Pointer checkbox on the Variability screen does not reset with the reset all button. If it is checked it will stay checked, and if it is unchecked it will stay unchecked.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Variability‬
URL: https://bayes.colorado.edu/dev/phettest/center-and-variability/center-and-variability_en.html?ea&brand=phet
Version: 1.1.0-dev.11 (unbuilt)
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by matthew-blackman** [comment]
Nice catch @KatieWoe. Fix is implemented and code change is very straightforward. Tested and all looks good. Closing.
