### ISSUE TITLE
Large memory snapshots

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#365]
**Device**
Samsung
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
Seen on a build off of master on 7/17/23. The first memory snapshot seemed unusually large. @samreid said on slack:
> We knew it would be large, because we statically allocate everything, but 200 MB seems pretty crazy. Can you please open the issue and we’ll take a look?

![bigmem](https://github.com/phetsims/center-and-variability/assets/41024075/9c8caeb7-245b-4bea-9320-f918c0c3936c)

**Comment by KatieWoe** [comment]
Large snapshots still seen in https://github.com/phetsims/qa/issues/964.

**Comment by samreid** [comment]
@marlitas and I cut the memory by about 4x in the commit, since it was iterating over scenes one too many time.  So this main problem is resolved. Closing.
