### ISSUE TITLE
Should we extend AccessibleValueHandler or AccessibleSlider?

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#367]
In #316 we discussed that it is surprising that certain things are a "slider", like soccer balls.  We should consider whether we should extend AccessibleValueHandler instead.

Discovered in https://github.com/phetsims/center-and-variability/issues/351

**Comment by jessegreenberg** [comment]
AccessibleValueHandler is effectively a "superclass" for other traits like AccessibleSlider. It is less convenient to use on its own and using AccessibleSlider is better. AccessibleValueHandler is also a "slider" (input of type "range" in the PDOM) so there really isn't a difference in behavior, you would just need to provide a bit more code to use AccessibleValueHandler directly.

I am not sure if AccessibleSlider/AccessibleValueHandler are best for your use case in CAV. Using that trait is most convenient and accessible if you are working with a component that moves in one dimension or is controlled well by a single Property. If it makes sense to control a component like a slider, then great! If not, I would recommend using KeyboardDragListener instead.

**Comment by jessegreenberg** [comment]
I think KeyboardDragListener could be more straight forward in this case. Here is a patch for the cards with some comments. Its working OK for me but could be improved.

<details>

```patch
Subject: [PATCH] Hide a keyboard help section row if the locale is not english, see https://github.com/phetsims/quadrilateral/issues/444
---
Index: js/median/view/CardNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/median/view/CardNode.ts b/js/median/view/CardNode.ts
--- a/js/median/view/CardNode.ts	(revision 9f88e24034fb6da9c19c60090e2b3966492c9ab4)
+++ b/js/median/view/CardNode.ts	(date 1689711766994)
@@ -8,7 +8,7 @@
  */
 
 import centerAndVariability from '../../centerAndVariability.js';
-import { Color, DragListener, Node, NodeOptions, Rectangle, Text } from '../../../../scenery/js/imports.js';
+import { Color, DragListener, KeyboardDragListener, Node, NodeOptions, Rectangle, Text } from '../../../../scenery/js/imports.js';
 import optionize, { EmptySelfOptions } from '../../../../phet-core/js/optionize.js';
 import PhetFont from '../../../../scenery-phet/js/PhetFont.js';
 import SoccerBall from '../../soccer-common/model/SoccerBall.js';
@@ -24,6 +24,7 @@
 import cvCardDropSound_mp3 from '../../../sounds/cvCardDropSound_mp3.js';
 import CAVQueryParameters from '../../common/CAVQueryParameters.js';
 import CAVConstants from '../../common/CAVConstants.js';
+import TReadOnlyProperty from '../../../../axon/js/TReadOnlyProperty.js';
 
 type SelfOptions = EmptySelfOptions;
 export type CardNodeOptions = SelfOptions & NodeOptions & PickRequired<NodeOptions, 'tandem'>;
@@ -46,7 +47,8 @@
 
 export default class CardNode extends Node {
 
-  public readonly dragListener: DragListener;
+  // Whether any form of input is interacting with this Node.
+  public readonly isPressedProperty: TReadOnlyProperty<boolean>;
 
   // Emit how far the card has been dragged for purposes of hiding the drag indicator arrow when the user
   // has dragged a sufficient amount
@@ -71,7 +73,12 @@
     } );
 
     const card = new Node( {
-      children: [ rectangle, text ]
+      children: [ rectangle, text ],
+
+      // pdom - Make this Node focusable. CardNode is a container with layout management, make this Node focusable
+      // so that the focus highlight only surrounds the graphically visible Node.
+      tagName: 'div',
+      focusable: true
     } );
 
     // For layout only, a bounding box that the card animates within for the "pick up" and "drop" effects.
@@ -111,26 +118,64 @@
       }
     } );
 
-    this.dragListener = new DragListener( {
-      tandem: options.tandem.createTandem( 'dragListener' ),
-      positionProperty: cardModel.positionProperty,
-      start: () => {
-        cardModel.isDragging = true;
-        this.moveToFront();
-
-        // Set the relative position within the parent.
-        card.setTranslation( PICK_UP_DELTA_X, PICK_UP_DELTA_Y );
-        cardPickUpSoundClip.play();
-      },
-      end: () => {
-        cardModel.isDragging = false;
+    // Work on drag start do be done for all forms of input
+    const handleDragStart = () => {
+      cardModel.isDragging = true;
+      this.moveToFront();
+      card.setTranslation( PICK_UP_DELTA_X, PICK_UP_DELTA_Y );
+    };
+
+    // Work to be done on drag end for all forms of input
+    const handleDragEnd = () => {
+      cardModel.isDragging = false;
 
-        // Restore the relative position within the parent.
-        card.setTranslation( 0, 0 );
+      // Restore the relative position within the parent.
+      card.setTranslation( 0, 0 );
+    };
+
+    const dragListener = new DragListener( {
+      tandem: options.tandem.createTandem( 'dragListener' ),
+      positionProperty: cardModel.positionProperty,
+      start: () => {
+        handleDragStart();
+
+        // The pickup sound was too much for keyboard input IMO, so I opted to only have it for DragListener
+        cardPickUpSoundClip.play();
+      },
+      end: () => {
+        handleDragEnd();
+
+        // The drop sound was too much for keyboard input IMO, so I opted to only have it for DragListener
         cardDropSoundClip.play();
       }
     } );
-    this.addInputListener( this.dragListener );
+    this.addInputListener( dragListener );
+
+    const keyboardDragListener = new KeyboardDragListener( {
+      tandem: options.tandem.createTandem( 'keyboardDragListener' ),
+      positionProperty: cardModel.positionProperty,
+
+      // The amount of movement in view coordinates per keyboard press and every interval.
+      // TODO: This value felt OK, but maybe there is a better one or way to calculate it.
+      dragDelta: 50,
+      moveOnHoldInterval: 250,
+      moveOnHoldDelay: 750,
+
+      // So that up/down arrow keys move the cards horizontally as well
+      keyboardDragDirection: 'leftRight',
+
+      start: () => {
+        handleDragStart();
+      },
+      end: () => {
+        handleDragEnd();
+      }
+    } );
+    card.addInputListener( keyboardDragListener );
+
+    this.isPressedProperty = phet.axon.DerivedProperty.or( [
+      keyboardDragListener.isPressedProperty, dragListener.isPressedProperty
+    ] );
 
     this.soccerBall.dragStartedEmitter.addListener( () => this.moveToFront() );
 
Index: js/median/view/CardNodeContainer.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/median/view/CardNodeContainer.ts b/js/median/view/CardNodeContainer.ts
--- a/js/median/view/CardNodeContainer.ts	(revision 9f88e24034fb6da9c19c60090e2b3966492c9ab4)
+++ b/js/median/view/CardNodeContainer.ts	(date 1689710807869)
@@ -106,7 +106,7 @@
       cardNode.cardModel.positionProperty.link( this.createDragPositionListener( cardNode ) );
 
       // When a card is dropped, send it to its home cell
-      cardNode.dragListener.isPressedProperty.lazyLink( isPressed => {
+      cardNode.isPressedProperty.lazyLink( isPressed => {
 
         if ( isPressed ) {
           this.wasSortedBefore = model.isDataSorted();
@@ -160,7 +160,7 @@
 
               successSoundClip.play();
 
-              const cardBeingDragged = this.cardNodes.filter( cardNode => cardNode.dragListener.isPressed ).length;
+              const cardBeingDragged = this.cardNodes.filter( cardNode => cardNode.isPressedProperty.value ).length;
               const cardsAnimating = model.cardCells.filter( card => card.animation ).length;
               if ( cardBeingDragged === 0 && cardsAnimating === 0 ) {
                 this.pickable = false;
@@ -391,7 +391,7 @@
   // The listener which is linked to the cardNode.positionProperty
   private createDragPositionListener( cardNode: CardNode ): ( position: Vector2 ) => void {
     return ( position: Vector2 ) => {
-      if ( cardNode.dragListener.isPressedProperty.value ) {
+      if ( cardNode.isPressedProperty.value ) {
 
         const originalCell = this.model.cardCells.indexOf( cardNode.cardModel );
 

```

</details>

**Comment by samreid** [comment]
Thanks @jessegreenberg, can you please also review the other cases in center-and-variability where we use `extends AccessibleSlider` and see if those should change as well? Or let us know if this is more efficient to look at in a short zoom call.

**Comment by terracoda** [comment]
I'll gently chime in that when considering the appropriate "PhET-Component-Type" for an interaction, we need to consider the rendered HTML/ARIA role and ensure that role is appropriate for the interaction and the interaction's context. 

The HTML/ARIA role affects more than just the keys you can press by default to move the rendered element. The HTML/ARIA is automatically accessible to screen reader software and will be communicated out loud without or without accessible descriptions. 

I agree with @jessegreenberg (and @emily-phet elsewhere) that the cards and soccer balls are not HTML sliders in the full context of the interactions. They are each a related group of things that can be re-ordered.

Sliders are for a range of values.

**Comment by samreid** [comment]
Considering the case of 1 soccer ball, you can move it left and right from 1 to 15 in increments of 1. So it does seem like a slider-ish interaction at least for the keyboard.

> The HTML/ARIA role affects more than just the keys you can press by default to move the rendered element. The HTML/ARIA is automatically accessible to screen reader software and will be communicated out loud without or without accessible descriptions.

I'd like to understand more about how what HTML/aria role would be appropriate for moving a soccer ball, and how it should be communicated.

**Comment by jessegreenberg** [comment]
`AccessibleSlider` might be a good fit for the Soccer Balls. Differences are mostly about Interactive Description and not Alt Input.

For screen reader accessibility, you can set things like:
- Role: What kind of object is this?  This guides the user toward how to use it. (slider, checkbox, button, other)
- Name: What is the component called?
- Description: Extra information about what this component is/does/how to use it.
- Object response: Feedback that describes how the component changed after interaction.
- Context response: Feedback that describes how the application changed after interaction.

When using a slider, the user quickly knows what the component is and how to control it with their device. From the categories above you might design:

- Name: "Soccer Ball 1 position"
- Role: slider
- Description: "In position {{CURRENT_POSITION}}, on top of {{COUNT}} other Soccer Balls."
- Object Response: "Position {{NEW_POSITION}}"
- Context Response: "Now on top of {{COUNT}} other balls."

This would produce the following output when you focus on the ball:
>'Soccer Ball 1 position, slider, in position 3 on top of 2 other balls.'

And when you move the soccer ball:
> 'Soccer Ball 1 position, position 4, now on top of 4 other balls." 

I think this would work pretty well! But if we are worried that thinking of the balls as "stacks of sliders" is too confusing, it could be better to use a custom role with KeyboardDragListener.

**Comment by samreid** [comment]
Soccer balls and cards no longer use accessible slider. The interval tool and predict mean/median tools do, which we agreed makes sense.  So I think this issue can be closed.
