### ISSUE TITLE
MAD info dialog is buggy

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#369]
Not sure what's going on here, but when looking at the sim, I created a situation with two balls in the field, one at 7 and one at 9. The mean = 8, and the MAD should be calculated as (1 + 1)/2 = 1, but this is what happened instead. I'm creating an issue, although I don't know exactly the problem.  

<img width="568" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/0b2ea6a9-715b-4346-b536-1e117ff5868c">

It might be happening when there are two balls in the playing field and one of the was moved: 
<img width="618" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/e9063bf5-d187-4492-93f5-ff821c82cc02">

**Comment by catherinecarter** [comment]
Now I'm not sure why, but I was able to put three balls in the playing field and the calculation was still inconsistent with the distances each soccer ball is from the mean: 
<img width="753" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/a49abd0d-57ad-4ded-bb64-355a1f75493b">

**Comment by matthew-blackman** [comment]
@samreid @marlitas and I looked into this and confirmed that falls under the work done in https://github.com/phetsims/center-and-variability/issues/169. We'd like to confirm the desired behavior before coming up with a way to implement.

**Comment by matthew-blackman** [comment]
Fixed and ready for your review @catherinecarter. Feel free to close if all looks good.

**Comment by catherinecarter** [comment]
I couldn't reproduce again, so thanks for figuring out what was happening. Closing!
