### ISSUE TITLE
Move soccer common repo outside of CaV

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#374]
This is the last remaining work for: https://github.com/phetsims/center-and-variability/issues/222

We want to wait until development is done to do this so that we don't have to deal with cross repo commits as often.

**Comment by marlitas** [comment]
Soccer Common is now a separate repo. Imports seem to be working well overall. Keeping this issue open for a few days to ensure everything is good to go. Also sending to @samreid and @matthew-blackman for review.

**Comment by samreid** [comment]
What strategy was used to migrate the repo? It seems like the history stops at June 9 2023 in https://github.com/phetsims/center-and-variability/commit/1802160874212de191ac4dc3000969a2d10a6923 as if it could not track the moves prior to that commit.

**Comment by marlitas** [comment]
I used `copy-history-to-different-repo.js` in perennial and also double checked that I saw a git history before committing and merging.

**Comment by marlitas** [comment]
I think many of these files were new when we did the original refactoring to SoccerCommon which might explain the June 9th date.

**Comment by samreid** [comment]
The commits above look good. I don't why our tooling lost history before June 9, 2023 and I don't know how much time it is worth to spend on it. I tried looking into the history to see why something is unexpectedly private for https://github.com/phetsims/center-and-variability/issues/431 and I run into the June 9 dead-end. I also think we need to add implementation notes and model.md, and ideally (if there's time) an example main usage for this repo.  @marlitas what do you think?

**Comment by marlitas** [comment]
I think adding an implementation-notes.md, model.md, and example main are good ideas. I'll create some placeholders for those now.

**Comment by marlitas** [comment]
So implementation-notes.md and model.md templates are already in there. I tried looking for examples of an example main and I couldn't find any... I'm not exactly sure what I should be creating for that...

**Comment by samreid** [comment]
I feel this issue can be closed. Would you recommend we open new issues for writing the documentation and creating a sample usage?

**Comment by marlitas** [comment]
> Would you recommend we open new issues for writing the documentation and creating a sample usage?

Sounds good. Issues are: https://github.com/phetsims/center-and-variability/issues/442, https://github.com/phetsims/center-and-variability/issues/443

> For instance, bamboo is a common code repo that has a sample main.

I am very confused... I searched bamboo and could not find a file with `sample` or `main` or any other file that seemed might fill that space. I noticed there is a `demo` directory, but that seems unnecessary for `soccer-common`.

**Comment by samreid** [comment]
For instance: http://localhost/bamboo/bamboo_en.html or you can select it from phetmarks

**Comment by marlitas** [comment]
Ahh I see. I'm not sure it is necessary for soccer-common to have a demo. That feels like an enhancement we can undertake down the line we start to see a whole suite of sims using soccer-common, but doesn't seem necessary for the purposes of CaV and MSaB. 

I'm going to go ahead and close, but @samreid feel free to re-open if you feel differently.
