### ISSUE TITLE
Rename SoccerPlayer (and related variables) to Kicker

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#377]
For PhET-iO we want to be consistent and not switch between SoccerPlayer and Kicker. This will change the tandem names. But may also be good to rename the class also.

**Comment by marlitas** [comment]
Changes have been applied in the above commits. This is ready for review by @catherinecarter. If all looks good feel free to close.

**Comment by catherinecarter** [comment]
Looks great and consistent. Thanks!
