### ISSUE TITLE
Uninstrument isAnimationHighlightVisibleProperty

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#378]
We want to make centerAndVariability.medianScreen.model.sceneModel.soccerBalls.soccerBall1.isAnimationHighlightVisibleProperty uninstrumented, and possible factor out of the SoccerBalls in the Median and Variability Screens.

**Comment by marlitas** [comment]
This has been fixed in the above commit and tested in state. @catherinecarter over to you for review. Close if all looks good.

**Comment by catherinecarter** [comment]
Looks great. Didn't find any instances in the tree.
