### ISSUE TITLE
Make numberOfScheduledSoccerBallsToKick to readonly & rename

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#381]
Make it readonly and rename to numberOfQueuedKicksProperty

**Comment by marlitas** [comment]
Fixed above and ready for @catherinecarter

**Comment by catherinecarter** [comment]
Looks great! Seems to working as intended with it's Current Value counting down when the 'Kick 1' or 'Kick 5' buttons are pressed. For the Variability screen, this element counts down per kicker. 

Looks great.
