### ISSUE TITLE
soccerBallPhaseProperty should be readonly

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#382]
Make it readonly for PhET-iO

**Comment by marlitas** [comment]
This is addressed and ready for review by @catherinecarter.

**Comment by catherinecarter** [comment]
While it was fun to manually change the phase of the ball, this was a good call. No more buggy behavior with the kickers or balls in the play area. Thanks.

**Comment by samreid** [comment]
Thanks for catching this. I couldn't tell when it got marked as non-read only. But I corrected it, closing.
