### ISSUE TITLE
Investigate the instrumentation of InfoDialog

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#384]
The current instrumentation seems odd and @arouinfar is not accustomed to seeing infoDialogs show up this way. We don't remember why we did it like that so we're going to check in on it. Notes from the meeting doc:

- Complication in the code
- Sam is looking into whether this needs to be instrumented
- Could have been a layout thing?
- API for the info dialog doesn’t have a visible property
- TODO: Looking into whether this needs to be uninstrumented

**Comment by samreid** [comment]
@matthew-blackman @marlitas and I addressed this in the commit.  We uninstrumented the model `isInfoVisibleProperty` which we think was one of the main problems.  So we feel this can be closed.
