### ISSUE TITLE
Uninstrument SelectedSceneModelProperty from screens 1 & 2

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#385]
It clutters the space, and is not needed for state in the Median and Mean & Median screens.

**Comment by marlitas** [comment]
I addressed this above and is ready for @catherinecarter. I would also like @samreid to double check the approach in case there's any PhET-iO edge case or specifics that I may not be thinking of.

**Comment by marlitas** [comment]
@samreid this issue and https://github.com/phetsims/center-and-variability/issues/394 use the same implementation.

**Comment by catherinecarter** [comment]
I only see one and it's on the Variability screen. Confirmed success from my end!

**Comment by samreid** [comment]
I reviewed the commit and feel this issue can be closed, thanks!
