### ISSUE TITLE
Confirm cellPositionProperty is phetioFeatured: false and rename

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#386]
we don't want to feature it, and we also want to rename the property to `indexProperty`.

**Comment by marlitas** [comment]
Accidentally committed to #385, but this is ready to go. Over to @catherinecarter

**Comment by catherinecarter** [comment]
I am remembering this to only apply to the Median screen, but would love confirmation about that. I don't see any instances of cellPositionProperty, and the indexProperty looks great as readOnly and not featured.
