### ISSUE TITLE
Rename all predictMean related nodes and Properties

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#392]
Make sure they are consistent with the checkBox label "predictMean". For example, `meanPredictionNode` would change to `predictMeanNode`.

**Comment by marlitas** [comment]
Addressed and ready for @catherinecarter.

**Comment by catherinecarter** [comment]
Looks great. I didn't find any instances of meanPredict or medianPredict, and all elements look to be named predictMedian or predictMean. Thanks!
