### ISSUE TITLE
Hide dataLayer globally instead of by each different plotNode

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#397]
For PhET-iO we want to instrument the visibility of ALL dataPoints in a screen. There should be a globalProperty instrumented for this.

**Comment by marlitas** [comment]
All data points (except ones in the infoDialog) can be turned off on a per screen basis through `isDataPointLayerVisibleProperty` in the model. This is only for the Mean & Median, and Variability screens.

Ready for @catherinecarter and code review for @samreid.

**Comment by catherinecarter** [comment]
Yep, it is working and works globally as described. Looks good to me.

**Comment by samreid** [comment]
Code review looks good, closing.
