### ISSUE TITLE
Scenes and Plot Nodes should reference Kicker in VariabilityScreen

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#398]
All scenes and plot nodes should reference which kicker they are tied to. For example, `sceneKicker1`, `plotNodeKicker1`.

This will be only for the variability screen.

**Comment by marlitas** [comment]
This is implemented and affecting only the variability screen. Over to @catherinecarter for review.

**Comment by catherinecarter** [comment]
Looks much more consistent within the tree, but also with the sim since the players have numbers on their jerseys. Thanks!
