### ISSUE TITLE
CV Sound Levels Adjustment

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/center-and-variability#404]
I wen't through the sim today and overall we got the levels almost perfect out of the box! There only two things I would like you to adjust.

1. Eraser Button sound can be lowered 10%
2. On the third screen the interval tool can be lowered 25% (left and right handles and main movement continuous sound)

**Comment by samreid** [comment]
I'll implement this.

**Comment by samreid** [comment]
I adjusted the sound output levels as prescribed, and I fixed the variable name/tandem for the eraser button.  @Ashton-Morris can you please test on phettest?  Please close if it seems OK.

**Comment by samreid** [comment]
@catherinecarter requested to make the interval tool even quieter, and @marlitas and I agreed.  We worked together to tune it and I'll commit momentarily.

**Comment by samreid** [comment]
Since we have opened the overall balancing issue, it seems this one can be closed.  We'll continue in https://github.com/phetsims/center-and-variability/issues/304
