### ISSUE TITLE
Accordion box checkboxes aligned on screens 1 and 2

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#407]
When moving between screens 2 and 3, I noticed the checkboxes in the accordion box (on the right) are both centered vertically. Curious if we can instead have them align with the top checkbox on screen 2. Below is a screenshot of screen 2(left) and screen 3 (right). 

![Screenshot 2023-07-26 at 10 17 14 AM](https://github.com/phetsims/center-and-variability/assets/109630002/936f12d1-e700-487e-b64d-2ff6e9f73819) ![Screenshot 2023-07-26 at 10 17 09 AM](https://github.com/phetsims/center-and-variability/assets/109630002/c7c34d9c-c489-4aea-b167-ff6ebeebe3b9) 

This will be similar to the Median and Mean readOuts (on screen 3) be always in their location instead of centering vertically when the IQR/MAD checkboxes are not checked on the left side of the accordion box:

![Screenshot 2023-07-26 at 10 16 11 AM](https://github.com/phetsims/center-and-variability/assets/109630002/d7da9ead-da08-44ec-91e0-7a8101b351c2) ![Screenshot 2023-07-26 at 10 16 18 AM](https://github.com/phetsims/center-and-variability/assets/109630002/03d53e2e-9512-4fd6-9bb5-e062268106b1)

**Comment by marlitas** [comment]
This is implemented, but honestly it looked a bit odd to me on the third screen... not sure if it's because I'm just used to seeing it in the center... not sure what you think @catherinecarter.

**Comment by marlitas** [comment]
Okay great! I'll send over to @samreid or @matthew-blackman to review.

**Comment by samreid** [comment]
Code review looks good to me, nice work, closing.
