### ISSUE TITLE
Create infrastructure for global characters

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#408]
@kathy-phet mentioned that we are getting close to the point where global characters will be ready to add into sims. It would be good to keep in mind what is needed in the sim infrastructure to make implementation easy in the future.

**Comment by kathy-phet** [comment]
@mariahmaephet - Tagging you here as well!

**Comment by samreid** [comment]
Will this be part of the initial (non-prototype) release?

**Comment by kathy-phet** [comment]
Yes, for one of the funders, we should plan to implement this infrastructure for Africa localizations at least.

**Comment by samreid** [comment]
What is the next step for this issue? Does it require a new set of artwork? Who should be assigned? Should the issue be marked "on hold" until something else happens?

**Comment by kathy-phet** [comment]
The infrastructure can be set up in the code, and the exact artwork can follow. 

You can look at what Jesse did in Energy Skate Park sim and code (https://phet.colorado.edu/sims/html/energy-skate-park/latest/energy-skate-park_all.html). 

There will be a number of sims that need a coding pattern for swapping out character sets. Eventually we will have maybe 5 or 6 character sets to choose from.

**Comment by marlitas** [comment]
I am at the point where I now need the assets to finish the global characters feature. Since this issue is titled `Create infrastructure...` I am going to mark it read-for-review and open a new issue for adding in the assets once they are ready.

**Comment by marlitas** [comment]
@matthew-blackman and I reviewed synchronously. We are ready to close this issue and finish adding in assets in #425.
