### ISSUE TITLE
Bring the pointers and interval tool handles down a few pixels to not occlude the number

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#409]
Currently when tabbing to the pointer on any of the three screens (predict median/mean and pointer tool), the focus area slightly occludes the number on the number line.

Proposing to bring both the pointer and the interval tool handles a couple pixels to remedy the occlusion.
<img width="192" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/9f507124-a8ed-4ac1-bdf9-4513e10402e4"> <img width="156" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/f2c1962c-6262-4e21-8aee-1683a357cbf9">

**Comment by samreid** [comment]
Moving things down 5px seemed to work well. Commit on the way:

![image](https://github.com/phetsims/center-and-variability/assets/679486/7b036dfc-394e-4cf1-b5dc-17dfb6b603ca)

**Comment by samreid** [comment]
Commit pushed in https://github.com/phetsims/center-and-variability/commit/031ea7d5725c0990fc4da09bcdd234e8c0aee305 (not showing in thread yet).  @catherinecarter can you please review/test?  Please close if all is well.

**Comment by catherinecarter** [comment]
Looks great. An improved change without even really noticing it. I don't see any occlusion with the numbers. Thanks!
