### ISSUE TITLE
Rename kickOneButton and kickFiveButton to numerals

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#411]
Rename the kickOneButton and kickFiveButton in studio to be numerals: 

- kick1Button
- kick5Button

This will help with the alphabetizing to have the kick1 be first, as well as match the already-created children's names, which have numerals.

**Comment by samreid** [comment]
I'll work on this.

**Comment by samreid** [comment]
Fixed, looks much better. Closing.
