### ISSUE TITLE
Change drag indicator on soccer balls to a hand with arrow

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#412]
In interviews, students did not know what the blue cueing arrow was prompting them to do. Based on two initial interviews, we moved the blue cueing arrow from above the soccer ball to around the soccer ball hoping it would better indicate the soccer balls were moveable. 

In the most recent interview, the student still did not move the soccer ball, despite our change in the cueing arrow. During design meeting, we decided to change the cue to mimic the hand from the Median screen with slight modification since the hand was very effective in cueing the student to move the card. 

Here's a screenshot of the design, with assets coming shortly. Two images, one if the ball is on the axis, and one with the ball in a stack with other balls to its left:
![image](https://github.com/phetsims/center-and-variability/assets/109630002/c50fbb33-cc75-4898-b322-b8f0a92daa0c) ![image](https://github.com/phetsims/center-and-variability/assets/109630002/dddf3a48-1d77-4be4-b468-f36f218b6dea)

**Comment by marlitas** [comment]
This has been implemented and is now ready for design review as well as code review.

**Comment by samreid** [comment]
The behavior and implementation look good. Some code review recommendations:
* Create a new image called hand.png which is pointing up and has no arrow
* Use hand.png for both the cards and soccer balls (rotated as appropriate for the soccer balls)
* Create the single and double headed arrows programmatically (squares and triangles)
* For https://github.com/phetsims/center-and-variability/commit/68d152ffbde3cc43b6716f52a42bd09ba4e50b22, consider iterating over stacks rather than soccer balls.
* Consider or ask designers whether hand.png should be in scenery-phet/

**Comment by marlitas** [comment]
I'll need a file of just the hand pointing upwards to address the first three review suggestions. But will work on implementing the third.

**Comment by marlitas** [comment]
Okay I addressed `consider iterating over stacks rather than soccer balls.`. The rest will need to wait until @catherinecarter is back, so putting this issue on hold until then.

**Comment by terracoda** [comment]
Also, for keyboard interaction, for a two-step drag, you will need a visual hint on focus to "Press Space to Grab or Release", until the first successful grab action. And on first successful grab you might want left and right arrows or just a single right arrow if the hint appears on the first card.

Here's an example from Friction. There are similar examples in BASE and FL.
<img width="771" alt="Screen Shot 2023-08-02 at 10 37 15 AM" src="https://github.com/phetsims/center-and-variability/assets/1902116/5f54bfca-89df-468e-9210-bacb37eebbc3">
<img width="771" alt="Screen Shot 2023-08-02 at 10 39 01 AM" src="https://github.com/phetsims/center-and-variability/assets/1902116/5e339794-ff89-4b6a-9016-fc96691479f0">
<img width="770" alt="Screen Shot 2023-08-02 at 10 37 58 AM" src="https://github.com/phetsims/center-and-variability/assets/1902116/26a3332a-8916-49a6-ba7d-9e1c9b15442a">
<img width="770" alt="Screen Shot 2023-08-02 at 10 38 32 AM" src="https://github.com/phetsims/center-and-variability/assets/1902116/aeddecd6-a65d-44b6-92d5-ee1d876e6f97">

**Comment by terracoda** [comment]
There are some options supported by common code, but it may not be straight forward. Please reach out if you need assistance.

**Comment by catherinecarter** [comment]
From above: 

> The behavior and implementation look good. Some code review recommendations:

>- Create a new image called hand.png which is pointing up and has no arrow
>- Use hand.png for both the cards and soccer balls (rotated as appropriate for the soccer balls)
>- Create the single and double headed arrows programmatically (squares and triangles)
>- Consider or ask designers whether hand.png should be in scenery-phet/

I created a new .ai file called, "cueinghands.ai," and put it in the asset folder. This .ai file contains the vertical hand with and without the arrow, as well as the tilted hand and arrow (separate, not grouped).

I also created a new asset called, "hand.png," and also uploaded to the assets folder. This is the vertical hand without the arrow. 

In terms of placing the hand in scenery-phet/, if this isn't too difficult, I can see this being useful in the future, but I don't know everything that goes into this move to say whether it's worth the time.

**Comment by marlitas** [comment]
All of @samreid's review feedback has been applied and is ready for review again. I made a new issue (https://github.com/phetsims/center-and-variability/issues/433) for the keyboard interaction hints @terracoda mentioned above.

**Comment by matthew-blackman** [comment]
Reviewed this with @samreid and all of the changes to the drag indicator hand are looking really good. Nice work @marlitas! We cleaned up a few stray files in the assets folder, and did a small cleanup in the dragIndicatorHand illustrator file. Closing this issue.
