### ISSUE TITLE
Create global InputEnabledProperty for the Interval Tool

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#413]
For PhET-iO We would like the enabling of both the IntervalTool in the AccordionBox and the IntervalTool in the PlayArea to be based off of one property. We will add an intervalToolInputEnabledProperty to the main model. There will only be one property for the Variability screen.

**Comment by marlitas** [comment]
Done above. Over to @catherinecarter for design review, and @samreid / @matthew-blackman  for code review.

**Comment by catherinecarter** [comment]
Looks clean from my end. Having this property global seems like a good change. Thanks.

**Comment by samreid** [comment]
Code changes look good to me, and I tested it in studio. Nice work, closing.
