### ISSUE TITLE
Remove double tandems in tree

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#416]
In the studio tree, sometimes there are double tandems. Example: 
`centerAndVariability.medianScreen.view.accordionBox.infoButton.infoButton.firedEmitter` (double ‘infoButton’)

Moving forward, for tree PhET-iO IDs, let's make sure if there is a pattern of X.X (X's are equal strings), often the second tandem can be removed, or the tandem can move up a level.

**Comment by samreid** [comment]
Fixed with @catherinecarter, closing.
