### ISSUE TITLE
Change cards on Median screen to be inputEnabled rather than enabled

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#417]
Currently, the cards on the Median screen are very dark when the enabled=false. @arouinfar suggested making the cards inputEnabled rather than enabled when the client does not want students to be able to interact (move) the cards in the accordion box. 

In the studio tree, change the enabledProperty on the cards to be an inputEnabledProperty instead.

The cueing hand on the cards will need to be not visible when this is true.

**Comment by samreid** [comment]
@catherinecarter and I collaborated on that fix, and it seems good to us in studio testing. Closing.
