### ISSUE TITLE
Change name of cueing indicators to be consistent

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#419]
In the studio tree, the card drag indicator is called, "dragIndication" while the soccer ball drag indicator is called, "dragIndicator." 

With a nesting structure that indicates which drag indicator is being interacted with in the tree, this will be ok to have them be called the same thing for consistency. 

In the tree, let's be consistent and call these "dragIndicator" rather than "indication." 

See issue #418  for a possible restructure of the tree so this is more clear for the user.

**Comment by samreid** [comment]
I renamed tandems for cueing indicator and other related (and some unrelated) tandems as we discussed with @catherinecarter @matthew-blackman and @marlitas today.

**Comment by marlitas** [comment]
Is this issue done and ready to close then?

**Comment by samreid** [comment]
@catherinecarter want to review the changes that were implemented during our mini-design meeting today?

**Comment by catherinecarter** [comment]
All of these look great. Closing.
