### ISSUE TITLE
Musical scale for soccer balls is off by one note

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#422]
It used to be 2 full octaves from 1 to 15, but now it seems everything is shifted by a whole note. That is, "1" sounds like a "D" in a c major scale.  Not sure why things went off.  Discovered in https://github.com/phetsims/center-and-variability/issues/420

**Comment by samreid** [comment]
Looks like a change was committed as part of https://github.com/phetsims/center-and-variability/commit/fc4421ff11d29daf7103d6388635e4745ae3d86f. @marlitas can you please take a look? Specifically, in NumberTone.ts, the notes were shifted by 1:

![image](https://github.com/phetsims/center-and-variability/assets/679486/fcbfe560-d924-42be-bd8f-c88007d3b0e6)

**Comment by marlitas** [comment]
@samreid We wanted the predict tool to play sounds between 0 and 1 since it has the ability to hit that range in the sim. I thought this was the proper way to implement but perhaps I messed something up. Let me know what should be done for that case.

**Comment by samreid** [comment]
I restored the original notes and added support for 0-1, can you please review?

**Comment by marlitas** [comment]
That looks great and clarifies what I got wrong on the original change. Thanks! Closing.
