### ISSUE TITLE
Some files have no documentation at the top

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#423]
We are getting closer to a code review and I noticed at least one file with no documentation at the top. We should spot check before starting code review.

**Comment by marlitas** [comment]
I'll tackle this one.

**Comment by marlitas** [comment]
Went through all the files in `center-and-variability` and `soccer-common` and added documentation where needed. I also based author tags off of the first few commits on the file in the git history. If any of that should be changed feel free to do so. Over to @samreid and @matthew-blackman for review.

**Comment by samreid** [comment]
Looks great to me, I went through each file and confirmed each has documentation at the top. I made minor updates. Closing.
