### ISSUE TITLE
Uninstrument Text and RichText

### ISSUE THREAD

**Issue by zepumph** [phetsims/center-and-variability#424]
In https://github.com/phetsims/phet-io/issues/1952#issuecomment-1664495275 we decided that we generally don't want to instrument Text nodes, and instead just want to focus on the stringProperties, especially if they are derived or pattern. 

- [x] Let's double check that sim code isn't instrumenting Texts unless there is a reason (like hiding the Text).
- [x] Let's also look for common code UI that needs to be generally updated to support this new PhET-iO instrumented decision. (For example Natural Selection dealt with NumberDisplay and OopsDialog)

**Comment by marlitas** [comment]
Went through and checked usages of Text to make sure we are only purposefully instrumenting for visibility purposes. That all looks good. Next up is checking in on common code UI.

**Comment by marlitas** [comment]
I'm not sure I understand the decision fully, but I see that AccordionBox instruments it's `titleNode` if one is not provided. We provide one in AccordionBox so it does not directly affect our sim, but is this an example of a common code situation where we would want to uninstrument?

I think either @zepumph or @samreid might be able to answer this.

**Comment by samreid** [comment]
I uninstrumented the QuestionBar.questionText since it provided no value. A client would just hide the entire question bar if they wanted to get rid of that.

For the readout texts, I observed some had visibleProperty elements, so could be turned on and off. Others were controlled by the code. For those, I added gated visibility properties so they could be turned off by the clients. But if I additionally uninstrument the Text, then those are no longer studio autodiscoverable (by mouseover):

```diff

Subject: [PATCH] Adjust the soccer ball group focus area based on the bottom of the accordion box, see https://github.com/phetsims/center-and-variability/issues/410
---
Index: js/variability/view/VariabilityAccordionBox.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/variability/view/VariabilityAccordionBox.ts b/js/variability/view/VariabilityAccordionBox.ts
--- a/js/variability/view/VariabilityAccordionBox.ts	(revision af01371020720a50b6470e7aeccb5d821c0d721d)
+++ b/js/variability/view/VariabilityAccordionBox.ts	(date 1691537143471)
@@ -233,7 +233,7 @@
         const madReadoutText = new VariabilityReadoutText( madEqualsValueStringProperty, {
           fill: CAVColors.madColorProperty,
           visibleProperty: createGatedVisibleProperty( model.isMADVisibleProperty, madReadoutTextTandem ),
-          tandem: madReadoutTextTandem
+          // tandem: madReadoutTextTandem
         } );
 
         // Nest in a new Node so that ToggleNode has independent control over the visibility

```

</details>

So is being able to autodiscover a text a good reason to leave it instrumented?

**Comment by samreid** [comment]
> As for the QuestionBar I believe we also wanted to instrument that text so that clients could change the question. But we should confirm with @catherinecarter.

I mentioned to @marlitas that you can still autoselect the string itself to change the text, and instrumenting the Text is not necessary to do that.

**Comment by samreid** [comment]
Here are the remaining instrumented TextIO and RichTextIO, 

centerAndVariability.medianScreen.view.playArea.numberOfKicksText
phetioEngine.ts:669 centerAndVariability.meanAndMedianScreen.view.playArea.numberOfKicksText
phetioEngine.ts:669 centerAndVariability.variabilityScreen.view.variabilityMeasureAccordionBox.valueReadouts.medianReadoutText
phetioEngine.ts:669 centerAndVariability.variabilityScreen.view.variabilityMeasureAccordionBox.valueReadouts.meanReadoutText
phetioEngine.ts:669 centerAndVariability.variabilityScreen.view.playArea.numberOfKicksText

We agree all of those should be instrumented, for autoselect and so the PhET-iO Studio Client can change the visibility.  Closing.

**Comment by catherinecarter** [comment]
Reopening. Looks like we missed a couple that will need to be uninstrumented (the bottom two have dependencies pointing to the string):
- centerAndVariability.medianScreen.view.distanceAccordionBox.cardNodeContainer.medianReadoutText.visibleProperty
- centerAndVariability.meanAndMedianScreen.view.plotAccordionBox.meanReadoutStringProperty
- centerAndVariability.meanAndMedianScreen.view.plotAccordionBox.medianReadoutStringProperty

**Comment by samreid** [comment]
Can you join us on the blue zoom? The latter two are String, not Text.  The top one is a Text we agreed should remain instrumented.

**Comment by samreid** [comment]
In discussion, we agreed to uninstrument the medianReadoutText.visibleProperty, but we discovered that in https://github.com/phetsims/studio/issues/304 that the PatternStringProperty much be phet-io instrumented.

**Comment by samreid** [comment]
OK we uninstrumented that, closing.
