### ISSUE TITLE
Add in Global Characters

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#425]
This is a follow up from https://github.com/phetsims/center-and-variability/issues/408. The infrastructure is ready and we are now waiting on assets to complete the implementation of Global Characters. Assigning @mariahmaephet and marking as an artwork issue until assets are ready.

**Comment by samreid** [comment]
@catherinecarter will work with @amanda-phet to normalize the characters in the artboards.

**Comment by catherinecarter** [comment]
Done! 

https://github.com/phetsims/soccer-common/issues/3

**Comment by catherinecarter** [comment]
Added the kickers for Africa and Africa modest for the Variability screen (kickers with numbered jerseys). Description for order is in #523.

**Comment by marlitas** [comment]
This work is now being tracked in #523. Closing.
