### ISSUE TITLE
0.0 deviation dot in front of Mean Line

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#427]
In the MAD Info dialog any dots that sit on the mean should be in front of the Mean Line instead of behind. 

![image](https://github.com/phetsims/center-and-variability/assets/42476338/b7c2f287-7721-4155-a875-6b3afba0a195)

**Comment by catherinecarter** [comment]
The dot looks great in front. Thanks!

**Comment by samreid** [comment]
Taking a look at the code

**Comment by matthew-blackman** [comment]
Thanks @samreid! The updated ariable names look great and glad to see that we didn't need those visibility calls. Design feedback looks good as well - closing!

**Comment by samreid** [comment]
@catherinecarter observed that the lines are going in the wrong direction in the accordion box after this commit.  @matthew-blackman can you please take a look?
