### ISSUE TITLE
Sound should play on ALL keyboard input for soccer balls

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#428]
Anytime a soccerBall moves via keyboard input we should here the corresponding sound. Right now this is not being triggered by the number keyboard shortcuts, or page up, page down, home, and end.

**Comment by samreid** [comment]
I'll take a look

**Comment by samreid** [comment]
Fixed, and it was straightforward. However, I observed that there is no action for pgup/pgdwn. I'll open a side issue for that. Closing.
