### ISSUE TITLE
Unexpected sounds in studio tree when setting a value

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#429]
When I set the value of the predict median/mean, the pointer, or either handle of the interval tool, I hear the sound of the number line location even when the checkbox is not checked. 

Is it possible to only play a sound when setting the value when the checkbox is active? Otherwise, no sound is played?

**Comment by samreid** [comment]
In today's discussion, we agreed it is not a good cost-benefit analysis to spend time muting those sounds when controlling it from studio. There may be a listener order dependency for when sounds are played when the checkbox is checked.  Closing.
