### ISSUE TITLE
Unexpected `private static readonly enumeration` occurrences

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#431]
Unexpected `private static readonly enumeration` occurrences observed in https://github.com/phetsims/center-and-variability/issues/374 (including in the soccer-common repo). Should those be public or eliminated?

**Comment by samreid** [comment]
Fixed. @marlitas can you please spot check at your convenience?

**Comment by marlitas** [comment]
I'm very confused... some of the ones you hit aren't in center-and-variability or soccer-common. I see occurrences that you hit in: joist, cck, bending light, phet-core... Should we make an issue about this in each of those repos and hit the changes there?

I also am unclear why these should be public if they're not being used outside of the class? I see that it's instantiating an enumeration, but I don't see it being used anywhere...

**Comment by marlitas** [comment]
Discussed with @samreid and @matthew-blackman and we are ready to close.
