### ISSUE TITLE
Small MAD deviations show as 0.0 but do not appear as a dot

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/center-and-variability#432]
See screenshot below. This is being caused by the way that MADNode is checking to see if a zero dot should be drawn. Currently this is based on the length of the deviation line, but should be using the deviation value to make sure that a dot always shows up when the value is 0.0.

![Screen Shot 2023-08-08 at 10 12 35 AM](https://github.com/phetsims/center-and-variability/assets/108756567/78ac95ae-48cc-4966-92d4-360f29e5e6ef)

**Comment by matthew-blackman** [comment]
I implemented this so that a dot always appears when the deviation value rounds to zero, but there are still some oddities. For example, if the deviation rounds to zero but is something like 0.04 the MAD plot looks like this:
![Screen Shot 2023-08-08 at 10 30 09 AM](https://github.com/phetsims/center-and-variability/assets/108756567/9e2f289e-355e-466e-aa7f-45b7ae78388d)

In this case, should we be showing small line segments instead of dots for the small deviations? If we use dots, should we force them to be on the mean line even if the deviation is nonzero but still rounding to zero? So many questions. Will check in with @catherinecarter.

**Comment by catherinecarter** [comment]
After thinking about this, I feel it's better to not force the mean to snap to the rounded value, which would then naturally point to whether the deviations should snap to the rounded value. I think it's better to visually show more precision while keeping the numerical value rounded to the nearest 10th. That said, let's go with the example below, where the rounded deviations that are 0.0 show a small horizontal line as the deviation. 

<img width="466" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/7efd6044-d8c5-47a3-bc53-e072d89fc853">
