### ISSUE TITLE
Change name of bottomCheckBoxGroup to checkboxGroup in playArea

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#434]
Another name change, please. In the playArea folder, the checkboxGroup starts with `bottomCheckboxGroup`. Since this is in the playArea folder, the word, 'bottom' is not needed. 

Please rename to `checkboxGroup` to be consistent with the naming of this group in the accordion box folder. Thanks!

**Comment by samreid** [comment]
Fixed, good idea @catherinecarter. Closing.
