### ISSUE TITLE
Change meanVisibleProperty to isMeanVisibleProperty

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#436]
I noticed there was a boolean property in the model that should have an 'is' as a prefix:

`centerAndVariability.meanAndMedianScreen.model.plotAccordionBox.meanVisibleProperty`

Thanks!

**Comment by samreid** [comment]
I'll work on this

**Comment by samreid** [comment]
Fixed and pushed, seemed straightforward, closing.
