### ISSUE TITLE
Should there be soccer ball movement action for pgup/pgdwn?

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#437]
https://github.com/phetsims/center-and-variability/issues/428 said:

> number keyboard shortcuts, or page up, page down, home, and end.

We support numbers, home and end, but not yet page up and down.  Should we add that? How many steps should they move? It will be easy to implement.

**Comment by catherinecarter** [comment]
Yes, let's support that and have the increment be by 3's.

**Comment by samreid** [comment]
I added page up and page down for soccer balls, @catherinecarter can you please test/verify? Please close if it is working as expected.

**Comment by catherinecarter** [comment]
Working very well. Great! Closing.
