### ISSUE TITLE
Add page up/down home/end keyboard navigation to the cards on Median screen

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#441]
Being able to move the soccer balls by jumping to the front/back, and jumping a few number line positions with page up/down made me wish we had similar functionality on the cards. 

Can we add page up/down (to move the card three positions right/left), and jump to the beginning/end (with home/end) to the cards?

**Comment by marlitas** [comment]
This has been implemented above. Ready for review from @catherinecarter and @samreid.

**Comment by catherinecarter** [comment]
It's working for me! It's great to be able to move the card to the front and back right away. Thanks!

**Comment by marlitas** [comment]
@samreid I'm actually not sure how to read this... I'm confused by the use of `includes`. Can you explain the following syntax to me?

```js
[ 'arrowRight', 'arrowLeft' ].includes( keysPressed ?? '' )
```

I didn't know you could pass an array to includes... but it seems like the double question marks are doing something to help with that?

**Comment by samreid** [comment]
`keysPressed` is not an array, it is a `string | null`. The nullish coalescing operator was to satisfy the type checker. Without it, tsc says `TS2345: Argument of type  string | null  is not assignable to parameter of type  string `. Alternatively, we could use `const keysPressed = listener.keysPressed!;` or `if ( keysPressed==='arrowRight' || keysPressed==='arrowLeft'){`

**Comment by samreid** [comment]
We discussed the above comment and agreed @samreid would reapply the patch and commit.  I'll send back to @marlitas for a spot check and testing at runtime after committing.

**Comment by samreid** [comment]
Today @jessegreenberg and @zepumph hypothesized that the `keysPressed` may be null if it is fired on a cancel. However, we checked the implementation and it doesn't appear to be fired on a cancel. @jessegreenberg were we going to create an issue about this?

**Comment by jessegreenberg** [comment]
No, I think null is correct for that one. It may not be null during the callback but the keysPressed instance variable on the KeyboardListener will often be null.

**Comment by samreid** [comment]
Oh right, thanks for reminding me.  Could we add a `keysPressed` option to the callback that is non-null?  Instead of 

```ts
      callback: ( event, listener ) => {

        const keysPressed = listener.keysPressed;
        if (keysPressed!==null){//...etc}
```

Something like:

```ts
      callback: ( event, listener,keysPressed ) => { // here keysPressed is non-null
```

**Comment by jessegreenberg** [comment]
Sure, Ill make an issue.

**Comment by samreid** [comment]
This issue has been implemented and reviewed, @marlitas approved the changes from the review, and I reworked them for main and committed them. I opened a new issue for a bug that was discovered. @jessegreenberg said he would open an issue for the `keysPressed` listener, so I think this issue can be closed.
