### ISSUE TITLE
Improvements for randomSkew

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/center-and-variability#444]
It seems like the current interface of the 'randomSkew' distribution type is a bit limited, and I wonder if it can be improved. Currently the initial value of the skew can be set via the API, but the sim chooses a random skew when the sim is reset. This is a bit odd to me for two reasons:

1) Why would a player's kick distribution change when the sim is reset? Wouldn't the skew be a property of that player's kicking tendency?
2) Why would a designer want to pre-set the initial skew if it would just be randomized when a user hits reset?

I could be missing something, but I think we could allow for more flexibiity if we gave designers the ability to select a left or right skew which do not change on reset, OR select a random skew. It might even be worth considering whether the "randomize on reset" behavior could be parametrized as well, or at least discussing why it is the default.

The updated type might look something like this:
```
type DistributionType = 'probabilityByDistance' | 'distanceByIndex' | 'skewed';
...
skewType: 'left' | 'right' | 'random' | null;
```

Would like to discuss with @catherinecarter @marlitas @samreid.

**Comment by samreid** [comment]
We implemented this together. @matthew-blackman will take a look.

**Comment by matthew-blackman** [comment]
This is looking great! Nice improvement to the distributionType API. Closing.
