### ISSUE TITLE
Specify phetioFeatured

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#445]
I think @catherinecarter said she was working with @arouinfar to define the `phetioFeatured` elements.

**Comment by catherinecarter** [comment]
Indeed! There is a new Heading in the PhEt-iO design doc with the overrides. Perhaps you can help me know where to put them to make it easier to access/read. Thanks!

**Comment by samreid** [comment]
I'll start on this.

**Comment by samreid** [comment]
OK I moved these into the code. Some implementation and design questions came up, mainly listed as TODOs in the code. Also, there were patterns in the specification where one value was shown, like "instrument screen1.somethingProperty" and I took that to mean "instrument all occurrences of somethingProperty", not just in screen 1.  So if there were places where it was intended to be featured in one place and not featured in another, we will have to refine that.

**Comment by catherinecarter** [comment]
Everything looks great. I don't see anything missing. Looks good from my end!

**Comment by samreid** [comment]
Thanks @catherinecarter. This issue was straightforward and doesn't require code review. Closing.

**Comment by samreid** [comment]
The 2 properties listed above are in common code.

First, the screen.isActiveProperty is a read-only boolean that indicates whether a screen is visible. The preferable way for a client to deal with knowing which screen is active is to use: `centerAndVariability.general.model.screens.selectedScreenProperty` which is featured.  

Second, the screen.view.visibleProperty is similar, it is a read-only boolean property, and the client should be using `centerAndVariability.general.model.screens.selectedScreenProperty` instead. Therefore I recommend to remove those overrides. If we want to feature those, we should do it in common code for all screens across all simulations (or possibly just for all simulations with N>=2 screens).  I'll commit this now and reach out to @arouinfar and @catherinecarter to double check.

**Comment by arouinfar** [comment]
> Therefore I recommend to remove those overrides. 

Good catch @samreid, I agree. Those look like mistakes in the overrides. Using `selectedScreenProperty` (which is already featured) is preferable.

**Comment by samreid** [comment]
Thanks, I removed those above. Closing.
