### ISSUE TITLE
Address 26 TODOs in code

### ISSUE THREAD

**Issue by chrisklus** [phetsims/center-and-variability#45]

**Comment by chrisklus** [comment]
@samreid and I decided to remove this from the milestone since we won't be able to address all the TODOs in time for the prototype. We are taking RC shas now.

**Comment by marlitas** [comment]
There are 68 TODO's left as of 4/20/23.

**Comment by samreid** [comment]
Many of the a11y view TODOs are listed in https://github.com/phetsims/chipper/issues/916 and it seems unlikely that we would address them for this milestone.  So from here on, omit the TODOs in the a11y view?

**Comment by zepumph** [comment]
Thanks for the ping, there is no reason that a11y-view, low-priority improvements should get in the way of CAV development. Also it is awkward to have TODOs leaking into every sim repo with alt input. So I remove them upon generation over in https://github.com/phetsims/chipper/issues/916

**Comment by samreid** [comment]
From today's discussion:

* We would like to associate remaining TODOs with issues
* We would like to leave the TODOs in the code (not worrying about double counting).
* Once each TODO has an issue and the lint rule is turned on, this issue can be closed.
