### ISSUE TITLE
For the Interval Tool, it is confusing to have "enabledProperty" not gray it out, so we want to use "inputEnabledProperty" instead

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#450]

**Comment by samreid** [comment]
We renamed the model property, but still want to try to rename the linked element too:

![image](https://github.com/phetsims/center-and-variability/assets/679486/b1ccc014-4d61-4296-a281-ca9ea317da4e)

**Comment by samreid** [comment]
In the commit, I switched to using the `inputEnabledProperty` instead of the `enabledProperty`. It seems OK to me in studio usage. @catherinecarter will you please test?  Close if all is well.

**Comment by catherinecarter** [comment]
Looks great. Thanks for update, I think it's more clear what the toggle does to the tool now. Thank you! Closing.
