### ISSUE TITLE
InteractiveHighlight should be dashed when cards and balls are grabbed with mouse.

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#451]
Split off from: https://github.com/phetsims/center-and-variability/issues/406

We would like the interactiveHighlight to match the keyboard highlight behavior. When a card or ball is grabbed with the mouse, the highlight should become dash.

**Comment by marlitas** [comment]
In https://github.com/phetsims/center-and-variability/issues/459 we decided not to use GrabDragInteraction

**Comment by marlitas** [comment]
The dashing has been applied in the above commits. SoccerBallNode followed the same convention as CardNode, so I believe all that remains is design sign off. Over to you @catherinecarter!

**Comment by catherinecarter** [comment]
Working as expected on both the soccer balls and the cards on the Median screen. Good from my end.
