### ISSUE TITLE
Memory Test 8/12/23

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#452]
For code review.

**Comment by marlitas** [comment]
Fuzzing PhET-iO brand:

<img width="179" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/ad67c491-1a46-485e-8ad6-c32f4686ae7b">

**Comment by marlitas** [comment]
Fuzzing PhET brand:

<img width="193" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/21888cb8-dbd6-4f95-80be-f114e9903f49">

**Comment by samreid** [comment]
That is a bit on the high side, but it doesn't appear to be a leak.

**Comment by samreid** [comment]
By the way, the built version memory snapshot is 111MB (this reported for PhET brand), so is much more acceptable.

![image](https://github.com/phetsims/center-and-variability/assets/679486/d3cf6caf-ce59-4f33-9dae-36c1f72fab5e)
