### ISSUE TITLE
Data values not accurate with shuffled listeners

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#455]
From #449, I noticed that the data values in the readout and the visual representations aren't matching. This example is from the second screen, but should be fixed in all three. 

<img width="1043" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/223ebb07-105d-4fef-b17a-5bbb6ddac644">

**Comment by samreid** [comment]
I do not have a good understanding of why there is a listener order dependency, but I determined the subset of Property instances that can use `hasListenerOrderDependencies: true` to give the correct behavior.  @marlitas can you please review and test?

**Comment by marlitas** [comment]
Tested on my side. The way these values are updated is complex, so i think identifying them as having listerOrderDependencies makes sense. Thanks @samreid.
