### ISSUE TITLE
IntervalTool body does not display pointer area

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#456]
When using the query parameter `showPointerAreas` the IntervalTool body does not display a pointer area. It is still draggable, so I'm not sure if this is a problem with the code or a problem with how the pointer area visibility is working? 

<img width="623" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/60ad7f2b-af22-494f-b0e6-901db1d3f620">

**Comment by samreid** [comment]
?showPointerAreas only shows custom (non-default) pointer areas, so I think this issue can be closed.

**Comment by samreid** [comment]
@marlitas @matthew-blackman and I discussed this, and it seems good to close.
