### ISSUE TITLE
Add/change documentation to studio tree

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#457]
Please add or change the documentation in the studio tree. Thanks!

- [x] `meanAndMedianScreen.model.playArea.soccerBallDragIndicatorModel.dragIndicatorValueProperty`
   - Sets the location of the hand/arrow on the number line. If one or more soccer balls exist at that location, the indicator appears on the topmost ball.  
   
- [x] `meanAndMedianScreen.model.plotAccordionBox.isDataPointLayerVisibleProperty`
   - Sets the visibility of the entire set of data points in the accordion box.
   
- [x] `model.sceneModel.numberOfDataPointsProperty` (all three screens (six instances))
   - Indicates the number of soccer balls on the field.
   
- [x] `variabilityScreen.model.selectedSceneModelProperty`
   - Indicates which kicker is active by jersey number.
   
- [x] `variabilityScreen.model.variabilityMeasureAccordionBox.isRangeVisibleProperty`
   - Sets the visibility of the range. Only relevant when the range radio button is active. 
   
- [x] `variabilityScreen.model.variabilityMeasureAccordionBox.isIQRVisibleProperty`
   - Sets the visibility of the IQR. Only relevant when the IQR radio button is active. 
   
- [x] `variabilityScreen.model.variabilityMeasureAccordionBox.isMADVisibleProperty`
   - Sets the visibility of the MAD. Only relevant when the MAD radio button is active. 
   
- [x] `variabilityScreen.model.playArea.intervalTool.isEnabledProperty`
   - When false, the interval cannot be translated left/right, but the handles are still moveable/interactive. 
   
- [x] `variabilityScreen.view.playArea.intervalToolNode.handle1.selfVisibleProperty` and `variabilityScreen.view.playArea.intervalToolNode.handle2.selfVisibleProperty`
   - Sets the visibility of the interval tool handle. When false, the corresponding side of the interval tool cannot be used to change the range.

**Comment by samreid** [comment]
I'll work on this.

**Comment by samreid** [comment]
I addressed the above recommendations. I noted that 2 or so notes in the specification did not match the current simulation value. For instance: `meanAndMedianScreen.model.playArea.soccerBallDragIndicatorModel.dragIndicatorValueProperty` was renamed to `...dragIndicatorModel.valueProperty` and `intervalTool.isEnabledProperty` became `inputEnabledProperty`. 

That being said, I updated each of the documentations accordingly. @catherinecarter could you please spot check in studio?
