### ISSUE TITLE
Median not showing when checkbox is checked prior to any kicks

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#458]
When I was taking screenshots in preparation for publishing, I noticed that when I activated the median checkbox prior to kicking, the median did not appear in the accordion box. When I unchecked and rechecked the checkbox, the median appeared, and when I used the eraser to zero kicks were in the playing field, the median appeared on the first kick.

See screenshots below where I was able to duplicate the bug multiple times.

![Center and Variability screenshot (4)](https://github.com/phetsims/center-and-variability/assets/109630002/49029d66-e825-4dd5-ae99-e41ee047b627)
![Center and Variability screenshot (5)](https://github.com/phetsims/center-and-variability/assets/109630002/d0b6a341-c2cc-443a-94be-26626c5d543c)

**Comment by samreid** [comment]
I'll investigate

**Comment by samreid** [comment]
Fixed in the commit, @matthew-blackman or @marlitas can you please code review? @catherinecarter can you please test/verify?

**Comment by matthew-blackman** [comment]
I am still able to reproduce the issue when doing the following steps:

- Open screen 2
- Check 'Median' in accordion box
- Kick soccer balls

For me this causes the median bracket to appear in the accordion box with no arrow. See screenshot:
<img width="1154" alt="Screen Shot 2023-08-16 at 9 01 01 AM" src="https://github.com/phetsims/center-and-variability/assets/108756567/6d974f37-0c49-4011-88f5-6d9c9bd9e24a">

I will investigate further.

**Comment by matthew-blackman** [comment]
I pushed a small refactor above which makes the phet io state-setting logic a bit more clear. Having issues pulling the latest commits, so reassigning to @marlitas for now.

**Comment by catherinecarter** [comment]
This bug is fixed! Closing.
