### ISSUE TITLE
Review of pointer areas

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/center-and-variability#462]

**Comment by samreid** [comment]
In #461 @matthew-blackman reported:

> Some pointer areas are very small and difficult to hit on mobile. Specifically the kick buttons, the info button in the accordion box, and the prediction sliders were challenging to interact with.

**Comment by catherinecarter** [comment]
Let's increase the pointer areas around the following components: 
- [ ] info button 
   <img width="68" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/840cb900-bc52-4ad7-8d63-1cafeaf44122">

- [ ] eraser button  
   <img width="154" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/906b3561-6f57-47e2-ab62-6f4cbd8a7edc">

- [ ] kick buttons   
   <img width="110" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/70193082-03c4-49a5-a293-cba95d52af7a">

- [ ] variability radio buttons 
   <img width="76" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/404e03ae-de5d-460e-bf65-19b5b705d246">

- [ ] kicker buttons 
   <img width="87" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/ccb91c5f-a5f6-4aeb-9861-c52e247a0314">

- [ ] accordion box: variability measure checkbox
   <img width="174" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/74121413-43fa-47a7-ade7-0913fe9f7e97">

- [ ] close info dialog x
   <img width="60" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/7df040e0-af81-484b-858e-33e35bbf6464">

**Comment by samreid** [comment]
Note for who works on this issue: This is just to increase the touch area. The mouse area should remain well-fitted to the object as it is.

**Comment by samreid** [comment]
I'll take a look

**Comment by samreid** [comment]
All fixed, except the RadioButtonGroup ones are broken due to a common code bug. I'll open an issue for that.

**Comment by samreid** [comment]
Looks good with the proposed patch, but the patch may disrupt other code. So I may need help. But it looks like this with the patch:

![image](https://github.com/phetsims/center-and-variability/assets/679486/cea79252-65c0-4129-94a4-a38f616ef795)

**Comment by samreid** [comment]
OK all done except for the radio buttons. @catherinecarter can you please characterize the importance of changing the radio button pointer areas? It will likely require coordination with @jonathanolson and @jessegreenberg.

**Comment by samreid** [comment]
In today's discussion, we agreed the radio buttons are not blocking for this sim since the radio buttons are large enough. We will reduce the clear button touch area slightly.
