### ISSUE TITLE
Build artifacts are comparatively large

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#464]
For code review #447 ...

> - [ ] Does the html file size seem reasonable, compared to other similar sims?

center-and-variablility (9306 loc) + soccer-common (2551 loc) = 11857 loc.  The size of the built html files is:

```
-rw-r--r--  1 cmalley  staff  36612714 Aug 18 08:22 center-and-variability_all_phet_debug.html
-rw-r--r--  1 cmalley  staff   7688835 Aug 18 08:22 center-and-variability_en_phet.html
```

For comparison, equality-explorer is 13563 loc. The size of its built html files is:

```
-rw-r--r--  1 cmalley  staff  25165566 Aug 18 08:25 equality-explorer_all_phet_debug.html
-rw-r--r--  1 cmalley  staff   2645383 Aug 18 08:25 equality-explorer_en_phet.html
```

Why is CaV so much larger? The `en_phet.html` is almost 3x larger. It's probably due to sound and image files, but I wanted to make sure.

**Comment by samreid** [comment]
The soccer images *.ts files alone are 4,891,080 bytes (before minimization). The sim will get even bigger once https://github.com/phetsims/center-and-variability/issues/425 artwork is complete.

**Comment by pixelzoom** [comment]
So it sounds like this is expected. Feel free to close if there's nothing that can be done to reduce size.

**Comment by samreid** [comment]
@matthew-blackman and @marlitas and I discussed it and we feel the images are the main reason here, closing.

**Comment by samreid** [comment]
On second thought, @matthew-blackman discovered that the images themselves are likely larger than necessary. We would like to try reducing this.

**Comment by samreid** [comment]
We will continue in https://github.com/phetsims/center-and-variability/issues/498, closing.
