### ISSUE TITLE
Avoid using concatenation to create strings that will be visible in the user interface

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#465]
For code review #447 ...

>  - [ ] Avoid using concatenation to create strings that will be visible in the user interface. Use `StringUtils.fillIn` and a string pattern to ensure that strings are properly localized.

I see concatentation used in 2 places, see below.  This may be an acceptable exception to this code-review item -- up to you.  I'd be fine with adding a comment and closing.

```ts
// MeanAndMedianInfoNode.ts
       numeratorText.string = values.join( ' + ' );

// MADInfoNode.ts
      numeratorText.string = deviations.map( deviation => Utils.toFixed( deviation, 1 ) ).join( ' + ' );
```

**Comment by samreid** [comment]
What is the reason for this code review recommendation? Is there a StringUtils.fillIn equivalent that supports a variable number of terms?

**Comment by pixelzoom** [comment]
I believe the reason for the code review item is to avoid creating hardcoded ordering dependencies that should be translatable.  I'll add that info to the template.   

If that's not relevant here, feel free to close.

**Comment by samreid** [comment]
Since we will not localize the summations e.g., "1+3+4", I feel this issue can be closed.
