### ISSUE TITLE
Revise soccer-common README.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#466]
For code review #447 ...

> - [ ] For simulations, was the README.md generated by `grunt published-README` or `grunt unpublished-README`? Common code repos can have custom README files.

soccer-common currently has the default  `grunt unpublished-README`, which is not appropriate for a common-code repo.   See density-buoyancy-common/README.md for an example.

**Comment by samreid** [comment]
I'll work on this, thanks!

**Comment by samreid** [comment]
I updated the text. I also referred to "Mean:Share and Balance" which doesn't currently use it, but will use it soon.  @pixelzoom can you please review? Close if all is well.

**Comment by pixelzoom** [comment]
👍🏻
