### ISSUE TITLE
Notify Translators that some translations will be lost next time CAV is published

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#467]
Similar to https://github.com/phetsims/gravity-force-lab/issues/166 and based on decisions in https://github.com/phetsims/center-and-variability/issues/373#issuecomment-1674859913 and below, some of the translated strings will be lost when we move from "prototype" to "full release".

This copied comment applies here as well:

> While we had originally considered trying to move the translated strings too, it turned out to be too complex to make it worthwhile.  The consequence will be that the next time the Gravity Force Labs simulation is published off of master, some of the strings that were previously translated by the trusted translators will revert to English in the translated versions.  Therefore, **The next time this sim is published off of master, we need to notify translators that their translation needs to be updated.**

**Comment by marlitas** [comment]
There is no work to be done prior to publication here, so adjusting the title of the issue to reflect that this is a reminder to notify translators

**Comment by marlitas** [comment]
@oliver-phet is doing sending out the email. Assigning over to him, feel free to close when all is done!

**Comment by oliver-phet** [comment]
Email sent, closing!
