### ISSUE TITLE
Regenerate center-and-variability README.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#468]
For code review #447 ...

> - [ ] For simulations, was the README.md generated by `grunt published-README` or `grunt unpublished-README`? Common code repos can have custom README files.

The README.md is currently the output of `grunt published-README`. I wasn't sure if that was appropriate yet.  According to @samreid in Slack#DM:

> README accidentally overwritten in https://github.com/phetsims/center-and-variability/commit/029c5a203c077a10c0a04fa8676334e104789eed

**Comment by samreid** [comment]
I ran `grunt unpublished-README`, @pixelzoom can this issue be closed?

**Comment by pixelzoom** [comment]
👍🏻
