### ISSUE TITLE
Fix `colorName` for `skyGradient*ColorProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#469]
For code review #447 ...

In CAVColors.ts:

```ts
  // sky gradient, sampled from a screenshot
  skyGradientTopColorProperty: new ProfileColorProperty( centerAndVariability, 'skyGradientTop', { default: '#365b9b' } ),
  skyGradientMiddleColorProperty: new ProfileColorProperty( centerAndVariability, 'skyGradientMiddle', { default: '#81b5ea' } ),
  skyGradientBottomColorProperty: new ProfileColorProperty( centerAndVariability, 'skyGradientBottom', { default: '#c9d9ef' } ),
```

The `colorName` argument for these 3 instances is missing the "Color" prefix that is used for other instances in this file. For example,  'skyGradientTop' should be  'skyGradientTopColor'.

**Comment by samreid** [comment]
I'll work on this, thanks!

**Comment by samreid** [comment]
Renamed, tested in the sim and in the color editor. @pixelzoom can you please review? Close if all is well.

**Comment by pixelzoom** [comment]
👍🏻
