### ISSUE TITLE
More documentation in CAVColors.ts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#470]
For code review #447 ...

A bit more documentation seems useful in CAVColors.ts.  Some of these color names are not obvious or are very general -- `pointerColorProperty`, `rangeFillProperty`,...

**Comment by samreid** [comment]
I added 2 commits with documentation. @marlitas and @matthew-blackman can you please skim the colors file and see if others warrant any/more documentation?

**Comment by marlitas** [comment]
Looks good. I added a bit more documentation for some of the obscure names. I feel this is ready to close.
