### ISSUE TITLE
Should PhetColorScheme be used anywhere? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#471]
For code review #447 ...

> Is [PhetColorScheme](https://github.com/phetsims/scenery-phet/blob/master/js/PhetColorScheme.ts) used where appropriate? Verify that the sim is not inventing/creating its own colors for things that have been standardized in PhetColorScheme. Identify any colors that might be worth adding to PhetColorScheme.

I don't see any use of PhetColorScheme.  I do see some red object that would typically be PhetColorScheme.RED_COLORBLIND.   So creating this issue to verify whether PhetColorScheme should be used.

**Comment by samreid** [comment]
@catherinecarter do you think any of the colors for the sim should use any of the values from https://github.com/phetsims/scenery-phet/blob/master/js/PhetColorScheme.ts ?

**Comment by catherinecarter** [comment]
I checked the colorblind test and all colors pass for all types of colorblindness. @amanda-phet designed the original red and also colorblind-proofed the red to ensure it passes. The red color in the existing sim shows better against the ground in the tests than the PhET colorblind red.

For reference, here's a visual equivalent for the color scheme: https://docs.google.com/document/d/1K7SLrK2_rAugnC1IdRbeLwcUShP0rVdARNZdk-OkY50/edit#heading=h.y1wn8jx7bgs8
