### ISSUE TITLE
Why does soccer-common need `screen.name` string?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#472]
For coe review #447 ...

Why is this needed in soccer-common-strings_en.json?  And if it is needed, the key should be `screen.soccerCommon`.

```ts
  "screen.name": {
    "value": "Soccer Common"
  },
```

**Comment by samreid** [comment]
Thanks, I removed that unused string and also the title in the commits. Is that correct? Please close if all is well.

**Comment by pixelzoom** [comment]
👍🏻
