### ISSUE TITLE
Change a few string keys to improve discoverability in Studio?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#473]
For code review #447 ...

> - [ ] Make sure the string keys are all perfect.  ...

String keys are generally excellent for center-and-variability and soccer-common, nice job.

In center-and-variability, I'm wondering about these 3 keys:

```
  "medianQuestion": {
    "value": "What is the typical kick distance?"
  },
  "meanAndMedianQuestion": {
    "value": "How does each kick influence the mean and median?"
  },
  "variabilityQuestion": {
    "value": "How spread out are the kick distances?"
  },
```

The key names are consistent with each other -- 1 question per screen --  but not related to the values. With the goal of making string Properties easily "discoverable" in Studio, perhaps these keys should be changed?  You might want to consult with @arouinfar, since she is the PhET-iO designer with the most experience in this area.

**Comment by samreid** [comment]
In my opinion, these strings should be discovered via studio autoselect. That being said, this is the best time to make sure the key names are what we want since they are difficult to change later. @catherinecarter or @arouinfar what do you recommend?

**Comment by catherinecarter** [comment]
Each question bar is currently named by the screen name, which seems to be a good naming scheme. Since all questions are auto-selectable, they seem fairly easy to find. I can see a reason for naming them all with "questionMedian" for example, but I think it's ok to leave as is to minimize changes.
@arouinfar feel free to override if you feel differently.

**Comment by arouinfar** [comment]
@pixelzoom raises a good point, as it's generally recommended for the sting key to match the string used in the sim. However, I think this is a bit of an edge case.  The question strings are quite lengthy and would be cumbersome as string keys. I think the current naming convention sounds reasonable, as is leveraging autoselect to find them in Studio.

> @arouinfar feel free to override if you feel differently.

No need, let's close.
