### ISSUE TITLE
Duplicated method of sorting cards in CardContainerModel.ts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#475]
For code review #447 ...

In CardContainerModel.ts, the method of sorting cards is duplicated in 2 places, so seems to be worth factoring out:

```ts
    const sorted = _.sortBy( this.getCardsInCells(), card => card.soccerBall.valueProperty.value );
```

The name `sorted` could also be improved -- it sounds like a boolean. Perhaps `sortedCards`?

**Comment by samreid** [comment]
I'll start on this one

**Comment by samreid** [comment]
Thanks, proposed fix in the commits. @pixelzoom can you please review?

**Comment by pixelzoom** [comment]
👍🏻
