### ISSUE TITLE
Reconsider `playAreaTandem`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#477]
For code review #447 ...

In CAVScreenView.ts

```ts
  protected readonly playAreaTandem: Tandem;
```

In ScreenView.ts:

```ts
  protected readonly pdomPlayAreaNode: PlayAreaNode;
```

For better or worse, PDOM has appropriate the term "play area".  So I would avoid using it in cases like `playAreaTandem`.

**Comment by samreid** [comment]
Perhaps the comment means "has appropriated"? @matthew-blackman and @marlitas what do you recommend to do here?

**Comment by pixelzoom** [comment]
Also recommended to rename PlayAreaCheckboxFactory, isPlayAreaMeanVisibleProperty, isPlayAreaMedianVisibleProperty, playAreaNumberLineNode, etc.

**Comment by samreid** [comment]
Assigning @catherinecarter since she advocated for the term "play area" in these cases. @matthew-blackman and @marlitas feel "Soccer Field" would be an appropriate alternative. @catherinecarter what do you think?

**Comment by catherinecarter** [comment]
Oh yes, if PDOM already uses the phrase, let's definitely change it to avoid confusion. Would just "Field" be ok? For some reason, "soccer field" seems to point my focus to just the number line and balls. The checkboxes, kick buttons, player choice (screen 3) are outside the soccer field, but for some reason seem to be within a more generic "field." 

I'm open to other ideas, but that's what my initial thought was.

**Comment by samreid** [comment]
I also opened https://github.com/phetsims/center-and-variability/issues/499 about another issue I observed regarding the PDOM play area.  Not sure about "field". It would show up in tandems like: 

```
centerAndVariability.variabilityScreen.view.field.checkboxGroup
```

Should we discuss something like `soccerArea` instead of `playArea`? The main thing is to distinguish it from the accordion box and charts.

**Comment by catherinecarter** [comment]
Let's discuss today during or right after standup. `soccerArea` or `fieldArea` might work.

**Comment by catherinecarter** [comment]
`soccerArea` it is!

**Comment by samreid** [comment]
Fixed, closing.
