### ISSUE TITLE
Address `REVIEW` comments

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#479]
For code review #447...  This issue will be a catch-all for commiting `REVIEW` comments.

**Comment by samreid** [comment]
@matthew-blackman volunteered to take a first look, thanks!

**Comment by pixelzoom** [comment]
I see that @matthew-blackman assigned this back to me for review. But I'm not sure what the status is, or what he'd like reviewed. @matthew-blackman ?

**Comment by matthew-blackman** [comment]
Sorry, I should have been more clear. I added documentation for each of the sites marked //REVIEW. The reason I assigned back to you was to check if the documentation sounded clear and concise from the reviewer's POV. Would you prefer that I review with the other devs before doing this?

**Comment by pixelzoom** [comment]
Thanks for clarifying. I'll take a look later this evening.  Up to you whether you'd like @samreid and @marlitas to have a look, but it would be best if that happens before I review.

**Comment by matthew-blackman** [comment]
Sound good - will reassign you when we have completed the dev review of the added documentation.

**Comment by samreid** [comment]
@matthew-blackman, @marlitas and I reviewed your changes in center-and-variability and everything is looking really great. Would you like to continue in the soccer-common repo?

**Comment by matthew-blackman** [comment]
Review comments have been addressed in soccer-common.

**Comment by samreid** [comment]
All review comments addressed, @pixelzoom would you like to spot check? Please close if all is well.

**Comment by pixelzoom** [comment]
👍🏻
