### ISSUE TITLE
needAtLeastOneKickText is duplicated 3 times

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#480]
For code review #447 ...

Duplicated in 3 files. Not a big deal, but worth factoring out?

```ts
    const needAtLeastOneKickText = new Text( CenterAndVariabilityStrings.needAtLeastOneKickStringProperty, {
      fontSize: 18,
      maxWidth: CAVConstants.INFO_DIALOG_MAX_TEXT_WIDTH
    } );
```

**Comment by samreid** [comment]
I'll work on this

**Comment by samreid** [comment]
I factored it out in the commit, @marlitas or @matthew-blackman would you like to review/verify and close?

**Comment by matthew-blackman** [comment]
Commits look great, nice work @samreid! Reviewed and tested - closing.
