### ISSUE TITLE
Should `.isIntervalToolInputEnabledProperty ` be an `EnabledProperty`?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#483]
For code review #447 ...

> - [ ] When defining a boolean Property to indicate whether something is enabled, use `AXON/EnabledProperty`. This should be done in both the model and the view. If you're using a DerivedProperty, skip this item.

I'm not sure if this review item is still "a thing".  That said...

In VariabilityModel.ts:
```ts
    this.isIntervalToolInputEnabledProperty = new BooleanProperty( true, {
```

In VariabilityAccordionBox.ts:
```ts
        enabledProperty: model.isIntervalToolInputEnabledProperty,
```

So should VariabilityModel `this.isIntervalToolInputEnabledProperty` be an instance of `EnabledProperty`?  I don't know.  You might want to consult @zepumph on this one.

**Comment by zepumph** [comment]
EnabledProperty was created to share code between SCENERY/Node and EnabledComponent. I don't have any problem if you want to use it, but it totally isn't necessary or our convention. It is nice that it handles the consistent tandem name for you `enabledProperty`, but it you are going to have a different name, then it probably isn't worth it.

**Comment by pixelzoom** [comment]
Thanks @zepumph  --- that's kind of what I thought.  Should the code-review item be revised or deleted?

**Comment by pixelzoom** [comment]
Oh right, duh...  This is an `inputEnabledProperty`.  Nevermind.  It's probably still useful to update the checklist item.

**Comment by samreid** [comment]
@marlitas and @matthew-blackman and I discussed that this issue seems good for CaV, and that @marlitas will open a new issue in phet-info about updating the checklist. This seems in line with the recommendations above, so we feel comfortable closing the issue. @pixelzoom please reopen if necessary.
