### ISSUE TITLE
Pointer areas for cards are a little off-center

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#484]
For code review #447 ...

Behavior of pointer areas for the cards in the Distance accordion box is a little odd. Nothing that impacts usability, but I thought I'd report it anyway.

To reproduce:

Go to the Median screen, press "Kick 5 button".  You'll see something like the screenshot below, with pointer areas for the leftmost card.  That card's pointer areas are presumably being set explicitly because it has the hand+arrow to cue dragging.  The other cards are draggable, but don't show pointer areas because their pointer areas have not been explicitly set.  Everything is as expected here so far.

<img width="514" alt="screenshot_2729" src="https://github.com/phetsims/center-and-variability/assets/3046552/d58ad62c-a934-483e-98ec-6576b61630d1">

Next, move the leftmost card. The hand+arrow disappears. The pointer areas are adjusted, but they are a little off-center -- there is more space to the left than the right:

<img width="421" alt="screenshot_2730" src="https://github.com/phetsims/center-and-variability/assets/3046552/cffec142-c4f9-43d2-a1ec-f8bd4aac591a">

Press the Reset All button, followed by the "Kick 5" button.  Do this a few times.  Eventually you'll see something like this:

<img width="509" alt="screenshot_2731" src="https://github.com/phetsims/center-and-variability/assets/3046552/24ba0c54-1946-4aa7-9df4-3960aa23c488">

I'm guessing that the cards are being reused, and eventually they will all have explicitly-set pointer areas. And they are all a little off-center.

**Comment by catherinecarter** [comment]
Let's expand the touch area in case a user doesn't quite grab directly on a card. This will help with the centering, but the centering is less of the issue as is the area that a user can use to move a card.

**Comment by samreid** [comment]
Proposed fix in the commits. It has been code reviewed by @marlitas and @matthew-blackman.

@catherinecarter does this look OK to you?  If so, please reassign to @pixelzoom as part of the code review:

![image](https://github.com/phetsims/center-and-variability/assets/679486/3e213e1b-79c7-45bc-8315-9f037ed98f0a)

**Comment by catherinecarter** [comment]
Much better. Reassigning to @pixelzoom, but also acknowledging some of the pointer areas might increase, per #462.

**Comment by pixelzoom** [comment]
Nice improvement!
