### ISSUE TITLE
Replace param `options/providedOptions` with `tandem`?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#486]
For code review #447 ...

There are several places where `options` or `provideOptions` parameters are being defined solely for passing `tandem`.  This is adding unnecessary types and code. Why not just use param `tandem: Tandem` in these cases?

Examples (not a complete list):

SoccerSceneModel:

```ts
type SelfOptions = EmptySelfOptions;
export type SoccerSceneModelOptions = SelfOptions & PickRequired<PhetioObjectOptions, 'tandem'>;
...
  public constructor(
    ...
    providedOptions: SoccerSceneModelOptions
  ) {
```

CAVSoccerSceneModel:

```ts
type CAVSoccerSceneModelOptions = EmptySelfOptions & SoccerSceneModelOptions;
...
  public constructor( maxKicksProperty: TReadOnlyProperty<number>,
      ...
                      providedOptions: CAVSoccerSceneModelOptions ) {
```

DragIndicatorModel:

```ts
  public constructor( public readonly soccerBallsEnabledProperty: TReadOnlyProperty<boolean>, options: PickRequired<PhetioObjectOptions, 'tandem'> ) {
```

SoccerScreenView:

```ts
  public constructor(
...
    options: PickRequired<PhetioObjectOptions, 'tandem'> ) {
```

**Comment by samreid** [comment]
Upon reflection, @marlitas and I agreed this would be a good change to make. Commit coming soon.

**Comment by samreid** [comment]
I committed usage of `tandem: Tandem` instead of passing tandem through the options. This seems much clearer and simpler to me. @pixelzoom would you like to spot check? Please close if all is well.

**Comment by pixelzoom** [comment]
👍🏻
