### ISSUE TITLE
Suggested improvement to SoccerSceneView constructor signature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#487]
For code review #447 ...

SoccerSceneView.ts:

```ts
  public constructor(
    dragIndicatorModel: DragIndicatorModel,
    soccerBallsEnabledProperty: Property<boolean>,
    public readonly sceneModel: SoccerSceneModel,
```

- [x] Since this is the view of SoccerSceneModel, I'd like/expect to see `sceneModel` as the first constructor parameter. 

- [x]  There is unnecessary coupling to `dragIndicatorModel` here. SoccerSceneModel only needs `dragIndicatorModel.soccerBallHasBeenDraggedProperty`.

**Comment by samreid** [comment]
I'll work on this.

**Comment by samreid** [comment]
Fixed, @pixelzoom can you spot check? Please close if all is well.

**Comment by pixelzoom** [comment]
👍🏻
