### ISSUE TITLE
soccer-common imports CAVConstants.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#489]
For code review #447 ...

In center-and-variability/package.json, I see this lint rule:

```ts
          "soccer-common-cannot-reference-center-and-variability": "error",
```

Did you mean to put this rule in soccer-common/package.json?  Because it's not effective where it is.  In fact, in soccer-common KickDistributionStrategy.ts:

```ts
import CAVConstants from '../../../center-and-variability/js/common/CAVConstants.js';

...

phetioDocumentation: ...
 ... with these values: [${CAVConstants.LEFT_SKEWED_DATA.join( ',' )}]. ...
```

Putting `CAVConstants.LEFT_SKEWED_DATA.join( ',' )`  in `phetioDocumentation` seems a little brittle to me. I would just get rid of it.  But your call.

**Comment by samreid** [comment]
Good save @pixelzoom, there were indeed incorrect dependencies from soccer-common on to center-and-variability. I cleaned that up, deleted the no-longer-necessary lint rule, and added a bad-text rule to prevent that from happening again. Closing.
