### ISSUE TITLE
Unnecessary use of `as` in RangeNode.ts ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#495]
For code review #447, related to:

> - [ ] Are TypeScript conventions outlined in the [TypeScript Conventions Document](https://github.com/phetsims/phet-info/blob/master/doc/typescript-conventions.md) followed and adhered to?

In RangeNode.ts:

```ts
      const leftmostDot = sortedDots[ 0 ] as SoccerBall | undefined;
      const rightmostDot = sortedDots[ sortedDots.length - 1 ] as SoccerBall | undefined;
```

Why is `as SoccerBall | undefined` necessary in these 2 cases?  `sortedDots` is of type `SoccerBall[]`.  And if I remove the "as", there is no lint or TS error.  So inferred type seems to be correct.

**Comment by samreid** [comment]
Good catch, thanks. The resolution was straightforward, closing.
