### ISSUE TITLE
`parentContext` type is duplicated

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#497]
This type:

```ts
  parentContext: 'accordion' | 'info';
```

.. is duplicated at least 7 times, in CAVPlotNode, MeanAndMedianPlotNode, CardContainerModel (2x), IQRNode, MADNode, and RangeNode.  

The values are also abbreviated, and therefore not very helpful/readable in context. 

Recommended to factor out a type, and use full names for the values:

```ts
export type ParentContext = 'accordion' | 'info';
```

Or if you prefer:

```ts
export const ParentContextValues = [ 'accordionBox', 'infoDialog' ] as const;
export type ParentContext = ( typeof ParentContextValues )[number];
```

**Comment by pixelzoom** [comment]
Also recommended to document. I found this in CardContainerModel.ts, but the other sites are undocumented.

```ts
  // accordionBox is the full-featured interactive version with drag input and sound effects
  // info is the non-interactive version used in the info dialog
  parentContext: 'info' | 'accordion';
```

**Comment by samreid** [comment]
I'll work on this

**Comment by pixelzoom** [comment]
I'm not sure if `ParentContext` (shown above) is the best name for this type, it's a bit vague.  I don't have a better idea.

**Comment by samreid** [comment]
I went with RepresentationContext in the commit, @pixelzoom does the commit look OK to you? Want to reach out to @marlitas and @matthew-blackman for better name ideas?

**Comment by pixelzoom** [comment]
RepresentationContext seems nice to me, and nice doc. Up to you if you'd like to ask your team.  If not, feel free to close.

**Comment by samreid** [comment]
I think it's at a good point to close, thanks.
