### ISSUE TITLE
Soccer player images are larger than other sim image files

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/center-and-variability#498]
When investigating https://github.com/phetsims/center-and-variability/issues/464, it was noted that the image files in Center and Variability are significantly larger than the image files in other sims. See below comparison of Energy Skatepark skater (15.6 kB) to Center and Variability kicker (61.5 kB).

![Screen Shot 2023-08-21 at 2 41 42 PM](https://github.com/phetsims/center-and-variability/assets/108756567/8b3ff648-65fa-469b-9007-5c5f13bc9b77)
![Screen Shot 2023-08-21 at 2 41 51 PM](https://github.com/phetsims/center-and-variability/assets/108756567/c31d1fea-f90c-4630-9039-ead0b7b8e536)

The devs wanted to reach out to @mariahmaephet to ask about ways to reduce the size of the image files in Center and Variability without sacrificing quality. We are aware that the images will need to look un-pixelated in all environments including Retina displays.

@mariahmaephet - Is there a norm for the size of png images in PhET sims? We are willing to shrink the PNG files on our end using a software like Photoshop, but want to make sure that we aren't sacrificing quality in the rendered sim.

**Comment by mariahmaephet** [comment]
Hmmm, I'm not actually sure I'm the person who would know about that. In general I'm only working in Illustrator making everything as vectors, and then whoever is making the sim takes that .ai file and breaks it up from there. I'm not the one saving individual pngs like those. 

The actual vectors probably vary in size--because I remember for the skateboarders they gave me specifics on the pixels to make sure they were small and fit into the click box area. I don't normally get specific size requests, though I tend to make them all a similar size for consistency in stroke width. 

So if resizing the png file pixelates it too much, then we'd just need to rescale it in illustrator to be smaller.

**Comment by matthew-blackman** [comment]
Thanks @mariahmaephet! I will take this info back to the dev team for next steps. Really appreciate the quick reply!

**Comment by amanda-phet** [comment]
I can make them smaller, since I exported them. I can also do it with Cathy
so we both see what is going on.

**Comment by matthew-blackman** [comment]
Sounds good @amanda-phet!

**Comment by amanda-phet** [comment]
OK just did a quick review of this issue and the resolution for the people in CaV is 980x1342 which is pretty big. However the kickers in this sim are also larger than the skaters in ESP, so it wouldn't make sense to scale it down to 180x242. Before we export all of the images again at a lower resolution, should we do just the four on the Variability screen and see how they look? You'll probably also need to adjust the scaling in the code, so it would take some tweaking to get it just right again.

**Comment by amanda-phet** [comment]
We discussed this just now and @matthew-blackman is going to scale all of the pngs down by 50% and apply that to the "magic numbers" that are aligning people just right, and then assess the situation. If the characters look good, we can use the new resolution for the Africa character set. If the characters don't look good, we will export them again from illustrator at a lower resolution and go from there.

**Comment by matthew-blackman** [comment]
I scaled all kicker image files down 50% and things are looking really good on my end. It turns out I only had to update a single SCALE_FACTOR - really nice! The image quality in the sim looks identical to me. The images are smaller but still pretty big - we could try to reduce further to see how small they can be before we see a drop in quality.

Over to you for review and feedback @amanda-phet @catherinecarter!

**Comment by amanda-phet** [comment]
I would try reducing the file size further. Maybe 25% of the original, so another 50% smaller? 

Once you finalize the size that works can you share the final aspect ratio of the pngs so we know what size to export the Africa character set at?

**Comment by matthew-blackman** [comment]
Implemented and ready for review @amanda-phet. I still can't see any drop in quality for the rendered sim. The file sizes of the images are now significantly smaller (about 60-70%). If things are looking good to you, I think we should be at a point where we can re-evaluate https://github.com/phetsims/center-and-variability/issues/464 with the new build size.

**Comment by amanda-phet** [comment]
I think they look pretty good. What do you think @catherinecarter ?

**Comment by catherinecarter** [comment]
I think they're a little grainy when pan and zoom is used, even for a tiny bit of zooming. If it makes the sim more functional and faster, I'm ok with them, but if there's "space" to make the resolution a tiny bit larger, I'm curious if the zoom wouldn't get grainy so fast.

**Comment by samreid** [comment]
We also need to check whether this effort is having a significant impact on the built file size.

**Comment by samreid** [comment]
@catherinecarter and I are double checking that experiment. We ran a build with the current state of main (small pictures), and the _en HTML file was 4.8MB 4,780,985 bytes (4.8 MB on disk).

**Comment by samreid** [comment]
Since we aren't fully finalized on the exact resolution, we are thinking @catherinecarter should just generate the 980x1342 size and @matthew-blackman can run a script to size them whatever we decide (so we don't have to risk generating them twice).  We also were going to ask if @matthew-blackman went from full to 1/2 to 1/4 or directly from full to 1/4 --noted it may be a slightly different result.

**Comment by matthew-blackman** [comment]
Commit [Shrink kicker images and update scale factor - see](https://github.com/phetsims/soccer-common/commit/e421dfbd17ab0819bd65061186c8fb4b68a08e46) has the images at 50% original size, and commit [Shrink kicker images and update scale factor - see](https://github.com/phetsims/soccer-common/commit/80c59b9804072cba0e4440197d6f6a7f787c36f8) has them at 25% original size.

**Comment by samreid** [comment]
Thanks @matthew-blackman, so it looks like they went x 0.5 x 0.5 instead of x 0.25 (may not be identical).

**Comment by matthew-blackman** [comment]
Yes that's right. I used the same png scaling algorithm in Photoshop twice. It tends to be very good at maintaining the same appearance when downscaling. Is it worth trying one from the original size with 25% scaling, to see if it looks better than the  x 0.5 x 0.5 results? I have the action set so it will take < 1 minute to try if we'd like to see how it looks.

**Comment by samreid** [comment]
Our questions all arose from "what size should @catherinecarter" generate the PNGS from the AI. Since I don't think we fully decided on 980px vs 490px vs 245px, we decided she would generate them at 980px wide, and we can rescale them when we decide on a scale. Also we can choose any size, it doesn't have to be 0.5 vs 0.25. Why not 0.4? etc.

**Comment by matthew-blackman** [comment]
Sounds good @samreid. I can revert the two commits above so we have large images to work with for now. For reference, here is a comparison of the two scaling methods to quarter-size:

x50% twice:
![player01Kicking_half_size_twice](https://github.com/phetsims/center-and-variability/assets/108756567/7b5f34bd-d011-4500-a7df-dccd0d43309a)

x25% once:
![player01Kicking_quarter_size](https://github.com/phetsims/center-and-variability/assets/108756567/9b786d95-4ea2-4947-a0ba-f6eb25fd1851)

**Comment by catherinecarter** [comment]
I have uploaded the new character sets as their original size into Africa and Africa modest. All files are now the same size.

**Comment by samreid** [comment]
Thanks, I can see the images. I also can see that the sizes of the new images are 490x671.  This differs from the conclusion above where we agreed:

> we decided she would generate them at 980px wide, and we can rescale them when we decide on a scale (to avoid any risk of having to run that time consuming manual step twice).

However, I think it will be fine, and I think we should use the 490px width for now.  I will bring the USA character back to the 490px width.  Now that we have all artwork, I think we should run a file size comparison at 490px and see if it is a good size, or if we want to reduce below that.

**Comment by samreid** [comment]
I have reverted https://github.com/phetsims/soccer-common/commit/80c59b9804072cba0e4440197d6f6a7f787c36f8 and tried to push twice, but it keeps hanging with:

```
~/phet/root/soccer-common$ git push
Enumerating objects: 154, done.
Counting objects: 100% (154/154), done.
Delta compression using up to 8 threads
Compressing objects: 100% (120/120), done.
Writing objects: 100% (120/120), 5.67 MiB | 624.00 KiB/s, done.
Total 120 (delta 4), reused 114 (delta 0), pack-reused 0
```

**Comment by samreid** [comment]
OK I recloned and that seemed to help.

**Comment by marlitas** [comment]
We reverted one too many times. We are now using the 490 png width for ALL characters no matter what location they are. This also fixed https://github.com/phetsims/center-and-variability/issues/526. 

Closing this issue as completed.
