### ISSUE TITLE
A11y view has an empty play area and control area

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#499]
From #477 I noticed that almost nothing is showing up under the play area or control area in the a11y view:

![image](https://github.com/phetsims/center-and-variability/assets/679486/1a38d05a-2b89-46e8-85f0-49dbe03c4150)

Our team has already signed off on the keyboard navigation order, but I'm wondering if we need to nest things under the play area or control area. Or is that more for voicing?

@jessegreenberg can you please advise?

**Comment by jessegreenberg** [comment]
Hey @samreid, in my opinion there is no need to consider this until you take on Interactive Description (screen reader access).

**Comment by pixelzoom** [comment]
+1 for what @jessegreenberg said.  The current modus operandi is to ignore pdomPayArea and pdomControlArea in sims that don't have Interactive Description.
