### ISSUE TITLE
IntervalBarNode options do not appear to be used

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/center-and-variability#501]
When addressing @pixelzoom's review comments in IntervalBarNode, I noticed that intervalBarNodeWidth and dropLineLength are defined as an options but do not appear to be used by any instance of an IntervalBarNode. Can these options be removed?

**Comment by pixelzoom** [comment]
There's no correct answer here - it's up to you. There's no harm in leaving it the way it is.  But it's flexibility that's not needed, resulting in addition (unexercised) code.  

If you do get rid of option `dropLineLength`, then you could also get rid of `this.dropLineLength` and replace it with `const DROP_LINE_LENGTH = 6`.

**Comment by pixelzoom** [comment]
Looks good.  I made one minor change in the above commit -- moved DROP_LINE_LENGTH outside of the class definition, which is where constants like this typically live.
