### ISSUE TITLE
Should SoccerBall constructor be protected?

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/center-and-variability#510]
From @pixelzoom's review of SoccerBall.ts:

> "Base class" in the doc above implies that it's not intended to be instantiated directly. Is that accurate? Should constructor be protected?

**Comment by matthew-blackman** [comment]
@marlitas and I discussed this, and would be surprised if MSaB did not end up with its own subclass of SoccerBall. With that in mind, we think that this can be made protected for now and changed to public if we want to instantiate it directly in MSaB. @samreid does this sound reasonable?

**Comment by samreid** [comment]
Sounds reasonable, I made it protected. Closing.
