### ISSUE TITLE
Should SoccerSceneModel constructor be protected?

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/center-and-variability#511]
From @pixelzoom's review on SoccerSceneModel:

> "Base class" in the doc above implies that it's not intended to be instantiated directly. Is that accurate? Should constructor be protected?

**Comment by matthew-blackman** [comment]
@marlitas and I have a similar question for @samreid here as in https://github.com/phetsims/center-and-variability/issues/510#issuecomment-1690643563

**Comment by samreid** [comment]
I followed the same logic as #510 and made SoccerSceneModel constructor protected, closing.
