### ISSUE TITLE
kickDistributionStrategy documentation needs updating

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#514]
The current documentation includes: 
>There are **three** ways to customize the values:

Since we added a fourth way to fix the skew, this needs to say, 

"There are four ways to customize the values:"

  I'd also like to change the word, "likelihood" to "frequencies" in the first part of the sentence (but not the second), and delete the word, "each."

> Probability by Distance: Defines the frequencies or relative **likelihoods** per each value on the number line.

Please change to:

  **Probability by Distance:** Defines the frequencies or relative frequencies per value on the number line.

**Comment by samreid** [comment]
I updated the wording as requested, @catherinecarter want to review? Please close if all is well.

**Comment by catherinecarter** [comment]
Looks great! Thanks, @samreid.
