### ISSUE TITLE
We would like the keyboard focus to be the same as the hand focus

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#515]
We originally designed the first group focus highlight to appear on the leftmost ball. However, now we want to put it on the same one the hand gets.  @terracoda and @kathy-phet said it is nice to bring these together. (Keep in mind the median may move the hand elsewhere). But the main point is the group focus highlight should begin where the hand begins. (Though you can move it).

But if you tab into the group before there is a hand, then we would like the leftmost one to be highlighted first. Then if you tab out and back it should remember what you had selected, even if there are new or more "leftmost" balls.

**Comment by samreid** [comment]
Fixed in the commit, would be good for code review and design spot check.

**Comment by marlitas** [comment]
Quick question on this. Currently the cards are not remembering which one you had selected when you tab back to the group. Do we want the behavior to match in both of these contexts? 

For further consideration... it might get tricky to have the cards remember which one was previously focused. A new property will probably have to be added to track that.

**Comment by samreid** [comment]
Also @matthew-blackman and I discovered there is a bug with the arrow location when the median stack is the last stack:

![image](https://github.com/phetsims/center-and-variability/assets/679486/edd028cb-2b2f-449c-ac16-9e82ec107a63)

Patch for testing:

<details>

```diff

Subject: [PATCH] test
---
Index: js/model/KickDistributionStrategy.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/model/KickDistributionStrategy.ts b/js/model/KickDistributionStrategy.ts
--- a/js/model/KickDistributionStrategy.ts	(revision c5156c60f7d164000297f7f74cad1c4c9206a5a3)
+++ b/js/model/KickDistributionStrategy.ts	(date 1693234318155)
@@ -66,28 +66,31 @@
   }
 
   public getKickDistance( kickIndex: number ): number {
-    if ( this.type === 'randomSkew' || this.type === 'skew' ) {
-      if ( this.skewType === 'left' ) {
-        return dotRandom.sampleProbabilities( LEFT_SKEWED_DATA ) + 1;
-      }
-      else if ( this.skewType === 'right' ) {
-        return dotRandom.sampleProbabilities( RIGHT_SKEWED_DATA ) + 1;
-      }
-      else {
-        assert && assert( false, 'incorrect skewType: ' + this.skewType );
-        return -1;
-      }
-    }
-    else if ( this.type === 'probabilityByDistance' ) {
-      return dotRandom.sampleProbabilities( this.values! ) + 1;
-    }
-    else if ( this.type === 'distanceByIndex' ) {
-      return this.values![ kickIndex ];
-    }
-    else {
-      assert && assert( false, 'incorrect type: ' + this.type );
-      return -1;
-    }
+    const distances = [ 1, 2, 3, 4, 4, 4, 4, 4, 4, 5, 6, 7, 8, 9, 4 ];
+    console.log( distances.length );
+    return distances[ kickIndex ];
+    // if ( this.type === 'randomSkew' || this.type === 'skew' ) {
+    //   if ( this.skewType === 'left' ) {
+    //     return dotRandom.sampleProbabilities( LEFT_SKEWED_DATA ) + 1;
+    //   }
+    //   else if ( this.skewType === 'right' ) {
+    //     return dotRandom.sampleProbabilities( RIGHT_SKEWED_DATA ) + 1;
+    //   }
+    //   else {
+    //     assert && assert( false, 'incorrect skewType: ' + this.skewType );
+    //     return -1;
+    //   }
+    // }
+    // else if ( this.type === 'probabilityByDistance' ) {
+    //   return dotRandom.sampleProbabilities( this.values! ) + 1;
+    // }
+    // else if ( this.type === 'distanceByIndex' ) {
+    //   return this.values![ kickIndex ];
+    // }
+    // else {
+    //   assert && assert( false, 'incorrect type: ' + this.type );
+    //   return -1;
+    // }
   }
 
   public applyState( stateObject: KickDistributionStrategySpecification ): void {

```

</details>

**Comment by samreid** [comment]
@matthew-blackman and I reviewed and addressed some more bugs in this area. Seems good to close and we will continue in the side issues. After we address similar issues we will request testing in https://github.com/phetsims/center-and-variability/issues/518
