### ISSUE TITLE
The soccer ball arrow needs to move up slightly so it doesn't interfere with the highlight rectangle

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#516]
![image](https://github.com/phetsims/center-and-variability/assets/679486/8f0250e7-aefe-420d-a3ac-7af4620eb518)

**Comment by samreid** [comment]
OK I moved it up 3.5px and it looked like this:

![image](https://github.com/phetsims/center-and-variability/assets/679486/6975187d-9eba-417d-be46-b2940e09b639)

I tried to moved it up a bit more but that created a mismatch with the other keyboard (selection or move when grabbed) arrows, so I left it like this.  @catherinecarter can this issue be closed?

**Comment by catherinecarter** [comment]
Looking great on the Median screen and Mean&Median screen. 

On the Variability screen, I saw this: 
<img width="215" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/7c4ad9e2-7be4-463b-9516-1cb615b34740">

and this: 
<img width="166" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/6f5d8677-697b-42ad-aeed-ad3a8fe1e720"> <img width="179" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/16e627cd-4d5e-4103-b421-1f22fb6bb94f">

**Comment by samreid** [comment]
OK it sounds like moving up the arrow worked well, but we have some straggling issues about the highlights. Several of those have been fixed. Let's accumulate and fix the rest in #518, closing.
