### ISSUE TITLE
Preliminary testing before dev test

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#518]
Today @matthew-blackman asked if @catherinecarter could take a look through the sim before we begin dev testing, to see if there are problems that need to be addressed before testing. He indicated this would be good to check particularly regarding the focus highlights, keyboard/mouse cues, etc and all those new features. But I would recommend even broader testing--please open new issues for any problems you see.

**Comment by catherinecarter** [comment]
A screenshot of a new perspective. After reset-all, my tab was in the nav bar so I shift-tabbed so I could kick more. When shift-tabbing, the soccer ball play area is tabbed to first, and this is what I saw (so no balls had been kicked):

![Image](https://github.com/phetsims/center-and-variability/assets/109630002/b0111a1d-82c6-4c19-9e72-a41af181a903)

Next, I kicked 5 and pressed tab once: 

![Image](https://github.com/phetsims/center-and-variability/assets/109630002/47292e7f-b4b3-4914-aaae-8f3419920501)

**Comment by catherinecarter** [comment]
It looks like the drag indicator, as well as the alt-input focus, is currently being placed on the rightmost ball rather than the last kicked ball. Is this the case? If so, we'll want the drag indicator (and the focus) to be on the last ball kicked. 

In the case when the last ball kicked lands in the stack of the median, rather than have the logic go to the 2nd-last ball kicked, maybe move it one stack right or left of the Median stack?

**Comment by samreid** [comment]
Good catch @catherinecarter, likely broken because https://github.com/phetsims/soccer-common/commit/9487bb0ebf15a83f02302d280a696462dff579c0 has a different sort order, thanks!

**Comment by samreid** [comment]
Some other errors reported in https://github.com/phetsims/center-and-variability/issues/516#issuecomment-1695975796 which may have been addressed:

![image](https://github.com/phetsims/center-and-variability/assets/679486/daf809da-5763-41f5-8876-818e033be4ce)

![image](https://github.com/phetsims/center-and-variability/assets/679486/e69a6681-e20d-44da-8eb3-ea73e177910f)

**Comment by samreid** [comment]
Thanks, I was able to reproduce the problem--the issue was that if a soccer ball gets focus, we want to show the indicators there. I'll push a proposed commit for testing.

**Comment by samreid** [comment]
@catherinecarter can you help test after that change?

**Comment by marlitas** [comment]
The work in this issue now seems to be overlapping with https://github.com/phetsims/center-and-variability/issues/521. Closing this issue.
