### ISSUE TITLE
Soccer ball drag indicator is supposed to move away from the median and it may not be

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#519]
In testing the cueing arrow mixed with the alt-input focus rectangle around the ball, I changed my max number of kicks to be 5. I kicked several iterations until the last ball was the same as the median (currently, the dragIndicator shows on the last ball kicked), and I saw this: 

<img width="140" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/70ae0a44-974c-4ca7-ab55-c57102f33824">

Not sure if it's a maxKicks=5 issue, or more global. Will do more testing.

**Comment by samreid** [comment]
I was able to replicate this after a few trials:

![image](https://github.com/phetsims/center-and-variability/assets/679486/396b9580-b78e-4a6a-ae46-ca2b5c7bc158)

**Comment by samreid** [comment]
That median object doesn't seem correct.

**Comment by samreid** [comment]
After the commit, that error case no longer occurs for me.  Let's close this and pick it up in #518
