### ISSUE TITLE
Kick order for Africa and Africa Modest character sets

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#523]
This issue is to identify the order of kickers for the Africa and Africa Modest character sets. 

**Africa**
1. Africa, player01
2. Africa, player 02
3. Africa, player 03
4. Africa, player 04
5. USA, player 08 
6. USA, player 14 
7. Africa, player 06
8. USA, player 12
9. USA, player 10
10. USA, player 2
11. Africa, player 05
12. USA, player 04
13. Africa, player 07

**Africa Modest**
1. Africa, player 01
2. Africa, player 04
3. Africa modest, player 01
4. USA, player 14
5. Africa, player03
6. Africa modest, player 02
7. Africa, player 06
8. USA, player 08
9. USA, player 02
10. Africa, player 05

**Comment by samreid** [comment]
I have transferred this issue to center-and-variability since we would like to track soccer-common work in the center-and-variability issues for this publication.

**Comment by samreid** [comment]
OK I updated the order, but it needs to be carefully checked since the indices in the filenames don't always match the indices as they appear in the arrays.  @catherinecarter can you please review? You can use the preferences dialog to change Region and Culture.

**Comment by samreid** [comment]
Also needs code review.

**Comment by KatieWoe** [comment]
In https://github.com/phetsims/qa/issues/976, in addition to https://github.com/phetsims/center-and-variability/issues/526 many of the players seem to repeat rather than the described order.

**Comment by catherinecarter** [comment]
Kicker order for Variability screen, African set is as it looks in the Africa folder:
1. variabilityPlayer01
2. variabilityPlayer02
3. variabilityPlayer03
4. variabilityPlayer04

For Africa modest, replace the variabilityPlayer02 from the Africa set with variabilityPlayer01 from the Africa modest set. 

@KatieWoe - the players have to repeat due to the smaller number of kickers in the African and African modest set of characters. For the African set, there are 13 kickers, so there shouldn't be any repeats until kicker 14. For the modest set, there are 10 kickers, so there shouldn't be any repeats until kicker 11. Are you seeing repeats prior to those numbers?

**Comment by KatieWoe** [comment]
In the modest set it starts to repeat at 10, not 11. And this character shows up twice.
![showsuptwice](https://github.com/phetsims/center-and-variability/assets/41024075/1d1fdc2b-a55c-433e-bbfc-fec6f77d4791)

**Comment by marlitas** [comment]
I think this is corrected in the above commit. @catherinecarter can you double check?

**Comment by catherinecarter** [comment]
Yes, the order looks correct now. Thank you :)

**Comment by marlitas** [comment]
Great. Closing :-)
