### ISSUE TITLE
Field needs to clear when changing character sets

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#524]
I noticed when I switched character sets in the preferences, the field did not clear. I noticed when testing #523.

Seems like the field should clear when switching character sets.

**Comment by marlitas** [comment]
This was straightforward. Sending to @catherinecarter to double check on main. If all looks good feel free to close.

**Comment by catherinecarter** [comment]
I tested all screens, and all looks great. Thanks, @marlitas :)
