### ISSUE TITLE
Checkboxes missing default sound

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#525]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/976, the median checkbox in the panel on the Mean and Median screen is missing the default checkbox sound. If balls haven't been kicked, checking the box results in no sound. When balls have been kicked, I hear the tones when I check the box. 

**Steps to reproduce**
1. On the Mean and Median screen, check the Median checkbox in the panel

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Variability‬
URL: https://phet-dev.colorado.edu/html/center-and-variability/1.1.0-dev.14/phet/center-and-variability_all_phet.html
Version: 1.1.0-dev.14 2023-09-01 18:18:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15
Language: en-US
Window: 1354x716
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
Also, the Sort Checkbox makes a specific noise instead of the default when I check it before kicking any balls.

**Comment by marlitas** [comment]
This has been addressed in the above commits. Over to @Nancy-Salpepi to check on main. Thanks!
