### ISSUE TITLE
Tiny flying soccer players

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#526]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/976
The soccer players in the Africa and Africa (Modest) set are both very small and floating in the air.

**Visuals**
![tiny](https://github.com/phetsims/center-and-variability/assets/41024075/243e1cca-9834-4cc0-8ca1-88ec32e9439f)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Variability‬
URL: https://phet-dev.colorado.edu/html/center-and-variability/1.1.0-dev.14/phet/center-and-variability_all_phet.html
Version: 1.1.0-dev.14 2023-09-01 18:18:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language: en-US
Window: 1536x707
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
This is not happening in my local working copy.  All my changes appear to be pushed.

**Comment by marlitas** [comment]
This was addressed by reverting a revert in another issue. Over to @KatieWoe to confirm all looks good on main.

**Comment by KatieWoe** [comment]
Soccer players seem to be the correct size and firmly on the ground :)

**Comment by marlitas** [comment]
Yay! Closing. Thanks!
