### ISSUE TITLE
Interactive highlight for card remains after pressing Eraser button

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#528]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/976 on the Median Screen:  after pressing the Eraser button, the interactive highlight is still present for the last card that had focus. Pressing space freezes the sim. 

**Steps to reproduce**
1. On the Median Screen, Kick some balls
2. TAB to the Eraser button and press
3. press Shift + Tab until you reach the interactive highlight for a card. 
4. Press Space 

**Visuals**
<img width="504" alt="Screenshot 2023-09-05 at 10 07 28 AM" src="https://github.com/phetsims/center-and-variability/assets/87318828/db32f4da-88c4-4363-809c-d50022b08ca6">

https://github.com/phetsims/center-and-variability/assets/87318828/3f9fd8ea-d198-4f7e-ba6e-7a22c7db2191

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Variability‬
URL: https://phet-dev.colorado.edu/html/center-and-variability/1.1.0-dev.14/phet/center-and-variability_all_phet.html
Version: 1.1.0-dev.14 2023-09-01 18:18:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15
Language: en-US
Window: 1317x716
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by marlitas** [comment]
This was also straightforward. @Nancy-Salpepi please check if this is working as expected now on main, and close if all looks good. Thanks!

**Comment by Nancy-Salpepi** [comment]
Looks good on main 🙂
@marlitas I was wondering if I should be able to tab to the empty soccer ball area and card area or if they should just be skipped over? 

<img width="795" alt="Screenshot 2023-09-13 at 7 45 23 AM" src="https://github.com/phetsims/center-and-variability/assets/87318828/8d7caeae-693a-4b65-ab41-14756d250c48">

<img width="348" alt="Screenshot 2023-09-13 at 7 46 48 AM" src="https://github.com/phetsims/center-and-variability/assets/87318828/6a9fb860-12a3-419e-b804-8aec1d0b6432">

**Comment by marlitas** [comment]
We decided we wanted to still have users tab through both of those empty areas since they are core parts of the sim, and if description is added we would want to describe the empty field and the fact that no data is present.

Thanks for checking in on it! Closing.
