### ISSUE TITLE
Sounds heard when pressing Reset All in downstream/launched sim

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#533]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/976 with both Studio and State wrappers: 
On the Variability screen, if the interval tool was moved in Studio or upstream wrapper in State, I hear the interval tool noise when pressing Reset All in launched sim. 

**Steps to reproduce**
1. In State: Set state rate =0
2. In the upstream sim: On the Variability screen, press kick 5 button once
3. Check the interval tool checkbox and move one side of the interval tool
4. Press Set State Now
5. In the downstream sim, uncheck the interval tool checkbox
6. press Reset All

**Visuals**

https://github.com/phetsims/center-and-variability/assets/87318828/fe0ae405-05ed-450d-b057-aa1bbac2e85d

**Comment by KatieWoe** [comment]
I'm seeing this on Win 11 Chrome as well

**Comment by Nancy-Salpepi** [comment]
I also wanted to note that I sometimes hear an extra sound when pressing Reset All on any screen in the PhET brand sim. I haven't been able to pin down exact steps.

**Comment by Nancy-Salpepi** [comment]
Here are the steps to reproduce the extra sound when pressing Reset All:
1. Clear your cache
2. Go to either the first or second screen
3. Check the Predict Median Checkbox
4. Move the Predict Median arrow
5. Press Reset All

**Comment by marlitas** [comment]
This feels like a remnant of https://github.com/phetsims/center-and-variability/issues/260, which I think may involve the help of @jbphet.

I see that a `resetInProgressProperty: model.variabilityModelResetInProgressProperty` is defined, but it seems like the continuousSoundGenerator listener may be triggering twice? The first time resetInProgressProperty reads as `true`, the second time it reads as `false`.

I also noticed that the soundGenerator is still firing when we set state.

This is as far as I could go on my own.

**Comment by zepumph** [comment]
@marlitas and I solved this problem. 

```diff
Subject: [PATCH] reset back to query parameter particle numbers, https://github.com/phetsims/build-a-nucleus/issues/195
---
Index: js/variability/model/IntervalToolModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/variability/model/IntervalToolModel.ts b/js/variability/model/IntervalToolModel.ts
--- a/js/variability/model/IntervalToolModel.ts	(revision 97b1de3b3651207b758bf9cb29968e0841d74ef9)
+++ b/js/variability/model/IntervalToolModel.ts	(date 1694811693157)
@@ -75,6 +75,11 @@
       } );
 
     this.deltaStableProperty = new NumberProperty( this.getIntervalToolWidth() );
+
+    // https://github.com/phetsims/center-and-variability/issues/533
+    Tandem.PHET_IO_ENABLED && phet.phetio.phetioEngine.phetioStateEngine.stateSetEmitter.addListener( () => {
+      this.deltaStableProperty.value = this.getIntervalToolWidth();
+    } );
   }
 
   /**
```

**Comment by Nancy-Salpepi** [comment]
@marlitas I don't know if this is helpful or not, but I usually hear a clipping sound in the downstream sim and in the launched sim in studio. I believe this is the issue for it: https://github.com/phetsims/tambo/issues/159

**Comment by zepumph** [comment]
Just noting that that issue has not blocked other PhET-iO sims, and we should probably not make it block this one.

**Comment by samreid** [comment]
@marlitas and I experimented with a few things and came to the same conclusion as @zepumph.  We will request testing from @Nancy-Salpepi on the commit above to see if everything is fixed except for that clipping.

**Comment by marlitas** [comment]
Thanks for the reminder @Nancy-Salpepi! That should now be handled in the above commits. Feel free to close if all looks good.

**Comment by Nancy-Salpepi** [comment]
looks good @marlitas!
