### ISSUE TITLE
Unable to move balls in launched sim

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#534]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/976, in State (and studio): On all screens I see that any balls kicked before the sim is launched aren't interactive. Any balls kicked afterwards are interactive. 

**Steps to reproduce**
1. In State, set the rate = 0
2. On any screen, press kick 5 button once
3. Press Set State Now button
4. Try and move a ball

**Visuals**

https://github.com/phetsims/center-and-variability/assets/87318828/d32fca97-3f6b-4649-b51a-e2263335f1ff

**Comment by Nancy-Salpepi** [comment]
Noting that the balls are still moveable with keyboard nav

**Comment by pixelzoom** [comment]
Looking at SoccerBall.ts, I'm wondering why`isDraggingProperty` is not instrumented, and if that's related:

```ts
  public readonly isDraggingProperty = new BooleanProperty( false );
```

**Comment by pixelzoom** [comment]
Also wondering why `dragPositionProperty` is not instrumented in SoccerBall:

```ts
    this.dragPositionProperty = new Vector2Property( this.positionProperty.value.copy() );
```

If is OK that they are not instrumented, some comments in the code would be helpful for the next person who wonders.

**Comment by marlitas** [comment]
I updated that documentation and also ran a test to see if instrumenting would change the behavior. It did not. These Properties only track active dragging information which is not needed to set state in the sim. 

There is a universal enabledProperty for the balls that I assume might be getting in the way here, but the part that confuses me is that the balls are still movable with keyboard nav...

**Comment by pixelzoom** [comment]
> These Properties only track active dragging information which is not needed to set state in the sim.

But is it needed for record/playback?  I don't know. Recommend asking @samreid and @zepumph.

**Comment by marlitas** [comment]
Confirmed with @zepumph and @samreid that both of those properties are not needed for record/playback, since they only track transient moments that are not necessarily valuable in tracking a user's actions in the sim.

**Comment by pixelzoom** [comment]
Noting that this problem also occurs in the "Standard PhET Wrapper".   Follow the steps that @Nancy-Salpepi provided above, but do so in Studio.  Press the Test button in Studio to launch the "Standard PhET Wrapper".  Note that all of the balls in wrapper are non-interactive.

**Comment by pixelzoom** [comment]
My hypothesis: Something that: happens after a ball has been kicked to make it interactive.  And the fact that it's interactive is not stateful.  So when balls are created in their initial positions when restoring state, the balls that are created are not interactive because the "kick" code has not run.

**Comment by pixelzoom** [comment]
This looks like a potential suspect, in SoccerBallNode.ts.  My guess is that the balls that are not interactive all have their `inputEnabledProperty` set to false. 

```ts
    // Prevent dragging or interaction while the object does not have a value (when it is not in the play area yet),
    // when it is animating, if input for this individual node is disabled, or if input for all the object nodes
    // has been disabled
    Multilink.multilink(
      [ soccerBall.soccerBallPhaseProperty, soccerBall.valueProperty, enabledProperty, soccerBallsEnabledProperty ],
      ( mode, value, selfInputEnabled, objectsInputEnabled ) => {
        const inputEnabled = value !== null && mode === SoccerBallPhase.STACKED && selfInputEnabled && objectsInputEnabled;

        // if input is disabled and the ball is in the play area, show the darker version
        const showEnabledSoccerBall = selfInputEnabled && objectsInputEnabled;
        const showDisabledSoccerBall = !showEnabledSoccerBall;
        soccerBallDarkNode.visible = showDisabledSoccerBall;
        soccerBallNode.visible = !showDisabledSoccerBall;

        this.inputEnabled = inputEnabled;
      } );
```

**Comment by pixelzoom** [comment]
For posterity... @marlitas, @matthew-blackman, and I worked on this today.  We eventually identified the problem code in SoccerSceneView.ts.   

```ts

    sceneModel.stackChangedEmitter.addListener( stack => {
...
        if ( i === stack.length - 1 ) {
...
          soccerBallNode.pickable = true;
        }
        else {
          soccerBallNode.pickable = false;
```

This is also relevant in SoccerBallNode.ts:

```ts
    soccerBall.resetEmitter.addListener( () => {
...
      this.pickable = false;
```

The problem here is that `pickable` is not stateful.  The quickest fix would be to add `pickableProperty` to the SoccerBall, and use it as the `pickableProperty` option value for SoccerBallNode.

@marlitas @samreid @zepumph and I also discussed the inherent problems with using both pickable and inputEnabled. The latter is preferred, and it's not a good idea to combine use of both.   We spent a little time trying to avoid using pickable, but it's looks like it's going to be a lot of work.  So @marlitas was proceeding with the `pickableProperty` approach in the above commits.  She had to use `isPickableProperty` because `pickableProperty` is currently unallowed (sic), see `Tandem.UNALLOWED_TANDEM_NAMES`.

**Comment by pixelzoom** [comment]
@marlitas FYI... In the above commits, I expanded the doc for `isPickableProperty`, and added a link to this issue. Hope you don't mind...

**Comment by marlitas** [comment]
> I think if it would be preferrable/cleaner to have isPickableProperty in the view, rather than the model.

After looking at `SoccerBallNode.ts` a little more closely I actually hate that this multi-link is in the view and not the model...
```js
    // Prevent dragging or interaction while the object does not have a value (when it is not in the play area yet),
    // when it is animating, if input for this individual node is disabled, or if input for all the object nodes
    // has been disabled
    Multilink.multilink(
      [ soccerBall.soccerBallPhaseProperty, soccerBall.valueProperty, enabledProperty, soccerBallsEnabledProperty ],
      ( mode, value, selfInputEnabled, objectsInputEnabled ) => {
        const inputEnabled = value !== null && mode === SoccerBallPhase.STACKED && selfInputEnabled && objectsInputEnabled;

        // if input is disabled and the ball is in the play area, show the darker version
        const showEnabledSoccerBall = selfInputEnabled && objectsInputEnabled;
        const showDisabledSoccerBall = !showEnabledSoccerBall;
        soccerBallDarkNode.visible = showDisabledSoccerBall;
        soccerBallNode.visible = !showDisabledSoccerBall;

        this.inputEnabled = inputEnabled;
      } );
```

But we are past a refactor at this time so I agree isPickableProperty should move to the view... as much as I hate it 😅

**Comment by marlitas** [comment]
This should now be addressed and ready for code review as well as a check on main from @Nancy-Salpepi. Sending over to @pixelzoom for code review.

**Comment by pixelzoom** [comment]
👍🏻 Code looks good.

**Comment by Nancy-Salpepi** [comment]
Now I can move some balls in the launched sim--there is an issue with a stack of balls. They aren't all interactive (I see a regular cursor instead of the hand). Once more balls are kicked in the launched sim, the previously non-interactive balls become interactive.

Steps:
1. In Studio on any screen: Press the Kick 5 button
2. If no stacks formed, move a ball on top of another
3. Press the test button
4. Hover your mouse over all balls in a stack--try to move ones that don't have a hand cursor
5. Kick more balls in the launched sim
6. Hover mouse over the previously immovable balls --they is now interactive



https://github.com/phetsims/center-and-variability/assets/87318828/bc9b811d-4638-4f5d-921b-2ffbd43cb763

**Comment by pixelzoom** [comment]
@Nancy-Salpepi is the problem reported in https://github.com/phetsims/center-and-variability/issues/534#issuecomment-1718066614 indeed new, or was it present in 1.1.0-dev.14 (the version for https://github.com/phetsims/qa/issues/976)?

**Comment by pixelzoom** [comment]
Oh... Nevermind. I guess that's impossible to answer, since no balls were interactive in  1.1.0-dev.14.

**Comment by marlitas** [comment]
well that's a bummer.

What's happening is that the mouse and pointer areas aren't getting set at launch because the `stackChangedEmitter` isn't firing. I looked into firing a `stackChangedListener` at launch so that the mouse and pointer areas can be appropriately set. The other option is to instrument the bounds for the mouse and pointer areas of each soccer ball but that seems less than ideal since that would create hundreds of new Properties and add clutter to the studio tree.

I worked on a patch to try the first option, but I keep getting stuck because the `phaseProperty` doesn't change until after launch. This means I can't just run the function at start up at the end of the `SoccerSceneView` constructor, instead I would have to link it to the `phaseProperty` and then the function would run every time the `phaseProperty` changes. This also seems gross.

I'm not sure which way to go now. I don't like any of the solutions I've thought of, so I think it's time to bring in some more help. @pixelzoom any thoughts here?

<details>

```diff
Subject: [PATCH] Derive inputEnabledProperty from translationEnabled and mouse/keyboard dragging, see: https://github.com/phetsims/center-and-variability/issues/538
---
Index: js/view/SoccerSceneView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/view/SoccerSceneView.ts b/js/view/SoccerSceneView.ts
--- a/js/view/SoccerSceneView.ts	(revision 4d68325d7c23b93a175e5ddb94a79974609f65cc)
+++ b/js/view/SoccerSceneView.ts	(date 1694632493156)
@@ -114,8 +114,8 @@
     } );
 
     // Update pointer areas and soccer ball focus (for keyboard and interactive highlight) when topmost ball changes
-    sceneModel.stackChangedEmitter.addListener( stack => {
-
+    const stackChangedListener = ( stack: SoccerBall[] ) => {
+      console.log( stack );
       let bounds: Bounds2 | null = null;
 
       for ( let i = 0; i < stack.length; i++ ) {
@@ -157,7 +157,8 @@
         const focusedStack = sceneModel.getStackAtValue( focusedSoccerBallProperty.value.valueProperty.value! );
         focusedSoccerBallProperty.value = focusedStack[ focusedStack.length - 1 ];
       }
-    } );
+    };
+    sceneModel.stackChangedEmitter.addListener( stackChangedListener );
 
     backLayerSoccerBallLayer.addInputListener( {
       focus: () => {
@@ -305,6 +306,11 @@
 
     this.backSceneViewLayer = backLayer;
     this.frontSceneViewLayer = frontLayer;
+
+    // For PhET-iO the stackChangedListener needs to fire at launch in case state includes already stacked
+    // soccer balls.
+    console.log( sceneModel.getSortedStackedObjects() );
+    sceneModel.getStacks().forEach( stack => stackChangedListener( stack ) );
   }
 
   /**
Index: js/model/SoccerBall.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/model/SoccerBall.ts b/js/model/SoccerBall.ts
--- a/js/model/SoccerBall.ts	(revision 4d68325d7c23b93a175e5ddb94a79974609f65cc)
+++ b/js/model/SoccerBall.ts	(date 1694633447643)
@@ -94,6 +94,11 @@
       tandem: tandem.createTandem( 'soccerBallPhaseProperty' ),
       phetioReadOnly: true
     } );
+
+    this.soccerBallPhaseProperty.link( phase => {
+      console.log( this.index, phase );
+    } );
+
     this.dragPositionProperty = new Vector2Property( this.positionProperty.value.copy() );
     this.valueProperty = new SoccerBallValueProperty( null, {
       tandem: tandem.createTandem( 'valueProperty' ),
```
</details>

**Comment by pixelzoom** [comment]
@marlitas @matthew-blackman and I looked at this.  The problem is that nothing is listening to soccerBallPhaseProperty  and firing stackChangedEmitter based on phase change. Instead, things like animation are setting soccerBallPhaseProperty and then firing stackChangedEmitter.  (In general, if an Emitter fires and doesn't affect something statefu/instrumentedl, you'll have problems).

We could not identify a good solution to this problem, so started looking for any solution.

Below is a super dirty way to fire `stackChangedEmitter` when soccerBallPhaseProperty is restored. It seems to work. We're not sure whether  `soccerBall.valueProperty` will have been restored properly here.  And we'd prefer not to run this in PhET brand (perhaps guard with `Tandem.PHET_IO_ENABLED`?)  More work needs to be done here.

```ts
    sceneModel.soccerBalls.forEach( soccerBall => {
      const soccerBallPhaseListener = ( phase: SoccerBallPhase ) => {
        stackChangedListener( sceneModel.getStackAtValue( soccerBall.valueProperty.value! ) );
        soccerBall.soccerBallPhaseProperty.unlink( soccerBallPhaseListener );
      };
      soccerBall.soccerBallPhaseProperty.lazyLink( soccerBallPhaseListener );
    } );
```

**Comment by marlitas** [comment]
I checked in with @catherinecarter and she mentioned that having the hovering state change across the different stacks throughout your interaction with the sim seems like poor UX, and I agree. Her decision was to move forward with the fix with the unfortunate fact that it's really ugly code. I'm going to do a small investigation on linking to phaseProperty, but I'm going to cap it at 30 minutes. If it seems like it could be straightforward to adjust just for this... might be worth it? 

I'll update in this issue.

**Comment by marlitas** [comment]
Here's a patch of firing the `stackChangedEmitter` on the `phaseProperty` link... I actually think this is much better. Cleans up a couple of spots of code and was not very intrusive. I don't think we're unnecessarily calling `stackChangedEmitter` here. It feels about the same as before. 

<details>

```diff
Subject: [PATCH] Remove vestigial code, see: https://github.com/phetsims/center-and-variability/issues/521
---
Index: js/model/SoccerSceneModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/model/SoccerSceneModel.ts b/js/model/SoccerSceneModel.ts
--- a/js/model/SoccerSceneModel.ts	(revision 2731a9c7faa20c10d08453854bb62536d4f00ca8)
+++ b/js/model/SoccerSceneModel.ts	(date 1694729020000)
@@ -190,6 +190,14 @@
         this.objectValueBecameNonNullEmitter.emit();
       } );
 
+      soccerBall.soccerBallPhaseProperty.link( phase => {
+        if ( phase === SoccerBallPhase.STACKED ) {
+
+          assert && assert( soccerBall.valueProperty.value !== null, 'if a ball is STACKED it cannot have a value of null' );
+          this.stackChangedEmitter.emit( this.getStackAtValue( soccerBall.valueProperty.value! ) );
+        }
+      } );
+
       // We only want this to fire if the valueProperty of a ball is changed after it has landed.
       // If oldValue is null, it means that the ball is going from FLYING to STACKING,
       // in which case we want it to animate to the top of the stack.
@@ -566,7 +574,6 @@
 
     if ( otherObjectsInStack.length === 0 ) {
       soccerBall.soccerBallPhaseProperty.value = SoccerBallPhase.STACKED;
-      this.stackChangedEmitter.emit( [ soccerBall ] );
       this.objectChangedEmitter.emit();
     }
     else {
@@ -586,10 +593,6 @@
         // If the sim is cleared while the animation is in progress, do not signify the ball as being at the top of a stack
         if ( soccerBall.valueProperty.value !== null ) {
           soccerBall.soccerBallPhaseProperty.value = SoccerBallPhase.STACKED;
-
-          // Identify the soccer balls in the stack at the time the animation ended
-          this.stackChangedEmitter.emit( this.getActiveSoccerBalls().filter( x =>
-            x.valueProperty.value === value && x.soccerBallPhaseProperty.value === SoccerBallPhase.STACKED ) );
         }
 
         this.objectChangedEmitter.emit();
```
</details>

**Comment by marlitas** [comment]
@Nancy-Salpepi this has been addressed in the above commits. Can you test and see if all is working well on main?

**Comment by Nancy-Salpepi** [comment]
Working well on main!
