### ISSUE TITLE
Examples doc lists incorrect elements

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#535]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/976
```
centerAndVariability.variabilityScreen.model.playArea.soccerBallDragIndicatorModel.isDragIndicatorVisibleProperty
centerAndVariability.variabilityScreen.model.playArea.soccerBallDragIndicatorModel.valueProperty
```
These are both listed in the Examples doc, but do not exist in Studio. I believe `playArea` should be `soccerArea`.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Variability‬
URL: https://phet-dev.colorado.edu/html/center-and-variability/1.1.0-dev.14/phet/center-and-variability_all_phet.html
Version: 1.1.0-dev.14 2023-09-01 18:18:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language: en-US
Window: 1536x707
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by catherinecarter** [comment]
You are correct! We changed the name, playArea, so soccerArea after noticing there was conflicting naming with a11y. Thought I caught the all.

Changing them now. Thank you :)  Closing.
