### ISSUE TITLE
Unable to change kickDistributionStrategy to "skew"

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#536]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/976, I get an error message if I try to change the kickDistributionStrategy to "skew" or in the case of sceneKicker3Model to change the skewType to "right". 

**Steps to reproduce**
Here is an example:
1. Go to centerAndVariability.variabilityScreen.model.sceneKicker3Model.kickDistributionStrategy
2. Press Get Value button
3. change "right" to "left"
4. Press Set Value button 

**Visuals**
<img width="504" alt="Screenshot 2023-09-06 at 8 08 47 AM" src="https://github.com/phetsims/center-and-variability/assets/87318828/72532bff-cd78-4660-9d4c-c69eede1ff2e">

<img width="504" alt="Screenshot 2023-09-06 at 8 06 31 AM" src="https://github.com/phetsims/center-and-variability/assets/87318828/381797e6-2062-4f31-a9cc-06b81e214204">

**Comment by marlitas** [comment]
Addressed above. This was a pretty straightforward validation update, so just needs a check from @Nancy-Salpepi and then we can close. Should be on main :-)

**Comment by Nancy-Salpepi** [comment]
This looks fixed on main. Closing 🙂

**Comment by Nancy-Salpepi** [comment]
Sorry! I should have closed this!
