### ISSUE TITLE
Unable to extract statistical data with Safari

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#537]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/976, for some reason I can't get this example for the Variability screen to work in safari. @catherinecarter also had the same issue. We both had no issue with mac + chrome. 

`const sceneElement = await phetioClient.invokeAsync('centerAndVariability.variabilityScreen.model.selectedSceneModelProperty','getValue'); await phetioClient.invokeAsync(sceneElement.phetioID + '.meanValueProperty', 'getValue');`

<img width="1119" alt="Screenshot 2023-09-06 at 1 01 28 PM" src="https://github.com/phetsims/center-and-variability/assets/87318828/129db993-cd94-4037-8270-bcb81cb7f053">

I made sure the dropdown in the console said "studio" and I didn't have any other issues from the examples so far when I needed to paste into the console. For example, I had no issue with this:
`phetioClient.invoke('centerAndVariability.medianScreen.model.distanceAccordionBox.cardContainerModel.manuallySortedEmitter','addListener',[()=>console.log('hello')])`

**Comment by pixelzoom** [comment]
@marlitas Does `await phetioClient.invokeAsync` work for other cases on macOS+Safari?  I.e., have you determined that this is a problem with this specific command, and not a general problem with `phetioClient.invokeAsync`?

**Comment by pixelzoom** [comment]
@marlitas Can you provide some info on what the 2 commands above are supposed to return?  

I started the sim, went to the Median screen, and pressed the "Kick 5" button a couple of time.  Then I entered the above commands in the console, and here's what I see:

```
> phetioClient.invoke('centerAndVariability.medianScreen.model.distanceAccordionBox.cardContainerModel.manuallySortedEmitter','addListener',[()=>console.log('hello')])
< undefined
> const sceneElement = await phetioClient.invokeAsync('centerAndVariability.variabilityScreen.model.selectedSceneModelProperty','getValue'); await phetioClient.invokeAsync(sceneElement.phetioID + '.meanValueProperty', 'getValue');
< null
> sceneElement
< {phetioID: 'centerAndVariability.variabilityScreen.model.sceneKicker1Model'}
```

I do not see the error that was reported.

**Comment by catherinecarter** [comment]
I'll chime in here to provide some framing the command.

We decided to only have the command be active for the Variability screen for two reasons:
- it is the only screen with more than one scene, and the command is designed to give the statistical information for the active kicker
- we wanted to make it it easier for a client to get the information they wanted without having to find the associated value in the tree. Since the values for the statistical measures are so easy to find for the other two screens in the tree, we wanted to make it more convenient for the 3rd screen

The command worked for me in Chrome but not Safari. Does this help, @pixelzoom?

**Comment by pixelzoom** [comment]
I'm still confused.  I thought the difference in the 2 commands was `phetioClient.invoke` vs `await phetioClient.invokeAsync`.   Now I see that there is an additional difference -- which screen is involved.  

Using macOS+Chrome, I started the sim in Studio, went to the Variable screen, and pressed the "Kick 5" button a couple of time. Then I entered the command in the browser console, and here's what I see:

```
> const sceneElement = await phetioClient.invokeAsync('centerAndVariability.variabilityScreen.model.selectedSceneModelProperty','getValue'); await phetioClient.invokeAsync(sceneElement.phetioID + '.meanValueProperty', 'getValue');
<· 7.8
```

Doing the same thing in macsOS + Safari, I see the reported problem:

```
> const sceneElement = await phetioClient.invokeAsync('centerAndVariability.variabilityScreen.model.selectedSceneModelProperty','getValue');
< SyntaxError: Unexpected identifier 'phetioClient'. Expected ';' after variable declaration.
```

As the error message says, there's a syntax error with this command.  And Safari appears to being more strict about synatax.  There is no problem if I remove the assignment to `sceneElement` and enter:

```
> await phetioClient.invokeAsync('centerAndVariability.variabilityScreen.model.selectedSceneModelProperty','getValue')
<· undefined
[Info] {phetioID: "centerAndVariability.variabilityScreen.model.sceneKicker1Model"}
```

**Comment by pixelzoom** [comment]
@Nancy-Salpepi said:
> For example, I had no issue with this:
`phetioClient.invoke('centerAndVariability.medianScreen.model.distanceAccordionBox.cardContainerModel.manuallySortedEmitter','addListener',[()=>console.log('hello')])`

That's because it using `invoke` and not `invokeSync`, it's not using `await`, and it's not doing assignment (`=`).  If I use that command in the same way as the failing command, it also fails with the same SyntaxError:

```
> const foo = await phetioClient.invokeAsync('centerAndVariability.medianScreen.model.distanceAccordionBox.cardContainerModel.manuallySortedEmitter','addListener',[()=>console.log('hello')])
< SyntaxError: Unexpected token ';'. const declared variable 'foo' must have an initializer.
```

**Comment by pixelzoom** [comment]
Here's another example, with an entiredly different phetioID.  Start the sim in Studio, then enter the following command browser console.

macOS + Chrome:
```
> const foo = await phetioClient.invokeAsync('centerAndVariability.medianScreen.model.sceneModel.numberOfQueuedKicksProperty', 'getValue' )
< undefined
> foo
< 0
```

macOS + Safari:

```
> const foo = await phetioClient.invokeAsync('centerAndVariability.medianScreen.model.sceneModel.numberOfQueuedKicksProperty', 'getValue' )
🛑 SyntaxError: Unexpected token ';'. const declared variable 'foo' must have an initializer.
```

**Comment by pixelzoom** [comment]
I'm not sure what the correct syntax is for `= await` in Safari.  But I suspect that this may involve updating public-facing PhET-iO documentation.

**Comment by pixelzoom** [comment]
` invokeAsync` appears to be declared properly in Client.ts.  It's `async` and returns `Promise`, so it should work with `await`.  Is the fact that it's a method instead of a `function` a problem?

```
public async invokeAsync<T>( phetioID: PhetioID, method: string, args: IntentionalAny[] = [] ): Promise<T> {
```

**Comment by pixelzoom** [comment]
The problem with using `const foo = await` is that a const must be initialized at the time the it's declared.  And it's technically not initialized because await returns a value asynchronously.   If you `let foo = await`, then there's no problem. For example:

```
> let foo = await phetioClient.invokeAsync('centerAndVariability.medianScreen.model.sceneModel.numberOfQueuedKicksProperty', 'getValue' )
< undefined
[Info] 0
```

I've moved the issue of updating PhET-iO documentation to https://github.com/phetsims/phet-io-sim-specific/issues/34.

@marlitas if there's nothing else to do here, please close.

**Comment by marlitas** [comment]
@pixelzoom that was really helpful, and I appreciate your investigation here. It does seem like all we need to do is update the documentation in examples.md to be something like the following:

- `let sceneElement = await phetioClient.invokeAsync('centerAndVariability.variabilityScreen.model.selectedSceneModelProperty','getValue')`
- Separately enter: `await phetioClient.invokeAsync(sceneElement.phetioID + '.meanValueProperty', 'getValue');`
- Not sure if that's clear enough for examples.md. Let's chat about it @catherinecarter

**Comment by samreid** [comment]
Please be aware @zepumph and @samreid are working on this in the context of https://github.com/phetsims/phet-io-sim-specific/issues/34

**Comment by marlitas** [comment]
I think this is ready to go for CAV, but want to make sure there are no further documentation changes after the meeting mentioned in https://github.com/phetsims/phet-io-sim-specific/issues/34. Waiting to close until then.

**Comment by samreid** [comment]
No more changes were necessary in https://github.com/phetsims/phet-io-sim-specific/issues/34, feel free to close.
