### ISSUE TITLE
Empty focus highlight for the cards

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/center-and-variability#544]
While looking into https://github.com/phetsims/center-and-variability/issues/530 I noticed that there is an empty focus highlight for the cards, I wasn't sure if it was intentional, assigning to @marlitas and @matthew-blackman,

![image](https://github.com/phetsims/center-and-variability/assets/6396244/86dce617-4ff9-477e-87b3-d61eaec108c2)

**Comment by marlitas** [comment]
Yes, whenever it is empty we still want to highlight the area where a card will be once data gets filled in. Thanks for checking!
