### ISSUE TITLE
Variability kicker ends kicking pose too soon when ball lands right after kick

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/center-and-variability#547]
@marlitas and I made some changes to the kicker array in the Variability screen when working on https://github.com/phetsims/center-and-variability/issues/530. Overall we feel that the changes are an improvement, but have created a bug with the kicker pose.

To reproduce - In the variability screen, kick multiple balls. If a ball happens to land right after the kicker has kicked, they will immediately go to the READY pose, instead of staying in the KICKING pose until the next kick is ready.

See video below. Left side is the version on main with this behavior visible, and the right side is the dev build not showing this behavior.

https://github.com/phetsims/center-and-variability/assets/108756567/19850f54-19c9-4e4a-9a98-f2b3168b68e8

**Comment by samreid** [comment]
Good catch @matthew-blackman, @marlitas and I observed that the logic checking "was the soccer player associated with a soccer ball" is different for single kicker scene, so we updated that part.  @matthew-blackman can you please spot check and test?

**Comment by matthew-blackman** [comment]
This is looking great on main. Reviewed commit [74c93f8](https://github.com/phetsims/soccer-common/commit/74c93f8ac8c9804da91e33d15916abb759a3cea9) - the changes make sense and are well-documented. Separating the logic for single-kicker scenes makes for good readability and maintainability for future devs. All looks well - closing.
