### ISSUE TITLE
Incorrect doc for IntervalToolNode.ts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#548]
Noted while working on https://github.com/phetsims/center-and-variability/issues/538 ...

This documentation at the top of IntervalToolNode.ts does not look correct:

```ts
/**
 * Shows the highlighted area for the interval tool in the play area.
 *
 * @author Sam Reid (PhET Interactive Simulations);
 */
```

**Comment by matthew-blackman** [comment]
Over to you for review @pixelzoom - feel free to close if good.

**Comment by pixelzoom** [comment]
Looks great. Closing.
