### ISSUE TITLE
SoccerBallPhase needs documentation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#549]
While working on https://github.com/phetsims/center-and-variability/issues/534, I had to get into the states of a soccer ball.  Unfortunately there is no documentation in SoccerBallPhase.ts, see below.  This hampered my progress. Please document the semantics of each of these phases.  Including @samreid on assignees, since he's one of the original authors.

```ts
export class SoccerBallPhase extends EnumerationValue {
  public static readonly INACTIVE = new SoccerBallPhase();
  public static readonly READY = new SoccerBallPhase();
  public static readonly FLYING = new SoccerBallPhase();
  public static readonly STACKING = new SoccerBallPhase();
  public static readonly STACKED = new SoccerBallPhase();

  public static readonly enumeration = new Enumeration( SoccerBallPhase );
}
```

**Comment by matthew-blackman** [comment]
I will give this a go.

**Comment by pixelzoom** [comment]
Excellent. Closing.
