### ISSUE TITLE
Set fireOnHold to true

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#550]
This will track the commit for allowing keyboard listener to fire when a key is held down.

**Comment by marlitas** [comment]
This was a straightforward code change, but I do want to make sure it didn't introduce any craziness in behavior or interactions we're not thinking of so I would like to keep this open for the next QA test.

Over to @catherinecarter first.

**Comment by catherinecarter** [comment]
Seems to be working perfectly when I tested it. Nice suggestion, @Nancy-Salpepi!

**Comment by marlitas** [comment]
I'll unassign @Nancy-Salpepi for now, and just flag this as an issue that we'll want to reference in the next dev test.

**Comment by Nancy-Salpepi** [comment]
For https://github.com/phetsims/qa/issues/985:
When pressing down the arrow key to move a card, the card speeds up drastically when it get closer to either end. This looks especially odd when zoomed in. 
Here is the non-zoomed version:

https://github.com/phetsims/center-and-variability/assets/87318828/091b6b45-f3cf-4804-bd69-68544418eaef

**Comment by marlitas** [comment]
I would love to get @catherinecarter's opinion on the priority of this problem. The interactions in the cards are rather complicated especially when it comes to keyboard interaction. @catherinecarter how much time would you like me to spend investigating this? I have a feeling this could go down a rabbit hole and I don't know how big of a concern it is right now.

If it is a large concern, the other option is to remove auto-firing when a keypress is held down for the cards.

**Comment by catherinecarter** [comment]
I agree that this is distracting and seems strange that the card would gain speed when moving towards the end. Not sure why that's happening.

I think spending maybe 15 minutes investigating would make sense, but not much more than that. I worry that changing anything in the cards could inspire a domino effect and create more issues down the road, especially since the code is complicated as is. 

If earlier in the process, I think spending more time would make sense to fix it, but since we're trying to get this published, I'm ok accepting the behavior as is if it takes longer than 15 minutes or would create more problems by fixing.

Does this sound reasonable? Thanks!

**Comment by marlitas** [comment]
@catherinecarter, very reasonable. I'll take a look today and report back.

**Comment by KatieWoe** [comment]
Noting that the sped up movement does not seem to happen when moving soccerballs.

**Comment by marlitas** [comment]
My first area of investigation was to see how frequently `swapCards()` was firing. This seems to be at a consistent rate when `fireOnHold` is activated.

<img width="535" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/d1475f0a-ad3c-4b2e-ac50-d229b55b0c6a">

**Comment by marlitas** [comment]
My next theory was that because the amount of `displacedCards` goes down the closer we get to the end, the less we have to iterate over and animate. However logging did not seem to indicate this was causing the hold up at the beginning/ speed up at the end.

<img width="784" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/e2c39182-3d82-47d0-ae75-eb4c718be6a4">


And having displacedCards go directly home instead of `animateToHomeCell` confirmed that this is not the hold up.

```js
displacedCards.forEach( ( card, index ) => {
          card.model.indexProperty.value = displacedIndexes[ index ];
          model.setAtHomeCell( card.model );
          console.log( Date.now() - lastDate, 'displaceCard Animating' );
        } );
```

**Comment by marlitas** [comment]
I removed animation from the focused card and that did indeed remove the speed ramping effect.

I created a query parameter `removeFocusedCardAnimation`, that when included will show the behavior that fixes the bug (the focused card will immediately snap to it's `homeCell` rather than animating to it). The difference looks pretty subtle to me, but I recommend that @catherinecarter take a look and see which she prefers.

This would be good for @Nancy-Salpepi to test and see if there's anything odd from that change as well. 

If we would rather remove the animation to fix this bug, let me know and I can remove the query parameter and make `setAtHomeCell` the default.

**Comment by Nancy-Salpepi** [comment]
@marlitas with the query parameter the screen no longer pans when moving the card with alt input.

**Comment by marlitas** [comment]
We met today and decided we liked it! We're going to remove the animation for the focused card.

**Comment by marlitas** [comment]
Done above! This was actually really nice because we got to remove some code complexity with `animatedPanZoomListener` here. I like it.

Over to @Nancy-Salpepi to check on main. Was relatively straightforward so shouldn't need a code review.

**Comment by Nancy-Salpepi** [comment]
Looks good to me! Closing.
