### ISSUE TITLE
Icons for character sets need updating

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#553]
@marlitas noticed that all the character icons next to the localization choices in the Preferences dialog are currently all the same: 

<img width="324" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/735e1fd4-7ad5-4705-8c49-86dda4be2815">

These will need to be updated with a character more representative of the locale being chosen. 

For Africa, let's use Player 07: 
<img width="96" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/e4783dfc-4066-4d19-97ff-44f909220308">

For Africa modest, let's use Player 03 from the Africa set.
<img width="106" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/ed010d80-54b7-4a01-b7a2-a77ce303b968">

Or, if anyone thinks a different character would look better, please feel free to adjust :)

**Comment by marlitas** [comment]
This has been addressed in the above commits. 

@catherinecarter let me know what you think. There is currently no standard for the headshot icon size in the regionAndCulture combo box, so I did my best to match to what I saw in Energy Skate Park.

Over to @matthew-blackman or @samreid for review.

**Comment by catherinecarter** [comment]
Everything looks great to me, too. Sizes of the icons look good and consistent with each other.
