### ISSUE TITLE
Change sound on soccer balls when Median or Mean checkbox is checked

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#559]
The current behavior of the soccer ball sounds is:
- the number line sound plays for each tick mark along the line when a ball lands or is moved to a new location
- on the Median screen, 
   - the sound of the number line location is heard when a ball lands or is moved to a new location when no boxes are checked
   - when the Median checkbox is checked, the median sound is the one heard rather than the actual location of a ball when a ball is moved to a new location
- on the Mean & Median screen, 
   - the sound of the number location is heard when no checkboxes are checked, when a ball lands or is moved
   - when the Median checkbox is checked, the same behavior described above happens
   - when the Mean checkbox is checked, the sound of the mean is heard when a ball is moved to a new location
   - when both checkboxes are checked
      - when a ball lands, the sound of the number line landing location is heard
      - when a ball is moved, the sound of the number line location is heard (rather than highlighting the mean or median) 

Due to the inconsistent behavior of the sounds when a ball is moved along the number line, the focus on the mean and median is potentially confusing. While pedagogically powerful to have a visual and auditory cue of the mean and median's location, it seems to make more sense to be consistent with the sounds.

So... I'd like to remove the focused sound on mean or median when those checkboxes are checked. Summarizing: 
- the number line location sound will be heard when a ball is moved to a new location or when a ball lands, regardless of whether any checkboxes are checked
- when one of the checkboxes is checked, the sound of the mean/median will play, but only when first checked

Hopefully that makes sense. Please let me know if this is confusing. Thanks!

**Comment by Nancy-Salpepi** [comment]
Also, noting that in https://github.com/phetsims/qa/issues/985 when the median or mean checkboxes were checked, the sound was muted when moving the soccer balls.

**Comment by marlitas** [comment]
This has been addressed in the above commit. Over to @catherinecarter and @Nancy-Salpepi for review.

**Comment by Nancy-Salpepi** [comment]
Sounds good to me on main --the number line sound is always heard when moving the balls and it isn't muffled. When I check the Mean checkbox, the Mean sound is slightly muffled, but since it is the only time I hear it, I don't think it is a big deal. Over to @catherinecarter 🙂.

**Comment by catherinecarter** [comment]
Agreed. While I'm sad to get rid of this feature, I think it was the right call. Thanks!

**Comment by marlitas** [comment]
Of course! Closing this issue as completed.
