### ISSUE TITLE
Interval tool no longer translates

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#560]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5.2

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/985, on the Variability Screen, the Interval tool no longer translates. When I click on the center of the highlighted area and attempt to drag it, the handle moves and the size of the interval changes. 

**Steps to reproduce**
1. On the Variability screen, check the Interval Tool.
2. Place your cursor in the center and attempt to move it.
--This also happens with alt input

**Visuals**

https://github.com/phetsims/center-and-variability/assets/87318828/930dc8d4-e1c2-492d-8d62-a7583a871278

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Variability‬
URL: https://phet-dev.colorado.edu/html/center-and-variability/1.1.0-dev.15/phet/center-and-variability_all_phet.html
Version: 1.1.0-dev.15 2023-09-25 23:06:33 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15
Language: en-US
Window: 1378x711
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by marlitas** [comment]
Woah... that's weird... Let me check this one and potentially get you a new dev build.

**Comment by marlitas** [comment]
Awkward... it was totally me. I thought I tested when I was addressing a CT issue, but apparently something went awry there.

Fix is pushed to main. @Nancy-Salpepi would you like a new dev build? The changes are isolated to the interval tool, but we might want to do more testing with the interval tool translation? I'm not sure what would be best for QA's time here.

**Comment by Nancy-Salpepi** [comment]
Fixed on main.
It would be good to be able to test this tool in PhET-iO so I guess a new dev version would work. 
I think I am the only one that has tested so far. I am going to assume all the issues I opened still hold true if that is OK @marlitas?

**Comment by marlitas** [comment]
This is now ready for review.

**Comment by marlitas** [comment]
This was reviewed with @samreid and @matthew-blackman. We feel these changes are good, but did see that the CT error in https://github.com/phetsims/center-and-variability/issues/556 was still coming up. I'll go ahead and close this issue, and reopen that one.
