### ISSUE TITLE
Character Set Icons are buggy

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#561]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5.2

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/985, the body of the character appears once you select a different character set. 

**Steps to reproduce**
1. In the preferences menu select African Character Set
2. Open the combo box again and select a different character set

**Visuals**

https://github.com/phetsims/center-and-variability/assets/87318828/46cf425d-318c-4b58-9f42-62ceca46682b

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Variability‬
URL: https://phet-dev.colorado.edu/html/center-and-variability/1.1.0-dev.15/phet/center-and-variability_all_phet.html
Version: 1.1.0-dev.15 2023-09-25 23:06:33 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15
Language: en-US
Window: 1378x711
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by marlitas** [comment]
Hmmm... I'm not able to reproduce this on chrome checking on Safari next.

**Comment by marlitas** [comment]
Yeah this seems to be a bug specific to Safari... It's like the clip area disappears for some reason? I'm going to try to do some debugging on Safari, but I'm not as familiar with browser specific bugs so may need to bring in some help.

**Comment by marlitas** [comment]
I tried to do some logging to see if the `clipAreaProperty` ever got overwritten, or was changing for some reason. I could not find it. It seems like the bounds calculations are remaining intact since the layout of the comboBox isn't changing. This feels render specific and I don't know where to go from here. 

Tagging @samreid as a potential helper in this, but open to any dev help from team phrench-phries.

**Comment by marlitas** [comment]
This was an easier fix than expected. @samreid and I switched the renderer for HeadshotIcon to `canvas`. Seems to be working well in both Safari and Chrome now. Over to @Nancy-Salpepi to double check on main.

**Comment by Nancy-Salpepi** [comment]
Looks good on main with mac + safari/chrome and on the iPad.
