### ISSUE TITLE
Character Sets don't change for Variability Screen

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#562]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5.2

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/985, on the Variability Screen the characters are the same no matter which set I choose in the Localization Tab. 

**Steps to reproduce**
1. Go to the Variability Screen and look at the 4 characters
2. In the preferences menu, choose the Africa character set--the 4 characters are still the same
3. Choose the Africa (modest) character set --the 4 characters are still the same

**Visuals**

<img width="667" alt="Screenshot 2023-09-27 at 1 58 14 PM" src="https://github.com/phetsims/center-and-variability/assets/87318828/3279ab16-7868-4854-9146-8f69bcd68d0c">

**Comment by Nancy-Salpepi** [comment]
The characters are listed [here](https://github.com/phetsims/center-and-variability/issues/523#issuecomment-1707073140)

**Comment by marlitas** [comment]
This has been addressed in the above commit. Thanks @Nancy-Salpepi! Can you check that this looks fixed on main?

**Comment by Nancy-Salpepi** [comment]
Looks good @marlitas! Closing.
