### ISSUE TITLE
Command + 0 to reset zoom moves ball at the same time on MacOS

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/center-and-variability#563]
For https://github.com/phetsims/qa/issues/985, if I zoom out while a soccer ball still has focus, the ball moves to a different position.

Steps: 
1. Zoom in
2. Tab to and grab the leftmost soccer ball
3. Move the ball to the opposite side of the number line
4. Zoom out (command + 0 on a mac) while the ball still has focus --you will see the ball moves to a different spot and its corresponding card is changing location

https://github.com/phetsims/center-and-variability/assets/87318828/38eaecc6-e270-4bea-a682-afd61869fb7d

_Originally posted by @Nancy-Salpepi in https://github.com/phetsims/center-and-variability/issues/539#issuecomment-1737882727_

**Comment by jessegreenberg** [comment]
I believe this is a failure of the KeyStateTracker, and specific to MacOS, where the meta keys are not in a list used by `areKeysDownWithoutExtraModifiers`. Added in the above commit. I was not able to test on MacOS though.

@Nancy-Salpepi can you please confirm this is fixed? It turns out Firefox has different codes for the command key, can you please make sure this is fixed in Safari, Chrome, and Firefox?

**Comment by Nancy-Salpepi** [comment]
looks good in all 3 browsers on the mac. Thanks @jessegreenberg!
