### ISSUE TITLE
Sort Data Animation occurs when sim is launched in Studio/State

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#566]
**Test device**
MacBook Air M1 chip

**Operating System**
14.0

**Browser**
Safari 17

**Problem description**
For https://github.com/phetsims/qa/issues/985 in the Studio and State wrappers:
On the Median Screen, with Sort Data checked the sim will launch with the Sort Data Checkbox Animation and Sound. Pressing Reset All will also cause the animation/sound to occur. 

**Steps to reproduce**
In Studio:
1. On the Median Screen, press the Kick 5 button
2. Check the Sort Data checkbox
3. Press Test
4. In the Standard PhET-iO wrapper, press the Reset All button

**Visuals**
Video using the State wrapper (sorry I didn't record with sound):

https://github.com/phetsims/center-and-variability/assets/87318828/63936142-4b60-41a9-980d-78092a85c6da

**Comment by marlitas** [comment]
This should be fixed on main now. Over to you @Nancy-Salpepi!

**Comment by Nancy-Salpepi** [comment]
Looks good in Studio and State wrappers on main!
