### ISSUE TITLE
Ball Cueing Hand disappears and then reappears in launched sim 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#567]
**Test device**
MacBook Air M1 chip

**Operating System**
14.0

**Browser**
Safari 17

**Problem description**
For https://github.com/phetsims/qa/issues/985, in Studio if I set `soccerBallDragIndicatorModel.isDragIndicatorVisibleProperty` to true and then kick another ball in the launched sim, the cueing hand will disappear. It will reappear once all of the balls are kicked. 

**Steps to reproduce**
Ex from the Median Screen:
1. In Studio, Press the Kick 5 button once on the Median Screen
2. Set `centerAndVariability.medianScreen.model.soccerArea.soccerBallDragIndicatorModel.isDragIndicatorVisibleProperty` to true
3. Press Test
4. In the Standard PhET-iO wrapper, Press Kick 1 -- the cueing hand disappears
5. Kick the rest of the balls --the cueing hand reappears

**Visuals**

https://github.com/phetsims/center-and-variability/assets/87318828/696e8ea7-d089-4a79-8bc9-0ee27e5b1a96

**Comment by marlitas** [comment]
I got to a reasonably working patch, but there are definitely some quirky edge cases:

- When setting the visibility of the hand to true in studio and all the balls have not been kicked it's value will be `null`. Which means it just appears floating in a corner behind the accordionBox. This seems like something that could be put in `examples.md` like: "you just need to give it a value" (This technically was happening anyways if no balls were kicked).
- Once you load the wrapper the hand will stay in the stack it's assigned to unless the stack it's assigned to is the median. I don't know if we can avoid this one and it can be jarring depending on the setup.

 We should talk about them as a team. I predict that fully solving the above scenarios will open up more sticky situations and code complexity...

<details>

```diff
Subject: [PATCH] drag cue
---
Index: js/model/DragIndicatorModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/model/DragIndicatorModel.ts b/js/model/DragIndicatorModel.ts
--- a/js/model/DragIndicatorModel.ts	(revision 9f7d68577bcd8efba85522150a07a73488ac0439)
+++ b/js/model/DragIndicatorModel.ts	(date 1696026497914)
@@ -66,16 +66,19 @@
 
     //  if an object was moved, objects are not input enabled, or the max number of balls haven't been kicked out
     //  don't show the dragIndicatorArrowNode
-    this.isDragIndicatorVisibleProperty.value = !this.soccerBallHasBeenDraggedProperty.value &&
+    this.isDragIndicatorVisibleProperty.value = soccerBallCount !== 0 &&
+                                                !this.soccerBallHasBeenDraggedProperty.value &&
                                                 !this.isKeyboardFocusedProperty.value &&
-                                                soccerBallCount === maxKicks &&
+                                                ( this.isDragIndicatorVisibleProperty.value || soccerBallCount === maxKicks ) &&
                                                 this.soccerBallsEnabledProperty.value &&
-                                                _.every( sceneModel?.getActiveSoccerBalls(), soccerBall => soccerBall.valueProperty.value !== null );
+                                                ( this.isDragIndicatorVisibleProperty.value || _.every( sceneModel?.getActiveSoccerBalls(), soccerBall => soccerBall.valueProperty.value !== null ) );
 
     const reversedBalls = sceneModel.getActiveSoccerBalls().filter( soccerBall => soccerBall.valueProperty.value !== null ).reverse();
 
     // Show the drag indicator over the most recently landed ball
-    this.valueProperty.value = reversedBalls.length > 0 ? reversedBalls[ 0 ].valueProperty.value : null;
+    this.valueProperty.value = !this.isDragIndicatorVisibleProperty.value ? null :
+                               this.valueProperty.value !== null ? this.valueProperty.value :
+                               reversedBalls.length > 0 ? reversedBalls[ 0 ].valueProperty.value : null;
   }
 
   public reset(): void {
```
</details>

**Comment by marlitas** [comment]
We met today and @catherinecarter is going to do some more research before coming to a decision.

**Comment by catherinecarter** [comment]
I spoke with @arouinfar, @amanda-phet, and @kathy-phet, and after weighing pros and cons, we are all in agreement to remove the ability to set the visibility and location of the cueing hand/arrow on the soccer balls. We will readdress this if a client asks for this feature to be implemented.

Hopefully this cleans up many issues surrounding the behavior of the cue, as well as simplifies the code. Let me know what else is needed from me.

**Comment by marlitas** [comment]
Okay all of the related phet-io Properties should now be set to readonly. Over to @catherinecarter and @Nancy-Salpepi to check on main. Feel free to close if all looks good!

**Comment by Nancy-Salpepi** [comment]
Looks good to me on main.

**Comment by catherinecarter** [comment]
The behavior is working as expected. While not featured, I noticed `centerAndVariability.meanAndMedianScreen.model.soccerArea.soccerBallDragIndicatorModel.soccerBallHasBeenDraggedProperty` is `readOnly=false` - should this be `readOnly=true`?

**Comment by catherinecarter** [comment]
I guess I can see an instructional designer wanting to turn off the cueing hand, so there's probably no harm in leaving it `readOnly = false`. 

Let's leave it as is, unfeatured and able to be set by the user. Thanks for checking.

**Comment by marlitas** [comment]
Sounds good. I'm closing this issue as completed.
