### ISSUE TITLE
phetioID changes needed for examples.md

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#568]
For https://github.com/phetsims/qa/issues/985

In the examples doc under "Handle" the phetioIDs for handle1ValueProperty  and handle2ValueProperty are now:

`centerAndVariability.variabilityScreen.model.intervalToolModel.handle1ValueProperty`
`centerAndVariability.variabilityScreen.model.intervalToolModel.handle2ValueProperty`

**Comment by catherinecarter** [comment]
The examples.md doc has been updated. Thanks, @Nancy-Salpepi. Closing.
