### ISSUE TITLE
Please make visibleProperty for the handles PhET-iO featured. 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#569]
For https://github.com/phetsims/qa/issues/985

The examples.md includes directions on how to hide the handles for the interval tool, but those phetioIDs are not featured:
`centerAndVariability.variabilityScreen.view.intervalToolNode.handle1.visibleProperty`
`centerAndVariability.variabilityScreen.view.intervalToolNode.handle2.visibleProperty`

I discussed this with @catherinecarter on Slack and she would like them featured. Thanks!

**Comment by catherinecarter** [comment]
Thanks, @Nancy-Salpepi. I'm tagging this issue (https://github.com/phetsims/phet-io-sim-specific/issues/21) as it seems to already be a discussion point for when changes happen between the time the items have been featured/`phetioID`s have been set and the time when code review/publishing happens. 

Perhaps we can tag this onto the PhET-iO design review process? Seems like it might be worthy of exploring.

**Comment by marlitas** [comment]
Addressed in the above commit. Over to @Nancy-Salpepi to check on main.

This doesn't need code review, but @catherinecarter would you like to keep it open for the PhET-iO design doc?

**Comment by Nancy-Salpepi** [comment]
Looks good on main.

**Comment by catherinecarter** [comment]
Yes, let's keep it open for a bit. @arouinfar is working on refining the review process and will take a look. Thanks!

**Comment by arouinfar** [comment]
Thanks, everyone! I've made a note to include this in the PhET-iO design process documentation, so I'll go ahead and close.
