### ISSUE TITLE
Random skew isn't working properly 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#570]
**Test device**
MacBook Air M1 chip

**Operating System**
14.0

**Browser**
Safari 17

**Problem description**
For https://github.com/phetsims/qa/issues/985, on any screen, if the sim is launched with a Random Skew Kick Distribution Strategy, the `skewType` (left or right) doesn't change on Reset All. 

For example, if this was the state on launch:
<img width="258" alt="Screenshot 2023-10-02 at 10 58 35 AM" src="https://github.com/phetsims/center-and-variability/assets/87318828/7f6f6728-630f-4103-8cfd-b7c9fcf9a485">

Then every time I press Reset All, the `skewType` will be left. 
@catherinecarter confirmed that she sees the same thing.

**Steps to reproduce**
Here is an example:
1. In Studio, go to `centerAndVariability.meanAndMedianScreen.model.sceneModel.kickDistributionStrategy` and note the `skewType`.
2. Press Test
3. Kick 15 balls --it will match the skewType listed
4.  Press Reset All
5. Keep repeating steps 3 and 4-- the skewType won't change back and forth between left and right.

**Comment by marlitas** [comment]
The skewType was getting overwritten after reset when applying the stateObject. This should be fixed now. I would like to confirm with @samreid that this is an appropriate way to handle the situation in the code.

Over to @Nancy-Salpepi to confirm all is looking well on main.

**Comment by Nancy-Salpepi** [comment]
Looks good on main 🙂.

**Comment by catherinecarter** [comment]
I tested it, too, and it looks good from my end :) Incredible catch, @Nancy-Salpepi!

**Comment by marlitas** [comment]
After code review yesterday @samreid pointed out some bugs with the implementation I had recommended, so we came up with a better solution that covers all the bases. @Nancy-Salpepi can you double check this one more time? It looks good on our end, but want to make we aren't missing anything. Thanks!

**Comment by Nancy-Salpepi** [comment]
The skew type randomly changes on reset all.

@marlitas @catherinecarter if I press the Eraser button each time instead of Reset All, the skewType remains the same. Is that what you wanted?

**Comment by catherinecarter** [comment]
@Nancy-Salpepi - yes. If a user presses erase, it should remove the soccer balls from the field, but everything else will remain as is. The "everything else" includes checkbox status, prediction pointer positions on the number line, skew type, etc.

Thanks for asking :)

**Comment by marlitas** [comment]
Great! That sounds to me like things are working well. I'll go ahead and close, feel free to reopen if there's anything else!
