### ISSUE TITLE
Ability to focus on cards lost

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#573]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/985
If your mouse moves while navigating the cards on the first screen the "inner" focus on one of the cards will disappear. Focus remains over all the cards, but you can't select or move any. To get that back focus needs to leave the cards and come back. This is very easy to do, the first time I saw it I had just bumped my desk.
**Steps to reproduce**
1. Use keyboard nav to focus on the cards on the first screen
2. Jiggle the mouse a bit, without clicking

**Visuals**
![loosefocus](https://github.com/phetsims/center-and-variability/assets/41024075/25a627e4-b8de-4a7d-a5e9-73f28f1023b6)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Variability‬
URL: https://phet-dev.colorado.edu/html/center-and-variability/1.1.0-dev.16/phet/center-and-variability_all_phet.html
Version: 1.1.0-dev.16 2023-09-27 19:58:34 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language: en-US
Window: 1280x643
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by marlitas** [comment]
Yeah. This might be a tricky one to solve. The reason this is happening is because of focus changes we had to implement for https://github.com/phetsims/center-and-variability/issues/406. We forcibly remove keyboard focus to both avoid flickering, and to prevent a card from staying in an "up" position when switching between keyboard focus highlight and interactive highlight. https://github.com/phetsims/center-and-variability/issues/460

In order to solve this we would have to be okay with flickering in the cards when using interactive highlight... This might be a good issue to discuss as a group.

**Comment by jessegreenberg** [comment]
Hmm, I thought this bit was supposed to handle that case: https://github.com/phetsims/center-and-variability/blob/dbca77e12801c429c4a4ad570b9a3b6eea83edf9/js/median/view/InteractiveCardNodeContainer.ts#L346-L354

I am wondering if it isn't in the right spot, should it be outside of this if statement?
https://github.com/phetsims/center-and-variability/blob/dbca77e12801c429c4a4ad570b9a3b6eea83edf9/js/median/view/InteractiveCardNodeContainer.ts#L305-L306

**Comment by marlitas** [comment]
Oh you're so right @jessegreenberg. Thanks for reminding me about that. I found that we need to add that guard in the `else` of that `if` you mentioned.

**Comment by marlitas** [comment]
@KatieWoe this should be ready to test on main now.

**Comment by KatieWoe** [comment]
Looks ok on main
