### ISSUE TITLE
Arrow remains even when ball is moved with focus

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#575]
I noticed that the cueing arrow on the balls does not disappear when a ball is first moved to the ends or in larger steps: 

https://github.com/phetsims/center-and-variability/assets/109630002/216abb4a-8499-44d9-a010-a50f67985852

At the end, I moved the ball with a single right arrow key, and the cueing arrow disappeared.

**Comment by marlitas** [comment]
Thanks for catching that! Should be updated now.

**Comment by catherinecarter** [comment]
Looks good to me. Thanks for the quick fix :)
