### ISSUE TITLE
Humming continues if you switch screens

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#579]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/993
When the screen is changed while the interval tool's hum is still playing, the sound continues as a consistent hum until the Variability screen is returned to. This was seen/heard during fuzz tests as well.
**Steps to reproduce**
1. Go to the variability screen and turn on the interval tool
2. Drag one of the ends of the tool to create it's sound
3. Before the sound ends, switch screens. This needs to be done quickly, but is relatively easy to do.

**Visuals**

https://github.com/phetsims/center-and-variability/assets/41024075/9733e593-eb18-4a89-8110-da461cd5d983

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Variability‬
URL: https://phet-dev.colorado.edu/html/center-and-variability/1.1.0-rc.1/phet/center-and-variability_all_phet.html
Version: 1.1.0-rc.1 2023-10-09 18:59:20 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language: en-US
Window: 1536x707
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by marlitas** [comment]
Worked on a good solution with @zepumph. This issue is now ready for cherry-pick.

**Comment by KatieWoe** [comment]
Looks good in rc.2
