### ISSUE TITLE
Extra focus highlight in median info dialog

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#584]
**Test device**
MacBook Air M1 chip

**Operating System**
14.0

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/993, I am able to tab to the cards in the median info dialog. 

**Steps to reproduce**
1. On the Median Screen, tab to and open the info dialog
2. Press tab

**Visuals**
<img width="1440" alt="Screenshot 2023-10-16 at 8 15 10 AM" src="https://github.com/phetsims/center-and-variability/assets/87318828/c2986581-9a56-4245-9e9b-9cbfe8bb07d6">

**Comment by marlitas** [comment]
Fixed above. Over to @samreid or @matthew-blackman for review.

**Comment by samreid** [comment]
I'll review this

**Comment by samreid** [comment]
Code change and runtime behavior look great. I'll label as ready for cherry-pick.

**Comment by Nancy-Salpepi** [comment]
looks good in rc.3
