### ISSUE TITLE
Possible to focus on non-kicked ball with keyboard nav

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#587]
**Test device**
Chromebook/MacBook Air M1 chip

**Operating System**
macOS14.0

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/993, if I change 'Max Kicks' in the preferences menu after kicking a ball with keyboard nav, I can then focus on and change the value of the ball in front of the player on the Median Screen. Pressing either Kick button after that will result in the wrong number of cards displayed. No further kicks are possible afterwards. 
The ability to focus and grab the non-kicked ball occurs on all screens. 

**Steps to reproduce**
1. On the Median screen, press the Kick 1 button with alt input 
2. In the preferences menu change the number of Max Kicks to 5
3. Use alt input to return to the Soccer Area --there will be a highlight around the non-kicked ball 
4. Grab the ball and press the right arrow key--a card appears showing its value changing
5. Navigate to the Kick 1 button and press.

**Visuals**

https://github.com/phetsims/center-and-variability/assets/87318828/5e5b46d2-e1de-413a-91c2-2ebb990bfac3

<img width="559" alt="Screenshot 2023-10-17 at 9 22 00 AM" src="https://github.com/phetsims/center-and-variability/assets/87318828/1293a982-5848-405d-86b2-9810ca3f31a6">

**Comment by Nancy-Salpepi** [comment]
This bug also happens when I change the character set.

**Comment by marlitas** [comment]
I was unable to hit the bug that @Nancy-Salpepi showed here, but I did hit a different bug where the value of the focusedSoccerBallProperty would be null. It seems similar but I am not able to confirm it fixes the initial problem since I wasn't able to test. Here's the patch:

<details>

```diff
Subject: [PATCH] clear data
---
Index: js/view/SoccerSceneView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/view/SoccerSceneView.ts b/js/view/SoccerSceneView.ts
--- a/js/view/SoccerSceneView.ts	(revision dd49cb15a1e750329fccf55980bc4fc1962afab7)
+++ b/js/view/SoccerSceneView.ts	(date 1697575981898)
@@ -311,6 +311,13 @@
 
     this.backSceneViewLayer = backLayer;
     this.frontSceneViewLayer = frontLayer;
+
+    sceneModel.clearDataEmitter.addListener( () => {
+        focusedSoccerBallProperty.reset();
+        isSoccerBallKeyboardGrabbedProperty.reset();
+        hasKeyboardFocusProperty.reset();
+      }
+    );
   }
 
   /**
Index: js/model/SoccerSceneModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/model/SoccerSceneModel.ts b/js/model/SoccerSceneModel.ts
--- a/js/model/SoccerSceneModel.ts	(revision dd49cb15a1e750329fccf55980bc4fc1962afab7)
+++ b/js/model/SoccerSceneModel.ts	(date 1697575981907)
@@ -425,6 +425,10 @@
    */
   public clearData(): void {
     this.isClearingData = true;
+
+    // We want to reset the interactive and focus highlight properties first.
+    this.clearDataEmitter.emit();
+
     this.numberOfQueuedKicksProperty.reset();
     this.timeProperty.reset();
     this.timeWhenLastBallWasKickedProperty.reset();
@@ -436,7 +440,6 @@
 
     this.isClearingData = false;
     this.updateDataMeasures();
-    this.clearDataEmitter.emit();
 
     // This emitter was suppressed during isClearingData, so we must synchronize listeners now
     this.objectChangedEmitter.emit();
```
</details>

**Comment by marlitas** [comment]
This fix has been committed and is ready for code review.

**Comment by marlitas** [comment]
This issue is now ready for cherry-pick. Thanks all!

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.3

**Comment by Nancy-Salpepi** [comment]
Sorry @marlitas. I need to reopen. I can get focus on the non-kicked ball by doing the following:
1. On the Median screen, press the Kick 5 button (with either mouse or keyboad nav)
2. Tab to and grab a soccer ball
3. Press opt + R to reset while the soccer ball is grabbed--the non-kicked ball will have a highlight.
4a. Press any arrow button--the console errors show below will appear
OR
4b. Tab away and then back to the non-kicked ball. Grab the non-kicked ball and press the arrows--Like in the original comment, the value will change in the card above. 
<img width="509" alt="Screenshot 2023-10-23 at 12 09 51 PM" src="https://github.com/phetsims/center-and-variability/assets/87318828/fd737021-d09a-40cb-a861-13fa48e71c7b">
<img width="509" alt="Screenshot 2023-10-23 at 12 10 14 PM" src="https://github.com/phetsims/center-and-variability/assets/87318828/edc2d822-ef6a-4a80-b517-647c880801d6">

**Comment by Nancy-Salpepi** [comment]
Something similar also happens with a grabbed card.
1. On the Median screen, Press the Kick 5 button (with either the mouse or with alt input)
2. Tab to the cards and grab one
3. Press opt + R--highlight remains around card
4. Press Space to grab
5. Press an arrow key--errors in the console appear

<img width="1300" alt="Screenshot 2023-10-23 at 12 45 57 PM" src="https://github.com/phetsims/center-and-variability/assets/87318828/1407e953-b2fc-412d-88b8-24edd3b4f411">

**Comment by marlitas** [comment]
Keyboard interactions are making things trickier and trickier in both contexts. I think all these issues will be important to consider when we address: https://github.com/phetsims/scenery-phet/issues/815

The commits above could use a code review. Over to @samreid or @matthew-blackman. Feel free to reach out if a synchronous review would be helpful here.

**Comment by samreid** [comment]
Everything looks great. @marlitas and I reviewed it together and tested it out. We added documentation and it is ready for cherry picking.

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.4 🤞🏻.  
Will reopen if anything pops up.
