### ISSUE TITLE
Internal changes for kicker animations

### ISSUE THREAD

**Issue by chrisklus** [phetsims/center-and-variability#59]
From work in https://github.com/phetsims/center-and-spread/issues/12 and https://github.com/phetsims/center-and-spread/issues/53, we have some TODOs in code that point to those issues and since we might close those soon, @samreid and I are pointing the remaining TODOs here.

**Comment by samreid** [comment]
I addressed one TODO, but feel help would be best to understand and work on the other 2.

**Comment by samreid** [comment]
These were addressed in #45, closing.
