### ISSUE TITLE
Horizontal spacing of Whisker plot buggy in Standard wrapper

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#590]
**Test device**
MacBook Air M1 chip

**Operating System**
14.0

**Browser**
Safari 17

**Problem description**
For https://github.com/phetsims/qa/issues/999, changing the max kicks in the standard wrapper will change the horizontal spacing of the "Whiskers". If this is done after launching the sim with balls kicked in the MAD scene, some of the "Whiskers" can be below the plot on Reset All. 

**Steps to reproduce**
1. In studio, in the MAD scene of the Variability screen, kick all 15 balls
2. Press Test
3. IN the Standard PhET-iO wrapper, change the Max Kicks to 10. 
4. Press Reset All

**Visuals**
Studio:
<img width="705" alt="Screenshot 2023-10-23 at 10 32 28 AM" src="https://github.com/phetsims/center-and-variability/assets/87318828/b4478382-3525-4056-a648-25697879b3db">

Standard 
<img width="823" alt="Screenshot 2023-10-23 at 10 32 10 AM" src="https://github.com/phetsims/center-and-variability/assets/87318828/b087d4fb-987a-443e-bc9a-4afebde2412a">
wrapper:

**Comment by KatieWoe** [comment]
Looking at this some more, the max stays 10 reset all is pressed, but 15 balls return to the field despite now being over the maximum.

**Comment by marlitas** [comment]
> Looking at this some more, the max stays 10 reset all is pressed, but 15 balls return to the field despite now being over the maximum.

Ummm... I'm not sure how to handle this... @catherinecarter?

I'm marking as an issue we'll want to discuss synchronously.

**Comment by kathy-phet** [comment]
@marlitas @catherinecarter - I reviewed this issue and the current behavior of how everything works. 

I believe this issues is addressed by adding specifics in an Example. Given that we do not want a preferences menu item to be reset by "reset all" button, the appropriate design solution here is for the instructional designer to hide the

**Comment by marlitas** [comment]
Reopening for @catherinecarter to add to examples.md

**Comment by catherinecarter** [comment]
Thanks, @marla and @kathy-phet. I have updated the examples document.
