### ISSUE TITLE
Home/End keys no longer work for grabbed ball

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#591]
**Test device**
MacBook Air M1 chip

**Operating System**
14.0

**Browser**
Safari 17

**Problem description**
For https://github.com/phetsims/qa/issues/999 and related to https://github.com/phetsims/center-and-variability/issues/588, I can no longer use the Home/End keys to jump to the beginning/end of the number line. Instead, those shortcuts move focus from the ball with the lowest value to the ball with the highest value. 

**Steps to reproduce**
1. On the any screen, press the Kick 5 button
2. Tab to and grab a ball 
3. Press Home and End keys

**Visuals**

https://github.com/phetsims/center-and-variability/assets/87318828/48533a6c-27fa-4df1-9330-d13619ebcd2d

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Variability‬
URL: https://phet-dev.colorado.edu/html/center-and-variability/1.1.0-rc.3/phet/center-and-variability_all_phet.html
Version: 1.1.0-rc.3 2023-10-22 23:55:32 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15
Language: en-US
Window: 1198x714
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by KatieWoe** [comment]
Pg Up and Pg down seem similarly messed up.

**Comment by marlitas** [comment]
Quite a dumb omission on my part. The bug @Nancy-Salpepi reported was fixed above.

@KatieWoe I wasn't able to find anything for pg Up/Down? That should only work when the soccer ball is grabbed. Page Up/Down will not work to switch focus to a different ball. That was a design decision made in #588

**Comment by KatieWoe** [comment]
Not sure what I was seeing. I can't reproduce it now. I'll update if I see it again.

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.4.
