### ISSUE TITLE
Cards can disappear from info dialog

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#593]
**Test device**
MacBook Air M1 chip

**Operating System**
14.0

**Browser**
Safari 17

**Problem description**
For https://github.com/phetsims/qa/issues/999, in the Studio and State Wrappers, moving balls, erasing them and then pressing Reset All can cause one or more cards to disappear from the info dialog. 
It has been very difficult to nail down a set of steps. @KatieWoe is able to get it to happen without moving the median ball, but I can consistently reproduce the bug by moving that ball. 

**Steps to reproduce**
Here are steps that have worked a lot for me:
In studio: 
1. On the Median screen, kick an odd number of balls (I like 11)
2. Check the Median checkbox in the play area
3. The median ball needs to be at the top of the stack (if not press Reset All and try again)
4. Press the Test button
5. Move the median ball elsewhere
6. Press the Eraser button
7. Press Reset All
8. Press the info button

**Visuals**

https://github.com/phetsims/center-and-variability/assets/87318828/3be58f19-f31e-45d5-ab56-d7dfad4aaafb

Here is a screenshot with 2 missing cards:
<img width="1162" alt="Screenshot 2023-10-24 at 4 44 17 PM" src="https://github.com/phetsims/center-and-variability/assets/87318828/3ed2fabb-64f3-4c46-bd1a-baedebcf7489">

**Comment by KatieWoe** [comment]
It may be faster to reproduce in the State wrapper rather than studio.

**Comment by KatieWoe** [comment]
These are the steps I came up with:
1. In State, turn the Set-State Rate to zero
2. On the first screen, kick multiple balls
3. Set state
4. On the bottom sim, move a ball from one position, to a new one
5. Press the eraser button
6. Press reset all
7. Check the info button, one or more cards may be missing

This works with some balls moved to some positions, but not all and we have not found the underlying cause

**Comment by marlitas** [comment]
This is a wonky one. I found a way to reliably reproduce in the state wrapper with the help of the `dev` query parameter and a mix of @KatieWoe and @Nancy-Salpepi steps.

1. In State, run with sim with query parameter `?dev` and turn set-state rate to zero
2. On the first screen kick three balls
3. Make sure the balls are in their kick order (eg. `ball 0` should be at a value before `ball 1` which should be at a value before `ball 2`). `Ball 0` must have space to be dragged past `ball 1` going up the number line. This can be set up manually. (The picture below shows an appropriate set up).
4. Set state
5. On the bottom sim move the middle (aka median) ball past `ball 1` going up the number line.
6. Press the eraser button
7. Press reset all
8. Check the info dialog. The middle card should be missing.

![image](https://github.com/phetsims/center-and-variability/assets/42476338/c1c6c023-80c4-40b2-b2e5-6afb407a4a44)

**Comment by Nancy-Salpepi** [comment]
This looks fixed in rc.4

**Comment by Nancy-Salpepi** [comment]
OMG this is happening again for me in https://github.com/phetsims/qa/issues/1268. I definitely didn't do as many steps as in https://github.com/phetsims/center-and-variability/issues/593#issuecomment-1778322247. I can't try and figure out other steps. 

<img width="535" height="629" alt="Image" src="https://github.com/user-attachments/assets/61a71d07-4ba5-41ae-ae6d-8e6c5cd2d071" />

**Comment by Nancy-Salpepi** [comment]
This has been working for me every time I tried it so far:

1. In the State wrapper go to the Median Screen
2. Set State rate =0
3. Kick 5 balls in the upstream sim (keep an eye on which ball was kicked first)
4. Move the soccer ball that has the same value as the first card (first ball kicked) to the position on the field that is the same as the value of the 3rd card.*
5. Press Info button
6. Press Set State Now

*Noting that every time I have been dragging the ball to the right. 

Here is a video: 

https://github.com/user-attachments/assets/40083825-5152-401f-bc01-225272430588

**Comment by marlitas** [comment]
Fixed above. Ready to cherry-pick.
