### ISSUE TITLE
Floating card with keyboard interaction

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#594]
While working on https://github.com/phetsims/center-and-variability/issues/587 I discovered that we can still have a floating card appear while using the reset hotkey.

Steps to reproduce:

1. Kick 5 balls
2. Tab to card area and grab a card
3. Use `opt+R` to reset
4. Kick 5 balls again.

<img width="496" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/c417dc50-16f2-4857-b367-5d390379e173">

**Comment by marlitas** [comment]
This was straightforward. Ready to cherry-pick.

**Comment by Nancy-Salpepi** [comment]
This looks fixed in rc.4
