### ISSUE TITLE
Able to set ball position at values greater than 15

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#595]
**Test device**
MacBook Air M1 chip

**Operating System**
14.0

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/999, when customizing the `kickDistributionStrategy` I am able to set a ball's value greater than 15. Shouldn't an error pop up in studio?

**Steps to reproduce**
1. In studio, on any screen, change the `kickDistributionStrategy` to `distanceByIndex` by copying and pasting the example data in the text box.
2. Change the first value from 5 to 16 and press Set Value
3. Press Kick 1

**Visuals**
<img width="208" alt="Screenshot 2023-10-25 at 9 40 55 AM" src="https://github.com/phetsims/center-and-variability/assets/87318828/1ecb10dc-76b4-4568-ba28-b14bae749c63">

<img width="777" alt="Screenshot 2023-10-25 at 9 41 14 AM" src="https://github.com/phetsims/center-and-variability/assets/87318828/33abecfa-8105-4acf-8808-6715b66abf91">

**Comment by marlitas** [comment]
I also noticed that you can set the ball position to non-integers. Kind of fun, but probably buggy:

![image](https://github.com/phetsims/center-and-variability/assets/42476338/42be2d48-fd63-48b0-be4a-0f11164a23d6)

**Comment by marlitas** [comment]
I added some checks for this that will provide an error message. Over to @samreid or @matthew-blackman for review.

**Comment by marlitas** [comment]
This was reviewed and is now ready for cherry pick.

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.4.
