### ISSUE TITLE
Center and Variability Postmortem

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#597]
# Center and Variability postmortem

- [x]  **1. Schedule the meeting** Tuesday, November 14th 11:00-12:00 MT
- Invite the entire sim team to participate, and optionally anyone else who had a significant involvement. Have the
  meeting as soon as possible after the sim is released, so that experiences are still fresh in everyone's mind. Allow
  sufficient time for the meeting, 1.5-2 hours.

- [x]  **2. Enlist a meeting moderator** @arouinfar 
- The moderator's job is to make sure the meeting runs efficiently, stays on point, and focuses on constructive (but not
  overly negative) criticism. The moderator can be someone not on the sim team, or in many cases the Development
  Coordinator. The moderator also documents the important points of the meeting.

- [x]  **3. Create github postmortem issue and postmortem google doc**
- Create a GitHub issue in the repository of the sim for which the postmortem is occurring. This checklist will should
  be copied into the issue.
- Create a postmortem Google doc for the sim and set phethelp as the owner. This Google doc should live within the
  appropriate sim folder on Google drive
  https://docs.google.com/document/d/1Otq41pw1Y58FeSmJYtTOXDXWjCMjNj2AymPu_aac5Fk/edit

- [x]  **4. Two successes and two improvements**
- Participants will bring a list of no more than 2 items that were done well during the project, and no more than 2
  items that could be improved upon. Limiting to 2 requires people to think critically about their experience.

- [x]  **5. Identifying the top five**
- At the meeting, start by having each person present their items (successes, then improvements). Make a list of these
  items, and note duplicates. Based on popularity, identify the top 5 success items and the top 5 items that need
  improvement.

* Discuss the 5 success items first. Identify specific things that can be applied to future sims. Celebrate, pat each
  other on the back. Then move on to the harder part.
* Discuss the 5 improvement items. Try to avoid getting personal. Discuss what was learned, and identify specific things
  that can be done to prevent these problems in the future. If anything needs more investigation, assign to specific
  individuals.

- [ ]  **6. Modifications to Look & Feel**
- Identify modifications to the PhET Look-&-Feel Guidelines. If applicable, based on what we learned during development
  of this sim, suggest revisions to the guidelines.

* [HTML5 Look and Feel](https://docs.google.com/document/d/1Fg4E6VNMsnId7CjsyqHKnZeIoQ4N-5ezM9PTkj7N3PM/edit)
* [HTML5 Visual Sim Design Elements
  ](https://docs.google.com/document/d/1rpp0vT7-bGUs_5tZP_77-HM8PnaGbIDQ5DGNygX5CBo/edit)

- [ ]  **7. Sim checklist**
- Review the [Sim Checklist](https://github.com/phetsims/phet-info/blob/main/checklists/sim-checklist.md)

- [ ]  **8. Action items**
- Note important items in the postmortem GitHub issue, and create issues for any tasks the require action, such as
  updating documents, leftover TODOs, etc.
- Action Item Questions:
  - Modifications to look and feel?
  - Modifications to sim design process?
  - Modifications to project process?
  - Messages to share at status?

- [ ]  **9. Take home messages**
- From the top 5 successes/improvements, decide what are the "take home" messages that would be useful to note in the
  future, and add these to the [HTML5 Postmortem Take Home Messages](https://docs.google.com/document/d/1hayLX0FbhYqGao-5xizAFU9kVBzqrW_RVX88Wk_C_Lc/edit#heading=h.krbf2d24bpav) Google doc
- Report out at status meeting

**Comment by brent-phet** [comment]
FYI - @JacquiHayes noticed the following:

Jacqui Hayes
[8:39 AM] I just downloaded the Center & Variability sim, and it is 9.6MB. That’s a really big file. Is that normal now?
[8:39] For reference, I thought our sims were ~4MB
[8:40] It’s not a huge file compared to other products, but since the sims get downloaded over mobile data in poor countries, we do try to minimize the file size.

**Comment by marlitas** [comment]
> I just downloaded the Center & Variability sim, and it is 9.6MB. That’s a really big file. Is that normal now?

We knew CAV was bigger than some other sims that have been published. A large part of this was the static allocation in PhET-iO that I think contributed to making the code easier to maneuver and maintain, but did result in a larger file size. This could be something to bring up during post-mortem if we're concerned about the large file size as something to consider when decided between static vs. dynamic allocation in PhET-iO sims.

**Comment by samreid** [comment]
Static vs dynamic allocation is not related to the HTML file size. The images directory for this sim is 10.5MB which accounts for most of the size (compared to other sims).

**Comment by marlitas** [comment]
Thanks to @samreid for clarifying that in today's meeting as well as in this issue. I was unaware and made incorrect assumptions.

**Comment by samreid** [comment]
Regarding the file size, I opened a new issue https://github.com/phetsims/center-and-variability/issues/598 for investigation. There is an experiment that relates the file size to the png size.

**Comment by marlitas** [comment]
The post-mortem for CaV was finished a while ago and file size investigation is heartily underway elsewhere. Closing.
