### ISSUE TITLE
Incorrect usages of the `soccerCommon` namespace

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#599]
There are 3 incorrect usages of the `soccerCommon` namespace.  All of these should be `centerAndVariability.register`:

```ts
soccerCommon.register( 'CAVObjectType', CAVObjectType );

soccerCommon.register( 'CAVPlotNode', CAVPlotNode );

soccerCommon.register( 'DataPointNode', DataPointNode );
```

**Comment by marlitas** [comment]
Thanks for catching that @pixelzoom. Commit above fixes those namespace usages. Closing.
