### ISSUE TITLE
Median + Mean and Median Screen Sprint

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#6]
Issue for tracking this initial sprint.

**Comment by samreid** [comment]
Questions and answers from slack today:

For the “mean” checkboxes, should they have the exact same i18n string, or should translators be able to specify them independently?

Amanda McGarry  1 hour ago
I’m thinking for “mean” and “median” checkboxes, there isn’t a reason to have these as separate strings.

---


Sam Reid Today at 10:05 AM
For the “mean” checkboxes, should they have the exact same i18n string, or should translators be able to specify them independently?

Amanda McGarry  1 hour ago
I’m thinking for “mean” and “median” checkboxes, there isn’t a reason to have these as separate strings.

---

Sam Reid Today at 10:08 AM
It’s difficult to see the black text on the dark purple, should this be changed?


Amanda McGarry  6 hours ago
I can provide final hex codes in the design doc, and make sure they pass all tests for contrast and color blindness.

---


Sam Reid Today at 10:11 AM
I think we will need a soccer ball asset.

Amanda McGarry  1 hour ago
I just uploaded a soccer ball https://github.com/phetsims/center-and-spread/tree/master/images

Sam Reid  1 hour ago
Looks great, thanks!

Sam Reid  1 hour ago
Who is the artist for the ball so I can add it to the metadata?

---

Sam Reid Today at 10:24 AM
The “kick” buttons being gray kind of makes them look disabled or less attractive.

Amanda McGarry  6 hours ago
They are white, not gray, but they can be another color too. White has nice contrast on green, but we could consider yellow too.

Chris Klusendorf  5 hours ago
We made them a colorProperty so you can test it out live on phettest

---


Sam Reid Today at 10:43 AM
For i18n “kick”, should we disallow clients from changing the number by using a template variable, like Kick {{NUMBER}}, or leave them full flexibility to phrase it as they see fit?
5 replies

Amanda McGarry  6 hours ago
I can't recall having a number be translatable for any sim I've worked on. Do you have an example of a precedent for this?

Sam Reid  5 hours ago
My intuition is that it will be clearer for the translator to have full control of this part.  Like if in Chinese it is conventional to say 踢一個球 instead of 踢 1

Chris Klusendorf  5 hours ago
That sounds good to me, and we did find some numbers in string files, so there are precedents

Amanda McGarry  4 hours ago
Can someone point me to a sim that does this? It's not a question I remember being asked before, so just curious about when we've done it before. If you recommend it then I don't see why not?

Sam Reid  1 hour ago
I’m not sure of the search CK ran to find numbers in the strings file, I’ll wait for him to chime in on that part.

--- 


Amanda McGarry  12:44 PM
See slides 14-15 for the latest kicking animation 

Kathy Perkins  12:49 PM
Happy to start here and modify if students in interviews think the ball is part of the data set.
Were you going to also try the hold the ball option? Or is that off the table for now.

Amanda McGarry  12:56 PM
We can still ask Mariah to try it! This is just what she has right now and I thought it was helpful to see it in the mockups
12:57
I kind of like the glow, myself

--- 


Sam Reid  3:50 PM
what is deleteme and what problem does it solve?
3:54
Is the text “What is the group’s typical ball distance?” or “What is the typical ball distance?”  It differs between the screenshots. (edited) 

--- 
Sam Reid  4:09 PM
The sun pushbutton doesn’t do very good shading for a white base color. (edited)

**Comment by amanda-phet** [comment]
Are you still using this issue to track? I'm thinking this can be closed now.

**Comment by samreid** [comment]
Yes, I agree this issue should be closed.
