### ISSUE TITLE
git-hooks fails: soccer-common-strings_en.json not found

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#600]
git-hooks is failing with:

```
Generating PhET-iO API for repos: acid-base-solutions, beers-law-lab, calculus-grapher, center-and-variability, circuit-construction-kit-dc, circuit-construction-kit-dc-virtual-lab, concentration, density, friction, geometric-optics, geometric-optics-basics, graphing-quadratics, gravity-and-orbits, gravity-force-lab, greenhouse-effect, molecule-polarity, molecule-shapes, molecule-shapes-basics, my-solar-system, natural-selection, ph-scale, ph-scale-basics
[                                        ] 0.00%
[.......                                 ] 16.67%
[.............                           ] 33.33%
[....................                    ] 50.00%
[...........................             ] 66.67%
[.................................       ] 83.33%
Error from sim: Failed to load resource: the server responded with a status of 404 (Not Found):
  http://localhost:59056/soccer-common/soccer-common-strings_en.json
```

Reproduceable example from the command line:

```
% cd center-and-variability
/Users/cmalley/PhET/GitHub/center-and-variability
% grunt generate-phet-io-api
Running “generate-phet-io-api” task
Error from sim: Failed to load resource: the server responded with a status of 404 (Not Found):
 http://localhost:60883/soccer-common/soccer-common-strings_en.json
Done.
```

soccer-common-strings_en.json does not exist. If I create an empty soccer-common-strings_en.json (containing only `{}`), the problem goes away. 

I'm also seeing this in CT for phet-io-wrappers, which looks suspiciously similar:

```
Failed to load resource: the server responded with a status of 404 (Not Found):
http://128.138.93.172/continuous-testing/ct-snapshots/1700701871241/phet-io-wrappers/phet-io-wrappers-strings_en.json
```

I'm not sure if this is specific to center-and-variability, or if something about `grunt generate-phet-io-api` has changed that requires all repos to have a strings_en.json file, or ???? So I'll assign this to everyone who might be able to help.

In the meantime, I'll push an empty soccer-common-strings_en.json, so that I can proceed with other work. That file should be deleted when this issue is resolved.

**Comment by pixelzoom** [comment]
Slack#developer:

@marlitas:
I can help check on this on Monday. There were only three strings in the soccer-common file that got moved to joist, so I deleted and generated the API. I'm surprised that it killed git hooks so late... I committed a bunch after that change...

@pixelzoom:
I doubt that the problem is specific to CaV or soccer-common. I suspect there’s something in the API comparison that doesn’t properly handle the situation where a file that was present for the old API (like soccer-common-string_en.json) may no longer exist in the next API.

**Comment by zepumph** [comment]
>git-hooks is failing with:

Hmm, did this ever actually fail? Or did it just print that error. When I deleted soccer common strings, the API generation worked just fine, but printed that line that you saw. 

I re-removed the strings file and silenced the useless logging. Ready to close?

**Comment by pixelzoom** [comment]
> Hmm, did this ever actually fail? 

"Failed to load resource... "  If it didn't fail, then it sure is good at faking it :)   And it doesn't give me a lot of confidence that I should continue.

> % grunt generate-phet-io-api
Running “generate-phet-io-api” task
Error from sim: Failed to load resource: the server responded with a status of 404 (Not Found):
 http://localhost:60883/soccer-common/soccer-common-strings_en.json
Done.

> I re-removed the strings file and silenced the useless logging. Ready to close?

OK.
