### ISSUE TITLE
CardNode cursor should be on the whole draggable area

### ISSUE THREAD

**Issue by zepumph** [phetsims/center-and-variability#609]
Discussed briefly with @marlitas and @jbphet while working on https://github.com/phetsims/scenery-phet/issues/815 and https://github.com/phetsims/center-and-variability/issues/605, and then with @jonathanolson. @jonathanolson and I highly recommend having the cursor set on the Node that gets the input listener. This way we would have the cursor on the whole mouse area specified by CardNode.

**Comment by zepumph** [comment]
After the above commit, we now have a cursor on the whole touch area (including on the drag cue hand/arrow). This is much nicer given the code we have to expand mouse areas:

![image](https://github.com/phetsims/center-and-variability/assets/6856943/4b040fd1-d61f-41aa-a7a3-caecf4114d24)


@marlitas can you please review and let me know if there are any problems. I didn't see any other usages of `CardNode` to worry about.

**Comment by marlitas** [comment]
This change looks great, and definitely seems like an improvement. Thanks!
