### ISSUE TITLE
Artwork for homescreen icons and navbar icons

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#61]
We need Artwork for homescreen icons and navbar icons

**Comment by amanda-phet** [comment]
Here are the screen icons! 

![median-screen-icon](https://user-images.githubusercontent.com/7852916/159023034-9eb0639c-ecf2-4a29-9885-4a67dd5a7661.png)

![mean-and-median-screen-icon](https://user-images.githubusercontent.com/7852916/159023032-0281b657-07f4-4673-99aa-f027b78632ad.png)

**Comment by chrisklus** [comment]
@samreid and I added the screen icons in the above commit. We noticed there was a 1 pixel margin on the top and right side of the image, and that the image was 1 pixel wider and taller than the recommended size (we found that the recommended size was 548x373). @amanda-phet could you please re-export them with the extra pixel removed? 

We also noticed that the dots on the mean icon dip below the mean bar and there's a gap in the two stacked dots that might be nice to close.

**Comment by amanda-phet** [comment]
That's really strange, because my artboards are exactly 548x373! I don't know why it's adding the extra pixel but I resized the exported images, so hopefully these will work. 

>We also noticed that the dots on the mean icon dip below the mean bar and there's a gap in the two stacked dots that might be nice to close.

I thought that was an illusion because illustrator snapped the objects next to each other, but they are the tiniest hair overlapping. I went ahead and added a pixel between since the illusion is still present even when they are not overlapping.

**Comment by amanda-phet** [comment]
@chrisklus can you make sure these are the right size now?

**Comment by samreid** [comment]
The dimensions look correct now, thanks!  However, when we look at the new image in photoshop, there is still a border of transparent pixels.  We presume that is unintentional:

<img width="646" alt="image" src="https://user-images.githubusercontent.com/679486/159051358-aac0b353-48c9-47f9-8089-62ba2fa46b68.png">

**Comment by amanda-phet** [comment]
Please check again. Hopefully it is fixed now.

**Comment by samreid** [comment]
Looks good to me, thanks!  Closing.
