### ISSUE TITLE
Should changing the region and culture clear the kicked soccer balls?

### ISSUE THREAD

**Issue by zepumph** [phetsims/center-and-variability#610]
Reported in https://github.com/phetsims/phet-io-wrappers/issues/612#issuecomment-1924709515. 

To reproduce:

1. median screen
2. kick out 15 soccer balls
3. Change the region and culture. Even if we are mid-kick, this will clear all balls and change the character.

Feel free to close if this is desirable, but it seems like something that may have precedent across all implementations of region and culture, so I'll assign to @amanda-phet to start. Thanks!

**Comment by zepumph** [comment]
It also effects our support for changing the region and culture of a customized PhET-iO Wrapper, as shown in https://github.com/phetsims/phet-io-wrappers/issues/612#issuecomment-1924736563. Here we customize a sim in studio, then support having the saves standard wrapper change the region and culture. But when you do that, it automatically clears all the balls (likely the primary customization for the wrapper). Happy to talk synchronously to see if we need to make any changes to how we are thinking about region and culture with PhET-iO design.

**Comment by amanda-phet** [comment]
Let's chat about this if we still aren't sure what to do. I would default to whatever sounds best for PhET-iO. Right now it clears and it has not been bothering me at all, and even seems reasonable.

**Comment by zepumph** [comment]
No preference over here. I seemed like a bug to me, but if it doesn't to me, then that is very nice! Certain features and preferences are know and expected to reset sim behavior. I'm happy if this is how we want to treat the region and culture Property.
