### ISSUE TITLE
Migration processors for Region and Culture changes.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#615]
In https://github.com/phetsims/joist/issues/954, the keys for Region and Culture strings were renamed.  Because these strings are in joist, this changed the API for all PhET-iO sims, including CAV.

CAV 1.1 is the only PhET-iO sim that has been published with the Region and Culture feature -- the only sim that appears in phet-io-stable and has "supportedRegionsAndCultures" in its package.json. So for migration, we will ignore the change for all PhET-iO sims except CAV.

For CAV, we will need the following migration rules:

- [x] RenamePhetioElement: centerAndVariability.general.model.regionAndCulturePortrayalProperty to centerAndVariability.general.model.regionAndCultureProperty
- [x] ChangePhetioElementIOType: `PropertyIO<RegionAndCulturePortrayalIO>` to `PropertyIO<StringIO>`, with callback to change values (e.g. "centerAndVariability.global.model.preferences.regionAndCulturePortrayals.usa" to "usa"), will likely require help from @zepumph.
- [x] RenamePhetioElement for each of the joist strings Properties that were changed.

This work should be done after converting to the new Region and Culture approach. 

@marlitas @amanda-phet @Luisav1 FYI.

**Comment by pixelzoom** [comment]
Note that CAV will continue to fail CT until this issue is addressed.

```
center-and-variability : migration : 1.1->main : assert
http://128.138.93.172/continuous-testing/ct-snapshots/1710237779115/phet-io-wrappers/migration/?sim=center-and-variability&oldVersion=1.1&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710237779115%22%2C%22timestamp%22%3A1710238312412%7D
Assertion failed: MigrationReport problem: missingStringPhetioElements
```

**Comment by pixelzoom** [comment]
We can't write migration rules until the things being migrated (regionAndCulturePortrayalProperty, RegionAndCulturePortrayalIO, ...) have been removed.  They can't be completed removed until all sims have been ported to the new approach in https://github.com/phetsims/joist/issues/958.  So to remove them for the purposes of PhET-iO,  I uninstrumented them in https://github.com/phetsims/joist/commit/7ab9eeaa376c0002ef6d09f17a9dc07d16a04b97.

**Comment by pixelzoom** [comment]
I made a start on migration processors in https://github.com/phetsims/phet-io-sim-specific/commit/0350f8dffa00d3d36c735aee5cbc69862ad57990.  But I ran into these problems that I have no idea how to resolve:

(1) CAV 1.1 had `regionAndCulturePortrayalProperty: PropertyIO<RegionAndCulturePortrayalIO>`, which was replaced by`regionAndCultureProperty: PropertyIO<StringIO>`. @mjkauzmann pointed me to `ChangePhetioElementIOType` processor for handling that migration. But `ChangePhetioElementIOType` has zero useful documentation, and the existing usages are not helping me understand. I have no idea how to migrate from a reference IOType (`RegionAndCulturePortrayal`) to a `string`. 

(2) The values that were of type `RegionAndCulturePortrayalIO` were static instances, and they have been deleted. `DeleteUnsupportedPhetioElement` does part of the job. But there are `incompletePhetioElementDeletes` messages in the Migration Report because the phetioIDs of those elements are used as values for `regionAndCulturePortrayalProperty`.  MigrationReport.ts told me that much, but didn't tell me how to address it:

```ts
  // DeletePhetioElement only support deleting an entry from the state. If trying to delete a phetioID that is used in
  // a state value, that goes beyond the scope of DeletePhetioElement and needs to be handled in a Processor before the
  // DeletePhetioElement processor.
  public readonly incompletePhetioElementDeletes: string[] = [];
```

I feel like I'm way outside the scope of what I was supposed to be doing for https://github.com/phetsims/joist/issues/953, so I'm going to stop here.  And the lack of documetation and exemplars is telling me that I should not continue.

Assigning to @marlitas and @samreid to complete.  Search for `TODO https://github.com/phetsims/center-and-variability/issues/615` in center-and-variability-migration-processors.ts.

**Comment by zepumph** [comment]
That seems very reasonable to stop here, and thanks for the write up. Migration is a new feature, and there is a lot of complexity to convey. I recommend that @pixelzoom be a part of this issue to completion to help aid us in better understanding where the pitfalls where, and how best to make updates. 


> I feel like I'm way outside the scope of what I was supposed to be doing for [phetsims/joist#953](https://github.com/phetsims/joist/issues/953), so I'm going to stop here.

PhET-iO migration is in scope for any change that causes a migration issue, and for which migration needs to be supported. We spent careful time considering when it is best to handle migration issues, and determined it is when the deviation occurs, and not later on. So I consider this issue intimately tied to the goals and scope of https://github.com/phetsims/joist/issues/953 (the issue that caused the migration problem). Just like for API compatibility support, there is going to be a learning curve for this important feature that has been noted as valuable for PhET-iO clients by management.

**Comment by pixelzoom** [comment]
> I feel like I'm way outside the scope of what I was supposed to be doing for https://github.com/phetsims/joist/issues/953, so I'm going to stop here.
> 
> PhET-iO migration is in scope for any change that causes a migration issue, and for which migration needs to be supported. 

I agree that this issue is in the scope of https://github.com/phetsims/joist/issues/953.  But (as I said) it's not within the scope of _my role_ in that issue.  My role was to review the common-code work, convert graphing-lines and graphing-slope-intercept as exemplars, and pair with @Luisav1 to familiarize her with the new Region and Culture approach.  My role was not to dive into any of the 11 other sims that need conversion/attention as the result of these changes.

**Comment by pixelzoom** [comment]
Btw...  I'll be happy to continue to consult on this issue, pitfalls, etc.   But I have higher-priority tasks that are now behind schedule, and I need to get back to those.

**Comment by zepumph** [comment]
Sounds great. @marlitas let me know when we should work on this as part of the Region and Culture work. Maybe schedule a meeting to go through it?

**Comment by zepumph** [comment]
Notes to start off next time:

* note that the state handler is run on initialState
* We didn't need ioTypesToAdd because there was a PropertyIO<StringIO>
* Remove the assertion?

**Comment by samreid** [comment]
I was surprised to see this patch not yielding any problems in the migration wrapper:

<details>

```diff

Subject: [PATCH] Simplify IntervalTool and edge management, see https://github.com/phetsims/projectile-data-lab/issues/274
---
Index: repos/center-and-variability/js/center-and-variability-migration-processors.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/repos/center-and-variability/js/center-and-variability-migration-processors.ts b/repos/center-and-variability/js/center-and-variability-migration-processors.ts
--- a/repos/center-and-variability/js/center-and-variability-migration-processors.ts	(revision f4931653324411431d0e556ab7aa95bf21d8bae4)
+++ b/repos/center-and-variability/js/center-and-variability-migration-processors.ts	(date 1712023720273)
@@ -67,9 +67,9 @@
 
     // Region and Culture 'portrayals' were deleted, and there is no mapping to something else.
     // See https://github.com/phetsims/joist/issues/953
-    new DeleteUnsupportedPhetioElement( `${simName}.global.model.preferences.regionAndCulturePortrayals`, {
-      clientMessage: 'regionAndCulturePortrayals is no longer supported. See regionAndCultureProperty.'
-    } ),
+    // new DeleteUnsupportedPhetioElement( `${simName}.global.model.preferences.regionAndCulturePortrayals`, {
+    //   clientMessage: 'regionAndCulturePortrayals is no longer supported. See regionAndCultureProperty.'
+    // } ),
     //TODO https://github.com/phetsims/center-and-variability/issues/615
     // The above DeleteUnsupportedPhetioElement processor results in incompletePhetioElementDeletes messages
     // in the console, because the child elements of regionAndCulturePortrayals are used as values for

```

</details>

@zepumph can you help me understand?

**Comment by marlitas** [comment]
This has been addressed in the above commits. Thanks all!

**Comment by zepumph** [comment]
Noting also that in fact the deletion of the portrayal instances weren't needed, since after we changed the Property to be a `StringIO`, the portrayal instances weren't phetioState:true, or used by anything that is phetioState:true, so the report doesn't need any work to update things that aren't actually possible to get to via the state feature.
