### ISSUE TITLE
Use `ResetAllButton.isResettingAllProperty` to mute sound in `IntervalToolNode`

### ISSUE THREAD

**Issue by jbphet** [phetsims/center-and-variability#622]
In https://github.com/phetsims/tambo/issues/190 a more globally available flag was created that can be used to determine if a "reset all" action is in progress.  This could be used in `IntervalToolNode` to mute sound generation during reset.

**Comment by jbphet** [comment]
Changes made. Assigning to @samreid and @mariahmaephet for review, as they are listed as the responsible devs for this sim.

**Comment by samreid** [comment]
I'll take a look.

**Comment by samreid** [comment]
I reviewed the code and tested with mouse and keyboard, everything seems good, thanks, closing.
