### ISSUE TITLE
Add "SetDataPoints" to Examples.md

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/center-and-variability#623]
In reviewing CaV behavior as part of MSaB, we noticed that the Examples.md does list GetDataPoints method, but doesn't show this setDataPoints functionality that does work: 
await phetioClient.invokeAsync('centerAndVariability.medianScreen.model','setDataPoints',[[7,6,1,2,3]]);;

**Comment by kathy-phet** [comment]
Not sure who is in charge of Examples.md here?

**Comment by catherinecarter** [comment]
I wrote the document, so I think I'm probably the one in charge :) 

There is a "Customize the distribution of kicks" section, under which is a sub-section: 
- Exact locations in order of kicks

I could put the command you wrote there. Do you think that's a logical place to put it? Or would it be better to be coupled with the getDataPoints section?
