### ISSUE TITLE
Symbols/words overlap or are cut off with stringTests

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#79]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.2.1

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/781
Several words and symbols are cut off with stringTest=double and stringTest=long.

**Examples with stringTest=long on the Mean and Median Screen:**
* mean symbol is cut off
<img width="449" alt="Screen Shot 2022-03-07 at 2 24 43 PM" src="https://user-images.githubusercontent.com/87318828/157104077-f580b4c2-56c8-4f14-8337-0ceade5c3ebc.png">
* soccer ball is behind checkbox
<img width="449" alt="Screen Shot 2022-03-07 at 2 25 30 PM" src="https://user-images.githubusercontent.com/87318828/157104100-9a36c9c9-d28e-4f5e-bb3e-24ac89f0e6ef.png">
* median bracket over "words"
<img width="449" alt="Screen Shot 2022-03-07 at 2 25 48 PM" src="https://user-images.githubusercontent.com/87318828/157104110-495dd8a6-4280-4312-a793-87633cbd4478.png">

**Examples with stringTest=double on the Mean and Median Screen:** 
* question is cut off and median symbol is cut off and data overlaps median value

<img width="1411" alt="Screen Shot 2022-03-07 at 2 37 07 PM" src="https://user-images.githubusercontent.com/87318828/157105562-09c83fe5-d381-431c-a958-838df5d2becd.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Spread‬
URL: https://phet-dev.colorado.edu/html/center-and-spread/1.0.0-dev.11/phet/center-and-spread_all_phet.html
Version: 1.0.0-dev.11 2022-03-07 01:50:02 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36
Language: en-US
Window: 980x467
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
For stringTest=rtl
The mean symbol is cut off in the panel. 
<img width="346" alt="Screen Shot 2022-03-07 at 2 41 29 PM" src="https://user-images.githubusercontent.com/87318828/157106177-d78cdd0d-6f06-4528-ad71-746e3e2f5ce6.png">

**Comment by amanda-phet** [comment]
This will be a 1.0 priority for sure, but not necessary for the classroom prototype.

**Comment by KatieWoe** [comment]
This is also seen in https://github.com/phetsims/qa/issues/795
![Center and Variability_Center and Variability screenshot](https://user-images.githubusercontent.com/41024075/162267374-9527d317-3d75-48bf-8f2c-d183414e9466.png)

**Comment by KatieWoe** [comment]
I also found it a bit odd that the spacing between the text and the images differed even when the text length was the same.
<img width="199" alt="distance" src="https://user-images.githubusercontent.com/41024075/162269920-2fd03e8a-5b22-4a7f-9864-a9aa6c755cfd.png">

**Comment by chrisklus** [comment]
@samreid and I did some quick fixes for this issue to improve everything noted in this issue except what's described in https://github.com/phetsims/center-and-variability/issues/79#issuecomment-1092060684. Fixing the icon spacing will be a more in-depth refactor that we would like to wait until 1.1 to do.

@Nancy-Salpepi could you test this on phettest and mark for cherry picking if it looks okay? Thanks!

**Comment by Nancy-Salpepi** [comment]
@chrisklus: a lot of things look better. The mean symbol still gets cut off in some string tests, but I think this might get fixed when you address https://github.com/phetsims/center-and-variability/issues/79#issuecomment-1092060684.


<img width="673" alt="Screen Shot 2022-04-15 at 4 38 03 PM" src="https://user-images.githubusercontent.com/87318828/163629839-a66c95e1-f925-4eb8-bad2-6961de0fef0b.png">

Also, with stringTest=long, the checkboxes are really close to the soccer balls on 15. 


<img width="608" alt="Screen Shot 2022-04-15 at 4 33 47 PM" src="https://user-images.githubusercontent.com/87318828/163629938-511b90b5-b67c-4432-81f5-bd6b46f3d57c.png">

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi! @amanda-phet can you comment on whether this is acceptable for the prototype? Let me know if you need more context.

Note the comment above:

>@samreid and I did some quick fixes for this issue to improve everything noted in this issue except what's described in https://github.com/phetsims/center-and-variability/issues/79#issuecomment-1092060684. Fixing the icon spacing will be a more in-depth refactor that we would like to wait until 1.1 to do.

I think we've done what we can for this issue without refactoring the icon spacing to make it adjust to any translated string length.

**Comment by amanda-phet** [comment]
Yup, this is all good for the prototype. Thanks!

**Comment by chrisklus** [comment]
@samreid and I deployed these changes for version 1.0.1, closing.

I opened https://github.com/phetsims/center-and-variability/issues/137 for the remaining work from this issue for 1.1
