### ISSUE TITLE
Verify credits 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/center-and-variability#8]
@samreid asked on slack: 

>Do you want Findley, Hartzell, Webb, Abrahamson and the Embodied Design Research Lab listed in the team and/or credits? 

and set up the following credits: 

```credits: {
  leadDesign: 'Amanda McGarry',
  softwareDevelopment: 'Chris Klusendorf, Sam Reid',
  team: 'Dor Abrahamson, Kelly Findley, Marily Hartzell, Ariel Paul, Kathy Perkins, David Webb',
  qualityAssurance: 'Logan Bray, Clifford Hardin, Brooklyn Lash, Emily Miller, Nancy Salpepi, Kathryn Woessner',
  graphicArts: 'Mariah Hermsmeyer'
}
``` 
Please change the credits to the following: 

```credits: {
  leadDesign: 'Amanda McGarry',
  softwareDevelopment: 'Chris Klusendorf, Sam Reid',
  team: 'Kelly Findley, Marilyn Hartzell, Ariel Paul, Kathy Perkins, David Webb, with early input/ideas from
Dor Abrahamson and the Embodied Design Research Lab at UC Berkeley',
  qualityAssurance: '',
  graphicArts: 'Mariah Hermsmeyer'
}
``` 

(I think it's customary to wait to add QA credits until QA has occurred, but if we need something then it's probably fine to put Kathryn Woessner.)

**Comment by kathy-phet** [comment]
Yep, sounds good for this sim.

**Comment by samreid** [comment]
Fixed as prescribed, closing.

**Comment by chrisklus** [comment]
Reopening to add QA members

**Comment by chrisklus** [comment]
@samreid added QA team members who opened issues (Nancy Salpepi, Kathryn Woessner, Devon Quispe). @KatieWoe is there anyone we missed?

**Comment by KatieWoe** [comment]
Emily Miller and Clifford Hardin should also be added.

**Comment by chrisklus** [comment]
Thanks! @samreid and I added above, marking ready to cherry-pick.

**Comment by chrisklus** [comment]
@samreid and I deployed these changes for version 1.0.1, closing.
