### ISSUE TITLE
Feature Suggestion: Delete individual soccer balls

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#80]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/781
I noticed that you are able to move soccer balls after they are in the play area. You are also able to delete all balls in the play area with the eraser button. However, you are unable to erase just one if you, for instance, were aiming for a certain number and hit the button one too many times. The ability to remove one ball at a time may be a useful feature.

**Visuals**
![deleteone](https://user-images.githubusercontent.com/41024075/157107013-52aeeb92-ca9a-4e3a-bbcb-1a6a4fabded2.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Spread‬
URL: https://phet-dev.colorado.edu/html/center-and-spread/1.0.0-dev.11/phet/center-and-spread_all_phet.html
Version: 1.0.0-dev.11 2022-03-07 01:50:02 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by chrisklus** [comment]
Thanks @KatieWoe! Noting for @amanda-phet and @samreid that i've noticed myself wanting to do this as well.

**Comment by amanda-phet** [comment]
I have thought about this as well, but not sure if there is a good way to allow it to happen. It seems like if someone wants a specific number of balls, they can just kick that many, but "removing" data is something that isn't realistic with actual data. While I recognize that changing the data (like dragging a ball after it has landed) is also unrealistic, it is pedagogically powerful. Removing a ball doesn't help to address any learning goals that I can think of. 

I'm open to having a conversation about this, but that's just my first thought.

**Comment by samreid** [comment]
> but "removing" data is something that isn't realistic with actual data.

Yes, but we are also moving around data, which seems it has the same problem.  That being said, I don't see a straightforward interaction for deleting soccer balls (would require dragging to a garbage can--outside of the bounds, or clicking to highlight one, then tapping a garbage can or 'x' button), so I think this issue should be closed as won't fix.

**Comment by amanda-phet** [comment]
Replying to @samreid : I addressed that moving individual balls is pedagogically powerful, but deleting them isn't. So I am fine closing this.
