### ISSUE TITLE
Soccer balls fuzzy in screenshot

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#81]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/781.
When taking a screenshot from the PhET Menu, the soccer balls were unclear. The lines within the image seemed to be the cause.

**Visuals**
![Center and Spread screenshot](https://user-images.githubusercontent.com/41024075/157115686-33cf228c-860e-4cdb-bb8b-1d20982cb870.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Spread‬
URL: https://phet-dev.colorado.edu/html/center-and-spread/1.0.0-dev.11/phet/center-and-spread_all_phet.html
Version: 1.0.0-dev.11 2022-03-07 01:50:02 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by amanda-phet** [comment]
Does this happen with the people artwork as well? Curious if it's a ball issue or an artwork issue.

**Comment by stemilymill** [comment]
@amanda-phet this is on my win10 dell, the person and soccer balls have fuzzy/pixelated lines

![screenshot wrapper person and soccer balls pixelated](https://user-images.githubusercontent.com/85511101/157749490-f4b9b544-8443-4cf9-a423-d50df557c989.jpg)

**Comment by Nancy-Salpepi** [comment]
Using the screenshot wrapper this is what it looks like for me with win10 + Firefox, but I think this computer might be part of the reason. Everything looks very clear on my MacBook.
![CaS screenshot2](https://user-images.githubusercontent.com/87318828/157763718-4ebb7a08-0fe6-43a1-a79d-5f7f330f6ae4.PNG)

**Comment by amanda-phet** [comment]
This seems like something that would be useful to fix for 1.0, but not a priority for the classroom prototype.

**Comment by amanda-phet** [comment]
@chrisklus says it might be easy or worthwhile to try mipmaps for this problem.

**Comment by samreid** [comment]
This is a symptom of a more general problem which is described in https://github.com/phetsims/joist/issues/664 and depicted as non-blocking.  I'll make a comment there as well.

**Comment by samreid** [comment]
Since https://github.com/phetsims/joist/issues/664 is depicted as non-blocking and caused by a common code issue, I recommend removing from the current milestone.  Anyone else please feel free to disagree.

**Comment by amanda-phet** [comment]
We can remove it from the milestone, but we will likely still need to mipmap all images.

**Comment by samreid** [comment]
There is a proposal in https://github.com/phetsims/joist/issues/664 that seems like it will work to address this issue.

**Comment by samreid** [comment]
Soccer balls look really nice on Mac 13.0.1 running Chrome Version 112.0.5615.137 (Official Build) (arm64).

<img width="215" alt="image" src="https://user-images.githubusercontent.com/679486/233507860-6ce1b93b-c808-4e09-914b-36d8fe8ddad0.png">

https://github.com/phetsims/joist/issues/664 was also tested on Windows by QA, so I think this issue can be closed.
