### ISSUE TITLE
Possible to get floating soccer balls

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#82]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/781. Seen when using `?speed=.1` but it may be possible, if hard, during normal use.
When a soccer ball is about to land in a spot, dragging another on/off that spot as it lands can cause the positions to overlap, making it look like a ball is floating and/or missing. This requires precise timing and luck, even with the sim slowed down, so I'm not sure how likely it is during normal use.
**Steps to reproduce**
1. Use the query parameter `?speed=.1`
2. One the first screen, use the kick 5 button
3. When one ball lands, drag it to where the next ball will land
4. As the second ball lands drop the first
5. It may also happen if you pick up the first ball from the landing spot as the second lands
6. This may take several tries

**Visuals**
![lastsecgrab](https://user-images.githubusercontent.com/41024075/157128808-24bf4564-e634-401a-ba43-e759880a8f17.gif)
<img width="956" alt="floating" src="https://user-images.githubusercontent.com/41024075/157128810-f7a8bb1b-59fa-43ab-bcad-2f6d74ae8de4.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Spread‬
URL: https://phet-dev.colorado.edu/html/center-and-spread/1.0.0-dev.11/phet/center-and-spread_all_phet.html
Version: 1.0.0-dev.11 2022-03-07 01:50:02 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by amanda-phet** [comment]
I've wondered if this might happen, but wasn't fast enough to make it happen on my own (and didn't know about the speed qp). I think this is a potentially strange issue if someone is just moving balls around and not trying to make it happen, so it would be helpful to think through a solution sooner rather than later, if possible.

**Comment by KatieWoe** [comment]
As a data point, I managed to reproduce this in https://github.com/phetsims/qa/issues/795 without the speed parameter.
<img width="956" alt="reproduced" src="https://user-images.githubusercontent.com/41024075/162079872-597d5bcd-fa64-4fcd-924d-64990b555f5e.png">

**Comment by samreid** [comment]
Good discovery!  @amanda-phet would you recommend investigation into this for the current milestone?

**Comment by amanda-phet** [comment]
I think we can keep this on the 1.1 milestone.

**Comment by samreid** [comment]
@amanda-phet and @catherinecarter is the right kind of solution to investigate: when a ball is moved, detect if there are any floating soccer balls, and animate them to the ground?

**Comment by catherinecarter** [comment]
If there's a way to do that, your proposition seems best. We'd need to consider when there is a stack of floating balls like in the 2nd image above (two balls are stacked) and make sure to move the entire stack down.

**Comment by samreid** [comment]
I have seen this bug more and more after recent refactorings.

**Comment by samreid** [comment]
Even after other changes, this is still buggy by the instructions above (drag lower ball away while landed ball animating up)

<img width="357" alt="image" src="https://user-images.githubusercontent.com/679486/236576991-58a0e8a8-098e-4d55-9e5c-775f843b8cf1.png">

**Comment by samreid** [comment]
Fixed and ready for review.  After reviewing and discussing the commits, let's reassign to @KatieWoe for testing.

**Comment by samreid** [comment]
I'm still seeing problems on multikicks.

**Comment by samreid** [comment]
The recent commits seem to help a lot. I also opened a side issue.  Probably ready for review again?

**Comment by samreid** [comment]
Today I got a floating soccer ball by dragging one from a stack while a ball was animating up the stack.  Maybe also be tested in #188

**Comment by matthew-blackman** [comment]
There is some buggy behavior here, but I'm no longer able to get floating soccer balls. Continuing this in https://github.com/phetsims/center-and-variability/issues/188

**Comment by samreid** [comment]
@marlitas can this issue be closed?

**Comment by marlitas** [comment]
Closing as completed.
