### ISSUE TITLE
"You sorted the data" message doesn't always appear

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#85]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.2.1

**Browser**
chrome and safari

**Problem description**
For https://github.com/phetsims/qa/issues/781:
The "You sorted the data" message doesn't always appear. It was hard to pinpoint exactly when it wouldn't happen, but it seems to occur when the soccer balls have been moved a few times (less than 5) and are on fewer data points. 

**Steps to reproduce**
I have been able to reproduce this issue MOST of the time by doing this:
1. On the Median Screen, press the 'Kick 5' button 3 times. 
2. Move 4 soccer balls so that only 6 different values have balls (depending on the initial spread, this may not be possible--press reset and try again)
3. Sort the tiles--the "you sorted the data" message fails to appear

* I was also able to reproduce using 5 balls and 10 balls.
* This is also reproducible on master. No errors in console. 

**Visuals**

https://user-images.githubusercontent.com/87318828/157256829-13f877ad-a713-4fd8-8741-5322a4dc47f7.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Spread‬
URL: https://phet-dev.colorado.edu/html/center-and-spread/1.0.0-dev.11/phet/center-and-spread_all_phet.html
Version: 1.0.0-dev.11 2022-03-07 01:50:02 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36
Language: en-US
Window: 980x467
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
The "you sorted the data message"also did not appear in this instance. In this case, this is where the balls were originally kicked. I just sorted the data. 

https://user-images.githubusercontent.com/87318828/157258063-a54eb50d-2240-420d-a531-20a15f1a3ddc.mp4

**Comment by samreid** [comment]
May be related to https://github.com/phetsims/center-and-spread/issues/78?

**Comment by amanda-phet** [comment]
@Nancy-Salpepi and @stemilymill can you try to reproduce this again now that #78 is fixed?

**Comment by Nancy-Salpepi** [comment]
This issues still occurs.

**Comment by Nancy-Salpepi** [comment]
@chrisklus I think this can be closed because it was addressed in https://github.com/phetsims/center-and-variability/issues/115. I haven't come across a situation where the "You sorted the data" message doesn't appear since.

**Comment by chrisklus** [comment]
Awesome, thanks @Nancy-Salpepi! Closing.
