### ISSUE TITLE
launching sim triggers median animation

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#87]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.2.1

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/781 in the studio wrapper:

On the Mean and Median screen, if the Median Checkbox in the panel is checked, launching the sim triggers the median animation to occur. 

**Steps to reproduce**
1. In the Studio wrapper, on the Mean and Median Screen, check the Median Checkbox in the panel. 
2. Press the 'Kick 5' button 
3. Launch the sim--the median animation will occur

**Visuals**

https://user-images.githubusercontent.com/87318828/157314024-9b845368-cf97-47b7-89aa-789236c3b872.mp4

**Comment by amanda-phet** [comment]
While this seems logical, I agree that it would be ideal if that animation didn't happen in this case.

**Comment by amanda-phet** [comment]
@chrisklus says this shouldn't be hard to fix, so I'm adding it to the milestone!

**Comment by samreid** [comment]
Fixed and appears to be working nicely in our testing.  @Nancy-Salpepi can you please test as well?  Please also test the expected animation behavior in PhET brand.  Please close if all is well.
