### ISSUE TITLE
Text moves when sorting data in Firefox

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#89]
**Test device**
Dell

**Operating System**
Win10

**Browser**
Firefox

**Problem description**
For https://github.com/phetsims/qa/issues/781:

This seems to be specific to Firefox:
On the Median screen, moving the tiles or the soccer balls causes the text "Sort Data" and "Median" to shift. 

**Visuals**
![textmoves](https://user-images.githubusercontent.com/87318828/157548148-330d9639-3b16-4418-ad39-9614b0e7c5c3.gif)

**Comment by amanda-phet** [comment]
Since this is a known issue, I updated the status since it may or may not be resolved for this sim.

**Comment by Nancy-Salpepi** [comment]
I know this is an ongoing problem with Firefox and might not get fixed, but I just wanted to point out that the cards move up and down a bit as well. 
![cards move](https://user-images.githubusercontent.com/87318828/162857106-1e36860b-a182-47d5-be01-d9bf36c943c5.gif)

**Comment by samreid** [comment]
I do not see this bug on Mac/Firefox 112.0.1.  @Nancy-Salpepi is it still happening on Win/Firefox?

**Comment by Nancy-Salpepi** [comment]
@samreid I wasn't able to reproduce this issue with Win10/FF this morning.
