### ISSUE TITLE
Change the name of the sim

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/center-and-variability#95]
Due to QA feedback and some teacher feedback, we'd like the sim renamed as Center and Variability. 

The third screen, previously called Spread, should also be renamed Variability.

**Comment by samreid** [comment]
I asked on slack:

> Is there a process or checklist for renaming a sim?  Context is https://github.com/phetsims/center-and-spread/issues/95

**Comment by KatieWoe** [comment]
I think when it's done people will need to delete this repo from their local copies and then clone missing repos again. But I'm not sure beyond that.

**Comment by samreid** [comment]
@chrisklus identified a checklist within new_repo_checklist:

```
## Steps for renaming a repo
- [ ] Make sure all commits are pushed to that repo.
- [ ] On Github.com, go to repo -> Settings -> Options -> "Repository name"  and rename.
- [ ] Rename in `perennial/data/active-repos`. Push the change to perennial and then pull perennial-alias.
- [ ] Delete the old repo
- [ ] Run `perennial/bin/clone-missting/repos.sh`.
- [ ] Update `package.json` accordingly. Including but not necessarily limited to:
  * `name`
  * `repository.url`
  * `phet.requirejsNamespace`
- [ ] Change entry in [responsible_dev.json](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.json).
- [ ] Notify Slack channel dev-public that the repo has been renamed. E.g. "I just renamed repository {{OLD_REPO}} to {{NEW_REPO}}. Please pull perennial and perennial-alias and run `clone-missing-repos.sh` at your convenience."
- [ ] If applicable, "refresh perennial" on phettest.
- [ ] Add the sim to chipper/tsconfig/all/tsconfig.json
```

**Comment by chrisklus** [comment]
@samreid and I completed this change in the commits above. We are going to close - please reopen if a problem is found. Total time was 1 hour.
