### ISSUE TITLE
Add sound effects for kicking soccer balls

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#96]
In email, @emily-phet suggested:

> I was curious if you had considered sound for it? Having a simple “thud” sound when the ball is kicked could really lean into the playfulness of that representation. There are also general UI sounds already in place for the buttons, checkboxes, and accordion boxes.
> 
> I mentioned this today in a sound meting with Ashton and John, and Ashton could send a soccer sound (or multiple to try out) your way if you’re interested.

**Comment by amanda-phet** [comment]
We have considered sound for this sim, yes, in particular for the kick action. I have added this suggestion to the sound design section of the design doc.

**Comment by Ashton-Morris** [comment]
@samreid  Here is a sound for that whenever you decide to test it out.

[- center-and-variability-ball-kick-sound.mp3](https://drive.google.com/file/d/1X8mgf4vhrA45aY7248guIyrM9dJWXz2Q/view?usp=sharing)

**Comment by samreid** [comment]
@amanda-phet or @catherinecarter should we add this kick sound? And/or standard UI sounds? Or wait until we do a thorough design?

**Comment by samreid** [comment]
@amanda-phet said @kathy-phet would be the best person to answer about how to deal with sounds in the sim.

**Comment by samreid** [comment]
@kathy-phet recommends a sound design meeting with @Ashton-Morris and @emily-phet.  See if we have capacity for this now. Once we brainstorm and understand the scope, we can decide.  @catherinecarter can you please schedule something?  We suspect basic UI sounds + soccer kicks would be easy enough to implement.  Would be more difficult if we add sonification for different range sounds, or distributions.

Maybe we would have a "ball flying" sound, so you can hear how long they are in the air. Or maybe when they land?

**Comment by samreid** [comment]
We are moving forward with sound effects, the soccer balls have sound effects. Closing.
