### ISSUE TITLE
Improve the kick buttons

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#98]
In https://github.com/phetsims/center-and-variability/issues/72 @pixelzoom reported:

> [...] And the buttons are just not fun, and so indirect. The buttons might be more fun/inviting with an icon on them instead of text [...]

I can see the value in having a written number on the button.  But @chrisklus and I have previously discussed that the buttons look washed out (the shading is almost non-existent because the color is very bleached).  We also discussed icons and shared a mock-up in [on the buttons](https://github.com/phetsims/center-and-variability/issues/25#issuecomment-1035946942).  @chrisklus says they may look better without text (only icon).  Anyways, I moved this issue here from #72 so #72 can be just about clicking on the players and balls.

**Comment by amanda-phet** [comment]
I was not a fan of the buttons with images- they seem much too busy for this sim that has a lot of soccer balls flying around. 

I provided @chrisklus with a hex code (#DAE6F7) to use instead of white, so we're going to move ahead with that for now.

**Comment by chrisklus** [comment]
Committed above, closing.
