### ISSUE TITLE
Unable to open example sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#99]
**Device**
Dell
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/789
When pressing launch under the example code in the wrapper index to see the example sim, it loads only part way and the console shows the below error.
**Visuals**
<img width="347" alt="example" src="https://user-images.githubusercontent.com/41024075/159567077-f551477b-5dcc-44eb-bc33-5b2ac57cbad8.png">

**Comment by Nancy-Salpepi** [comment]
I am also unable to open the HTML generated in the Studio Wrapper.

**Comment by KatieWoe** [comment]
I have been able to open HTML generated in Studio, so I'm curious about this. Let me know if I can help track it down.

**Comment by KatieWoe** [comment]
I think I figured it out. If the HTML Output is Production, launching and saving work. If Output is Development then the error is seen.

**Comment by samreid** [comment]
This seems fixed after the commits.  @KatieWoe can you please verify on phettest?  If all is well, please relabel as "ready for cherry pick".

**Comment by samreid** [comment]
@chrisklus and I confirmed this is fixed in in https://github.com/phetsims/center-and-variability/issues/122, closing.
